<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'Sample\API\ACL'                     => __DIR__ . '/src/Sample/API/ACL.php',
  'Sample\API\EventManager'            => __DIR__ . '/src/Sample/API/EventManager.php',
  'Sample\API\Sample'                  => __DIR__ . '/src/Sample/API/Sample.php',
  'Sample\Controller\SampleController' => __DIR__ . '/src/Sample/Controller/Admin.php',
  'Sample\Controller\Client'           => __DIR__ . '/src/Sample/Controller/Client.php',
  'Mail\Factory\DbAdapterFactory'      => __DIR__ . '/src/Sample/Factory/DbAdapterFactory.php',
  'Sample\Form\Sample'                 => __DIR__ . '/src/Sample/Form/Sample.php',
  'Sample\Install'                     => __DIR__ . '/src/Sample/Install.php',
  'Sample\Model\Sample'                => __DIR__ . '/src/Sample/Model/SampleModel.php',
  'Sample\Model\SampleTable'           => __DIR__ . '/src/Sample/Model/SampleTable.php',
  'Sample\View\Helper\Sample'          => __DIR__ . '/src/Sample/View/Helper/Sample.php',
);
