<?
$this->headLink()->prependStylesheet($this->basePath() . '/css/payment.css');
?>
<div>
    <?
    $form = $this->form;
    $form->prepare();
    echo $this->form()->openTag($form);
    foreach($form->getElements() as $el){
        echo $this->iptFormRow($el);
    }
    echo $this->iptFormCollection($form->get('buttons'));
    echo $this->form()->closeTag();
    ?>
</div>


<!--
<form name="frm_mellat_submit" id="frm_mellat_submit" action="<?/*=$this->post_url;*/?>" method="POST">
    <input type="hidden" name="RefId" value="<?/*=$this->RefId*/?>">

    <p>
        در حال انتقال به سایت بانک ... لطفا منتظر بمانید ...
    </p>

    <!--    <input type="submit" name="submit" class="button" value="برای انتقال به سایت بانک اینجا کلیک کنید.">-->
<!--</form>-->
<script type="text/javascript">
 //   document.getElementById("frm_mellat_submit").submit();
</script>