<?
//$this->headScript()->appendFile($this->basePath() . '/js/load-google-map.js');
$this->headScript()->appendFile($this->basePath() . '/js/ContactsGoogleMapHandler.js');
?>
<div>
    <h3 class="page-title">
        <?= $this->translate('New User For Section Contact'); ?>
    </h3>

    <p class="description">
        <?= t('New user registration, visitors can be in contact with the user.') ?>
    </p>

    <div>
        <?
        $form = $this->form;
        $form->prepare();
        echo $this->form()->openTag($form);
        foreach ($form->getElements() as $el) {
            echo $this->iptFormRow($el);
        }
        ?>
        <a href="#googleMap" id="find-google" class="input-google-map btn btn-default btn-lg disabled">
            <?= t('Google Map') ?>
            <i class="fa fa-refresh fa-spin"></i>
        </a>

        <div id="google_text"><?= $this->google ?></div>
        <?
        echo $this->formCollection($form->get('select'));
        ?>
        <br/><br/>
        <?
        echo $this->iptFormCollection($form->get('buttons'));
        echo $this->form()->closeTag();
        ?>
    </div>
</div>


<div id="map-dialog" style="display: none;">
    <div>
        <input type="button" id="select_return" class="btn btn-default pull-right flip"
               value="<?= t('Confirm and return') ?>">
        <input type="button" id="select_cancel" class="btn btn-default pull-right flip" value="<?= t('Close') ?>">

        <div>
            <?= t('To obtain the coordinates of the desired location click on the map.') ?>
        </div>
        <div id="map_selected_loc"></div>
    </div>
    <div id="map" style="width: 100%;height: 100%;">
        <?= t('Google Maps is not available due to filtering.') ?>
    </div>
</div>


<script type="text/javascript">
    <?$this->inlineScript()->captureStart();?>
    $(document).ready(function () {
        <?\Application\API\App::setEditor('description',$this)?>
//        Contacts.map = null;
        Contacts.init();
    });
    <?$this->inlineScript()->captureEnd();?>
</script>
