<div>
    <h3 class="page-title">
        <?=$this->translate('Geographical Areas');?>
    </h3>

    <div class="btn-group">
        <a class="btn btn-default ajax_page_load"
           href="<?= $this->url('admin/geographical-areas/country') ?>">
            <?=$this->translate('Countries')?>
        </a>
        <a class="btn btn-default ajax_page_load"
           href="<?= $this->url('admin/geographical-areas/state') ?>">
            <?=$this->translate('States')?>
        </a>
        <a class="btn btn-default ajax_page_load"
           href="<?= $this->url('admin/geographical-areas/city') ?>">
            <?=$this->translate('Cities')?>
        </a>
        <a class="btn btn-default ajax_page_load"
           href="<?= $this->url('admin/geographical-areas/area') ?>">
            <?=$this->translate('GEO_AREA')?>
        </a>
    </div>
</div>