<div class="box-add-to-any">

    <!-- AddToAny BEGIN -->
    <div class="a2a_kit a2a_default_style">
        <a class="a2a_dd" href="http://www.addtoany.com/share_save"><?=t('Share')?></a>
        <span class="a2a_divider"></span>
        <a class="a2a_button_email"></a>
        <a class="a2a_button_facebook"></a>
        <a class="a2a_button_twitter"></a>
        <a class="a2a_button_google_plus"></a>
        <a class="a2a_button_google_gmail"></a>
        <a class="a2a_button_yahoo_mail"></a>
    </div>
    <!-- AddToAny END -->

</div>
<script type="text/javascript">
    var a2a_config = a2a_config || {};
    a2a_config.locale = "fa";
</script>
<script type="text/javascript" src="<?= $this->basePath() . '/js/add-to-any/addToAny.js' ?>"></script>

