<div>
    <h3><?=sprintf($this->translate('Are you sure you want to delete Page %s with ID:%s ?'),
        "<em>" . $this->item->pageTitle . "</em>",
        "<em>" . $this->item->id . "</em>")?>
    </h3>

    <div>
        <form method="post" action="<?=$this->url(
            $this->url,
            array('id' => $this->item->id, 'type'=>$this->type ))?>">
            <input class="button yes_button" type="submit" name="submit" value="<?=$this->translate('Yes')?>">
            <input class="button no_button" type="submit" name="cancel" value="<?=$this->translate('No')?>">
        </form>
    </div>
</div>