<ul>
    <li>
        <a class="ajax_page_load" href="<?=url('admin/ad/config/first-config')?>"><?=t('ADS_FIRST_STAGE')?></a>
    </li>
    <li>
        <a class="ajax_page_load" href="<?=url('admin/ad/config/second-config')?>"><?=t('ADS_SECOND_STAGE')?></a>
    </li>
    <li>
        <a class="ajax_page_load" href="<?=url('admin/ad/config/third-config')?>"><?=t('ADS_THIRD_STAGE')?></a>
    </li>
</ul>