<? if ($this->error) { ?>
    <div class="alert alert-danger">
        <?= t('ADS_CONFIG_ERROR') ?>
    </div>
<? } else { ?>
    <div class="col-md-12">
        <? foreach ($this->baseType as $row) { ?>
            <div class="col-md-4">
                <a class="ajax_page_load btn btn-default btn-lg btn-block"
                   href="<?= url($this->route_prefix . '/ad/new', array('baseType' => $row['id'])) ?>">
                    <span><?= $row['name'] ?></span>
                </a>
            </div>
            <?
            if ($row['isRequest']) {
                ?>
                <div class="col-md-4">
                    <a class="ajax_page_load btn btn-default btn-lg btn-block"
                       href="<?= url($this->route_prefix . '/ad/new', array('baseType' => $row['id'], 'isRequest' => $row['isRequest'])) ?>">
                        <span><?= t('ADS_REQUEST') . ' ' . $row['name'] ?></span>
                    </a>
                </div>
            <?
            }
        } ?>
    </div>
<? } ?>
