<?
if ($this->baseType) {
    ?>
    <div class="col-md-12">
        <p class="alert alert-info">
            <?=t('ADS_INDEX_DESC')?>
        </p>
    </div>
    <div class="col-md-12">
        <? foreach ($this->baseType as $row) {
            ?>
            <div class="col-md-4">
                <a class="ajax_page_load btn btn-default btn-lg btn-block"
                   href="<?= url('admin/ad/list', array('baseType' => $row['id'])) ?>">
                    <span><?= $row['name'] ?></span>
                </a>
            </div>
        <?
        } ?>
    </div>
<?
} else {
    ?>
    <div class="alert alert-info">
        <?= t('ADS_NOT_FOUND'); ?>
    </div>
<?
}
?>
