<?
if (!$this->error) {
    $this->headScript()->appendFile($this->basePath() . '/__/js/filter-fields.js');
    $this->headScript()->appendFile($this->basePath() . '/js/geographical.js');
    if ($this->isGoogleMap) {
        $this->headScript()->appendFile($this->basePath() . '/__/js/adsGoogleMapHandler.js');
    }

    ?>
    <style>
        .ad_new_form #ad_part_2{ display:none; }
        #image_settings .add_collection_item{ display:none; }
        #ad_part_2 .select2-container-multi{ width:auto !important; }
        .filter-field-hidden{ display:none; }
    </style>
    <div class="ad_new_form">
    <h3 class="page-title">
        <?= $this->translate('ADS_NEW'); ?>
    </h3>

    <p class="text-muted">
        <?= t('ADS_NEW_DESC') ?>
    </p>
    <?
    $form = $this->form;
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('id'));
    echo $this->formRow($form->get('googleLatLong'));
    if ($form->has('sendRequestId'))
        echo $this->formRow($form->get('sendRequestId'));
    if ($form->has('notifyPrice'))
        echo $this->formRow($form->get('notifyPrice'));
    if ($form->has('notifyType'))
        echo $this->formRow($form->get('notifyType'));

    ?>
    <div id="ad_part_1" style="height:100%;">
        <div class="col-md-12 ad_view_type">
            <?= $this->formRow($form->get('adType')); ?>
            <button class="ad_next btn btn-default" data-in="1">
                    <span class="glyphicon glyphicon-chevron-left">
<?= t('Next') ?>
                    </span>
            </button>
        </div>
        <div style="clear:both"></div>
    </div>
    <div id="ad_part_2">
    <div class="col-md-12">
    <p class="description_ad alert alert-info">
        <?= sprintf(t('ADS_VIEW_TYPE'), '<span id="ad_view_param_1"></span>') ?>
        <br>
        <?= sprintf(t('ADS_VIEW_COUNT_AT_DAY'), '<span id="ad_view_param_2"></span>') ?>
        <br>
        <?= sprintf(t('ADS_VIEW_COUNT_CAT_ITEM'), '<span id="ad_view_param_3"></span>') ?>
        <br>
        <?= sprintf(t('ADS_VIEW_COUNT_KEYWORD'), $this->keywordCount) ?>
        <br>
        <?= sprintf(t('ADS_VIEW_COUNT_IMAGE'), '<span id="ad_view_param_4"></span>') ?>
        <br>
        <?= sprintf(t('ADS_VIEW_STAR_PRICE'), '<span id="ad_view_param_5"></span>') ?>
        <br>
        <? //= t('ADS_AMOUNT_PAYMENT') . ' : ' . $this->currencyFormat($this->amount) ?>
    </p>

    <p class="description_ad alert alert-success">
        <?= t('ADS_FINAL_PRICE') . " : " ?>
        <span id="ad_view_final_price"></span>
        <?= t(getCurrency()) ?>
    </p>

    <div class="col-xs-7">
        <div class="row">
            <div class="col-md-2">
                <label>
                    <?= t('Title') ?>
                </label>
            </div>
            <div class="col-md-10">
                <?= $this->formRow($form->get('title')); ?>
            </div>
        </div>
    </div>
    <div class="col-xs-7 a_n_cat">
        <div class="row">
            <div class="col-md-2">
                <label>
                    <?= t('Categories') ?>
                </label>
            </div>
            <div class="col-md-10">
                <?= $this->formRow($form->get('catId')); ?>
            </div>
        </div>

    </div>
    <div class="col-xs-7">
        <div class="row">
            <div class="col-md-2">
                <label>
                    <?= t('Name') ?>
                </label>
            </div>
            <div class="col-md-10">
                <?= $this->formRow($form->get('name')); ?>
            </div>
        </div>
    </div>

    <div class="col-xs-7" id="ad_view_star_count">
        <div class="row">
            <div class="col-md-2">
                <label>
                    <?= t('ADS_STAR_COUNT') ?>
                </label>
            </div>
            <div class="col-md-10">
                <?= $this->formRow($form->get('starCount')); ?>
            </div>
        </div>
    </div>
    <div class="col-xs-9">
        <div class="row">
            <div class="col-md-2">
                <label>
                    <?= t('Description') ?>
                </label>
            </div>
            <div class="col-md-10">
                <?= $this->formRow($form->get('text')); ?>
            </div>
        </div>
    </div>
    <div class="col-xs-9">
        <div class="row">
            <div class="col-md-2">
                <label>
                    <?= t('Address') ?>
                </label>
            </div>
            <div class="col-md-10">
                <?= $this->formRow($form->get('address')); ?>
            </div>
        </div>
    </div>
    <div class="col-xs-9">
        <div class="row">
            <div class="col-md-2">
                <label>
                    <?= t('ADS_KEYWORDS') ?>
                </label>
            </div>
            <div class="col-md-10">
                <?= $this->formRow($form->get('keyword')); ?>
            </div>
        </div>
    </div>
    <div class="col-xs-5 ">
        <div class="row">
            <div class="col-md-2">
                <label>
                    <?= t('State') ?>
                </label>
            </div>
            <div class="col-md-10">
                <?= $this->formRow($form->get('stateId')); ?>
            </div>
        </div>
    </div>
    <div class="col-xs-5 col-xs-offset-1">
        <div class="row">
            <div class="col-md-2">
                <label>
                    <?= t('City') ?>
                </label>
            </div>
            <div class="col-md-10">
                <?= $this->formRow($form->get('cityId')); ?>
            </div>
        </div>
    </div>
    <div class="col-xs-5">
        <div class="row">
            <div class="col-md-2">
                <label>
                    <?= t('Phone') ?>
                </label>
            </div>
            <div class="col-md-10">
                <?= $this->formRow($form->get('fax')); ?>
            </div>
        </div>
    </div>
    <div class="col-xs-5 col-xs-offset-1">
        <div class="row">
            <div class="col-md-2">
                <label>
                    <?= t('Mobile') ?>
                </label>
            </div>
            <div class="col-md-10">
                <?= $this->formRow($form->get('mobile')); ?>
            </div>
        </div>
    </div>
    <div class="col-xs-5" id="ad_view_link">
        <div class="row">
            <div class="col-md-2">
                <label>
                    <?= t('ADS_LINK') ?>
                </label>
            </div>
            <div class="col-md-10">
                <?= $this->formRow($form->get('link')); ?>
            </div>
        </div>
    </div>
    <div class="col-xs-5 col-xs-offset-1">
        <div class="row">
            <div class="col-md-2">
                <label>
                    <?= t('Email') ?>
                </label>
            </div>
            <div class="col-md-10">
                <?= $this->formRow($form->get('mail')); ?>
            </div>
        </div>
    </div>
    <div class="col-xs-8">
        <?= $this->formRow($form->get('showPm')); ?>
    </div>
    <? if ($this->isGoogleMap) { ?>
        <div class="col-xs-4">
            <a href="#googleMap" id="find-google" class="input-google-map btn btn-default btn-lg disabled">
                <?= t('Google Map') ?>
                <i class="fa fa-refresh fa-spin"></i>
            </a>

            <div id="google_text"><? //= $this->google ?></div>
        </div>
    <? } ?>
    <div class="col-xs-12">
        <?= $this->formRow($form->get('smallImage')); ?>
        <? if ($this->flagEdit && $this->oldSmallImagePath) { ?>
            <div class="box-file-collection">
                <a id="del_smallImage_ad" class="btn">
                    <span class="glyphicon glyphicon-remove text-danger"></span>
                </a>
                <img src="<?= $this->oldSmallImagePath ?>">
            </div>
        <? } ?>
    </div>

    <div class="col-xs-12 a_n_images_f">
        <?= $this->formCollection($form->get('image')); ?>
        <? if ($this->flagEdit) { ?>
            <div class="box-file-collection">
                <?= $this->fileDisplay($this->imagesFile, $this->countImage) ?>
            </div>
        <? } ?>
    </div>
    <div class="col-xs-12">
        <?= $this->formCollection($form->get('fields')); ?>
    </div>
    <div class="col-md-12">
        <? if ($form->has('captcha')) echo $this->iptFormRow($form->get('captcha')); ?>
    </div>
    <div style="clear:both"></div>
    <button class="ad_prev btn btn-default" data-in="2">
                    <span class="glyphicon glyphicon-chevron-right">
<?= t('Back') ?>
                    </span>
    </button>


    <div id="send_request_dialog" style="display:none;">
        <div class="count_request">
            <?= sprintf(t('ADS_COUNT_REQUEST_VIEW'), '<span class"c_r_dialog">0</span>') ?>
        </div>
        <div>
            <? if ($form->has('sendRequestType')) echo $this->formRow($form->get('sendRequestType')); ?>
        </div>
        <a href="#" id="submit_form_final" class="btn btn-default">
            <?= t('Next') ?>
        </a>
    </div>



    <?
    echo $this->iptFormCollection($form->get('buttons'));
    ?>
    </div>
    <div style="clear:both"></div>
    </div>
    <?
    echo $this->form()->closeTag();
    ?>
    </div>
    <div id="map-dialog" style="display: none;">
        <div>
            <input type="button" id="select_return" class="btn btn-default pull-right flip"
                   value="<?= t('Confirm and return') ?>">
            <input type="button" id="select_cancel" class="btn btn-default pull-right flip" value="<?= t('Close') ?>">

            <div>
                <?= t('To obtain the coordinates of the desired location click on the map.') ?>
            </div>
            <div id="map_selected_loc"></div>
        </div>
        <div id="map" style="width: 100%;height: 100%;">
            <?= t('Google Maps is not available due to filtering.') ?>
        </div>
    </div>
    <script>
    <?$this->inlineScript()->captureStart();?>
    var ads = {
        config: <?=json_encode($this->adConfig)?>,
        fieldsRequestSearch: <?=json_encode($this->fieldsRequestSearch)?>,
        adConfigId: 0,
        notConfig: '<?=t('ADS_NOT_CONFIG_MESSAGE')?>',
        flagEdit: <?=$this->flagEdit?>,
        filter:<?=$this->filterFields?>,
        filterFieldName:<?if($this->filterFieldsName) echo $this->filterFieldsName; else echo json_encode(false);?>,
        isGoogleMap:<?=$this->isGoogleMap?>,
        flagFormSubmit:<?=$this->flagFormSubmit?>,
        baseType:<?=$this->baseType?>,
        baseTypePriceOneEmail:<?=$this->baseTypePriceOneEmail?>,
        baseTypePriceOneSms:<?=$this->baseTypePriceOneSms?>
        /*requestId: '',
        price_r_1: 0,
        price_r_2: 0,
        price_r_3: 0*/
    };
    $(document).ready(function () {

        if (ads.flagFormSubmit)
            $('#new_ad_form #buttons_submit').addClass('submitRequest');

        if (ads.flagEdit) {
            $('#ad_part_1 .ad_view_type .form-group').hide();
            $('#ad_view_star_count').hide();
            $('#ad_part_1 .ad_view_type').prepend($('input[name=adType]:radio:checked').parent().text());
        }

        $('#new_ad_form #buttons_submit').click(function (e) {
            var form_tag = $(this);
            if (form_tag.hasClass('submitRequest')) {
                if (ads.fieldsRequestSearch) {
                    e.preventDefault();
                    form_tag.addClass('ajax-loading-inline');
                    var params = {};
                    $.each(ads.fieldsRequestSearch, function (index, value) {
                        if ($('input[name=' + value + ']').val())
                            params[value] = $('input[name=' + value + ']').val();
                        else if ($('textarea[name=' + value + ']').val())
                            params[value] = $('textarea[name=' + value + ']').val();
                    });
                    var data = {};
                    data['baseType'] = ads.baseType;
                    data['params'] = params;

                    $.ajax({
                        url: '<?=url('admin/ad/request-search-count')?>',
                        type: 'POST',
                        data: data,
                        complete: function () {
                            form_tag.removeClass('ajax-loading-inline');
                        },
                        success: function (data) {
                            if (data.status == 1) {
                                $('.count_request span').html(data.count);
                                $('.send_request_type').each(function () {
                                    var r_value = $(this).val();
                                    switch (parseInt(r_value)) {
                                        case 1 :
                                            $(this).parent().append('<span>' + data.p_sms_v + '</span>');
                                            /*ads.price_r_1 = data.p_sms;*/
                                            break;
                                        case 2 :
                                            $(this).parent().append('<span>' + data.p_email_v + '</span>');
                                           /* ads.price_r_2 = data.p_email;*/
                                            break;
                                        case 3 :
                                            $(this).parent().append('<span>' + data.p_sms_email_v + '</span>');
                                            /*ads.price_r_3 = data.p_sms_email;*/
                                            break;
                                    }
                                });
                               /* $('input[name=sendRequestId]').val(data.r_id);*/
                                $("#send_request_dialog").dialog({
                                    resizable: false,
                                    height: 250,
                                    width: 400,
                                    modal: false
                                    // title: Comment.title,
                                });
                                form_tag.removeClass('submitRequest');
                            } else {
                                form_tag.removeClass('submitRequest');
                                //form_tag.submit();
                            }
                        }

                    });

                }
            }
        });

        $('#submit_form_final').click(function(e){
            e.preventDefault();
            var notifyType = $('input[name=sendRequestType]:radio:checked').val();
            console.log(notifyType);
            switch(parseInt(notifyType))
            {
                case 0:$('input[name=notifyPrice]').val(-1); break;
                case 1:$('input[name=notifyPrice]').val(ads.price_r_1); break;
                case 2:$('input[name=notifyPrice]').val(ads.price_r_2); break;
                case 3:$('input[name=notifyPrice]').val(ads.price_r_3); console.log(123); break;
            }
            $('input[name=notifyType]').val(parseInt(notifyType));
            $('#new_ad_form #buttons_submit').submit();
        });

        $('.ad_next').click(function (e) {
            e.preventDefault();
            var idLink = parseInt($(this).data('in')) + 1;
            ads.adConfigId = $('input[name=adType]:radio:checked').val();
            var adConfigText = $('input[name=adType]:radio:checked').parent().text();
            if (ads.config[ads.adConfigId]) {

                $('#ad_view_param_1').html(adConfigText);
                $('#ad_view_param_2').html(ads.config[ads.adConfigId]['countInDay']);
                $('#ad_view_param_3').html(ads.config[ads.adConfigId]['countCatItem']);
                $('#ad_view_param_4').html(ads.config[ads.adConfigId]['countImage']);
                $('#ad_view_param_5').html(ads.config[ads.adConfigId]['starPrice_name']);
                $('#ad_view_final_price').html(insertcomma(ads.config[ads.adConfigId]['starPrice']));
                // var finalPrice = ads.config[ads.adConfigId]['starPrice'];
                // $('#ad_view_final_price_deducted').html(insertcomma(finalPrice));

                var countImage = parseInt(ads.config[ads.adConfigId]['countImage']);
                if (countImage == 0)
                    $('#image_settings').parent().hide();
                else {
                    $('#image_settings').parent().show();
                    for (var i = 1; i < countImage; i++) {
                        $('#image_settings .add_collection_item').click();
                    }
                }

                if (parseInt(ads.config[ads.adConfigId]['haveLink']) == 1)
                    $('#ad_view_link').show();
                else
                    $('#ad_view_link').hide();

                if (parseInt(ads.config[ads.adConfigId]['starPrice']) > 0 && !ads.flagEdit)
                    $('#ad_view_star_count').show();
                else if (parseInt(ads.config[ads.adConfigId]['starPrice']) <= 0 && !ads.flagEdit)
                    $('#ad_view_star_count').hide();
                $(this).parent().parent().fadeOut(700, function () {
                    $('#ad_part_' + idLink).fadeIn(1000);
                });
            } else
                System.AjaxMessage(ads.notConfig);
        });

        $('.ad_prev').click(function (e) {
            e.preventDefault();
            var idLink = parseInt($(this).data('in')) - 1;
            console.log()
            var counter = 1;
            $('#image_settings #image').each(function () {
                if (counter != 1)
                    $(this).remove();
                counter++;
            });
            $(this).parent().parent().fadeOut(700, function () {
                $('#ad_part_' + idLink).fadeIn(1000);
            });
        });

        $('select[name=starCount]').change(function () {
            var result = parseInt(ads.config[ads.adConfigId]['starPrice']) * parseInt($(this).val());
            $('#ad_view_final_price').html(insertcomma(result));
            //  var finalPrice = result;
            //  $('#ad_view_final_price_deducted').html(insertcomma(finalPrice));
        });

        $('#del_smallImage_ad').click(function (e) {
            e.preventDefault();
            var tag = $(this);
            tag.removeClass('remove-icon').addClass('ajax-loading-inline');
            var data = {};
            data['id'] = $('input[name=id]').val();

            $.ajax({
                url: '<?=url('admin/ad/delete-img')?>',
                type: 'POST',
                data: data,
                complete: function () {
                    tag.removeClass('ajax-loading-inline').addClass('remove-icon');
                },
                success: function (data) {
                    if (data.status) {
                        tag.parent().remove();
                    }
                    else {
                        System.AjaxMessage('Error . Please try again');
                    }
                }

            });
        });

        if (ads.filterFieldName) {
            var fieldsName = [];
            $.each(ads.filterFieldName, function (index, item) {
                fieldsName.push('select[name="' + item + '"]');
                $('select[name="' + item + '"]').data('index', index);
            });

            $(fieldsName.join(',')).change(function () {
                __showFields();
                var baseName = $(this).attr('name');
                var key = $(this).data('index');
                var name = baseName.replace('fields[', '').replace(']', '');
                var filters = ads.filter;
                var that = $(this);
                $.each(ads.filterFieldName, function (index, item) {
                    var el = null;
                    var elName = '';
                    if (item != baseName) {
                        el = $('select[name="' + item + '"]');
                        item = item.replace('fields[', '').replace(']', '');
                        elName = item;
                    } else {
                        el = that;
                        elName = name;
                    }
                    filters = filters[elName][el.val()];
                });
                $.each(filters, function (index, item) {
                    if (item == '0') {
                        $('[name="fields[' + index + ']"]').parent().addClass('filter-field-hidden');
                    }
                });

            });
        }

        function __showFields() {
            $('.filter-field-hidden').each(function () {
                $(this).removeClass('filter-field-hidden');
            });
        }

        if (ads.isGoogleMap)
            Ads.init();

    });
    <?$this->inlineScript()->captureEnd();?>
    </script>
<? } ?>