<?
if ($this->error) {
    ?>
    <div class="alert alert-danger">
        <?= t('ADS_CONFIG_ERROR') ?>
    </div>
<?
} else {
    if ($this->flagView) {
       // $this->headScript()->appendFile($this->basePath() . '/js/file.js');
        ?>
        <div>
            <h3 class="page-title">
                <?= $this->translate('ADS_CONFIGS'); ?>
            </h3>

            <p class="help-block"><?= t('ADS_SECOND_CONFIG_DESC') ?></p>
            <?
            $form = $this->form;
            $form->prepare();
            echo $this->form()->openTag($form);
            if ($form->has('limited_ads'))
                echo $this->formCollection($form->get('limited_ads'));
            echo $this->iptFormCollection($form->get('buttons'));
            echo $this->form()->closeTag();
            ?>
            <div class="box-file-collection">
                <?= $this->fileDisplay($this->imagesFile, 100) ?>
            </div>
        </div>
    <?
    } else {
        ?>
        <div class="col-md-12">
            <? foreach ($this->baseType as $row) { ?>
                <div class="col-md-4">
                    <a class="ajax_page_load btn btn-default btn-lg btn-block"
                       href="<?= url('admin/ad/config/second-config', array('baseType' => $row['id'])) ?>">
                        <span><?= $row['name'] ?></span>
                    </a>
                </div>
                <? if ($row['isRequest']) { ?>
                    <div class="col-md-4">
                        <a class="ajax_page_load btn btn-default btn-lg btn-block"
                           href="<?= url('admin/ad/config/second-config', array('baseType' => $row['id'], 'isRequest' => 1)) ?>">
                            <span><?= t('ADS_REQUEST') . ' ' . $row['name'] ?></span>
                        </a>
                    </div>
                <?
                }
            } ?>
        </div>
    <?
    }
}?>

