<?
$form = $this->form;
?>
<div class="new-form">
    <?
    //    $form->prepare();
    //    echo $this->form()->openTag($form);
    //    foreach ($form->getElements() as $el) {
    //        echo $this->iptformRow($el);
    //    }
    //    echo $this->iptFormCollection($form->get('buttons'));
    //    echo $this->form()->closeTag();
    print $this->form($this->form);

    if ($this->oldImage) {
        ?>
        <div>
            <a href="#" id="delete_table_image" class="btn btn-default btn-xs" data-id="<?= $this->galleryItemId ?>">
                <span class="glyphicon glyphicon-remove text-danger"></span>
            </a>
            <img src="<?= $this->oldImage ?>">
        </div>
    <?
    }
    ?>

</div>
<script>
    <?$this->inlineScript()->captureStart()?>

    var GalleryItem = {
        deleteUrl: '<?=url('admin/'.$this->type.'/item/delete-img')?>'
    };

    $(document).ready(function () {

        $('#delete_table_image').click(function (e) {
            e.preventDefault();
            var tag = $(this);
            tag.addClass('tiny-ajax-loader');
            var data = {};
            data['itemId'] = $(this).data('id');
            $.ajax({
                url: GalleryItem.deleteUrl,
                type: 'POST',
                data: data,
                complete: function () {
                    tag.removeClass('tiny-ajax-loader');
                },
                success: function (data) {
                    if (data.status == 1) {
                        tag.parent().remove();
                    }
                },
                error: System.AjaxError
            });
        });

    });
    <?$this->inlineScript()->captureEnd()?>
</script>
