<?
$basePath = $this->basePath();
$path = $basePath . TEMPLATE_PATH;
//$this->headScript()
//    ->prependFile($basePath . '/js/jquery-1.9.1.min.js');
$leaf = '/images/leaf.png';
?>
<!DOCTYPE html>
<html lang="fa" xmlns="http://www.w3.org/1999/html">
<head>
    <?= $this->head() ?>
    <?= $this->headTitle() ?>
    <?= $this->headMeta() ?>
    <style type="text/css">
        html{ height:100%; }
        body{ padding:0; margin:0; background:#f7f9f4; overflow:hidden; max-height:100%; }
        #bg{ position:fixed; bottom:0; text-align:center; z-index:-2; width:100%; max-width:100%; height:auto; }
        #bg img{ display:block; margin:auto; position:relative; bottom:0; width:100%; }
        #leaf{ position:fixed; top:0; left:0; z-index:-1; width:15%; }
        #logo{ margin:auto; text-align:center; position:relative; top:0; }
        #logo-image{ max-width:100%; max-height:100%; vertical-align:middle; }
        #buttons{ position:absolute; bottom:0; left:0; height:50px; text-align:center; width:100%; }
        #buttons div{ width:50%; height:100%; float:right; }
        #buttons a{ display:block; width:100px; height:100%; text-decoration:none; }
        #buttons a:hover{ text-decoration:none; }
        #fa{ float:left; }
        #en{ float:right; }
    </style>
</head>
<body onload="position();" onresize="position();">
<img id="leaf" src="<?= $path . $leaf ?>">

<div id="bg">
    <img src="<?= $path ?>/images/bg.jpg">
</div>
<div id="logo">
    <div style="height:100%;width:100%;">
        <img id="logo-image" src="<?= $path ?>/images/big-logo.png">

        <div id="buttons">
            <div>
                <a href="http://urumgreenlight.com/fa" id="fa">&nbsp;</a>
            </div>
            <div>
                <a href="http://urumgreenlight.com/en" id="en">&nbsp;</a>
            </div>
        </div>
    </div>
</div>
<? //= $this->headScript() ?>
<script>
    function windowSize() {
        var myWidth = 0, myHeight = 0;
        if (typeof( window.innerWidth ) == 'number') {
            //Non-IE
            myWidth = window.innerWidth;
            myHeight = window.innerHeight;
        } else if (document.documentElement && ( document.documentElement.clientWidth || document.documentElement.clientHeight )) {
            //IE 6+ in 'standards compliant mode'
            myWidth = document.documentElement.clientWidth;
            myHeight = document.documentElement.clientHeight;
        } else if (document.body && ( document.body.clientWidth || document.body.clientHeight )) {
            //IE 4 compatible
            myWidth = document.body.clientWidth;
            myHeight = document.body.clientHeight;
        }
        return {width: myWidth, height: myHeight};
    }
    var logoHeight = false;
    function position() {
        var windowHeight = windowSize().height;
//        document.body.style.height = windowHeight + "px";
        if (!logoHeight)
            logoHeight = document.getElementById('logo-image').offsetHeight;

        if (windowHeight > logoHeight) {
            document.getElementById('logo').style.top = (windowHeight - logoHeight) / 2 + "px";
        } else {
            document.getElementById('logo').style.top = 0;
            document.getElementById('logo').style.height = windowHeight + "px";
        }
    }
</script>
</body>
</html>