<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'Comment\API\ACL'                           => __DIR__ . '/src/Comment/API/ACL.php',
  'Comment\API\EventManager'                  => __DIR__ . '/src/Comment/API/EventManager.php',
  'Comment\Controller\CommentAdminController' => __DIR__ . '/src/Comment/Controller/CommentAdminController.php',
  'Comment\Controller\CommentController'      => __DIR__ . '/src/Comment/Controller/CommentController.php',
  'Comment\Form\CommentForm'                  => __DIR__ . '/src/Comment/Form/CommentForm.php',
  'Comment\Form\Config'                       => __DIR__ . '/src/Comment/Form/Config.php',
  'Comment\Install'                           => __DIR__ . '/src/Comment/Install.php',
  'Comment\Model\Comment'                     => __DIR__ . '/src/Comment/Model/Comment.php',
  'Comment\Model\CommentTable'                => __DIR__ . '/src/Comment/Model/CommentTable.php',
  'Comment\View\Helper\Comment'               => __DIR__ . '/src/Comment/View/Helper/Comment.php',
);
