<div>
    <!--    <a class="toolbar-button button add_button"-->
    <!--       href="--><?//= $this->url('admin/geographical-areas/city/new',
//           array('countryId' => $this->country->id, 'stateId' => $this->state->id)) ?><!--">-->
    <!--        --><? //=$this->translate('New City')?>
    <!--    </a>-->
    <?= $this->buttons ?>
    <h3 class="page-title">
        <?
        if (!$this->country->id && !$this->state->id) {
            echo $this->translate('Cities');
        } else {
            echo $this->translate('Cities list for');
            if ($this->state->id) {
                ?>
                &nbsp;
                <span class="emphasize">
                            <?= sprintf($this->translate('%s State'), $this->state->stateTitle) ?>
                    </span>
                <?
                echo "&nbsp;" . $this->translate('in');
                ?>
                <span class="emphasize" rel='tooltip' title="<?=
                sprintf($this->translate('The List of Cities for %s in %s'),
                    $this->state->stateTitle, $this->translate($this->country->countryTitle))?>">
                            <?= $this->translate($this->country->countryTitle) ?>
                    </span>
            <?
            } elseif ($this->country->id) {
                ?>
                <span class="emphasize">
                            <?= $this->translate($this->country->countryTitle) ?>
                    </span>
            <?
            }
        }
        ?>

    </h3>

    <div>
        <?= $this->grid ?>
    </div>
</div>