CREATE TABLE IF NOT EXISTS `tbl_realestate` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ownerName` varchar(200) DEFAULT NULL COMMENT 'full name',
  `ownerPhone` varchar(13) DEFAULT NULL,
  `ownerMobile` varchar(13) DEFAULT NULL,
  `ownerEmail` varchar(100) DEFAULT NULL,
  `passForEdit` varchar(50) DEFAULT NULL COMMENT 'national ID',
  `estateArea` int(11) DEFAULT NULL COMMENT 'the area of the real estate in square meter',
  `addressShort` varchar(200) DEFAULT NULL,
  `addressFull` text,
  `description` text,
  `mortgagePrice` bigint(20) DEFAULT NULL,
  `totalPrice` bigint(20) DEFAULT NULL,
  `priceOneMeter` bigint(20) DEFAULT NULL,
  `rentalPrice` bigint(20) DEFAULT NULL,
  `regType` int(11) DEFAULT NULL COMMENT '1 => ''Sell'',\r\n        2 => ''Mortgage and Rent'',\r\n        3 => ''Pre-Sale'',\r\n        4 => ''Construction Partnership''',
  `estateType` int(11) DEFAULT NULL COMMENT 'fk to category estate_type',
  `isSpecial` tinyint(1) unsigned DEFAULT '0' COMMENT 'shows if submitted fom us special Realty',
  `showInfo` tinyint(4) DEFAULT '0',
  `expireSpecial` int(11) DEFAULT NULL,
  `expireShowInfo` int(11) DEFAULT NULL,
  `newArea` varchar(200) DEFAULT NULL,
  `areaId` int(11) DEFAULT NULL COMMENT 'fk to tbl_city_area_list.id',
  `cityId` int(11) DEFAULT NULL COMMENT 'fk to tbl_city_list.id',
  `stateId` int(11) DEFAULT NULL COMMENT 'fk to tbl_state_list.id',
  `allowEdit` tinyint(1) DEFAULT '0' COMMENT 'Allow edit foe guest : 0=>Inherited,1=>Allowed,2=>Unauthorized',
  `userId` int(11) DEFAULT '1',
  `isRequest` tinyint(1) DEFAULT '0',
  `status` int(11) DEFAULT '0' COMMENT '0=not-approved1=approved2=archived3=transfered4=canceled6=deleted',
  `created` int(11) DEFAULT '0' COMMENT 'creation time',
  `published` int(11) DEFAULT '0' COMMENT 'publish time',
  `modified` int(11) DEFAULT '0' COMMENT 'modified time',
  `expire` int(11) DEFAULT '0' COMMENT 'expire time',
  `version` int(11) DEFAULT '0',
  `localVersion` int(11) DEFAULT '0',
  `viewCounter` int(10) DEFAULT '0',
  `googleLatLong` varchar(300) DEFAULT NULL,
  `pm` text,
  PRIMARY KEY (`id`),
  KEY `expire` (`expire`),
  KEY `status` (`status`),
  KEY `isRequest` (`isRequest`),
  KEY `isSpecial` (`isSpecial`),
  KEY `ownerName` (`ownerName`),
  KEY `ownerPhone` (`ownerPhone`),
  KEY `ownerMobile` (`ownerMobile`),
  KEY `ownerEmail` (`ownerEmail`),
  KEY `addressShort` (`addressShort`),
  KEY `ownerName_2` (`ownerName`,`ownerPhone`,`ownerMobile`,`ownerEmail`,`addressShort`),
  KEY `cityId` (`cityId`),
  KEY `estateType` (`estateType`),
  KEY `stateId` (`stateId`),
  KEY `userId` (`userId`),
  KEY `passForEdit` (`passForEdit`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `tbl_realestate_agent_area` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `agentId` int(11) DEFAULT NULL,
  `areaId` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `agentId` (`agentId`,`areaId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;



