<?

$direction = $this->translate('lang_direction'); //rtl ? ltr

$this->headLink()
    ->prependStylesheet($this->basePath() . '/css/system.css')
    ->prependStylesheet($this->basePath() . '/css/base-theme/jquery-ui-1.10.1.custom.min.css')
    ->prependStylesheet($this->basePath() . '/css/reset.min.css');

$this->headLink()->appendStylesheet($this->basePath() . TEMPLATE_PATH . '/css/style.css');

$this->headScript()
    ->prependFile($this->basePath() . TEMPLATE_PATH . '/js/template.js')
    ->prependFile($this->basePath() . '/js/system.jquery.ui.buttons.js')
    ->prependFile($this->basePath() . '/js/system.jquery.ui.js')
    ->prependFile($this->basePath() . '/js/system.js')
    ->prependFile($this->basePath() . '/js/forms.js')
    ->prependFile($this->basePath() . '/js/jquery.transit.min.js')
    ->prependFile($this->basePath() . '/js/general-client.js')
    ->prependFile($this->basePath() . '/js/jquery-ui-1.10.1.custom.min.js')
    ->prependFile($this->basePath() . '/js/jquery-1.9.1.min.js');


$column_right_blocks = '';
$has_column_right = strlen(trim($column_right_blocks));

$mid_col_class = '';


if ($has_column_right)
    $mid_col_class = 'two_columns';

$user_block = $this->user_logged_in_block();
if (!$user_block) {
    $user_login_block = $this->blocks('user-popup');
}

$headerBlock = $this->blocks('header');
$topMenuBlock = $this->blocks('top-menu');

$colRightBlock = $this->blocks('col-right');
$hasRightColumn = !empty($colRightBlock);

$debugBlock = $this->blocks('debug');
$colMidTopBlock = $this->blocks('col-mid-top');

$colLeftTopBlock = $this->blocks('col-left-top');
$colLeftLeftBlock = $this->blocks('col-left-left');
$colLeftRightBlock = $this->blocks('col-left-right');
$hasLeftBlock = (!empty($colLeftTopBlock) || !empty($colLeftLeftBlock) || !empty($colLeftRightBlock));
$footerBlock = $this->blocks('footer');

$mainSlider = $this->blocks('main-slider');
$logo = $this->blocks('logo');
$menu = $this->blocks('menu');
$footer_menu = $this->blocks('footer-menu');
$footer_menu2 = $this->blocks('footer-menu2');
$footer_menu3 = $this->blocks('footer-menu3');
$footer_menu4 = $this->blocks('footer-menu4');
$languageSwitcher = $this->langSwitcher();

$breadcrumbs = $this->breadcrumb();
?>

<?php echo $this->doctype(); ?>

<html lang="fa" xmlns="http://www.w3.org/1999/html">
<head>
    <?= $this->head() ?>
    <?= $this->headMeta() ?>
    <?= $this->headLink() ?>
    <?= $this->headScript() ?>
    <style>
        .col-mid-top-header{ width:100%; display:block; border-bottom:1px solid #cccccc; }
        .mid-top-box-right{ width:20%; display:inline-block; }
        .mid-top-box-left{ width:65%; display:inline-block; }
        .main-body{ width:100%; margin-right:auto; margin-left:auto; }
        .mid-content, .box-mid-top-header{ width:80% !important; margin-right:auto; margin-left:auto; position:relative; }
        .column{ width:100%; display:block }
        .header{position:relative;}
        .sidebar{ width:30%; display:inline-table; margin-top:60px; }
        .box-content{ width:65%; display:inline-block; position:relative; top:-62px; }
        .top_menu_box{ width:100%; float:none; display:inline-block; background:#000000; }
        .box-top-menu{ width:auto; margin-left:auto; margin-right:auto; display:table; }
        .block-content{ background:none !important; }
        body{ padding:0px !important; background:#ececec !important; }
        .test{ width:200px; height:200px; display:inline-block; background:#78ab26; }
        .main-slider{ float:right; }
        .box-content-slider, .box-content_body{ width:100%; border:2px solid #CCCCCC; border-radius:10px; float:right; }
        #breadcrumbs{ margin:5px 0px; }
        .box-content_body{ margin-top:10px; }
        .th-container{ display:table; margin-left:auto; margin-right:auto; width:auto; }
        .th-box{ margin-right:50px; width:64px; height:64px; display:block; }
        .tarrahi-site{ background:url(<?=$this->basePath(). TEMPLATE_PATH?>/images/footericon/tarrahi-site.png) no-repeat center center; }
        .tarrahi-site:hover{ background:url(<?=$this->basePath(). TEMPLATE_PATH?>/images/footericon/tarrahi-site2.png) no-repeat center center; }
        .home2{ background:url(<?=$this->basePath() . TEMPLATE_PATH?>/images/footericon/home.png) no-repeat center center; }
        .home2:hover{ background:url(<?=$this->basePath() . TEMPLATE_PATH?>/images/footericon/home2.png) no-repeat center center; }
        .amlak-mostaghalat{ background:url(<?=$this->basePath() . TEMPLATE_PATH?>/images/footericon/amlak-mostaghalat.png) no-repeat center center; }
        .amlak-mostaghalat:hover{ background:url(<?=$this->basePath() . TEMPLATE_PATH?>/images/footericon/amlak-mostaghalat2.png) no-repeat center center; }
        .agahi-amlak{ background:url(<?=$this->basePath() . TEMPLATE_PATH?>/images/footericon/agahi-amlak.png) no-repeat center center; }
        .agahi-amlak:hover{ background:url(<?=$this->basePath() . TEMPLATE_PATH?>/images/footericon/agahi-amlak2.png) no-repeat center center; }
        .contact-us{ background:url(<?=$this->basePath() . TEMPLATE_PATH?>/images/footericon/contact-us.png) no-repeat center center; }
        .contact-us:hover{ background:url(<?=$this->basePath() . TEMPLATE_PATH?>/images/footericon/contact-us2.png) no-repeat center center; }
        .about-us{ background:url(<?=$this->basePath() . TEMPLATE_PATH?>/images/footericon/about-us.png) no-repeat center center; }
        .about-us:hover{ background:url(<?=$this->basePath() . TEMPLATE_PATH?>/images/footericon/about-us2.png) no-repeat center center; }
        .user_container{width:auto; display:table; position:absolute; left:50px; top:-45px; z-index: 99999;}
        .user_container .box , .user_container .block-content{background: none repeat scroll #DBDBDB; padding:0px;}
        .footer{width:95%; display:block; margin-right:auto; margin-left:auto; }
        .box-th-container{}
        .box-footer-menu{border-top:2px solid #ff1323; margin-top:10px;}
        .footermenu ul {
            column-width: 380px;
            -webkit-column-width:380px;
            -moz-column-width: 380px;
            height:440px;
        }
        .footermenu ul li {
            /* float: left; */
            margin: 20px;
            width: 300px;
            height: 200px;
            background-color: #dddddd;
            font-size: 72px;
            text-align: center;
            vertical-align: middle;
        }
.footermene a:link{color:#cc000;}
    </style>
</head>

<body class="<?= implode(' ', $this->body()->class) ?>">
<?= $this->body()->getSiteTitle() ?>
<?= $this->body()->getSiteSubTitle() ?>

<div class="main-body ajami">

    <div class="column header">





        <? if (!empty($headerBlock)) { ?>
            <?= $headerBlock ?>
        <? } ?>

        <?= $languageSwitcher ?>

        <div class="box top_menu_box">
            <div class="box-top-menu">
                <?= $topMenuBlock ?>
            </div>
        </div>

        <div class="col-mid-top-header">

            <div class="box-mid-top-header">
                <div class="mid-top-box-right">
                    <?= $logo ?>
                </div>
                <div class="mid-top-box-left">
                    <div id="main-menu">
                        <?= $menu ?>
                    </div>
                </div>
                <div class="user_container">
                    <?
                    if (!$user_block) {

                        ?>
                        <div class="box user_login">
                            <?= $user_login_block ?>
                        </div>
                    <?
                    } else {
                        if (isAllowed(\Application\Module::ADMIN)) {

                            ?>
                            <div class="box admin_link_box">
                                <a href="<?= url('admin') ?>">
                                <span>
                                    <?= t('Administration') ?>
                                </span>
                                </a>
                            </div>
                        <?
                        }
                        echo $user_block;
                    }

                    ?>
                </div>
            </div>



        </div>

    </div>

    <div class="column mid-content">


        <div class="sidebar">

            <div><a href="#"><img src="<?= $this->basePath() . TEMPLATE_PATH ?>/images/taghazaye-melk.png" width="300" height="70"/>
            </a></div>
            <div><a href="#"> <img src="<?= $this->basePath() . TEMPLATE_PATH ?>/images/sepordan-melk.png" width="300" height="70"/>
            </a></div>
            <div><a href="#"><img src="<?= $this->basePath() . TEMPLATE_PATH ?>/images/mosharekat.png" width="300" height="70"/>
            </a></div>

            <? if (!empty($colRightBlock)) { ?>
                <div class="column column1">
                    <?= $colRightBlock ?>
                </div>
            <? } ?>

        </div>

        <div class="box-content">

            <div id="breadcrumbs"><?= $breadcrumbs ?></div>

            <? if (!empty($mainSlider)) { ?>
                <div class="box-content-slider">
                    <div class="main-slider">
                        <?= $mainSlider ?>
                    </div>
                </div>
            <? } ?>
            <div class="box-content_body">
                <div id="system_messages"><?= $this->flashMessenger()->render(); ?></div>
                <?= $colMidTopBlock ?>
                <div id="content_body">
                    <?= $this->content; ?>
                </div>
            </div>

        </div>

    </div>

    <div class="footer">

        <?= $footerBlock ?>
        <div class="box-th-container">
            <div class="th-container">
                <a href="#" class="th-box tarrahi-site"></a>
                <a href="<?=url('app/front-page')?>" class="th-box home2"></a>
                <a href="#" class="th-box contact-us"></a>
                <a href="#" class="th-box agahi-amlak"></a>
                <a href="#" class="th-box amlak-mostaghalat"></a>
                <a href="#" class="th-box about-us"></a>
                <!-- <div class="th-box"><img
                    src="<?/*= $this->basePath() . TEMPLATE_PATH */?>/images/footericon/tarrahi-site.png"
                    width="64" height="64"/></div>
            <div class="th-box"><img src="<?/*= $this->basePath() . TEMPLATE_PATH */?>/images/footericon/home2.png"
                                         width="64" height="64"/></div>
            <div class="th-box"><img src="<?/*= $this->basePath() . TEMPLATE_PATH */?>/images/footericon/contact-us.png"
                                         width="64" height="64"/></div>
            <div class="th-box"><img
                    src="<?/*= $this->basePath() . TEMPLATE_PATH */?>/images/footericon/agahi-amlak.png"
                    width="64" height="64"/></div>
            <div class="th-box"><img
                    src="<?/*= $this->basePath() . TEMPLATE_PATH */?>/images/footericon/amlak-mostaghalat.png" width="64"
                    height="64"/></div>
            <div class="th-box"><img src="<?/*= $this->basePath() . TEMPLATE_PATH */?>/images/footericon/about-us.png"
                                         width="64" height="64"/></div>-->
            </div>
        </div>

        <div class="box-footer-menu">
            <? if (!empty($footer_menu)) { ?>
                <div class="footermenu">
                    <?= $footer_menu ?>
                </div>
            <? } ?>

            <? if (!empty($footer_menu2)) { ?>
                <div class="footermenu">
                    <?= $footer_menu2 ?>
                </div>
            <? } ?>

            <? if (!empty($footer_menu3)) { ?>
                <div class="footermenu">
                    <?= $footer_menu3 ?>
                </div>
            <? } ?>

            <? if (!empty($footer_menu4)) { ?>
                <div class="footermenu">
                    <?= $footer_menu4 ?>
                </div>
            <? } ?>
        </div>

    </div>

</div>

<div id="bottom-toolbar">
</div>
<div class="debug">
    <?= $debugBlock ?>
</div>
<?= $this->inlineScript() ?>
<script type="text/javascript">
    var c1W = parseInt($('.column1').width());
    c1W = isNaN(c1W) ? 0 : c1W;

    var c3W = parseInt($('.column3').width());
    c3W = isNaN(c3W) ? 0 : c3W;

    var c4W = parseInt($('.column4').width());
    c4W = isNaN(c4W) ? 0 : c4W;

    var c5W = parseInt($('.column5').width());
    c5W = isNaN(c5W) ? 0 : c5W;

    var leftColumnW = isNaN(c5W) ? c3W + c4W : c5W;
    var columnsW = c1W + leftColumnW;
    if (columnsW != 0)
        columnsW += 15;
    var main_contentW = parseInt($('.main_content').width());
    var c2W = main_contentW - columnsW;
    //console.log(c1W);
    $('.column2').css({width: c2W});
    $('.column_top').css({width: main_contentW});
</script>

</body>
</html>
