<div id="content-slider-<?= $this->blockId ?>"
     class="content-slider-container <? if ($this->$showLoading) echo 'ajax-loading'; ?> ">
    <? if ($this->directionalNav != 2) { ?>
        <div class="prev" rel='tooltip' title="<?= t('Previous') ?>">
        </div>
    <? } ?>
    <div class="viewport">
        <ul class="wrapper">
            <?
            foreach ($this->data as $row) {
                if ($this->externalLink) {
                    $url = $this->externalLink;
                } else {
                    if (isset($row['link']) && $row['link'])
                        $url = $row['link'];
                    else
                        $url = url('app/single-content', array('id' => $row['id'], 'title' => \Application\API\App::prepareUrlString($row['title'])));
                }

                ?>
                <li class="item media">
                    <?
                    if ($this->showImage) {
                        ?>
                        <a class="<?= $this->titleType ?> pull-left flip image-link" href="<?= $url ?>">
                            <?
                            if (isset($row['baseImage']) && $row['baseImage']) {
                                $data_img = '';
                                if (isset($row['secondImage']['image']) && $row['secondImage']['image'])
                                    $data_img = $row['secondImage']['image'];
                                ?>
                                <img data-img="<?= $data_img ?>"
                                     src="<? if (isset($row['baseImage']['image']) && $row['baseImage']['image']) echo $row['baseImage']['image']; ?>"
                                     alt="<? if (isset($row['baseImage']['alt']) && $row['baseImage']['alt']) echo $this->escapeHtml($row['baseImage']['alt']); ?>"
                                     title="<? if (isset($row['baseImage']['title']) && $row['baseImage']['title']) echo $this->escapeHtml($row['baseImage']['title']); ?>"
                                    <? if ((int)$this->responsiveImage) {
                                        echo 'class="img-responsive"';
                                    } ?>>
                            <? } else { ?>
                                <div class="empty-img"></div>
                            <?
                            }
                            ?>
                        </a>
                    <?
                    }
                    //  var_dump($row);
                    ?>
                    <? if ((int)$this->customType != 2) { ?>
                        <div class="text_img_url media-body">
                            <a href="<?= $url ?>">
                                <? if (isset($row['title']) && $row['title'] && $this->showTitle) { ?>
                                    <div class="title <?= $this->titleType ?>">
                                        <?= t($this->escapeHtml($row['title'])) ?>
                                    </div>
                                <? } ?>
                                <? if (isset($row['text']) && $row['text'] && ($this->customType == 1 || $this->customType == 3)) { ?>
                                    <div class="text">
                                        <?= t($row['text']) ?>
                                    </div>
                                <? } ?>
                                <? if ($this->showHits) { ?>
                                    <div class="hits"><?= $row['hits'] ?></div>
                                <? } ?>
                                <? if ($this->showPublished) { ?>
                                    <div class="publishUp"><?=
                                        $this->dateFormat(
                                            (int)$row['publishUp']
                                        ); ?></div>
                                <? } ?>
                            </a>
                        </div>
                    <? } ?>
                </li>
            <?
            }
            ?>
        </ul>
    </div>
    <? if ($this->directionalNav != 2) { ?>
        <div rel='tooltip' class="next" title="<?= t('Next') ?>">
        </div>
    <? } ?>
</div>
<script type="text/javascript">
    <?$this->inlineScript()->captureStart()?>
    $(document).ready(function () {

        $('#content-slider-<?=$this->blockId?>').contentSlider({
            orientation: '<?=$this->orientation?>',
            direction: '<?=$this->direction?>',
            autoscroll: '<?=$this->autoScroll?>',
            interval: <?=$this->interval?>,
            speed: <?=$this->speed?>,
            directionalNav: <?=$this->directionalNav?>,
            visibleCount: <?=$this->visibleCount?>,
            slideCount: <?=$this->slideCount?>
        });

    });
    <?$this->inlineScript()->captureEnd()?>
</script>