<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'Theme\API\ACL'                    => __DIR__ . '/src/Theme/API/ACL.php',
  'Theme\API\Common'                 => __DIR__ . '/src/Theme/API/Common.php',
  'Theme\API\EventManager'           => __DIR__ . '/src/Theme/API/EventManager.php',
  'Theme\API\Table'                  => __DIR__ . '/src/Theme/API/Table.php',
  'Theme\API\Themes'                 => __DIR__ . '/src/Theme/API/Themes.php',
  'Theme\Controller\ThemeController' => __DIR__ . '/src/Theme/Controller/ThemeController.php',
  'Theme\Form\Config'                => __DIR__ . '/src/Theme/Form/Config.php',
  'Theme\Install'                    => __DIR__ . '/src/Theme/Install.php',
  'Theme\Model\Theme'                => __DIR__ . '/src/Theme/Model/Theme.php',
  'Theme\Model\ThemeTable'           => __DIR__ . '/src/Theme/Model/ThemeTable.php',
  'Theme\View\Helper\Partial'        => __DIR__ . '/src/Theme/View/Helper/Partial.php',
);
