<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'ContentSharing\API\ACL'                             => __DIR__ . '/src/ContentSharing/API/ACL.php',
  'ContentSharing\Controller\ContentSharingController' => __DIR__ . '/src/ContentSharing/Controller/ContentSharingController.php',
  'ContentSharing\Form\Config'                         => __DIR__ . '/src/ContentSharing/Form/Config.php',
  'ContentSharing\Install'                             => __DIR__ . '/src/ContentSharing/Install.php',
  'ContentSharing\View\Helper\AddToAny'                => __DIR__ . '/src/ContentSharing/View/Helper/AddToAny.php',
);
