<div>
    <h3 class="page-title">
        <?= t('Edit/Create Category'); ?>
    </h3>

    <div>
        <?
        //        $form = $this->form;
        //        $form->prepare();
        //        echo $this->form()->openTag($form);
        //        foreach ($form->getElements() as $el) {
        //            echo $this->iptFormRow($el);
        //        }
        //        echo $this->iptFormCollection($form->get('buttons'));
        //        echo $this->form()->closeTag();
        print $this->form($this->form);
        ?>
    </div>
</div>