
<p><?=t('ADS_NEW_PAYMENT_SUCCESS')?></p>
<br>
<? if ($this->__PAYMENT_CODE__) { ?>
    <div>
        <span><?= t('ADS_PAYMENT_CODE').' : ' ?></span>
        <span><?= $this->__PAYMENT_CODE__ ?></span>
    </div>
<? } ?>
<? if ($this->__AD_CODE__) { ?>
    <div>
        <span><?= t('ADS_CODE').' : ' ?></span>
        <span><?= $this->__AD_CODE__ ?></span>
    </div>
<? } ?>
<?= $this->__SITE_URL__ ?>