<div>
    <h2 class="page-title">
        مرکز سلامتی/مشاوره
    </h2>
    <h4>
        خلاصه ای از عملکرد مرکز سلامتی/مشاوره
    </h4>
    <dl>
        <dt>
            پزشک/مشاور
        </dt>
        <dd>
            پزشک/مشاور کاربری ایست که در گروه کاربری پزشک/مشاور(یا هر گروه کاربری دیگری که در بخش
            <a href="<?= url('admin/health-center/config') ?>" class="ajax_page_load">
                تنظیمات
            </a>
            مشخص شده باشد) است.
        </dd>
        <dt>
            جدول زمانی
        </dt>
        <dd>
            جدول زمانی هر پزشک/مشاور از طریق
            <a href="<?=url('admin/health-center/doctors')?>" class="ajax_page_load">
            لیست پزشکان/مشاوران
            </a>
            قابل دسترسی است

        </dd>
    </dl>
</div>