<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'PhoneBook\Install'                        => __DIR__ . '/src/Install.php',
  'PhoneBook\API\ACL'                        => __DIR__ . '/src/PhoneBook/API/ACL.php',
  'PhoneBook\Controller\PhoneBookController' => __DIR__ . '/src/PhoneBook/Controller/PhoneBookController.php',
  'PhoneBook\Form\PhoneBook'                 => __DIR__ . '/src/PhoneBook/Form/PhoneBook.php',
  'PhoneBook\Form\PhoneBookSearch'           => __DIR__ . '/src/PhoneBook/Form/PhoneBookSearch.php',
  'PhoneBook\Model\PhoneBook'                => __DIR__ . '/src/PhoneBook/Model/PhoneBook.php',
  'PhoneBook\Model\PhoneBookTable'           => __DIR__ . '/src/PhoneBook/Model/PhoneBookTable.php',
  'Sample\View\Helper\Sample'                => __DIR__ . '/src/PhoneBook/View/Helper/Sample.php',
);
