<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'Page\API\ACL'                   => __DIR__ . '/src/Page/API/ACL.php',
  'Page\API\EventManager'          => __DIR__ . '/src/Page/API/EventManager.php',
  'Page\API\Page'                  => __DIR__ . '/src/Page/API/Page.php',
  'Page\Controller\PageController' => __DIR__ . '/src/Page/Controller/PageController.php',
  'Page\Form\Config'               => __DIR__ . '/src/Page/Form/Config.php',
  'Page\Form\Page'                 => __DIR__ . '/src/Page/Form/Page.php',
  'Page\Form\PageConfig'           => __DIR__ . '/src/Page/Form/PageConfig.php',
  'Page\Form\PageImage'            => __DIR__ . '/src/Page/Form/PageImage.php',
  'Page\Install'                   => __DIR__ . '/src/Page/Install.php',
  'Page\Model\Page'                => __DIR__ . '/src/Page/Model/Page.php',
  'Page\Model\PageTable'           => __DIR__ . '/src/Page/Model/PageTable.php',
  'Page\Model\PageTags'            => __DIR__ . '/src/Page/Model/PageTags.php',
  'Page\Model\PageTagsTable'       => __DIR__ . '/src/Page/Model/PageTagsTable.php',
  'Page\View\Helper\ContentBlock'  => __DIR__ . '/src/Page/View/Helper/ContentBlock.php',
  'Page\View\Helper\Widget'        => __DIR__ . '/src/Page/View/Helper/Widget.php',
);
