CREATE TABLE IF NOT EXISTS `tbl_ads` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(80) DEFAULT NULL,
  `text` text,
  `link` text,
  `address` varchar(300) DEFAULT NULL,
  `name` varchar(200) DEFAULT NULL,
  `mail` varchar(300) DEFAULT NULL,
  `mobile` varchar(100) DEFAULT NULL,
  `fax` varchar(50) DEFAULT NULL,
  `stateId` int(11) DEFAULT NULL,
  `cityId` int(11) DEFAULT NULL,
  `googleLatLong` varchar(300) DEFAULT NULL,
  `smallImage` text,
  `showPm` tinyint(4) NOT NULL DEFAULT '0',
  `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0=>not checked & 1=>approved & 2=>Revoked & 3=>not approved',
  `userId` int(11) NOT NULL DEFAULT '0',
  `createDate` int(11) DEFAULT NULL,
  `expireDate` int(11) DEFAULT NULL,
  `hits` int(11) NOT NULL DEFAULT '0',
  `baseType` int(11) DEFAULT NULL,
  `secondType` int(11) DEFAULT NULL,
  `regType` tinyint(4) DEFAULT '0',
  `time` int(11) NOT NULL DEFAULT '0',
  `starCount` int(11) NOT NULL DEFAULT '0',
  `finalPrice` bigint(20) NOT NULL DEFAULT '0',
  `payerStatus` tinyint(4) DEFAULT '0' COMMENT '0=>not payment , 1=>payment , 2=>have perm و 3=>Deducted from the balance , 4=>free',
  `editStatus` tinyint(4) DEFAULT '0',
  `notifyType` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0=>free , 1=>email , 2=>sms',
  `notifyIds` text,
  PRIMARY KEY (`id`),
  KEY `id` (`id`),
  KEY `title` (`title`),
  KEY `address` (`address`(255)),
  KEY `name` (`name`),
  KEY `fax` (`fax`),
  KEY `stateId` (`stateId`),
  KEY `cityId` (`cityId`),
  KEY `showPm` (`showPm`),
  KEY `status` (`status`),
  KEY `userId` (`userId`),
  KEY `createDate` (`createDate`),
  KEY `expireDate` (`expireDate`),
  KEY `hits` (`hits`),
  KEY `baseType` (`baseType`),
  KEY `secondType` (`secondType`),
  KEY `time` (`time`),
  KEY `starCount` (`starCount`),
  KEY `id_2` (`id`,`title`,`name`,`stateId`,`cityId`,`status`,`userId`,`createDate`,`expireDate`,`hits`,`baseType`,`secondType`,`time`,`starCount`),
  KEY `mobile` (`mobile`),
  KEY `payerStatus` (`payerStatus`),
  KEY `regType` (`regType`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=18 ;



CREATE TABLE IF NOT EXISTS `tbl_ads_order` (
  `baseType` int(11) DEFAULT NULL,
  `secondType` int(11) NOT NULL DEFAULT '0',
  `order` int(11) DEFAULT NULL,
  `homePage` tinyint(4) DEFAULT '0',
  `isRequest` tinyint(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`secondType`),
  KEY `secondType` (`secondType`),
  KEY `order` (`order`),
  KEY `secondType_2` (`secondType`,`order`),
  KEY `baseType` (`baseType`),
  KEY `baseType_2` (`baseType`,`secondType`,`order`,`homePage`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `tbl_ads_ref` (
  `adId` int(11) DEFAULT NULL,
  `roleId` int(11) DEFAULT NULL,
  `userId` int(11) DEFAULT NULL,
  `senderId` int(11) DEFAULT NULL,
  KEY `adId` (`adId`),
  KEY `roleId` (`roleId`),
  KEY `userId` (`userId`),
  KEY `senderId` (`senderId`),
  KEY `adId_2` (`adId`,`roleId`,`userId`,`senderId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;