<?
use User\Module as UserAcl;

if (isset($this->type) && $this->type)
    $flag = false;
else
    $flag = true;
?>
<div>
    <?
    if (isset($this->user)) {
        if ($this->user->id) {
            $this->headLink()->appendStylesheet($this->basePath() . '/css/user-admin.css');
            \JQuery\API\JQuery::loadColorBox($this);
            //only in user profile special button and information in related to user show
        if ($this->specialInformationShow) {
            ?>
            <? if (isAllowed(UserAcl::ADMIN_USER_EDIT) && $flag) {
        if (isCurrentUser($this->user->id) || isAllowed(UserAcl::ADMIN_USER_EDIT_ALL)) {
            ?>
            <a class="toolbar-button button add_button"
               href="<?= $this->url('admin/users/edit', array('id' => $this->user->id)) ?>">
                <?= $this->translate('Edit Account') ?>
            </a>
            <a class="toolbar-button button add_button"
               href="<?= $this->url('admin/users/edit/custom-profile', array('id' => $this->user->id)) ?>">
                <?= $this->translate('Edit Custom Profile') ?>
            </a>
            <a class="toolbar-button button refresh_button"
               href="<?= $this->url('admin/users/change-password', array('id' => $this->user->id)) ?>">
                <?= $this->translate('Change Password') ?>
            </a>
            <a class="toolbar-button button image_button"
               href="<?= url('admin/users/edit-image', array('id' => $this->user->id)) ?>">
                <?= t('Change Image') ?>
            </a>
        <?
        }
        } ?>
            <? if (isAllowed(UserAcl::ADMIN_USER_DELETE) && $flag) {
        if ((isCurrentUser($this->user->id) && isAllowed(UserAcl::ADMIN_USER_DELETE_OWN)) || isAllowed(UserAcl::ADMIN_USER_DELETE_ALL)) {
            ?>
            <a class="toolbar-button button delete_button"
               href="<?= $this->url('admin/users/delete', array('id' => $this->user->id)) ?>">
                <?= $this->translate('Delete Account') ?>
            </a>
        <?
        }
        } ?>
            <h3 class="page-title">
                <?= sprintf($this->translate("%s's Profile"), "<span class='user-name-title emphasize '>" . getUserDisplayName($this->user) . "</span>") ?>
            </h3>
        <? } ?>


            <table class="user-agent-tbl-view">
                <? if ($this->specialInformationShow) { ?>
                    <? if ($this->user->roleName) { ?>
                        <tr>
                            <td class="user-agent-tbl-view-td-title"><?= t('Roles') ?> :</td>
                            <td class="user-agent-tbl-view-td-value"><?= t($this->user->roleName) ?></td>
                            <td width="250" align="center" colspan="2" rowspan="9" class="user-agent-tbl-view-td-title">
                                <? if (!empty($this->user->image)) {
                                    $file_path = getThumbnail()->thumbnail($this->user->image, 200, 200);
                                    ?>
                                    <a class="colorbox img-comment-image"
                                       href="<?= $this->basePath() . $this->user->image ?>"> <img
                                            src="<?= $this->basePath() . $file_path ?>"
                                            alt="<?= getUserDisplayName($this->user) ?>">
                                    </a>
                                <?
                                } else {
                                    $file_path_resize = getThumbnail()->thumbnail($this->basePath() . '/images/not-image.png', 200, 200);
                                    $file_path_base = $this->basePath() . '/images/not-image.png';
                                    ?>
                                    <a class="colorbox" href="<?= $file_path_base ?>">
                                        <img class="img-comment-image" src="<?= $file_path_resize ?>" alt="">
                                    </a>
                                <?
                                }
                                ?>
                            </td>
                        </tr>
                    <?
                    }
                } else {
                    ?>
                    <tr>
                        <td class="user-agent-tbl-view-td-title"><?= t('Roles') ?> :</td>
                        <td class="user-agent-tbl-view-td-value">-------</td>
                        <td align="center" colspan="2" rowspan="9" class="user-agent-tbl-view-td-title">
                            <? if (!empty($this->user->image)) {
                                $file_path = getThumbnail()->thumbnail($this->user->image, 200, 200);
                                ?>
                                <a class="colorbox img-comment-image"
                                   href="<?= $this->basePath() . $this->user->image ?>"> <img
                                        src="<?= $this->basePath() . $file_path ?>"
                                        alt="<?= getUserDisplayName($this->user) ?>">
                                </a>
                            <?
                            } else {
                                $file_path_resize = getThumbnail()->thumbnail($this->basePath() . '/images/not-image.png', 200, 200);
                                $file_path_base = $this->basePath() . '/images/not-image.png';
                                ?>
                                <a class="colorbox" href="<?= $file_path_base ?>">
                                    <img class="img-comment-image" src="<?= $file_path_resize ?>" alt="">
                                </a>
                            <?
                            }
                            ?>
                        </td>
                    </tr>
                <?
                }
                if ($this->user->email) {
                    ?>
                    <tr>
                        <td class="user-agent-tbl-view-td-title"><?= $this->translate('Email') ?> :</td>
                        <td class="user-agent-tbl-view-td-value"><?= $this->user->email ?></td>
                    </tr>
                <?
                }
                if ($this->user->phone) {
                    ?>
                    <tr>
                        <td class="user-agent-tbl-view-td-title"><?= $this->translate('Phone') ?> :</td>
                        <td class="user-agent-tbl-view-td-value"><?= $this->user->phone ?></td>
                    </tr>
                <?
                }
                if ($this->user->mobile) {
                    ?>
                    <tr>
                        <td class="user-agent-tbl-view-td-title"><?= $this->translate('Mobile') ?> :</td>
                        <td class="user-agent-tbl-view-td-value"><?= $this->user->mobile ?></td>
                    </tr>
                <?
                }
                if ($this->user->firstName) {
                    ?>
                    <tr>
                        <td class="user-agent-tbl-view-td-title"><?= $this->translate('First Name') ?> :</td>
                        <td class="user-agent-tbl-view-td-value"><?= $this->user->firstName ?></td>
                    </tr>
                <?
                }
                if ($this->user->lastName) {
                    ?>
                    <tr>
                        <td class="user-agent-tbl-view-td-title"><?= $this->translate('Last Name') ?> :</td>
                        <td class="user-agent-tbl-view-td-value"><?= $this->user->lastName ?></td>
                    </tr>
                <?
                }
                if ($this->user->address) {
                    ?>
                    <tr>
                        <td class="user-agent-tbl-view-td-title"><?= $this->translate('Address') ?> :</td>
                        <td class="user-agent-tbl-view-td-value"><?= $this->user->address ?></td>
                    </tr>
                <?
                }
                if ($this->user->countryTitle || $this->user->stateTitle || $this->user->cityTitle) {
                    ?>
                    <tr>
                        <td class="user-agent-tbl-view-td-title"><?= $this->translate('Location') ?> :</td>
                        <td class="user-agent-tbl-view-td-value"><?=
                            ($this->user->countryTitle ? $this->user->countryTitle . ', ' : '') .
                            ($this->user->stateTitle ? $this->user->stateTitle . ', ' : '') .
                            ($this->user->cityTitle ? $this->user->cityTitle : '') ?></td>
                    </tr>
                <?
                }
                if ($this->user->aboutMe) {
                    ?>
                    <tr>
                        <td class="user-agent-tbl-view-td-title"><?= $this->translate('About Me') ?> :</td>
                        <td class="user-agent-tbl-view-td-value"><?= $this->user->aboutMe ?></td>
                    </tr>
                <? } ?>
            </table>
            <div style="clear: both;"></div>
            <script>
                $(document).ready(function () {
                    RealEstate.params.userId = '<?=$this->user->id?>';
                    RealEstate.loadList();
                });
            </script>
            <?= $this->realestate_list($this->path); ?>
        <?
        }
    }
    ?>
</div>