<h3><?=t('Domain name Samples')?></h3>
<table class="grid" style="width: 320px;" dir="ltr">
    <tr>
        <td class="left-align">*</td>
        <td align="right"><?=t('All domains and sub-domains')?></td>
    </tr>
    <tr>
        <td class="left-align">*.*</td>
        <td align="right"><?=t('All domains and sub-domains')?></td>
    </tr>
    <tr>
        <td class="left-align">*.ipt24.ir</td>
        <td align="right"><?=t('All ipt24.ir sub-domains. exp: a.ipt24.ir')?></td>
    </tr>
    <tr>
        <td class="left-align">sub.*</td>
        <td align="right"><?=t('All domains containing sub-domain named sub')?></td>
    </tr>
</table>