<?
$content = \Theme\API\Themes::renderLayout($this);
$direction = $this->translate('lang_direction'); //rtl ? ltr
$basePath = $this->basePath();
$this->headLink()
    ->prependStylesheet(
        $basePath . TEMPLATE_PATH . '/css/ie10.css',
        'screen',
        'IE 10'
    )
    ->prependStylesheet(
        $basePath . TEMPLATE_PATH . '/css/ie8.css',
        'screen',
        'lt IE 9'
    );

if ($direction == 'rtl')
    $this->headLink()->prependStylesheet($basePath . TEMPLATE_PATH . '/css/bootstrap-rtl.min.css');

$this->headLink()
    ->prependStylesheet($basePath . '/select2/select2-bootstrap.css')
    ->prependStylesheet($basePath . '/select2/select2.css')
    ->prependStylesheet($basePath . TEMPLATE_PATH . '/css/bootstrap-theme.min.css')
    ->prependStylesheet($basePath . TEMPLATE_PATH . '/css/bootstrap.min.css')
    // ->prependStylesheet($basePath . '/css/base-theme/jquery-ui-1.10.1.custom.min.css')
    ->prependStylesheet($basePath . '/css/system.css');


//------------------------------ TEMPLATE STYLE -------------------------------------------
$this->headLink()->appendStylesheet($basePath . TEMPLATE_PATH . '/css/style.css');
if ($direction == 'rtl')
    $this->headLink()->appendStylesheet($basePath . TEMPLATE_PATH . '/css/style-rtl.css');
////-------------------------------------------------------------


$this->headScript()
    // ->prependFile($basePath . '/js/system.jquery.ui.js')
    ->prependFile($basePath . '/js/system.js')
    ->prependFile($basePath . '/js/forms.js')
    ->prependFile($basePath . '/js/jquery.transit.min.js')
    ->prependFile($basePath . '/select2/select2.min.js')
    ->prependFile($basePath . '/js/general-client.js')
    //  ->prependFile($basePath . '/js/jquery-ui-1.10.4.custom.min.js')
    ->prependFile($basePath . TEMPLATE_PATH . '/js/bootstrap.min.js')
    ->prependFile($basePath . '/js/jquery-1.9.1.min.js')
    ->prependFile(
        $basePath . TEMPLATE_PATH . '/js/respond.min.js',
        'text/javascript',
        array('conditional' => 'lt IE 9')
    )
    ->prependFile(
        $basePath . TEMPLATE_PATH . '/js/html5shiv.min.js',
        'text/javascript',
        array('conditional' => 'lt IE 9')
    );

//------------------------------ TEMPLATE JAVASCRIPT -------------------------------------------
$this->headScript()->appendFile($basePath . TEMPLATE_PATH . '/js/template.js');

//---------------------------------- BLOCKS -----------------------------------------------//
$before_main_content = $this->blocks('before_main_content');
$after_main_content = $this->blocks('after_main_content');
$header = $this->blocks('header');
$footer = $this->blocks('footer');
$col_right = $this->blocks('col_right');
$col_left = $this->blocks('col_left');

$mainColSize = 12;
if ($col_left && $col_right)
    $mainColSize = 6;
if ($col_right || $col_left)
    $mainColSize = 9;

?>

<!DOCTYPE html>
<html lang="fa" xmlns="http://www.w3.org/1999/html">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <?= $this->head() ?>
    <?= $this->headTitle() ?>
    <?= $this->headMeta() ?>
    <?= $this->headLink() ?>
    <?= $this->headScript() ?>
</head>
<body>
<div id="container">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 box_intro">
                <img class="img-responsive"
                     src="<?= $basePath . TEMPLATE_PATH . '/images/main/logo_for_mainpage3.jpg' ?>">

                <div class="row box_intro_menu">
                    <div class="col-xs-3 col-xs-offset-2 col-sm-3 col-sm-offset-2 col-md-3 col-md-offset-2 mashaghel ">
                        <a href="<?= url('app/ad/search', array('baseType' => 1000)) ?>">
                            <img src="<?= $basePath . TEMPLATE_PATH . '/images/mashaghel_base.png' ?>"
                                 class="img-responsive">
                        </a>
                    </div>
                    <div class="col-xs-3 col-xs-offset-2 col-sm-3 col-sm-offset-2 col-md-3 col-md-offset-2 resume">
                        <a href="<?= url('app/ad/search', array('baseType' => 2000)) ?>">
                            <img src="<?= $basePath . TEMPLATE_PATH . '/images/resume_base.png' ?>" class="img-responsive">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- <div class="container-fluid footer sticky-bottom">
        <div class="row">
            <div class=" col-md-12">
                <div class="">
                    <? /*
                    $startYear = mktime(0, 0, 0, 6, 0, 2012);
                    $startYear = $this->dateFormat($startYear, \Localization\View\Helper\DateFormat::YEAR_ONLY);
                    $nowYear = $this->dateFormat(time(), \Localization\View\Helper\DateFormat::YEAR_ONLY);
                    */
    ?>
                    <p align="center">
                        <? /*= t('APPLICATION_BROWSERS') */ ?>
                    </p>

                    <p align="center">
                        <span><? /*= sprintf(t('APPLICATION_RIGHTS'), '[COMPANY]') */ ?></span>
                        <span dir="ltr"><? /*= sprintf(t('APPLICATION_COPY_RIGHT'), $startYear, $nowYear) */ ?></span>
                        &nbsp; .
                        <span><? /*= t('APPLICATION_SUPPORT') */ ?></span> .
                        <span><? /*= t('APPLICATION_POWERED_BY') */ ?></span>
                    </p>
                </div>
            </div>
        </div>
    </div>-->
</div>
<?= $this->inlineScript() ?>
</body>
</html>
