<div>
    <label>
        <?=t('Name').' :'?>
    </label>
    <p>
        <?=$this->__NAME__?>
    </p>
    <br/>
    <label>
        <?=t('Email').' :'?>
    </label>
    <p>
        <?=$this->__EMAIL__?>
    </p>
    <br/>
    <label>
        <?=t('Mobile').' :'?>
    </label>
    <p>
        <?=$this->__MOBILE__?>
    </p>
    <br/>
    <label>
        <?=t('Description').' :'?>
    </label>
    <p>
        <?=$this->__DESCRIPTION__?>
    </p>
    <br/>
    <label>
        <?=t('Type').' :'?>
    </label>
    <p>
        <?=$this->__TYPE__?>
    </p>
    <br/>
    <label>
        <?=t('Date').' :'?>
    </label>
    <p>
        <?= $this->__DATE__ ?>
    </p>
    <br/>
    <label>
        <?=t('Section').' :'?>
    </label>
    <p>
        <?=$this->__GETTER__?>
    </p>
    <br/>
</div>