<?
if (isset($this->type) && $this->type)
    $flag = false;
else
    $flag = true;
?>
<div class="box-view-user-info">
    <?
    if (isset($this->user)) {
        if ($this->user->id) {
            $this->headLink()->appendStylesheet($this->basePath() . '/css/user-admin.css');
            \JQuery\API\JQuery::loadColorBox($this);
            //only in user profile special button and information in related to user show
            if ($this->specialInformationShow) {
                echo $this->partial('user/user/user-toolbar', array('userId' => $this->user->id, 'flag' => $flag));
                ?>

                <h3 class="page-title">
                    <?= sprintf($this->translate("%s's Profile"), "<span class='user-name-title emphasize '>" . getUserDisplayName($this->user) . "</span>") ?>
                </h3>
            <? } ?>

            <? if (!empty($this->user->image))
                $file_path = getThumbnail()->resize($this->user->image, 160, 170);
            else
                $file_path = getThumbnail()->resize($this->basePath() . '/images/not-image.png', 120, 120); //resize image;
            ?>
            <div class="user-profile-image">
                <a class="colorbox" href="<?= $this->basePath() . $this->user->image ?>"> <img
                        src="<?= $this->basePath() . $file_path ?>"
                        alt="<?= getUserDisplayName($this->user) ?>">
                </a>
            </div>

            <table class="view-user-info">
                <? if ($this->specialInformationShow && $this->path != 'app') { ?>
                    <? if ($this->user->roleName) { ?>
                        <tr>
                            <td><?= t('Roles') ?> :</td>
                            <td><?= t($this->user->roleName) ?></td>
                        </tr>
                    <?
                    }
                }
                if ($this->user->email) {
                    ?>
                    <tr>
                        <td><?= $this->translate('Email') ?> :</td>
                        <td><img src="<?= getThumbnail()->createImage($this->user->email); ?>"></td>
                    </tr>
                <?
                }
                if ($this->user->phone) {
                    ?>
                    <tr>
                        <td><?= $this->translate('Phone') ?> :</td>
                        <td><?= $this->user->phone ?></td>
                    </tr>
                <?
                }
                if ($this->user->mobile && $this->path != 'app') {
                    ?>
                    <tr>
                        <td><?= $this->translate('Mobile') ?> :</td>
                        <td><?= $this->user->mobile ?></td>
                    </tr>
                <?
                }
                if ($this->user->firstName) {
                    ?>
                    <tr>
                        <td><?= $this->translate('First Name') ?> :</td>
                        <td><?= $this->user->firstName ?></td>
                    </tr>
                <?
                }
                if ($this->user->lastName) {
                    ?>
                    <tr>
                        <td><?= $this->translate('Last Name') ?> :</td>
                        <td><?= $this->user->lastName ?></td>
                    </tr>
                <?
                }
                if ($this->user->address) {
                    ?>
                    <tr>
                        <td><?= $this->translate('Address') ?> :</td>
                        <td><?= $this->user->address ?></td>
                    </tr>
                <?
                }
                if ($this->user->countryTitle || $this->user->stateTitle || $this->user->cityTitle) {
                    ?>
                    <tr>
                        <td><?= $this->translate('Location') ?> :</td>
                        <td><?=
                            ($this->user->countryTitle ? $this->user->countryTitle . ', ' : '') .
                            ($this->user->stateTitle ? $this->user->stateTitle . ', ' : '') .
                            ($this->user->cityTitle ? $this->user->cityTitle : '') ?></td>
                    </tr>
                <?
                }
                if ($this->user->aboutMe) {
                    ?>
                    <tr>
                        <td><?= $this->translate('About Me') ?> :</td>
                        <td><?= $this->user->aboutMe ?></td>
                    </tr>
                <? } ?>
            </table>
            <div style="clear: both;"></div>
        <?
        }
    }
    ?>
</div>
<div class="user-agent-estates">
    <script>
        $(document).ready(function () {
            RealEstate.params.userId = '<?=$this->user->id?>';
            RealEstate.loadList();
        });
    </script>
    <?= $this->realestate_list($this->path); ?>
</div>