<style>
    #to{
        text-align: left;
    }
    .hidden{
        display: none;
    }
</style>
<div>
    <h3 class="page-title">
        <?= $this->translate('Send News Letter'); ?>
    </h3>
    <div>
        <?
        $form = $this->form;
        $form->prepare();
        echo $this->form()->openTag($form);
        foreach ($form->getElements() as $el) {
            echo $this->iptFormRow($el);
        }
        echo $this->form()->closeTag();
        ?>
    </div>
</div>
<script type="text/javascript">

    $(document).ready(function () {
        <?\Application\API\App::setEditor('body',$this)?>
    });
</script>