<?
$this->headLink()->prependStylesheet($this->basePath() . '/css/page.css');
//if ($this->showTags) {
//
?>
    <!--    <div class="content-tags">-->
    <!--        --><? //
//        if (!$this->flagShowAllInfo) {
//            $tagRouteParams = array();
//            if ($this->tags)
//                foreach ($this->tags as $tag) {
//
//                    $tagRouteParams['tagName'] = \Application\API\App::prepareUrlString($tag['itemName']);
//                    $tagRouteParams['tagId'] = $tag['id'];
//
?>
    <!--                    <div class="box-content-tag">-->
    <!--                        <a href="--><? //= url('app/content', $tagRouteParams) ?><!--">-->
    <!--                            <p>--><? //= $this->escapeHtml($tag['itemName']) ?><!--</p>-->
    <!--                        </a>-->
    <!---->
    <!--                        <div class="line-gray"></div>-->
    <!--                        --><? // if ($this->showTags == 2) { ?>
    <!--                            <div>-->
    <!--                                --><? // if (isset($this->fileArray[$tag['id']])) { ?>
    <!--                                    <img src="--><? //= $this->fileArray[$tag['id']]['fPath'] ?><!--"-->
    <!--                                         alt="--><? //= $this->fileArray[$tag['id']]['alt'] ?><!--"-->
    <!--                                         title="--><? //= $this->fileArray[$tag['id']]['title'] ?><!--">-->
    <!--                                --><? // } ?>
    <!--                            </div>-->
    <!--                        --><? // } ?>
    <!--                    </div>-->
    <!--                --><? //
//                }
//        } else {
//            foreach ($this->tags as $tag) {
//
?>
    <!--                <br/>-->
    <!--                <div class="box-content-tag-all-info">-->
    <!--                    <p>--><? //= $this->escapeHtml($tag['itemName']) ?><!--</p>-->
    <!---->
    <!--                    <div class="line-gray"></div>-->
    <!--                    <div class="main-box">-->
    <!--                        --><? // if ($this->showTags == 2) { ?>
    <!--                            --><? // if (isset($this->fileArray[$tag['id']])) { ?>
    <!--                                <img src="--><? //= $this->fileArray[$tag['id']]['fPath'] ?><!--"-->
    <!--                                     alt="--><? //= $this->fileArray[$tag['id']]['alt'] ?><!--"-->
    <!--                                     title="--><? //= $this->fileArray[$tag['id']]['title'] ?><!--">-->
    <!--                            --><? // } ?>
    <!--                        --><? // } ?>
    <!--                        <div class="box-desc">-->
    <!--                            --><? //= $tag['itemText'] ?>
    <!--                            <div style="clear: both;"></div>-->
    <!--                        </div>-->
    <!--                    </div>-->
    <!--                </div>-->
    <!--            --><? //
//            }
//        }
//
?>
    <!--    </div>-->
    <!--    <div style="clear: both"></div>-->
<? //
//}
if ($this->paginator->count()) {
    ?>
    <articles class='articles-intro-list'>
        <?
        $pageRouteParams = array();
        /* @var $page \Page\Model\Page */
        foreach ($this->paginator as $page) {
            $pageRouteParams['id'] = $page['id'];
            $pageRouteParams['title'] = \Application\API\App::prepareUrlString($page['pageTitle']);
            ?>
            <article>
                <?
                $image = unserialize($page->image);
                if (isset($image['image']) && $image['image']) {
                $img = getThumbnail()->resize($image['image'], 250, 200); //resize image
                ?>
                <a href="<?= url('app/single-content', $pageRouteParams) ?>">
                    <img
                        src="<?= $img ?>"
                        alt="<? if (isset($image['alt'])) echo $this->escapeHtml($image['alt']); ?>"
                        title="<? if (isset($image['title'])) echo $this->escapeHtml($image['title']); ?>"
                        <? if ((int)$this->responsiveImage) {
                            echo 'class="img-responsive"';
                        } ?>>
                    <? } else { ?>
                        <div class="empty-img"></div>
                    <?
                    }
                    ?>
                    <!-- <span class="desc_icon"></span>-->
                    <span><?= t('PRODUCT_DESC', 'theme') ?></span>
                </a>
            </article>
        <?
        }
        ?>
    </articles>
    <div style="clear: both"></div>
    <div class="pager">
        <?
        /* @var $pages \Zend\Paginator\Paginator */
        echo $this->paginationControl($this->paginator,
            'Sliding',
            'application/pagination/search.phtml', array('route' => $this->route, 'route_params' => $this->routeParams, 'route_options' => $this->route_options));
        ?>
    </div>
    <?
    $this->body()->class[] = 'articles';
}
?>