<?
$direction = $this->translate('lang_direction'); //rtl ? ltr
$basePath = $this->basePath();
$this->headLink()
    ->prependStylesheet(
        $basePath . TEMPLATE_PATH . '/css/ie10.css',
        'screen',
        'IE 10'
    )
    ->prependStylesheet(
        $basePath . TEMPLATE_PATH . '/css/ie8.css',
        'screen',
        'lt IE 9'
    );

//if ($direction == 'rtl')
//    $this->headLink()->prependStylesheet($basePath . TEMPLATE_PATH . '/css/bootstrap-rtl.min.css');

//$this->headLink()
//    ->prependStylesheet($basePath . '/select2/select2-bootstrap.css')
//    ->prependStylesheet($basePath . '/select2/select2.css')
//    ->prependStylesheet($basePath . TEMPLATE_PATH . '/css/bootstrap-theme.min.css')
//    ->prependStylesheet($basePath . TEMPLATE_PATH . '/css/bootstrap.min.css')
//    ->prependStylesheet($basePath . '/css/system.css');


//------------------------------ TEMPLATE STYLE -------------------------------------------
$this->headLink()->appendStylesheet($basePath . TEMPLATE_PATH . '/css/style.css');
if ($direction == 'rtl')
    $this->headLink()->appendStylesheet($basePath . TEMPLATE_PATH . '/css/style-rtl.css');
////-------------------------------------------------------------


$this->headScript()
//    ->prependFile($basePath . '/js/system.jquery.ui.js')
//    ->prependFile($basePath . '/js/system.js')
//    ->prependFile($basePath . '/js/forms.js')
//    ->prependFile($basePath . '/js/jquery.transit.min.js')
//    ->prependFile($basePath . '/select2/select2.min.js')
//    ->prependFile($basePath . '/js/general-client.js')
//    ->prependFile($basePath . TEMPLATE_PATH . '/js/bootstrap.min.js')
    ->prependFile($basePath . '/js/jquery-1.9.1.min.js');
//    ->prependFile(
//        $basePath . TEMPLATE_PATH . '/js/respond.min.js',
//        'text/javascript',
//        array('conditional' => 'lt IE 9')
//    )
//    ->prependFile(
//        $basePath . TEMPLATE_PATH . '/js/html5shiv.min.js',
//        'text/javascript',
//        array('conditional' => 'lt IE 9')
//    );

//------------------------------ TEMPLATE JAVASCRIPT -------------------------------------------
//$this->headScript()->appendFile($basePath . TEMPLATE_PATH . '/js/template.js');


//$flashMS = trim($this->flashMessenger()->render());
?>

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <?= $this->head(false) ?>
    <?= $this->headTitle() ?>
    <?= $this->headMeta() ?>
    <?= $this->headLink() ?>
    <?= $this->headScript() ?>
</head>
<!-- The #page-top ID is part of the scrolling feature - the data-spy and data-target are part of the built-in Bootstrap scrollspy function -->
<body>
<div id="body">
    <?= $this->content ?>
</div>
<!--<section id="main_content" class="main_content">-->
<!--    <div class="container my-container">-->
<!--        <div class="row">-->
<!--            --><?// if (!empty($flashMS)) { ?>
<!--                <div class="col-xs-12">-->
<!--                    <div id="system_messages"> --><?//= $flashMS ?><!--</div>-->
<!--                </div>-->
<!--            --><?// } ?>
<!---->
<!--            <div class="col-md-12">-->
<!--                -->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--</section>-->
<?= $this->inlineScript() ?>
</body>
</html>