<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'GeographicalAreas\API\ACL'                      => __DIR__ . '/src/GeographicalAreas/API/ACL.php',
  'GeographicalAreas\Controller\AreaController'    => __DIR__ . '/src/GeographicalAreas/Controller/AreaController.php',
  'GeographicalAreas\Controller\CityController'    => __DIR__ . '/src/GeographicalAreas/Controller/CityController.php',
  'GeographicalAreas\Controller\CountryController' => __DIR__ . '/src/GeographicalAreas/Controller/CountryController.php',
  'GeographicalAreas\Controller\IndexController'   => __DIR__ . '/src/GeographicalAreas/Controller/IndexController.php',
  'GeographicalAreas\Controller\StateController'   => __DIR__ . '/src/GeographicalAreas/Controller/StateController.php',
  'GeographicalAreas\Form\Area'                    => __DIR__ . '/src/GeographicalAreas/Form/Area.php',
  'GeographicalAreas\Form\City'                    => __DIR__ . '/src/GeographicalAreas/Form/City.php',
  'GeographicalAreas\Form\Country'                 => __DIR__ . '/src/GeographicalAreas/Form/Country.php',
  'GeographicalAreas\Form\State'                   => __DIR__ . '/src/GeographicalAreas/Form/State.php',
  'GeographicalAreas\Install'                      => __DIR__ . '/src/GeographicalAreas/Install.php',
  'GeographicalAreas\Model\City'                   => __DIR__ . '/src/GeographicalAreas/Model/City.php',
  'GeographicalAreas\Model\CityArea'               => __DIR__ . '/src/GeographicalAreas/Model/CityArea.php',
  'GeographicalAreas\Model\CityAreaTable'          => __DIR__ . '/src/GeographicalAreas/Model/CityAreaTable.php',
  'GeographicalAreas\Model\CityTable'              => __DIR__ . '/src/GeographicalAreas/Model/CityTable.php',
  'GeographicalAreas\Model\Country'                => __DIR__ . '/src/GeographicalAreas/Model/Country.php',
  'GeographicalAreas\Model\CountryTable'           => __DIR__ . '/src/GeographicalAreas/Model/CountryTable.php',
  'GeographicalAreas\Model\State'                  => __DIR__ . '/src/GeographicalAreas/Model/State.php',
  'GeographicalAreas\Model\StateTable'             => __DIR__ . '/src/GeographicalAreas/Model/StateTable.php',
);
