<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'ECommerce\API\Product'                         => __DIR__ . '/src/ECommerce/API/Product.php',
  'ECommerce\Controller\ProductAdminController'   => __DIR__ . '/src/ECommerce/Controller/ProductAdminController.php',
  'ECommerce\Form\Product\Details'                => __DIR__ . '/src/ECommerce/Form/Product/Details.php',
  'ECommerce\Form\Product\General'                => __DIR__ . '/src/ECommerce/Form/Product/General.php',
  'ECommerce\Form\Product\Types\Code'             => __DIR__ . '/src/ECommerce/Form/Product/Types/Code.php',
  'ECommerce\Form\Product\Types\DownloadableFile' => __DIR__ . '/src/ECommerce/Form/Product/Types/DownloadableFile.php',
  'ECommerce\Form\Product\Types\PhysicalItem'     => __DIR__ . '/src/ECommerce/Form/Product/Types/PhysicalItem.php',
  'ECommerce\Form\Product\Types'                  => __DIR__ . '/src/ECommerce/Form/Product/Types.php',
  'ECommerce\Form\Product'                        => __DIR__ . '/src/ECommerce/Form/Product.php',
  'ECommerce\Install'                             => __DIR__ . '/src/ECommerce/Install.php',
  'ECommerce\Model\ProductTable'                  => __DIR__ . '/src/ECommerce/Model/ProductTable.php',
);
