<?
//$content = \Theme\API\Themes::renderLayout($this);
$direction = $this->translate('lang_direction'); //rtl ? ltr
$bootstrap = $direction == 'rtl' ? '/css/bootstrap.rtl.min.css' : '/css/bootstrap.min.css';
$basePath = $this->basePath();
$path = $basePath . TEMPLATE_PATH;
$this->headLink()
    ->prependStylesheet(
        $basePath . TEMPLATE_PATH . '/css/ie10.css',
        'screen',
        'IE 10')
    ->prependStylesheet(
        $basePath . TEMPLATE_PATH . '/css/ie.css',
        'screen',
        'lt IE 9'
    )
    ->prependStylesheet($basePath . '/css/system.css')
    ->prependStylesheet($basePath . '/select2/select2.css')
    ->prependStylesheet($basePath . '/css/base-theme/jquery-ui-1.10.1.custom.min.css')
    ->prependStylesheet($basePath . TEMPLATE_PATH . $bootstrap)
    ->prependStylesheet($basePath . '/css/reset.min.css');

//------------------------------ TEMPLATE STYLE -------------------------------------------
$this->headLink()->appendStylesheet($basePath . TEMPLATE_PATH . '/css/style.css');
if ($direction == 'rtl')
    $this->headLink()->appendStylesheet($basePath . TEMPLATE_PATH . '/css/style-rtl.css');
////-------------------------------------------------------------


$this->headScript()
    ->prependFile($basePath . '/js/system.jquery.ui.buttons.js')
    ->prependFile($basePath . '/js/system.jquery.ui.js')
    ->prependFile($basePath . '/js/system.js')
    ->prependFile($basePath . '/js/forms.js')
    ->prependFile($basePath . '/js/jquery.hoverIntent.min.js')
    ->prependFile($basePath . '/js/jquery.transit.min.js')
    ->prependFile($basePath . '/js/general-client.js')
    ->prependFile($basePath . '/select2/select2.min.js')
    ->prependFile($basePath . '/js/jquery-ui-1.10.1.custom.min.js')
    ->prependFile($basePath . '/js/jquery-1.9.1.min.js')
    ->prependFile(
        $basePath . TEMPLATE_PATH . '/js/respond.min.js',
        'text/javascript',
        array('conditional' => 'lt IE 9')
    );

//------------------------------ TEMPLATE JAVASCRIPT -------------------------------------------
$this->headScript()->appendFile($basePath . TEMPLATE_PATH . '/js/template.js');
if (SYSTEM_LANG != 'en')
    $this->headScript()->appendFile($basePath . '/select2/select2_locale_' . SYSTEM_LANG . '.js');

$user_block = $this->user_logged_in_block();
if (!$user_block) {
    $user_login_block = $this->user_login_block();
}

$slider = $this->blocks('col-slider');
$menu = $this->blocks('col-top-menu');
$logo = $this->blocks('col-logo');
$colRight = $this->blocks('col-right');
$colLeft = $this->blocks('col-left');
$bodyClass = '';
if ($slider)
    $bodyClass = 'has-slider';
?>

<!DOCTYPE html>
<html lang="fa" xmlns="http://www.w3.org/1999/html">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <?= $this->head() ?>
    <?= $this->headTitle() ?>
    <?= $this->headMeta() ?>
    <?= $this->headLink() ?>
    <?= $this->headScript() ?>
</head>
<body>

<div class="container-fluid header">
    <div class="row">
        <div class="col-md-12">
            <div class="box-header fix-menu">
                <?= $this->langSwitcher(null) ?>
                <? if (!$user_block) { ?>
                    <div class="sign-up">
                        <a href="">
                            <span>
                                <?= t('Sign Up') ?>
                            </span>
                        </a>
                    </div>
                <? } ?>
                <div id="user_popup_container">
                    <?
                    if (!$user_block) {
                        ?>
                        <div class="box user_login_popup" id="user_login_popup">
                            <?= $user_login_block ?>
                        </div>
                        <div class="box user_login_box">
                            <a id="user_login_link"
                               href="<?= url('app/user/login') ?>"><span><?= t('Login') ?></span></a>
                        </div>
                    <?
                    } else {
                        if (isAllowed(\Application\Module::ADMIN)) {
                            ?>
                            <div class="box admin_link_box">
                                <a href="<?= url('admin') ?>"><span><?= t('Administration') ?></span></a>
                            </div>
                        <?
                        }
                        echo $user_block;
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid container-menu">
    <div class="row">
        <div class="col-md-12 box-top-menu">
            <?
            if ($menu)
                echo $menu;
            ?>
        </div>
        <div id="logo" class="col-md-2">
            <?= $logo ?>
        </div>
    </div>
</div>
<div class="container-fluid container-slider">
    <div class="row">
        <div class="col-md-12">
            <?
            if ($slider)
                echo $slider;
            ?>
        </div>
    </div>
</div>
<div id="body" class="<?= $bodyClass ?>">
    <?if ($colLeft)
        echo $colLeft; ?>
    <?= $content ?>
    <?if ($colRight)
        echo $colRight; ?>
</div>
<div class="container contact-bottom">
    <div class="row">
        <div class="col-md-12">
            <div class="box-contact-bottom">
                <div class="contact-part-1">
                   <span class="label">
                       <?= t('Address') ?>
                   </span>
                   <span class="text">
                       <?= t('Application_IPT_ADDRESS') ?>
                   </span>
                </div>
                <div class="contact-part-2">
                   <span class="label">
                       <?= t('Phone') ?>
                   </span>
                   <span class="text">
                       0411-3250011
                   </span>
                </div>
                <div class="contact-part-3">
                   <span class="label">
                       <?= t('Contact Us') ?>
                   </span>

                    <div>
                        <a href="#" target="_blank">
                        <span class="text">
                            Facebook
                        </span>
                        <span class="fav-img">
                            <img alt="Facebook" title="Facebook" src="<?= $path ?>/images/socials/f.png"
                                 class="img-responsive">
                        </span>
                        </a>
                    </div>
                    <div>
                        <a href="#" target="_blank">
                        <span class="text">
                            Linkedin
                        </span>
                        <span class="fav-img">
                            <img alt="Linkedin" title="Linkedin" src="<?= $path ?>/images/socials/L.png"
                                 class="img-responsive">
                        </span>
                        </a>
                    </div>
                    <div>
                        <a href="#" target="_blank">
                        <span class="text">
                            Twitter
                        </span>
                        <span class="fav-img">
                            <img alt="Twitter" title="Twitter" src="<?= $path ?>/images/socials/t.png"
                                 class="img-responsive">
                        </span>
                        </a>
                    </div>
                    <div>
                        <a href="#" target="_blank">
                        <span class="text">
                            Google+
                        </span>
                        <span class="fav-img">
                            <img alt="Google+" title="Google+" src="<?= $path ?>/images/socials/g.png"
                                 class="img-responsive">
                        </span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid container-footer">
    <div class="row">
        <div class="col-md-12">
            <div class="bottom-footer">
                <?
                $startYear = mktime(0, 0, 0, 6, 0, 2012);
                $startYear = $this->dateFormat($startYear, \Localization\View\Helper\DateFormat::YEAR_ONLY);
                $nowYear = $this->dateFormat(time(), \Localization\View\Helper\DateFormat::YEAR_ONLY);
                ?>
                <p align="center">
                    <?= t('APPLICATION_BROWSERS') ?>
                </p>

                <p align="center">
                    <span><?= sprintf(t('APPLICATION_RIGHTS'), 'Azar Ideh Pardaz Tabriz') ?></span>
                    <span dir="ltr"><?= sprintf(t('APPLICATION_COPY_RIGHT'), $startYear, $nowYear) ?></span>
                    &nbsp; .
                    <span><?= t('APPLICATION_SUPPORT') ?></span> .
                    <span><?= t('APPLICATION_POWERED_BY') ?></span>
                </p>
            </div>
        </div>
    </div>
</div>

<?= $this->inlineScript() ?>
</body>
</html>
<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date();
        a = s.createElement(o),
            m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-50020021-1', 'ipt24.ir');
    ga('send', 'pageview');
</script>