<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Exlord
 * Date: 10/21/13
 * Time: 10:25 AM
 */
?>

<div id="real-estate-widget">
    <div class="real-estate-widget-header">
        <label class="real-estate-widget-header-text">
            <?= t('Real Estate') ?>
        </label>
    </div>
    <? if(isAllowed(\RealEstate\Module::ADMIN_REAL_ESTATE_WIDGET)){ ?>
    <table cellspacing="0" cellpadding="0" border="0" class="real-estate-widget-tbl">
        <tr class="real-estate-widget-tbl-tr1">
            <td class="real-estate-widget-tbl-td-title"><a class="real-estate-widget-tbl-td-title-links" href="<?=url('admin/real-estate')?>" ><?= t('Number of all RealEstates') ?></a></td>
            <td class="real-estate-widget-tbl-td-content"><b class="digit"><?= localizedDigits($this->data['count']['all']) ?></b></td>
        </tr>
        <tr class="real-estate-widget-tbl-tr2">
            <td class="real-estate-widget-tbl-td-title"><a class="real-estate-widget-tbl-td-title-links" href="<?=url('admin/real-estate',array(), array('query' => array('grid_filter_isRequest'=>1)))?>" ><?= t('Number of all Requested Estates') ?></a></td>
            <td class="real-estate-widget-tbl-td-content"><b class="digit"><?= localizedDigits($this->data['count']['requested']) ?></b></td>
        </tr>
        <tr class="real-estate-widget-tbl-tr1">
            <td class="real-estate-widget-tbl-td-title"><a class="real-estate-widget-tbl-td-title-links" href="<?=url('admin/real-estate',array(), array('query' => array('grid_filter_status'=>0)))?>" ><?= t('Number of Not Approved RealEstates') ?></a></td>
            <td class="real-estate-widget-tbl-td-content"><b class="digit"><?= localizedDigits($this->data['count']['not_approved']) ?></b></td>
        </tr>
        <tr class="real-estate-widget-tbl-tr2">
            <td class="real-estate-widget-tbl-td-title"><a class="real-estate-widget-tbl-td-title-links" href="<?=url('admin/real-estate',array(), array('query' => array('grid_filter_status'=>1)))?>" ><?= t('Number of Approved RealEstates') ?></a></td>
            <td class="real-estate-widget-tbl-td-content"><b class="digit"><?= localizedDigits($this->data['count']['approved']) ?></b></td>
        </tr>
        <tr class="real-estate-widget-tbl-tr1">
            <td class="real-estate-widget-tbl-td-title"><a class="real-estate-widget-tbl-td-title-links" href="<?=url('admin/real-estate',array(), array('query' => array('grid_filter_status'=>2)))?>" ><?= t('Number of Archived RealEstates') ?></a></td>
            <td align='center'><b class="digit"><?= localizedDigits($this->data['count']['archived']) ?></b></td>
        </tr>
        <tr class="real-estate-widget-tbl-tr2">
            <td class="real-estate-widget-tbl-td-title"><a class="real-estate-widget-tbl-td-title-links" href="<?=url('admin/real-estate',array(), array('query' => array('grid_filter_status'=>3)))?>" ><?= t('Number of Transferred RealEstates') ?></a></td>
            <td class="real-estate-widget-tbl-td-content"><b class="digit"><?= localizedDigits($this->data['count']['transferred']) ?></b></td>
        </tr>
        <tr class="real-estate-widget-tbl-tr1">
            <td class="real-estate-widget-tbl-td-title"><a class="real-estate-widget-tbl-td-title-links" href="<?=url('admin/real-estate',array(), array('query' => array('grid_filter_status'=>4)))?>" ><?= t('Number of Canceled RealEstates') ?></a></td>
            <td class="real-estate-widget-tbl-td-content"><b class="digit"><?= localizedDigits($this->data['count']['canceled']) ?></b></td>
        </tr>
        <tr class="real-estate-widget-tbl-tr2">
            <td class="real-estate-widget-tbl-td-title"><a class="real-estate-widget-tbl-td-title-links" href="<?=url('admin/real-estate',array(), array('query' => array('grid_filter_status'=>5)))?>" ><?= t('Number of Deleted RealEstates') ?></a></td>
            <td class="real-estate-widget-tbl-td-content"><b class="digit"><?= localizedDigits($this->data['count']['deleted']) ?></b></td>
        </tr>
        <tr class="real-estate-widget-tbl-tr1">
            <td class="real-estate-widget-tbl-td-title"><a class="real-estate-widget-tbl-td-title-links" href="<?=url('admin/real-estate',array(), array('query' => array('grid_filter_isSpecial'=>1)))?>" ><?= t('Number of Special RealEstates') ?></a></td>
            <td class="real-estate-widget-tbl-td-content"><b class="digit"><?= localizedDigits($this->data['count']['special']) ?></b></td>
        </tr>
    </table>
    <?}?>
</div>