<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'Domain\API\ACL'                  => __DIR__ . '/src/Domain/API/ACL.php',
  'Domain\API\Domain'               => __DIR__ . '/src/Domain/API/Domain.php',
  'Domain\Controller\Domain'        => __DIR__ . '/src/Domain/Controller/Domain.php',
  'Domain\Form\Domain'              => __DIR__ . '/src/Domain/Form/Domain.php',
  'Domain\Install'                  => __DIR__ . '/src/Domain/Install.php',
  'Domain\Model\Domain'             => __DIR__ . '/src/Domain/Model/Domain.php',
  'Domain\Model\DomainContentTable' => __DIR__ . '/src/Domain/Model/DomainContentTable.php',
  'Domain\Model\DomainTable'        => __DIR__ . '/src/Domain/Model/DomainTable.php',
);
