<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'Logger\API\ACL'                     => __DIR__ . '/src/Logger/API/ACL.php',
  'Logger\Controller\LoggerController' => __DIR__ . '/src/Logger/Controller/LoggerController.php',
  'Logger\Install'                     => __DIR__ . '/src/Logger/Install.php',
  'Logger\Model\Log'                   => __DIR__ . '/src/Logger/Model/Log.php',
  'Logger\Model\LogTable'              => __DIR__ . '/src/Logger/Model/LogTable.php',
);
