<?php
/**
 * Created by PhpStorm.
 * User: Exlord (adeli.farhad@gmail.com)
 * Date: 5/14/14
 * Time: 9:29 AM
 */

namespace System\DB\Sql;


use Zend\Db\Sql\Exception;
use Zend\Db\Sql\Having;
use Zend\Db\Sql\Where;

class Select extends \Zend\Db\Sql\Select
{
    const JOIN_COLUMNS = 'join_columns';

    public function reset($part)
    {
        switch ($part) {
            case self::JOIN_COLUMNS:
                foreach ($this->joins as &$join) {
                    $join['columns'] = array();
                }
                break;
        }
        return parent::reset($part); // TODO: Change the autogenerated stub
    }

} 