<div>
    <h3 class="page-title">
        صفحه اصلی مدیریت
    </h3>

    <p>
        برای شخصی سازی ویجت های این صفحه به قسمت
        <a class="ajax_page_load" href="<?= url('admin/configs') ?>">
            تنظیمات
        </a>
        »
        <a class="ajax_page_load" href="<?= url('admin/configs/widgets') ?>">
            ایزار های صفحه اصلی مدیریت
        </a>
        مراجعه کنید.
    </p>
</div>