<div>
    <a class="toolbar-button btn btn-sm btn-default ajax_page_load btn-default"
       href="<?= $this->url('admin/banner/size') ?>">
        <span class="glyphicon glyphicon-fullscreen text-info"></span>
        <?= $this->translate('GALLERY_CREATE_BANNER_SIZE') ?>
    </a>
    <h3 class="page-title">
        <?=$this->translate('Banner Settings');?>
    </h3>
    <div>
        <?
        $form = $this->form;
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->iptFormCollection($form->get('countPosition'));
        foreach($form->getElements() as $el){
            echo $this->iptFormRow($el);
        }
        echo $this->iptFormCollection($form->get('buttons'));
        echo $this->form()->closeTag();
        ?>
    </div>
</div>
<script>
    $(document).ready(function(){

        $('.withcomma').each(function () {
            $(this).keyup(function () {
                numFormat(this);
            })
        });

        $('.spinner').each(function(){
            numFormat(this);
        });

    });
</script>