<div>
    <h2>
       <?=t('gallery_order_banner_validate_success_msg')?>
    </h2>
    <label>
        <?=t('Payment Code')?>
    </label>
    <p>
        <?=$this->payerId?>
    </p>
    <br/>
    <label>
        <?=t('Customer Code')?>
    </label>
    <p>
        <?=$this->orderId?>
    </p>
    <br/>
    <label>
        <?=t('Reg Date')?>
    </label>
    <p>
        <?=$this->time?>
    </p>
</div>