<aside id="workshop-rules">
    <? if ($this->page) {
        ?>
        <h2 class="page-header">
            <?= $this->page->pageTitle ?>
        </h2>
        <p><?= $this->page->fullText ?></p>
    <?
    } ?>
</aside>
<div>
    <a class='btn btn-default btn-lg'
       href="<?= url('app/health-center/reserve', array('doctor' => $this->doctor, 'time' => $this->time)) ?>">
        <span class="glyphicon glyphicon-ok text-success icon-lg"></span>
        <?= t('I Accept') ?>
    </a>
    <a class='btn btn-default btn-lg'
       href="<?= url('app/health-center/doctor', array('id' => $this->doctor)) ?>">
        <span class="glyphicon glyphicon-remove text-danger icon-lg"></span>
        <?= t('I Do Not Accept') ?>
    </a>
</div>