<div>
    <h3 class="page-title">
        <?= $this->translate('Cancel Reservation'); ?>
    </h3>

    <p class="description">
        <?
        print sprintf(t("canceling the %s's reservation for %s"),
            \Theme\API\Common::Link(
                getUserDisplayName($this->reserver),
                url('app/user/user-profile', array('id' => $this->reserver['userId'])),
                array('target' => '_blank')
            ),
            \Theme\API\Common::Link(
                $this->doctorTitle,
                url('app/user/user-profile', array('id' => $this->reserver['doctorId'])),
                array('target' => '_blank')
            )
        )?>
    </p>
    <? if (has_value($this->reserver['note'])) {
        print $this->reserver['note'];
    }
    ?>
    <div>
        <? print $this->form($this->form); ?>
    </div>
</div>
