<div class="reservation-search-type">
    <div class="row">
        <div class="col-md-6">
            <div class="jumbotron">

                <a href="<?= url('app/health-center/specialization') ?>"
                   class="btn btn-primary btn-block btn-lg">
                    <?= t('Search by Specialization'); ?>
                </a>

                <p class="text-justify">
                    <?= t('Search throw a list of specializations to see witch doctors/counselors are available for that specializations') ?>
                </p>
            </div>
        </div>
        <div class="col-md-6">
            <div class="jumbotron">
                <a href="<?= url('app/health-center/doctors') ?>"
                   class="btn btn-primary btn-block btn-lg">
                    <?= t('Search by Doctor/Counselor'); ?>
                </a>

                <p class="text-justify">
                    <?= t('Search throw a list of Doctor/Counselor to see witch who is available') ?>
                </p>
            </div>
        </div>
    </div>
</div>