<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'Cron\API\Cron'                  => __DIR__ . '/src/Cron/API/Cron.php',
  'Cron\Controller\CronController' => __DIR__ . '/src/Cron/Controller/CronController.php',
  'Cron\Install'                   => __DIR__ . '/src/Cron/Install.php',
);
