<?
$this->headScript()->appendFile($this->basePath() . '/js/node-chart.js');
?>
<div>
    <h3 class="page-title">
        <?= $this->translate('OrgChart_NEWNODECHART'); ?>
    </h3>

    <p class="description">
        <? //= t('') ?>
    </p>

    <div>
        <?
        $form = $this->form;
        $form->prepare();
        echo $this->form()->openTag($form);
        foreach ($form->getElements() as $el) {
            echo $this->iptFormRow($el);
        }
        echo $this->iptFormCollection($form->get('buttons'));
        echo $this->form()->closeTag();
        ?>
    </div>
</div>
<script>
    <?$this->inlineScript()->captureStart()?>
    var Chart = {
        parentNodeUrl: '<?=url('admin/chart-node/parent-node')?>'
    };
    <?$this->inlineScript()->captureEnd()?>
</script>