<?
//$content = \Theme\API\Themes::renderLayout($this);

$topMenu = $this->blocks('top-menu');
$middleMenu = $this->blocks('middle-menu');
$col_product = $this->blocks('col-product');
$news = $this->blocks('col-news');
$mainSlider = $this->blocks('main-slider');
$search = $this->blocks('search');
$footer_menu = $this->blocks('footer-menu');


$direction = $this->translate('lang_direction'); //rtl ? ltr
$basePath = $this->basePath();
$this->headLink()
    ->prependStylesheet(
        $basePath . TEMPLATE_PATH . '/css/ie10.css',
        'screen',
        'IE 10'
    );

if ($direction == 'rtl')
    $this->headLink()->prependStylesheet($basePath . TEMPLATE_PATH . '/css/bootstrap-rtl.min.css');

$this->headLink()
    ->prependStylesheet($basePath . TEMPLATE_PATH . '/css/bootstrap-theme.min.css')
    ->prependStylesheet($basePath . TEMPLATE_PATH . '/css/bootstrap.min.css')
    ->prependStylesheet($basePath . '/css/base-theme/jquery-ui-1.10.1.custom.min.css')
    ->prependStylesheet($basePath . '/css/system.css');

//------------------------------ TEMPLATE STYLE -------------------------------------------
$this->headLink()->appendStylesheet($basePath . TEMPLATE_PATH . '/css/style.css');
if ($direction == 'rtl')
    $this->headLink()->appendStylesheet($basePath . TEMPLATE_PATH . '/css/style-rtl.css');
////-------------------------------------------------------------


$this->headScript()
    // ->prependFile($basePath . '/js/system.jquery.ui.buttons.js')
    ->prependFile($basePath . '/js/system.jquery.ui.js')
    ->prependFile($basePath . '/js/system.js')
    ->prependFile($basePath . '/js/forms.js')
    ->prependFile($basePath . '/js/jquery.transit.min.js')
    ->prependFile($basePath . '/js/jquery.hoverIntent.min.js')
    ->prependFile($basePath . '/js/general-client.js')
    ->prependFile($basePath . '/js/jquery-ui-1.10.4.custom.min.js')
    ->prependFile($basePath . '/js/jquery-1.9.1.min.js')
    ->prependFile(
        $basePath . TEMPLATE_PATH . '/js/respond.min.js',
        'text/javascript',
        array('conditional' => 'lt IE 9')
    )
    ->prependFile(
        $basePath . TEMPLATE_PATH . '/js/html5shiv.min.js',
        'text/javascript',
        array('conditional' => 'lt IE 9')
    );

//------------------------------ TEMPLATE JAVASCRIPT -------------------------------------------
$this->headScript()->appendFile($basePath . TEMPLATE_PATH . '/js/template.js');

?>

<!DOCTYPE html>
<html lang="fa" xmlns="http://www.w3.org/1999/html">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <?= $this->head() ?>
    <?= $this->headTitle() ?>
    <?= $this->headMeta() ?>
    <?= $this->headLink() ?>
    <?= $this->headScript() ?>
</head>
<body>
<div class="div-load-img">
    <span class="about_us"></span>
    <span class="online_counseling"></span>
    <span class="public_teach"></span>
    <span class="online_shop"></span>
</div>
<div id="container">
    <div class="my-container top-box">
        <div class="row">
            <div class="col-md-12 padding">
                <div class="bg-header"></div>
                <div id="header_wrapper">
                    <div class="logo-header"></div>
                    <? if ($topMenu) { ?>
                        <div class="box_top_menu">
                            <?= $topMenu ?>
                        </div>
                    <? } ?>
                    <? if ($search) { ?>
                        <div class="box_search">
                            <?= $search ?>
                        </div>
                    <? } ?>
                    <div class="box_stele_phone"></div>
                    <? if ($middleMenu) { ?>
                        <div class="box_middle_menu">
                            <?= $middleMenu ?>
                        </div>
                    <? } ?>
                </div>
                <div id="main_wrapper">
                    <div class="box-main">
                        <? if ($mainSlider) { ?>
                            <div class="box_slider">
                                <?= $mainSlider ?>
                            </div>
                            <div style="clear:both"></div>
                        <? } ?>
                        <? if ($news) { ?>
                            <div class="box_news">
                                <?= $news ?>
                                <? if ($footer_menu) { ?>
                                    <div class="box_social">
                                        <?= $footer_menu ?>
                                    </div>
                                <? } ?>
                            </div>
                        <? } ?>
                        <?
                        if ($this->content) {
                            $fm = $this->flashMessenger()->render();
                            if (!empty($fm)) {
                                ?>
                                <div id="system_messages"><?= $fm; ?></div>
                            <? } ?>
                            <div style="clear: both"></div>
                            <div class="box_main_content">

                                <?= $this->content ?>
                                <div style="clear: both;"></div>
                            </div>
                        <? } ?>
                        <div class="box_middle_menu">
                            <div class="about_us">
                                <a href="http://stele.ir/about-us">
                                    <span></span>

                                    <p><?= t('ABOUTUS','theme') ?></p>
                                </a>
                            </div>
                            <div class="online_counseling">
                                <a href="http://stele.ir/fa/tags/7/%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87-%D9%88-%D8%A7%D8%AC%D8%B1%D8%A7">
                                    <span></span>

                                    <p><?= t('ONLINE_COUNSELING','theme') ?></p>
                                </a>
                            </div>
                            <div class="public_teach">
                                <a href="http://stele.ir/fa/tags/1/%D9%85%D9%82%D8%A7%D9%84%D8%A7%D8%AA">
                                    <span></span>

                                    <p><?= t('PUBLIC_TEACH','theme') ?></p>
                                </a>
                            </div>
                            <div class="online_shop">
                                <a href="#">
                                    <div class="coming_soon"></div>
                                    <span></span>

                                    <p><?= t('ONLINE_SHOP','theme') ?></p>
                                </a>
                            </div>
                        </div>
                        <div style="clear:both"></div>
                        <? if ($col_product) { ?>
                            <div class="box_product">
                                <?= $col_product ?>
                            </div>
                        <? } ?>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container footer sticky-bottom">
        <div class="row">
            <div class=" col-md-12">
                <div class="bg-footer"></div>
                <div class="box_footer">
                    <div class="copy_right">
                    <?
                    $startYear = mktime(0, 0, 0, 6, 0, 2012);
                    $startYear = $this->dateFormat($startYear, \Localization\View\Helper\DateFormat::YEAR_ONLY);
                    $nowYear = $this->dateFormat(time(), \Localization\View\Helper\DateFormat::YEAR_ONLY);
                    ?>
                    <p align="center">
                        <?= t('APPLICATION_BROWSERS') ?>
                    </p>

                    <p align="center">
                        <span><?= sprintf(t('APPLICATION_RIGHTS'), t('Stele','theme')) ?></span>
                        <span dir="ltr"><?= sprintf(t('APPLICATION_COPY_RIGHT'), $startYear, $nowYear) ?></span>
                        &nbsp; .
                        <span><?= t('APPLICATION_SUPPORT') ?></span> .
                        <span><?= t('APPLICATION_POWERED_BY') ?></span>
                    </p>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
<?= $this->inlineScript() ?>
</body>
</html>
