<p>
    <?=
    str_replace(
        array('__RESERVATION__', '__DOCTOR__', '__USER__'),
        array($this->__RESERVATION__, $this->__DOCTOR__, $this->__USER__),
        t("__DOCTOR__ has canceled __USER__'s reservation(__RESERVATION__)")
    ) ?>
</p>
<dl class="dl-horizontal">
    <dt><?= t('Cancel Reason') ?></dt>
    <dd><?= $this->__RESERVE_CANCEL_REASON__ ?></dd>
    <dt><?= t('Refund Amount') ?></dt>
    <dd><?= $this->__RESERVE_CANCEL_REFUND_AMOUNT__ ?></dd>
</dl>