<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'RSS\API\ACL'                     => __DIR__ . '/src/RSS/API/ACL.php',
  'RSS\API\EventManager'            => __DIR__ . '/src/RSS/API/EventManager.php',
  'RSS\API\Reader'                  => __DIR__ . '/src/RSS/API/Reader.php',
  'RSS\Controller\ReaderController' => __DIR__ . '/src/RSS/Controller/ReaderController.php',
  'RSS\Form\Reader'                 => __DIR__ . '/src/RSS/Form/Reader.php',
  'RSS\Install'                     => __DIR__ . '/src/RSS/Install.php',
  'RSS\Model\Reader'                => __DIR__ . '/src/RSS/Model/Reader.php',
  'RSS\Model\ReaderTable'           => __DIR__ . '/src/RSS/Model/ReaderTable.php',
  'RSS\View\Helper\Reader'          => __DIR__ . '/src/RSS/View/Helper/Reader.php',
);
