<?php if ($this->pageCount): ?>
<div class="paginationControl">
    <span class="pager_items_count">
    <?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?>
        <?=$this->translate('of')?> <?php echo $this->totalItemCount; ?>
    </span>
    <!-- First page link -->
    <?php if (isset($this->previous)): ?>
    <a class=" button first_button" href="<?php echo $this->url($this->route, array('page' => $this->first)); ?>">
        <?=$this->translate('First')?>
    </a>
    <?php else: ?>
    <span class="disabled"><?=$this->translate('First')?></span> 
    <?php endif; ?>

    <!-- Previous page link -->
    <?php if (isset($this->previous)): ?>
    <a href="<?php echo $this->url($this->route, array('page' => $this->previous)); ?>">
        < <?=$this->translate('Previous')?>
    </a>
    <?php else: ?>
    <span class="disabled">< <?=$this->translate('Previous')?></span> 
    <?php endif; ?>

    <!-- Next page link -->
    <?php if (isset($this->next)): ?>
    <a href="<?php echo $this->url($this->route, array('page' => $this->next)); ?>">
        <?=$this->translate('Next')?> >
    </a>
    <?php else: ?>
    <span class="disabled"><?=$this->translate('Next')?> ></span> 
    <?php endif; ?>

    <!-- Last page link -->
    <?php if (isset($this->next)): ?>
    <a href="<?php echo $this->url($this->route, array('page' => $this->last)); ?>">
        <?=$this->translate('Last')?>
    </a>
    <?php else: ?>
    <span class="disabled"><?=$this->translate('Last')?></span>
    <?php endif; ?>

</div>
<?php endif; ?>