<div id="ads-slider-<?= $this->blockId ?>"
     class="content-slider-container <? if ($this->$showLoading) echo 'ajax-loading'; ?> ">
    <? if ($this->directionalNav == 1) { ?>
        <div class="prev" rel='tooltip' title="<?= t('Previous') ?>">
        </div>
    <? } ?>
    <div class="viewport a_helper_2000">
        <ul class="wrapper">
            <?
            foreach ($this->adsData as $row) {
                ?>
                <li class="item media">
                    <?
                    if ($this->showImage) {
                        if ($row->smallImage) {
                            $dataImages = unserialize($row->smallImage);
                            if (isset($dataImages['fPath']) && $dataImages['fPath'])
                                $fPath = $dataImages['fPath'];
                            else
                                $fPath = $this->basePath() . '/__/images/notImage100_100.png';
                            $imageUrl = getThumbnail()->resize($fPath, $this->imageWidth, $this->imageHeight); //resize image
                        }
                        ?>

                        <a href="<?= url('app/ad/view', array('baseType' => $row->baseType, 'adId' => $row->adId, 'adTitle' => \Application\API\App::prepareUrlString($row->title))) ?>"
                           class="pull-left flip">
                            <img src="<?= $imageUrl ?>" width="<?= $this->imageWidth ?>"
                                 height="<?= $this->imageHeight ?>">
                        </a>
                    <? } ?>
                    <div class="text_img_url media-body">
                        <a class="a_helper_link" href="<?= url('app/ad/view', array('baseType' => $row->baseType, 'adId' => $row->adId, 'adTitle' => \Application\API\App::prepareUrlString($row->title))) ?>">
                            <div class="top_text">
                                <span class="a_title"><?= $row->title ?></span>
                            </div>
                            <div>
                                <span class="a_text"><?=$row->stateTitle?></span>
                                <span class="a_text">,</span>
                                <span class="a_text"><?=$row->cityTitle?></span>
                            </div>
                            <div>
                                <span class="a_text"><?=t('Name').' : '?></span>
                                <span class="a_text"><?=$row->name?></span>
                            </div>
                        </a>
                    </div>

                </li>
            <?
            }
            ?>

        </ul>
    </div>
    <? if ($this->directionalNav == 1) { ?>
        <div rel='tooltip' class="next" title="<?= t('Next') ?>">
        </div>
    <? } ?>
</div>
<script type="text/javascript">
    <?$this->inlineScript()->captureStart()?>
    $(document).ready(function () {
        $('#ads-slider-<?=$this->blockId?>').contentSlider({
            orientation: '<?=$this->orientation?>',
            direction: '<?=$this->direction?>',
            autoscroll: '<?=$this->autoScroll?>',
            interval: <?=$this->interval?>,
            speed: <?=$this->speed?>,
            directionalNav: <?=$this->directionalNav?>,
            visibleCount: <?=$this->visibleCount?>,
            slideCount: <?=$this->slideCount?>
        });
    });
    <?$this->inlineScript()->captureEnd()?>
</script>
