<?
//$content = \Theme\API\Themes::renderLayout($this);
$direction = $this->translate('lang_direction'); //rtl ? ltr
$basePath = $this->basePath();
$this->headLink()
    ->prependStylesheet(
        $basePath . TEMPLATE_PATH . '/css/ie10.css',
        'screen',
        'IE 10'
    );

if ($direction == 'rtl')
    $this->headLink()->prependStylesheet($basePath . TEMPLATE_PATH . '/css/bootstrap-rtl.min.css');

$this->headLink()
    ->prependStylesheet($basePath . TEMPLATE_PATH . '/css/bootstrap-theme.min.css')
    ->prependStylesheet($basePath . TEMPLATE_PATH . '/css/bootstrap.min.css')
    ->prependStylesheet($basePath . '/css/base-theme/jquery-ui-1.10.1.custom.min.css')
    ->prependStylesheet($basePath . '/select2/select2-bootstrap.css')
    ->prependStylesheet($basePath . '/select2/select2.css')
    ->prependStylesheet($basePath . '/css/system.css');


//------------------------------ TEMPLATE STYLE -------------------------------------------
$this->headLink()->appendStylesheet($basePath . TEMPLATE_PATH . '/css/style.css');
if ($direction == 'rtl')
    $this->headLink()->appendStylesheet($basePath . TEMPLATE_PATH . '/css/style-rtl.css');
////-------------------------------------------------------------


$this->headScript()
    // ->prependFile($basePath . '/js/system.jquery.ui.buttons.js')
    ->prependFile($basePath . '/js/system.jquery.ui.js')
    ->prependFile($this->basePath() . '/js/jquery.cookie.js')
    ->prependFile($basePath . '/js/system.js')
    ->prependFile($this->basePath() . '/js/real-estate-compare.js')
    ->prependFile($basePath . '/js/forms.js')
    ->prependFile($basePath . '/js/jquery.transit.min.js')
    ->prependFile($basePath . '/js/jquery.hoverIntent.min.js')
    ->prependFile($basePath . '/js/general-client.js')
    ->prependFile($basePath . '/select2/select2.min.js')
    ->prependFile($basePath . '/js/jquery-ui-1.10.4.custom.min.js')
    ->prependFile($basePath . '/js/jquery-1.9.1.min.js')
    ->prependFile(
        $basePath . TEMPLATE_PATH . '/js/respond.min.js',
        'text/javascript',
        array('conditional' => 'lt IE 9')
    )
    ->prependFile(
        $basePath . TEMPLATE_PATH . '/js/html5shiv.min.js',
        'text/javascript',
        array('conditional' => 'lt IE 9')
    );

//------------------------------ TEMPLATE JAVASCRIPT -------------------------------------------
$this->headScript()->appendFile($basePath . TEMPLATE_PATH . '/js/template.js');


$topMenu = $this->blocks('top-menu');
$bottomMenu = $this->blocks('bottom-menu');
$user_block = $this->user_logged_in_block();
if (!$user_block) {
    $user_login_block = $this->blocks('user-popup');
}
$colLeft = $this->blocks('col-left');
$colRight = $this->blocks('col-right');
$mainSearch = $this->blocks('main-search');
$statisticsRight = $this->blocks('statistics-right');
$statisticsLeft = $this->blocks('statistics-left');
$statisticsBottom = $this->blocks('statistics-bottom');
$mainWidth = '960px';
if ($colLeft || $colRight)
    $mainWidth = '702px';
?>

<!DOCTYPE html>
<html lang="fa" xmlns="http://www.w3.org/1999/html">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <?= $this->head() ?>
    <?= $this->headTitle() ?>
    <?= $this->headMeta() ?>
    <?= $this->headLink() ?>
    <?= $this->headScript() ?>
</head>
<body>

<div id="container">
    <div class="my-container">
        <div class="row">
            <div class="col-md-12 padding">
                <div class="box_compare">
                    <a class="img_compare" href="#"></a>
                </div>
                <div class="box_statistic">
                    <div class="content_st"></div>
                    <div class="icon_st">
                        <a class="img_statistic" href="#"></a>
                    </div>
                </div>
                <div id="header_wrapper">
                    <div class="bg-header"></div>
                    <div class="position_absolute">
                        <div class="logo-header">
                            <img src="<?=$basePath . TEMPLATE_PATH .'/images/logo.png'?>">
                        </div>
                    </div>

                    <? if (!$user_block) { ?>
                        <a class="btn_register" href="<?= url('app/user/register') ?>"><?= t('Register') ?></a>
                        <div class="box user_login_popup" id="user_login_popup">
                            <?= $user_login_block ?>
                        </div>
                        <div class="box user_login_box">
                            <a id="user_login_link"
                               href="<?= url('app/user/login') ?>"><span><?= t('Login') ?></span></a>
                        </div>
                    <? } ?>
                    <div id="user_popup_container">
                        <?
                        if ($user_block) {
                            if (isAllowed(\Application\Module::ADMIN)) {
                                ?>
                                <div class="box admin_link_box">
                                    <a title="<?= t('Administration') ?>" href="<?= url('admin') ?>"></a>
                                </div>
                            <?
                            }
                            echo $user_block;
                        }
                        ?>
                    </div>
                    <? if ($topMenu) { ?>
                        <div class="box_top_menu">
                            <?= $topMenu ?>
                        </div>
                    <? } ?>
                </div>
                <div id="main_wrapper">
                    <? if ($colLeft) { ?>
                        <div class="col_left">
                            <?= $colLeft ?>
                        </div>
                    <? } ?>
                    <? if ($colRight) { ?>
                        <div class="col_right">
                            <?= $colRight ?>
                        </div>
                    <? } ?>
                    <div class="col_middle" style="width: <?= $mainWidth ?>;">
                        <?
                        if ($mainSearch)
                            echo $mainSearch;
                        if ($this->content) {
                            ?>
                            <div class="box-main">
                                <?
                                $fm = $this->flashMessenger()->render();
                                if (!empty($fm)) {
                                    ?>
                                    <div id="system_messages"><?= $fm; ?></div>
                                <? } ?>
                                <div style="clear: both"></div>
                                <div class="box_main_content">
                                    <?= $this->content ?>
                                    <div style="clear: both;"></div>
                                </div>
                            </div>
                        <? } ?>
                        <div style="clear: both"></div>
                        <? if ($statisticsRight) {
                            echo $statisticsRight;
                        } ?>
                        <? if ($statisticsLeft) {
                            echo $statisticsLeft;
                        } ?>
                    </div>

                </div>
                <div id="footer_wrapper">
                    <? if ($statisticsBottom) {
                        echo $statisticsBottom;
                    } ?>
                    <div style="clear: both"></div>
                    <? if ($bottomMenu) { ?>
                        <div class="box_bottom_menu">
                            <?= $bottomMenu ?>
                        </div>
                    <? } ?>
                    <div class="box_footer">
                        <?
                        $startYear = mktime(0, 0, 0, 6, 0, 2012);
                        $startYear = $this->dateFormat($startYear, \Localization\View\Helper\DateFormat::YEAR_ONLY);
                        $nowYear = $this->dateFormat(time(), \Localization\View\Helper\DateFormat::YEAR_ONLY);
                        ?>
                        <!--<p align="center">
                            <?/*= t('APPLICATION_BROWSERS') */?>
                        </p>-->
                        <p align="center">
                            <span><?= sprintf(t('APPLICATION_RIGHTS'), 'ملکبان') ?></span>
                            <span dir="ltr"><?= sprintf(t('APPLICATION_COPY_RIGHT'), $startYear, $nowYear) ?></span>
                            &nbsp; .
                            <!-- <span><? /*= t('APPLICATION_SUPPORT') */ ?></span> .
                        <span><? /*= t('APPLICATION_POWERED_BY') */ ?></span>-->
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?= $this->inlineScript() ?>
</body>
</html>
<script>
    var real_compare_url = '<?= url('app/real-estate/compare') ?>';
</script>
