<div>
    <h3 class="page-title"><?= t('New DataBase Backup') ?></h3>
    <?
//    $form = $this->form;
//    $form->prepare();
//    echo $this->form()->openTag($form);
//
//    foreach ($form->getElements() as $el) {
//        echo $this->iptFormRow($el);
//    }
//
//    echo $this->iptFormCollection($form->get('buttons'));
//    echo $this->form()->closeTag();
    echo $this->form($this->form);
    ?>
</div>