<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'Category\API\ACL'                       => __DIR__ . '/src/Category/API/ACL.php',
  'Category\API\CategoryItem'              => __DIR__ . '/src/Category/API/CategoryItem.php',
  'Category\API\CategoryList'              => __DIR__ . '/src/Category/API/CategoryList.php',
  'Category\API\EventManager'              => __DIR__ . '/src/Category/API/EventManager.php',
  'Category\Controller\CategoryController' => __DIR__ . '/src/Category/Controller/CategoryController.php',
  'Category\Controller\ItemsController'    => __DIR__ . '/src/Category/Controller/ItemsController.php',
  'Category\Form\Category'                 => __DIR__ . '/src/Category/Form/Category.php',
  'Category\Form\CategoryImageCollection'  => __DIR__ . '/src/Category/Form/CategoryImageCollection.php',
  'Category\Form\CategoryImageValue'       => __DIR__ . '/src/Category/Form/CategoryImageValue.php',
  'Category\Form\Items'                    => __DIR__ . '/src/Category/Form/Items.php',
  'Category\Install'                       => __DIR__ . '/src/Category/Install.php',
  'Category\Model\Category'                => __DIR__ . '/src/Category/Model/Category.php',
  'Category\Model\CategoryItem'            => __DIR__ . '/src/Category/Model/CategoryItem.php',
  'Category\Model\CategoryItemTable'       => __DIR__ . '/src/Category/Model/CategoryItemTable.php',
  'Category\Model\CategoryTable'           => __DIR__ . '/src/Category/Model/CategoryTable.php',
  'Category\Model\EntityRelation'          => __DIR__ . '/src/Category/Model/EntityRelation.php',
  'Category\Model\EntityRelationTable'     => __DIR__ . '/src/Category/Model/EntityRelationTable.php',
  'Category\View\Helper\categoryListBlock' => __DIR__ . '/src/Category/View/Helper/CategoryListBlock.php',
  'Category\View\Helper\Widget'            => __DIR__ . '/src/Category/View/Helper/Widget.php',
);
