<?
$this->headScript()->appendFile($this->basePath() . '/js/geographical.js');
if ((int)$this->baseType == 3000)
    print $this->form($this->form);
else {
    $form = $this->form;
    $form->prepare();
    $table = $form->get('table');
    $field = null;
    if ($form->has('field'))
        $field = $form->get('field');
    echo $this->form()->openTag($form);
    ?>
    <div class="col-xs-12 col-sm-12 col-md-11">
        <?
        foreach ($table as $el) {
            ?>
            <div class="col-xs-12 col-sm-6 col-md-2">
                <? echo $this->formRow($el); ?>
            </div>
        <?
        }
        if ($field)
            foreach ($field as $el) {
                ?>
                <div class="col-xs-12 col-sm-6 col-md-2">
                    <? echo $this->formRow($el); ?>
                </div>
            <?
            }?>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-1">
        <?
        echo $this->formRow($form->get('search'));
        ?>
    </div>
    <?
    echo $this->form()->closeTag();
} ?>
<script>
    <?$this->inlineScript()->captureStart();?>
    $(document).ready(function () {
        $('input[name="table[category]"]').select2({
            minimumInputLength: 2,
            maximumSelectionSize: 1,
            multiple: true,
            ajax: {
                type: 'POST',
                url: '<?=url('admin/category/items/search',array('catId'=>$this->catId))?>',
                dataType: 'json',
                data: function (term, page) {
                    return {
                        q: term, //search term
                        page_limit: 10, // page size
                        page: page ,// page number
                        type:1//id=itemName
                    };
                },
                results: function (data, page) {
                    console.log(data);
                    var more = (page * 10) < data.total;
                    return {results: data.items, more: more};
                }
            }
        });
    });
    <?$this->inlineScript()->captureEnd();?>
</script>
