<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'Contact\API\ACL'                                => __DIR__ . '/src/Contact/API/ACL.php',
  'Contact\API\EventManager'                       => __DIR__ . '/src/Contact/API/EventManager.php',
  'Contact\Controller\ContactController'           => __DIR__ . '/src/Contact/Controller/ContactController.php',
  'Contact\Controller\ContactUserAdminController'  => __DIR__ . '/src/Contact/Controller/ContactUserAdminController.php',
  'Contact\Controller\ContactUserClientController' => __DIR__ . '/src/Contact/Controller/ContactUserClientController.php',
  'Contact\Controller\RepresentativeController'    => __DIR__ . '/src/Contact/Controller/RepresentativeController.php',
  'Contact\Form\Config'                            => __DIR__ . '/src/Contact/Form/Config.php',
  'Contact\Form\ConfigSelect'                      => __DIR__ . '/src/Contact/Form/ConfigSelect.php',
  'Contact\Form\ConfigSelectValue'                 => __DIR__ . '/src/Contact/Form/ConfigSelectValue.php',
  'Contact\Form\Contact'                           => __DIR__ . '/src/Contact/Form/Contact.php',
  'Contact\Form\ContactUser'                       => __DIR__ . '/src/Contact/Form/ContactUser.php',
  'Contact\Form\RepresentativeConfig'              => __DIR__ . '/src/Contact/Form/RepresentativeConfig.php',
  'Contact\Install'                                => __DIR__ . '/src/Contact/Install.php',
  'Contact\Model\Contact'                          => __DIR__ . '/src/Contact/Model/Contact.php',
  'Contact\Model\ContactTable'                     => __DIR__ . '/src/Contact/Model/ContactTable.php',
  'Contact\Model\ContactType'                      => __DIR__ . '/src/Contact/Model/ContactType.php',
  'Contact\Model\ContactTypeTable'                 => __DIR__ . '/src/Contact/Model/ContactTypeTable.php',
  'Contact\Model\ContactUser'                      => __DIR__ . '/src/Contact/Model/ContactUser.php',
  'Contact\Model\ContactUserTable'                 => __DIR__ . '/src/Contact/Model/ContactUserTable.php',
);
