<div>
    <h3><?=sprintf($this->translate('Are you sure you want to delete User %s with ID:%s ?'),
            "<em>" . $this->user->username . "</em>",
            "<em>" . $this->user->id . "</em>")?>
    </h3>

    <div>
        <form method="post" action="<?=$this->url(
            'admin/users/delete',
            array('id' => $this->user->id))?>">
            <input class="button yes_button" type="submit" name="submit" value="<?=$this->translate('Yes')?>">
            <input class="button no_button" type="submit" name="cancel" value="<?=$this->translate('No')?>">
        </form>
    </div>
</div>