<?
$form = $this->form;
?>
<div class="row">
    <div class="col-md-12">
        <h3 class="page-header text-success">
            <?= t('Recover password') ?>
        </h3>
        <p class="help-block">
            <?=t('Enter the email address that you have registered your account with to recover your password')?>
        </p>
    </div>
    <div class="col-md-4 col-sm-6">
        <?
        //    $form->prepare();
        //    echo $this->form()->openTag($form);
        //    echo $this->iptFormRow($form->get('csrf_password_recovery_form'));
        //    echo $this->iptFormRow($form->get('email'));
        //    echo $this->iptFormRow($form->get('send-sms'));
        //
        ?>
        <!--    <div class="captcha-div">-->
        <!--        --><? //= $this->iptFormRow($form->get('captcha')) ?>
        <!--    </div>-->
        <!--    --><?//
        //    echo $this->iptFormRow($form->get('submit-send'));
        //    echo $this->form()->closeTag();
        print $this->form($this->form);
        ?>
    </div>
</div>

