<?
$this->headLink()->appendStylesheet($this->basePath() . '/css/user-admin.css');
$this->headScript()->appendFile($this->basePath() . '/js/geographical.js');
?>
<div>
    <h3 class="page-title">
        <?
        echo sprintf($this->translate("Edit %s's Account"),
            "<a href='" . url('admin/users/view', array('id' => $this->user['account']['id'])) . "'>
            <span class='user-name-title emphasize '>" .
            $this->user['account']['username'] . "</span></a>");
        ?>
    </h3>
    <?
    $form = $this->form;
    $form->prepare();
    echo $this->form()->openTag($form);

    foreach ($form->getElements() as $el) {
        echo $this->iptFormRow($el);
    }
    echo $this->iptFormCollection($form->get('account'));
    echo $this->iptFormCollection($form->get('profile'));
    echo $this->iptFormCollection($form->get('buttons'));
    echo $this->form()->closeTag();
    ?>
</div>