<style>
    .tbl_region_statistic {
        width: 235px;
        display: inline-block;
        float: right;
        margin: 0 3px 5px 0;
        background: #d3ebf7;
        height:375px;;
    }

    .tbl_region_statistic tr .labels {
        width: 100px;
        font-family: WYekan;
        font-size: 10pt;
        color: #707070;
        padding: 7px;
        display: block !important;
        border-bottom: 1px dotted #cccccc;
    }

    .tbl_region_statistic tr .value {
        width: 140px;
        font-family: tahoma;
        font-size: 10pt;
        color: #975320;
        padding: 7px;
        border-bottom: 1px dotted #cccccc;
    }

    .tbl_region_statistic .tr_first_st {
        background: none repeat scroll 0 0 #6dcef8;
        border: 2px solid #00acee;
    }
</style>
<?
if ($this->data) {
    foreach ($this->data as $row) {
        ?>
        <table class="tbl_region_statistic">
            <tr class="tr_first_st">
                <td class="labels"><?= t('Region') ?></td>
                <td class="value">
                    <a href=""></a>
                    <?
                    if (isset($row['title']) && !$row['title'])
                        echo '-----';
                    else {
                        $link = '#';
                        if (isset($row['id']) && $row['id'])
                            $link = url('app/real-estate/list', array(), array('query' => array('table' => array('parentAreaId' => $row['id']))));
                        echo '<a href="' . $link . '">' . $row['title'] . '</a>';
                    } ?></td>
            </tr>
            <?
            if (isset($row['data']) && $row['data'])
                foreach ($row['data'] as $key => $val) {
                    ?>
                    <tr>
                        <td class="labels"><?= t($key) ?></td>
                        <td class="value"><? if (empty($val)) echo '-----'; else echo $this->currencyFormat($val); ?></td>
                    </tr>
                <?
                }
            ?>
        </table>
    <?
    }
}