<div>
    <a class="toolbar-button button ajax_page_load"
       href="<?= url('admin/notify/config/advance') ?>"><?= t('Advance Config') ?></a>

    <h3 class="page-title">
        <?= $this->translate('Notification Settings'); ?>
    </h3>

    <div>
        <?
        $form = $this->form;
        $form->prepare();
        echo $this->form()->openTag($form);
        foreach ($form->getElements() as $el) {
            echo $this->iptFormRow($el);
        }

        $modules = $form->get('modules');
        ?>
       <fieldset>
           <legend><?=t($modules->getLabel())?></legend>
           <p class="form_element_description">
               <?=t($modules->getOption('description'))?>
           </p>
           <div id="module_notifications_settings">
               <ul>
                   <? foreach ($modules->getFieldsets() as $module) { ?>
                       <li>
                           <a href="#module-<?= str_replace(array('[' . ']'), '_', $module->getName()) ?>"><?= t($module->getLabel()) ?></a>
                       </li>
                   <? } ?>
               </ul>
               <? foreach ($modules->getFieldsets() as $module) { ?>
                   <div id="module-<?= str_replace(array('[' . ']'), '_', $module->getName()) ?>">
                       <div>
                           <div class="module_keys_tabs">
                               <ul>
                                   <? foreach ($module->getFieldsets() as $keys) { ?>
                                       <li>
                                           <a href="#module-key-<?= str_replace(array('[' . ']'), '_', $keys->getName()) ?>"><?= t($keys->getLabel()) ?></a>
                                       </li>
                                       <? $keys->setLabel('');
                                   } ?>
                               </ul>
                               <? foreach ($module->getFieldsets() as $keys) { ?>
                                   <div id="module-key-<?= str_replace(array('[' . ']'), '_', $keys->getName()) ?>">
                                       <?= $this->iptFormCollection($keys) ?>
                                   </div>
                               <? } ?>
                           </div>
                       </div>
                   </div>
               <? } ?>
           </div>
       </fieldset>
        <?
        echo $this->iptFormCollection($form->get('buttons'));
        echo $this->form()->closeTag();
        ?>
    </div>
</div>
<script type="text/javascript">
    $('#module_notifications_settings').tabs();
    $('.module_keys_tabs').tabs();
</script>