<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'ACL'                                              => __DIR__ . '/src/ServerManager/API/ACL.php',
  'ServerManager\API\Hosting\AbstractHost'           => __DIR__ . '/src/ServerManager/API/Hosting/AbstractHost.php',
  'ServerManager\API\Hosting\DA\AbstractDirectAdmin' => __DIR__ . '/src/ServerManager/API/Hosting/DA/AbstractDirectAdmin.php',
  'ServerManager\API\Hosting\DA\DirectAdmin'         => __DIR__ . '/src/ServerManager/API/Hosting/DA/DirectAdmin.php',
  'ServerManager\API\Hosting\DA\Error'               => __DIR__ . '/src/ServerManager/API/Hosting/DA/Error.php',
  'ServerManager\API\Hosting\DA\Result'              => __DIR__ . '/src/ServerManager/API/Hosting/DA/Result.php',
  'ServerManager\API\Hosting\Error'                  => __DIR__ . '/src/ServerManager/API/Hosting/Error.php',
  'ServerManager\API\Hosting\Host'                   => __DIR__ . '/src/ServerManager/API/Hosting/Host.php',
  'ServerManager\API\Hosting\Result'                 => __DIR__ . '/src/ServerManager/API/Hosting/Result.php',
  'ServerManager\Controller\ServerManagerController' => __DIR__ . '/src/ServerManager/Controller/ServerManagerController.php',
  'ServerManager\Controller\TestController'          => __DIR__ . '/src/ServerManager/Controller/TestController.php',
);
