<div>
    <h3 class="page-title">
        <?= $this->translate('New Doctor/Counselor Time for'); ?> » <?= \Theme\API\Common::Link(
            getUserDisplayName($this->doctorUser),
            url('app/user/user-profile',array('id'=>$this->doctorUser->userId)),
            array('target' => '_blank')
        ) ?>
    </h3>

    <div class="list-group">
        <a href="<?= url('admin/health-center/doctors/timetable/new', array('doctor' => $this->doctor, 'type' => 'single-day')) ?>"
           class="list-group-item ajax_page_load">
            <h4 class="list-group-item-heading"><?= t('Single Day') ?></h4>

            <p class="list-group-item-text">
                <?= t('create a entry in time table for a single specific date from start time to end time') ?>
            </p>
        </a>
        <a href="<?= url('admin/health-center/doctors/timetable/new', array('doctor' => $this->doctor, 'type' => 'periodic')) ?>"
           class="list-group-item ajax_page_load">
            <h4 class="list-group-item-heading"><?= t('Periodic Repeat') ?></h4>

            <p class="list-group-item-text">
                <?=
                t('create a entry in time table from start date to end date for selected days of week (saturday, sunday,
                ...) and from start time to rnd time')?>
            </p>
        </a>
    </div>
</div>