<div>
    <h2>
        <?= t('app_hello_dear_user') .' '. $this->__NAME__ ?>
    </h2>
    <p>
        <?=sprintf(t('realEstate_update_approvedEstateInSite'),ACTIVE_SITE )?>
    </p>
    <p>
        <?= sprintf(t('realEstate_estateIdIs%s'), $this->__CODE__) ?>
    </p>
    <a href="<?=$this->__VIEWURL__?>" target="_blank"><?=t('realEstate_showHomeLink')?></a>
    <br/>
    <?= ACTIVE_SITE ?>
</div>