<?

$direction = $this->translate('lang_direction'); //rtl ? ltr

$this->headLink()
    ->prependStylesheet($this->basePath() . '/css/system.css')
    ->prependStylesheet($this->basePath() . '/css/base-theme/jquery-ui-1.10.1.custom.min.css')
    ->prependStylesheet($this->basePath() . '/css/reset.min.css');

$this->headLink()->appendStylesheet($this->basePath() . TEMPLATE_PATH . '/css/style.css');
$this->headLink()->appendStylesheet($this->basePath() . TEMPLATE_PATH . '/css/real-estate-melkyab.css');

$this->headScript()
    ->prependFile($this->basePath() . TEMPLATE_PATH . '/js/template.js')
    ->prependFile($this->basePath() . '/js/system.jquery.ui.buttons.js')
    ->prependFile($this->basePath() . '/js/system.jquery.ui.js')
    ->prependFile($this->basePath() . '/js/jquery.cookie.js')
    ->prependFile($this->basePath() . '/js/system.js')
    ->prependFile($this->basePath() . '/js/forms.js')
    ->prependFile($this->basePath() . '/js/jquery.transit.min.js')
    ->prependFile($this->basePath() . '/js/general-client.js')
    ->prependFile($this->basePath() . '/js/jquery-ui-1.10.1.custom.min.js')
    ->prependFile($this->basePath() . '/js/jquery-1.9.1.min.js');


$column_right_blocks = '';
$has_column_right = strlen(trim($column_right_blocks));

$mid_col_class = '';


if ($has_column_right)
    $mid_col_class = 'two_columns';

$user_block = $this->user_logged_in_block();
if (!$user_block) {
    $user_login_block = $this->blocks('user-popup');
}

$headerBlock = $this->blocks('header');
$topMenuBlock = $this->blocks('top-menu');

$colRightBlock = $this->blocks('col-right');
$hasRightColumn = !empty($colRightBlock);

$debugBlock = $this->blocks('debug');
$colMidTopBlock = $this->blocks('col-mid-top');

$colLeftTopBlock = $this->blocks('col-left-top');
$colLeftLeftBlock = $this->blocks('col-left-left');
$colLeftRightBlock = $this->blocks('col-left-right');
$search = $this->blocks('search');
$hasLeftBlock = (!empty($colLeftTopBlock) || !empty($colLeftLeftBlock) || !empty($colLeftRightBlock));
$footerBlock = $this->blocks('footer');

$mainSlider = $this->blocks('main-slider');
$logo = $this->blocks('logo');
$menu = $this->blocks('menu');
$footer_menu = $this->blocks('footer-menu');
$footer_menu2 = $this->blocks('footer-menu2');
$footer_menu3 = $this->blocks('footer-menu3');
$footer_menu4 = $this->blocks('footer-menu4');
$languageSwitcher = $this->langSwitcher(null);

$breadcrumbs = $this->breadcrumb();
?>

<?php echo $this->doctype(); ?>

<html lang="fa" xmlns="http://www.w3.org/1999/html">
<head>
    <?= $this->head() ?>
    <?= $this->headTitle() ?>
    <?= $this->headMeta() ?>
    <?= $this->headLink() ?>
    <?= $this->headScript() ?>

</head>

<body class="<?= implode(' ', $this->body()->class) ?>">
<?= $this->body()->getSiteTitle() ?>
<?= $this->body()->getSiteSubTitle() ?>

<style>
    .box_compare{width: 0; background: #ffffff; height: 58px; position: fixed; left: 0; top: 30%;  -moz-box-shadow:0 0 5px -2px #000000;-webkit-box-shadow:0 0 5px -2px #000000; box-shadow:0 0 5px -2px #000000; border-top-right-radius: 5px; border-bottom-right-radius: 5px;}
    .box_compare .img_compare{background: url(<?=$this->basePath() . TEMPLATE_PATH . '/images/compare_icon.png'?>) no-repeat center center; height: 39px; width: 39px; display: block; margin: 10px auto;}
</style>
<div class="box_compare">
    <a class="img_compare" href="#" ></a>
</div>
<div class="main-body">

    <div class="column header">


        <? if (!empty($headerBlock)) { ?>
            <?= $headerBlock ?>
        <? } ?>

        <?= $languageSwitcher ?>

        <div class="top_menu_box">
            <div class="box-top-menu">
                <?= $topMenuBlock ?>
            </div>

        </div>

        <div class="col-mid-top-header">

            <div class="box-mid-top-header">
                <? if (!$user_block) { ?>
                    <div class="box user_login_popup" id="user_login_popup">
                        <?= $user_login_block ?>
                    </div>
                    <div class="box user_login_box">
                        <a id="user_login_link"
                           href="<?= url('app/user/login') ?>"><span><?= t('Login') ?></span></a>
                    </div>
                <? } ?>
                <div id="user_popup_container">
                    <?
                    if ($user_block) {
                        if (isAllowed(\Application\Module::ADMIN)) {
                            ?>
                            <div class="box admin_link_box">
                                <a href="<?= url('admin') ?>"><span><?= t('Administration') ?></span></a>
                            </div>
                        <?
                        }
                        echo $user_block;
                    }
                    ?>
                </div>
                <div id="allSearch">
                    <?=$search?>
                </div>
                <div class="mid-top-box-right">
                    <?= $logo ?>
                </div>
                <div class="mid-top-box-left">
                    <div id="main-menu">
                        <?= $menu ?>
                    </div>
                </div>

            </div>


        </div>

    </div>

    <div class="column mid-content">

        <div class="sidebar">

            <div class="sidebar-link"><a href="http://melkyab.org/fa/real-estate/new-request"><img
                        src="<?= $this->basePath() . TEMPLATE_PATH ?>/images/button2-01.png"
                        width="200"
                        height="40"/></a>
            </div>
            <div class="sidebar-link"><a href="http://melkyab.org/fa/real-estate/new-transfer"><img
                        src="<?= $this->basePath() . TEMPLATE_PATH ?>/images/button2-02.png"
                        width="200" height="40"/></a>

                <div class="sidebar-link-free"></div>
            </div>
            <div class="sidebar-link"><a href="#"><img
                        src="<?= $this->basePath() . TEMPLATE_PATH ?>/images/button2-03.png"
                        width="200" height="40"/></a>
            </div>

            <? if (!empty($colRightBlock)) { ?>
                <div class="column column1">
                    <?= $colRightBlock ?>
                </div>
            <? } ?>

        </div>

        <div class="box-content">

            <!--<div id="breadcrumbs"><?/*= $breadcrumbs */?></div>-->

            <div class="box-content_body">

                <div id="content_body">
                    <? if (!empty($mainSlider)) { ?>
                        <div class="box-content-slider">
                            <div class="main-slider">
                                <?= $mainSlider ?>
                            </div>
                        </div>
                    <? } ?>
                    <div style="clear:both"></div>
                    <div class="content-body-latest">
                        <?= $colMidTopBlock ?>
                    </div>
                    <div style="clear:both"></div>
                    <div id="system_messages"><?= $this->flashMessenger()->render(); ?></div>
                    <div class="search-form">
                        <?= $this->content; ?>
                    </div>
                </div>
            </div>

        </div>

    </div>

    <div class="footer">

        <?= $footerBlock ?>
        <div class="box-th-container">
            <div class="th-container">
                <a title="صفحه اصلی وب سایت تخصصی ملک یاب" href='http://www.melkyab.org' class="th-box home2"></a>
                <a title="جستجوی بانک اطلاعاتی ملک یاب" href='http://www.melkyab.org'
                   class="th-box amlak-mostaghalat"></a>
                <a title="راه اندازی وب سایت املاک " href='http://www.melkyab.org/fa/online-order'
                   class="th-box tarrahi-site"></a>
                <a title="آگهی نامه تخصصی املاک" href="http://ads.melkyab.org" class="th-box agahi-amlak"></a>
                <a title="درباره موتور جستجوی ملک یاب" href="#" class="th-box about-us"></a>
                <a title="تماس با شرکت ایده پرداز تبریز" href='http://www.melkyab.org/fa/contact'
                   class="th-box contact-us"></a>
            </div>
        </div>
        <div class="footer-menu-box">
            <div class="box-footer-menu">
                <? if (!empty($footer_menu)) { ?>
                <div class="footermenu">
                    <?= $footer_menu ?>
                    <div class="copyright">
                        <div class="copyright-box1">
                            برای مشاهده بهتر سایت از مرورگر های
                            <a href="http://www.firefox.com" target="_blank"> Firefox 3+ </a>

                            ،
                            <a href="http://www.microsoft.com/windows/internet-explorer/default.aspx" target="_blank">Internet
                                explorer7+</a>

                            ،
                            <a href="http://www.google.com/chrome" target="_blank">Google Chrome </a>

                            استفاده کنید و بهترین حالت نمایش سایت 768*1024 است.

                        </div>


                        <div class="box-copyright-mid">
                            <div class="copyright-col-right bottom">درج موارد ملکی در سایت ملک یاب رایگان می باشد.</div>

                            <div class="copyright-col-right bottom2">کلیه حقوق مادی و معنوی برای وب سایت ملک یاب محفوظ
                                است.
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <? } ?>


        </div>

    </div>

</div>

<!--<div id="bottom-toolbar">
</div>-->
<div class="debug">
    <?= $debugBlock ?>
</div>
<?= $this->inlineScript() ?>
<script type="text/javascript">
    var c1W = parseInt($('.column1').width());
    c1W = isNaN(c1W) ? 0 : c1W;

    var c3W = parseInt($('.column3').width());
    c3W = isNaN(c3W) ? 0 : c3W;

    var c4W = parseInt($('.column4').width());
    c4W = isNaN(c4W) ? 0 : c4W;

    var c5W = parseInt($('.column5').width());
    c5W = isNaN(c5W) ? 0 : c5W;

    var leftColumnW = isNaN(c5W) ? c3W + c4W : c5W;
    var columnsW = c1W + leftColumnW;
    if (columnsW != 0)
        columnsW += 15;
    var main_contentW = parseInt($('.main_content').width());
    var c2W = main_contentW - columnsW;
    //console.log(c1W);
    $('.column2').css({width: c2W});
    $('.column_top').css({width: main_contentW});
</script>

</body>
</html>
