<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'IPTProductOrder\Controller\OrderController' => __DIR__ . '/src/IPTProductOrder/Controller/OrderController.php',
  'IPTProductOrder\Install'                    => __DIR__ . '/src/IPTProductOrder/Install.php',
);
