<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'CustomersClub\API\ACL'                     => __DIR__ . '/src/CustomersClub/API/ACL.php',
  'CustomersClub\API\Club'                    => __DIR__ . '/src/CustomersClub/API/Club.php',
  'CustomersClub\API\EventManager'            => __DIR__ . '/src/CustomersClub/API/EventManager.php',
  'CustomersClub\API\Point'                   => __DIR__ . '/src/CustomersClub/API/Point.php',
  'CustomersClub\Controller\Club'             => __DIR__ . '/src/CustomersClub/Controller/Club.php',
  'CustomersClub\Controller\Point'            => __DIR__ . '/src/CustomersClub/Controller/Point.php',
  'CustomersClub\Form\Config'                 => __DIR__ . '/src/CustomersClub/Form/Config.php',
  'CustomersClub\Form\Point'                  => __DIR__ . '/src/CustomersClub/Form/Point.php',
  'CustomersClub\Install'                     => __DIR__ . '/src/CustomersClub/Install.php',
  'CustomersClub\Model\CustomerRecordsTable'  => __DIR__ . '/src/CustomersClub/Model/CustomerRecordsTable.php',
  'CustomersClub\Model\Point'                 => __DIR__ . '/src/CustomersClub/Model/Point.php',
  'CustomersClub\Model\PointsTable'           => __DIR__ . '/src/CustomersClub/Model/PointsTable.php',
  'CustomersClub\Model\PointsTotalTable'      => __DIR__ . '/src/CustomersClub/Model/PointsTotalTable.php',
  'CustomersClub\View\Helper\CustomerRecords' => __DIR__ . '/src/CustomersClub/View/Helper/CustomerRecords.php',
);
