<?
//$content = \Theme\API\Themes::renderLayout($this);
$direction = $this->translate('lang_direction'); //rtl ? ltr
$basePath = $this->basePath();
$this->headLink()
    ->prependStylesheet(
        $basePath . TEMPLATE_PATH . '/css/ie10.css',
        'screen',
        'IE 10'
    );

if ($direction == 'rtl')
    $this->headLink()->prependStylesheet($basePath . TEMPLATE_PATH . '/css/bootstrap-rtl.min.css');

$this->headLink()
    ->prependStylesheet($basePath . TEMPLATE_PATH . '/css/bootstrap-theme.min.css')
    ->prependStylesheet($basePath . TEMPLATE_PATH . '/css/bootstrap.min.css')
    ->prependStylesheet($basePath . '/css/base-theme/jquery-ui-1.10.1.custom.min.css')
    ->prependStylesheet($basePath . '/css/system.css');

//------------------------------ TEMPLATE STYLE -------------------------------------------
$this->headLink()->appendStylesheet($basePath . TEMPLATE_PATH . '/css/style.css');
if ($direction == 'rtl')
    $this->headLink()->appendStylesheet($basePath . TEMPLATE_PATH . '/css/style-rtl.css');
$this->headLink()->appendStylesheet(
    $basePath . TEMPLATE_PATH . '/css/ie8.css',
    'screen',
    'lt IE 9'
);
////-------------------------------------------------------------


$this->headScript()
    ->prependFile($basePath . '/js/system.jquery.ui.buttons.js')
    ->prependFile($basePath . '/js/system.jquery.ui.js')
    ->prependFile($basePath . '/js/system.js')
    ->prependFile($basePath . '/js/forms.js')
    ->prependFile($basePath . '/js/jquery.hoverIntent.min.js')
    ->prependFile($basePath . '/js/jquery.transit.min.js')
    ->prependFile($basePath . '/js/general-client.js')
    ->prependFile($basePath . '/js/jquery-ui-1.10.1.custom.min.js')
    ->prependFile($basePath . '/js/jquery-1.9.1.min.js')
    ->prependFile(
        $basePath . TEMPLATE_PATH . '/js/respond.min.js',
        'text/javascript',
        array('conditional' => 'lt IE 9')
    )
    ->prependFile(
        $basePath . TEMPLATE_PATH . '/js/html5shiv.min.js',
        'text/javascript',
        array('conditional' => 'lt IE 9')
    );

//------------------------------ TEMPLATE JAVASCRIPT -------------------------------------------
$this->headScript()->appendFile($basePath . TEMPLATE_PATH . '/js/template.js');
$tomMenu = $this->blocks('top-menu');
$content = $this->content;
$breadcrumbs = $this->breadcrumb(2);
?>

<!DOCTYPE html>
<html lang="fa" xmlns="http://www.w3.org/1999/html">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <?= $this->head() ?>
    <?= $this->headTitle() ?>
    <?= $this->headMeta() ?>
    <?= $this->headLink() ?>
    <?= $this->headScript() ?>
</head>
<body>
<div id="container">
    <div class="sticky-header">
        <div class="row">
            <div class="col-md-9 col-sm-10 col-xs-9">
                <div class="row">
                    <div class="col-md-12">
                        <?= $tomMenu ?>
                    </div>
                </div>

            </div>
            <div class="col-md-3 col-sm-2 col-xs-3">
                <div id="header-tel">
                    041-33250011
                </div>
            </div>
        </div>
    </div>
    <div id="body">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div id="system_messages"><?= $this->flashMessenger()->render(); ?></div>
                    <div id="breadcrumbs"><?= $breadcrumbs ?></div>
                    <?= $content ?>
                </div>
            </div>
        </div>
    </div>
<!--    <div class="container-fluid footer sticky-bottom">-->
<!--        <div class="row">-->
<!--            <div class=" col-md-12">-->
<!--                <div class="">-->
<!--                    --><?//
//                    $startYear = mktime(0, 0, 0, 6, 0, 2012);
//                    $startYear = $this->dateFormat($startYear, \Localization\View\Helper\DateFormat::YEAR_ONLY);
//                    $nowYear = $this->dateFormat(time(), \Localization\View\Helper\DateFormat::YEAR_ONLY);
//                    ?>
<!--                    <p align="center">-->
<!--                        --><?//= t('APPLICATION_BROWSERS') ?>
<!--                    </p>-->
<!---->
<!--                    <p align="center">-->
<!--                        <span>--><?//= sprintf(t('APPLICATION_RIGHTS'), t('Azar Ideh Parda Tabriz', TEMPLATE_NAME)) ?><!--</span>-->
<!--                        <span dir="ltr">--><?//= sprintf(t('APPLICATION_COPY_RIGHT'), $startYear, $nowYear) ?><!--</span>-->
<!--                        &nbsp; .-->
<!--                        <span>--><?//= t('APPLICATION_SUPPORT') ?><!--</span> .-->
<!--                        <span>--><?//= t('APPLICATION_POWERED_BY') ?><!--</span>-->
<!--                    </p>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
    <?=$this->partial('application/footer',array('company'=>t('Azar Ideh Parda Tabriz', TEMPLATE_NAME)))?>
</div>
<div id="fixed-menu">
    <span id="fixed-menu-toggle"></span>

    <div class="menu-item">
        <a href="http://ipt24.com/support/submitticket.php" target="_blank">
            <img src="<?= $basePath . TEMPLATE_PATH . '/images/fixed-menu/darkhaste-poshtibani.png' ?>">
                 <span>
                     درخواست پروژه
                 </span>
        </a>
    </div>
    <div class="menu-item">
        <a href="http://ipt24.com/price-inquiry" target="_blank">
            <img src="<?= $basePath . TEMPLATE_PATH . '/images/fixed-menu/arzyabi-raygane-proje.png' ?>">
                 <span>
                     ارزیابی رایگان پروژه
                 </span>
        </a>
    </div>

    <div class="menu-item">
        <a href="http://ipt24.com/support/cart.php" target="_blank">
            <img src="<?= $basePath . TEMPLATE_PATH . '/images/fixed-menu/host.png' ?>">
                 <span>
                     میزبانی وب
                 </span>
        </a>
         و
        <a href="http://ipt24.com/support/cart.php?a=add&domain=register" target="_blank" class="icon-less">
                 <span>
                     ثبت دامنه
                 </span>
        </a>
    </div>
    <div class="menu-item">
        <a href="http://ipt24.com/fa/contact/single/1" target="_blank">
            <img src="<?= $basePath . TEMPLATE_PATH . '/images/fixed-menu/contact-us.png' ?>">
                 <span>
                     تماس با ما
                 </span>
        </a>
    </div>
    <div class="menu-item">
        <a href="http://www.azaript.com/online-support/chat.php" target="_blank">
            <img src="<?= $basePath . TEMPLATE_PATH . '/images/fixed-menu/poshtibani-online.png' ?>">
                 <span>
                     پشتیبانی آنلاین
                 </span>
        </a>
    </div>
</div>
<?= $this->inlineScript() ?>
</body>
</html>
