<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'SimpleOrder\API\ACL'                               => __DIR__ . '/src/SimpleOrder/API/ACL.php',
  'SimpleOrder\API\EventManager'                      => __DIR__ . '/src/SimpleOrder/API/EventManager.php',
  'SimpleOrder\Controller\SimpleOrderAdminController' => __DIR__ . '/src/SimpleOrder/Controller/SimpleOrderAdminController.php',
  'SimpleOrder\Controller\SimpleOrderController'      => __DIR__ . '/src/SimpleOrder/Controller/SimpleOrderController.php',
  'SimpleOrder\Controller\StepOrderController'        => __DIR__ . '/src/SimpleOrder/Controller/StepOrderController.php',
  'SimpleOrder\Form\Categories'                       => __DIR__ . '/src/SimpleOrder/Form/Categories.php',
  'SimpleOrder\Form\CategoryCollection'               => __DIR__ . '/src/SimpleOrder/Form/CategoryCollection.php',
  'SimpleOrder\Form\Config'                           => __DIR__ . '/src/SimpleOrder/Form/Config.php',
  'SimpleOrder\Form\SimpleOrder'                      => __DIR__ . '/src/SimpleOrder/Form/SimpleOrder.php',
  'SimpleOrder\Install'                               => __DIR__ . '/src/SimpleOrder/Install.php',
  'SimpleOrder\Model\SimpleOrder'                     => __DIR__ . '/src/SimpleOrder/Model/SimpleOrder.php',
  'SimpleOrder\Model\SimpleOrderTable'                => __DIR__ . '/src/SimpleOrder/Model/SimpleOrderTable.php',
);
