<?
$this->headLink()->prependStylesheet($this->basePath() . '/__/css/ads.css');
if (!$this->error) {
    ?>
    <div class="box_list_ads_6000_0">
        <?
        if ($this->select) {
            $countEndTag = 0;
            $panelId = 0;
            foreach ($this->select as $row) {
                $fields_table = getSM('fields_api')->init('ads_' . $row->baseType . '_' . $row->regType);
                $fields = getSM('fields_table')->getByEntityType('ads_' . $row->baseType . '_' . $row->regType)->toArray();
                $fieldsData = getSM('fields_api')->generate($fields, $row);
                $urlTitle = '';
                if(!empty($row->title)){
                    $urlTitle = $row->title;
                }
                else
                    $urlTitle = $this->baseTypeMachineName;
                ?>
                <div class="col-md-6 box_panel">
                    <div class="row">
                        <div class="col-xs-12 col-sm-9 col-md-9 zero_padding">
                            <div class="">
                                <div class="panel-body">
                                    <div class="media">
                                        <!--<a class="pull-right" href="#">
                                            <?/*
                                            $width = 100;
                                            $height = 100;
                                            $fPath = '';
                                            if ($row->smallImage) {
                                                $dataImages = unserialize($row->smallImage);
                                                if ($dataImages) {
                                                    if (isset($this->smallImgConfig['width']))
                                                        $width = $this->smallImgConfig['width'];
                                                    if (isset($this->smallImgConfig['height']))
                                                        $width = $this->smallImgConfig['height'];
                                                }
                                                if (isset($dataImages['fPath']) && $dataImages['fPath'])
                                                    $fPath = $dataImages['fPath'];
                                            } else {
                                                $fPath = $this->basePath() . TEMPLATE_PATH . '/images/realestate/defult-img.png';
                                            }

                                            $imageUrl = getThumbnail()->resize($fPath, $width, $height); //resize image
                                            */?>
                                            <img class="media-object" src="<?/*= $imageUrl */?>"
                                                 alt="<?/*= $row->title */?>">
                                        </a>-->
                                        <div class="media-body">
                                            <? if ($row->title) { ?>
                                                <div class="col-xs-12 col-sm-12 col-md-12">
                                                    <a href="<?= url('app/ad/view', array('baseType' => $row->baseType, 'adId' => $row->adId, 'adTitle' => \Application\API\App::prepareUrlString($urlTitle))) ?>">
                                                <span class="media-heading">
                                                    <?
                                                    if (strlen($row->title) > 30) echo mb_substr($row->title, 0, 30, 'UTF-8') . '...'; else echo $row->title;
                                                    ?>
                                                </span>
                                                    </a>
                                                </div>
                                            <? } ?>
                                            <div class="col-xs-12 col-sm-12 col-md-12">
                                            <span class="r_label">
نوع آگهی :
                                            </span>
                                                    <span class="r_text">
                                                        <? if (isset($fieldsData['نوع ثبت']) && $fieldsData['نوع ثبت']) echo $fieldsData['نوع ثبت']; ?>
                                                        <? if (isset($fieldsData['نوع ملک']) && $fieldsData['نوع ملک']) echo $fieldsData['نوع ملک']; ?>
                                                    </span>
                                            </div>

                                            <? if ($fieldsData['نوع ثبت'] == 'خرید') { ?>
                                                <div class="col-xs-12 col-sm-12 col-md-12">
                                                    <span class="r_label">
توان پرداختی :
                                                    </span>
                                                    <span class="r_text">
                                                        <? if (isset($fieldsData['توان پرداختی']) && $fieldsData['توان پرداختی']) echo $this->currencyFormat($fieldsData['توان پرداختی']); else echo '---'; ?>
                                                    </span>
                                                </div>
                                            <? } elseif (($fieldsData['نوع ثبت'] == 'اجاره')) { ?>
                                                <div class="col-xs-12 col-sm-12 col-md-12">
                                                    <span class="r_label">
مبلغ رهن :
                                                    </span>
                                                    <span class="r_text">
                                                        <? if (isset($fieldsData['رهن']) && $fieldsData['رهن']) echo $this->currencyFormat($fieldsData['رهن']); else echo '---'; ?>
                                                    </span>
                                                </div>
                                                <div class="col-xs-12 col-sm-12 col-md-12">
                                                    <span class="r_label">
مبلغ اجاره :
                                                    </span>
                                                    <span class="r_text">
                                                        <? if (isset($fieldsData['اجاره']) && $fieldsData['اجاره']) echo $this->currencyFormat($fieldsData['اجاره']); else echo '---'; ?>
                                                    </span>
                                                </div>
                                            <? } ?>

                                            <? if (($fieldsData['نوع ملک'] == 'آپارتمان') || ($fieldsData['نوع ملک'] == 'خانه')) { ?>
                                                <div class="col-xs-12 col-sm-12 col-md-12">
                                                    <span class="r_label">
                                                        تعداد اتاق خواب :
                                                    </span>
                                                    <span class="r_text">
                                                        <? if (isset($fieldsData['تعداد اتاق']) && $fieldsData['تعداد اتاق']) echo $fieldsData['تعداد اتاق']; else echo '---'; ?>
                                                    </span>
                                                </div>
                                            <? } ?>

                                            <div class="col-xs-12 col-sm-12 col-md-12">
                                            <span class="r_label">
متراژ تقریبی :
                                            </span>
                                                    <span class="r_text">
                                                        <? if (isset($fieldsData['متراژ تقریبی']) && $fieldsData['متراژ تقریبی']) echo $fieldsData['متراژ تقریبی']; else echo '---'; ?>
                                                    </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-3 col-md-3 zero_padding">
                            <div class="col-xs-12 col-sm-12 col-md-12 box_id">
                               <span class="r_label">
کد آگهی :
                               </span>
                               <span class="r_text">
                                    <?= $row->adId ?>
                               </span>
                            </div>

                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <p class="text-muted created"><?= $this->dateFormat($row->createDate, 2); ?></p>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                                <a class="box_read_more"
                                   href="<?= url('app/ad/view', array('baseType' => $row->baseType, 'adId' => $row->adId, 'adTitle' => \Application\API\App::prepareUrlString($urlTitle))) ?>">
                                    مشاهده جزئیات
                                </a>
                            </div>
                            <? if ($row->starCount > 0) { ?>
                                <div class="col-md-12 zero_padding text_center">
                                    <?= getSM('ads_api')->createViewStarRate($this->starCount, $row->starCount); ?>
                                </div>
                            <? } ?>
                        </div>
                    </div>
                </div>

            <?
            }
        } else {
            ?>
            <div class="alert alert-info">
                <?= t('ADS_NOT_FOUND') ?>
            </div>
        <?
        }
        ?>
        <div style="clear:both"></div>
        <div class="pager" style="padding-top:12px;">
            <?
            /* @var $pages \Zend\Paginator\Paginator */
            echo $this->paginationControl($this->paginate,
                'Sliding',
                'ads/client/search.phtml',
                array(
                    'route' => 'app/ad/list',
                    'route_params' => array('baseType' => $this->baseTypeId, 'baseTitle' => $this->baseTypeMachineName)
                )
            ); ?>
        </div>
        <div style="clear:both"></div>
    </div>
<? } ?>


