<?
\JQuery\API\JQuery::loadColorBox($this);
use Localization\API\Date;

$this->headLink()->prependStylesheet($this->basePath() . '/__/css/ads.css');
$flagShowAllInfo = $this->flagShowAllInfo;
if ($this->select) {
    $select = $this->select;
    ?>

    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-6">
                <img src="<?= $this->basePath() . TEMPLATE_PATH . '/images/main/logo_new.png' ?>"
                     class="img-responsive logo_new">
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6">
                <span class="box_title_type">
                    آگهی فروش خودرو
                </span>
                <span class="box_title_id">
کد آگهی :
                    <?= $select->adId ?>
                </span>
            </div>
        </div>
    </div>

    <?
    if (($select->expireDate < time()) && (!$this->showStatusType)) {
        ?>
        <div class="alert alert-danger">
            <?= t('ADS_YOUR_AD_EXPIRED') ?>
        </div>
    <?
    } else {

        if (isAllowed(\Ads\Module::APP_AD_VIEW_ALL_INFO))
            $flagShowAllInfo = true;
        if ($this->baseTypeAmountAllInfo <= 0)
            $flagShowAllInfo = true;


        $fieldsData = getSM()->get('fields_api')->generate($this->fields, (array)$select);
        ?>
        <div class="col-xs-12 col-sm-12 col-md-12 box_view_6000_0">
        <?
        if ($this->baseTypeRate) {
            ?>
            <div class="col-xs-12 col-sm-6 col-sm-offset-6 col-md-5 col-md-offset-6 box_rate">
            <span class="title">
                این آگهی از نظر شما قابل قبول است یا خیر :
            </span>
                <?= $this->negative_positive($select->adId, 'ads_' . $select->baseType . '_' . $select->regType) ?>
            </div>
        <?
        }
        ?>
        <? if ($select->expireDate < time()) { ?>
            <div class="col-md-12 ads_expired">
                <div class="alert alert-info">
                    <?= t('ADS_YOUR_AD_EXPIRED') ?>
                </div>
            </div>
            <br>
        <? } ?>

        <fieldset class="f_view">
            <legend>
                مشخصات کلی آگهی
            </legend>
            <div class="col-md-8">
                <div class="row">
                    <? if ($select->title) { ?>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <h4 class="a_title"><?= $select->title ?></h4>
                        </div>
                    <? } ?>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                       <span class="a_label">
نام :
                       </span>
                        <span class="a_text"><?= $select->name; ?></span>
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <span class="a_label"><?= t('State') . ' : ' ?></span>
                        <span class="a_text"><?= $select->stateTitle; ?></span>
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <span class="a_label"><?= t('City') . ' : ' ?></span>
                        <span class="a_text"><?= $select->cityTitle; ?></span>
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <span class="a_label"><?= t('Address') . ' : ' ?></span>
                        <span
                            class="a_text"><? if ($flagShowAllInfo) echo $select->address; else echo t('ADS_LIMITED_SHOW') ?></span>
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <span class="a_label"><?= t('Mobile') . ' : ' ?></span>
                        <span
                            class="a_text"><? if ($flagShowAllInfo) echo $select->mobile; else echo t('ADS_LIMITED_SHOW') ?></span>
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <span class="a_label"><?= t('Email') . ' : ' ?></span>
                        <span
                            class="a_text"><? if ($flagShowAllInfo) echo $select->mail; else echo t('ADS_LIMITED_SHOW') ?></span>
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <span class="a_label"><?= t('ADS_REG_DATE') . ' : ' ?></span>
                        <span class="a_text"><?= $this->dateFormat($select->createDate, 2) ?></span>
                    </div>

                    <? if ($select->expireDate) { ?>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <span class="a_label"><?= t('ADS_TIME_REMAINING') . ' : ' ?></span>
                            <span class="a_text">
                                <?
                                $timeRemaining = 0;
                                if (time() < $select->expireDate) echo Date::formatInterval($select->expireDate - time());
                                ?>
                            </span>
                        </div>
                    <? } ?>

                    <?
                    if ($this->keywords && isset($this->keywords[$select->entityId])) {
                        ?>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <span class="a_label"><?= t('ADS_KEYWORDS') . ' : ' ?></span>
                            <?
                            foreach ($this->keywords[$select->entityId] as $key => $val) {
                                ?>
                                <a href="<?= url('app/ad/list', array('baseType' => $select->baseType, 'isRequest' => $select->regType, 'baseTitle' => $this->baseTypeMachineName), array('query' => array('table' => array('keyword' => $val)))) ?>"><?= $val ?></a> |
                            <?
                            }
                            ?>
                        </div>
                    <?
                    }
                    ?>

                </div>
            </div>

            <div class="col-md-12 col-sm-4 col-md-4">
                <div class="row text_center">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <?= getSM('ads_api')->createViewStarRate($this->starCount, $select->starCount); ?>
                    </div>
                    <?
                    $width = 100;
                    $height = 100;
                    $fPath = '';
                    if ($select->smallImage) {
                        $dataImages = unserialize($select->smallImage);
                        if ($dataImages) {
                            if (isset($this->smallImgConfig['width']))
                                $width = $this->smallImgConfig['width'];
                            if (isset($this->smallImgConfig['height']))
                                $width = $this->smallImgConfig['height'];
                        }
                        if (isset($dataImages['fPath']) && $dataImages['fPath'])
                            $fPath = $dataImages['fPath'];
                    } else {
                        $fPath = $this->basePath() . TEMPLATE_PATH . '/images/realestate/defult-img.png';
                    }

                    $imageUrl = getThumbnail()->resize($fPath, $width, $height); //resize image
                    ?>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <img class="media-object margin_auto" src="<?= $imageUrl ?>" alt="<?= $select->title ?>">
                    </div>
                </div>
            </div>

        </fieldset>

        <?
        $columns = array(
            array(
                'title' => 'جزئیات بیشتر آگهی',
                'part' => 1,
                'size' => 12,
                'items' => array(
                    'نوع خودرو' => 4,
                    'برند' => 4,
                    'مدل' => 4,
                    'سال' => 4,
                    'نوع سوخت' => 4,
                    'کارکرد' => 4,
                    'گیربکس' => 4,
                    'قیمت نقدی' => 4,
                    'وضعیت خودرو' => 4,
                    'نوع فروش' => 4,
                    'رنگ بدنه' => 4,
                    'رنگ داخل' => 4,
                    'نوع پلاک' => 4,
                    'در صورت لزوم معاوضه خواهد شد' => 12,
                    'فقط به صورت نقدی می فروشم' => 12,
                )
            ),
        );
        $html = '';

        foreach ($columns as $col) {
            $items = '';
            foreach ($col['items'] as $field => $size) {
                $value = '----';
                if (isset($fieldsData[$field]) && $fieldsData[$field]!='انتخاب کنید') {
                    $value = $fieldsData[$field];
                    if ($field == 'قیمت نقدی')
                        $value = $this->currencyFormat($value);
                }
                if ($field != 'فقط به صورت نقدی می فروشم' && $field != 'در صورت لزوم معاوضه خواهد شد' )
                    $items .= "<div class='col-xs-" . $size . "'><span class='a_label'>" . $field . " : </span><span class='a_text'> " . $value . "</span></div>";
                else
                    if ($value == 1)
                        $items .= "<div class='col-xs-" . $size . "'><span class='label label-danger'><span class='glyphicon glyphicon-ok text-success'></span>$field</span></div>";
            }
            $html .= "<fieldset class='f_view part_" . $col['part'] . "'><legend>" . $col['title'] . "</legend><div class='col-md-12'><div class='row'>" . $items . "</div></div></fieldset>";
        }
        echo $html;
        ?>

        <? if ($select->text) { ?>
            <fieldset class="f_view">
                <legend>
                    توضیحات آگهی
                </legend>
                <div>
                    <span class="a_label"><?= t('Description') . ' : ' ?></span>

                    <span class="a_text"><?= $select->text ?></span>
                </div>
            </fieldset>
        <? } ?>

        <? if ($this->selectImage) { ?>
            <div class="col-md-6">
                <fieldset class="f_view">
                    <legend>
                        تصاویر
                    </legend>

                    <div>
                        <?
                        foreach ($this->selectImage as $row) {
                            if ($row->fPath)
                                $fPathImg = $row->fPath;
                            else
                                $fPathImg = $this->basePath() . TEMPLATE_PATH. '/images/cars/def_car.png';
                            $imageUrl = getThumbnail()->resize($fPathImg, 100, 100); //resize image
                            $href = $fPathImg;
                            ?>
                            <div class="col-md-4">
                                <a class="colorbox" href="<?= $href ?>">
                                    <img src="<?= $imageUrl ?>" width="100"
                                         style="display: block; margin: auto;" height="100"
                                         title="<?= $row->fTitle ?>"
                                         alt="<?= $row->fAlt ?>">
                                </a>
                            </div>
                        <?
                        }
                        ?>
                    </div>

                </fieldset>
            </div>
        <? } ?>

        <? if (isset($fieldsData['فیلم']) && $fieldsData['فیلم']) { ?>
            <div class="col-md-6">
                <fieldset class="f_view text_center">
                    <legend>
                        فیلم
                    </legend>
                    <div>
                        <?
                        $pos = strpos($fieldsData['فیلم'], 'www.aparat.com');
                        $film = str_replace('width="640"', 'width="100%"', $fieldsData['فیلم']);
                        $film = str_replace('height="360"', 'height="200"', $film);
                        if ($pos)
                            echo $film;
                        else
                            echo t('ADS_ILLEGAL_FILM');
                        ?>
                    </div>
                </fieldset>
            </div>
        <? } ?>

        <div style="clear:both"></div>

        <br>
        <!--show all info-->
        <? if ($this->baseTypeAmountAllInfo > 0 && !$flagShowAllInfo) {
            //Payment
            $paymentParams = array(
                'amount' => $this->baseTypeAmountAllInfo,
                'email' => current_user()->email,
                'comment' => 'Pay For View All Data Ad',
                'validate' => array(
                    'route' => 'app/ad/view-data-validate',
                    'params' => array(
                        'id' => $select->adId,
                        'entityType' => 'ads_' . $select->baseType . '_' . $select->regType,
                        'userId' => current_user()->id,
                    ),
                )
            );
            $paymentParams = serialize($paymentParams);
            $paymentParams = base64_encode($paymentParams);
            ?>
            <? if (current_user()->id == 0) { ?>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <p class="alert alert-danger">
                        <?= t('ADS_ATTENTION_BUY_SHOW_INFO_GUEST_OR_MEMBER') ?>
                        <br>
                        <span class="glyphicon glyphicon-user text-primary"></span>
                        <a href="<?= url('app/user/register') ?>"><?= t('ADS_CLICK_FOR_REGISTER') ?></a>
                        <br>
                        <span class="glyphicon glyphicon-log-in text-primary"></span>
                        <a href="<?= url('app/user/login') ?>"><?= t('ADS_CLICK_FOR_LOGIN') ?></a>
                    </p>
                </div>
            <? } ?>
            <div class="col-xs-12 col-sm-12 col-md-12 text_center">
                <a href="<?= url('app/payment', array(), array('query' => array('routeParams' => $paymentParams))) ?>">
                    <button type="button" class="btn btn-default font_size">
                        <span class="glyphicon glyphicon-credit-card text-success"></span>
                        <?= sprintf(t('ADS_VIEW_DATA_PRICE'), $this->currencyFormat($this->baseTypeAmountAllInfo)) ?>
                    </button>
                </a>
            </div>
            <?
            //end
        } ?>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12 box_view_6000_0_count">
            <div class="col-xs-12 col-sm-4 col-md-4 margin_top">
                <span class="glyphicon glyphicon-comment text-info"></span>
                <?
                $countHits = 0;
                if ($select->hits)
                    $countHits = $select->hits;
                echo sprintf(t('ADS_COUNT_HITS'), $countHits);
                ?>
            </div>

            <div class="col-xs-12 col-sm-4 col-md-4 margin_top">
                <?
                echo $this->add_to_any_helper();
                ?>
            </div>

            <? if ($select->showPm && ($this->showStatusType == 1 || $select->expireDate > time())) { ?>
                <div class="col-xs-12 col-sm-4 col-md-4">
                    <?= $this->pm($select->userId) ?>
                </div>
            <? } ?>
        </div>

        <div style="clear:both"></div>
    <?
    }
} else {
    ?>
    <div class="alert alert-danger">
        <?= t('ADS_NOT_FOUND') ?>
    </div>
<?
}
?>




