<?
$this->headScript()->appendFile($this->basePath() . '/js/googlemap-in-colorbox.js');
\JQuery\API\JQuery::loadColorBox($this);
use Localization\API\Date;

$this->headLink()->prependStylesheet($this->basePath() . '/__/css/ads.css');
$flagShowAllInfo = $this->flagShowAllInfo;
if ($this->select) {
    $select = $this->select;
    $fieldsData = getSM()->get('fields_api')->generate($this->fields, (array)$select);
    ?>

    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-6">
                <img src="<?= $this->basePath() . TEMPLATE_PATH . '/images/main/logo_new.png' ?>"
                     class="img-responsive logo_new">
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6">
                <span class="box_title_type">
آگهی
                    <?= $fieldsData['نوع ثبت'] . ' ' . $fieldsData['نوع ملک'] ?>
                </span>
                <span class="box_title_id">
کد آگهی :
                    <?= $select->adId ?>
                </span>
            </div>
        </div>
    </div>



    <?
    if (($select->expireDate < time()) && (!$this->showStatusType)) {
        ?>
        <div class="alert alert-danger">
            <?= t('ADS_YOUR_AD_EXPIRED') ?>
        </div>
    <?
    } else {

        if (isAllowed(\Ads\Module::APP_AD_VIEW_ALL_INFO))
            $flagShowAllInfo = true;
        if ($this->baseTypeAmountAllInfo <= 0)
            $flagShowAllInfo = true;
        ?>
        <div class="col-xs-12 col-sm-12 col-md-12 box_view_6000_0">
        <?
        if ($this->baseTypeRate) {
            ?>
            <div class="col-xs-12 col-sm-6 col-sm-offset-6 col-md-5 col-md-offset-6 box_rate">
            <span class="title">
                این آگهی از نظر شما قابل قبول است یا خیر :
            </span>
                <?= $this->negative_positive($select->adId, 'ads_' . $select->baseType . '_' . $select->regType) ?>
            </div>
        <?
        }
        ?>

        <!-- <div class="col-xs-12 col-sm-3 col-sm-offset-8 col-md-3 col-md-offset-8">
            <? /*= getSM('ads_api')->createViewStarRate($this->starCount, $select->starCount); */ ?>
        </div>-->

        <div style="clear:both"></div>

        <? if ($select->expireDate < time()) { ?>
            <div class="col-md-12 ads_expired">
                <div class="alert alert-info">
                    <?= t('ADS_YOUR_AD_EXPIRED') ?>
                </div>
            </div>
            <br>
        <? } ?>


        <?
        $colSize = 12;
        if ($select->googleLatLong)
            $colSize = 7;
        ?>
        <div class="col-xs-12 col-sm-<?= $colSize ?> col-md-<?= $colSize ?>">
            <fieldset class="f_view">
                <legend>
                    مشخصات کلی آگهی
                </legend>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="row">
                        <? if ($select->title) { ?>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <h4 class="a_title"><?= $select->title ?></h4>
                            </div>
                        <? } ?>
                        <div class="col-xs-12 col-sm-12 col-md-12">
                       <span class="a_label">
نام :
                       </span>
                            <span class="a_text"><?= $select->name; ?></span>
                        </div>

                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <span class="a_label"><?= t('State') . ' : ' ?></span>
                            <span class="a_text"><?= $select->stateTitle; ?></span>
                        </div>

                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <span class="a_label"><?= t('City') . ' : ' ?></span>
                            <span class="a_text"><?= $select->cityTitle; ?></span>
                        </div>

                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <span class="a_label"><?= t('Address') . ' : ' ?></span>
                        <span
                            class="a_text"><? if ($flagShowAllInfo) echo $select->address; else echo t('ADS_LIMITED_SHOW') ?></span>
                        </div>

                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <span class="a_label"><?= t('Mobile') . ' : ' ?></span>
                        <span
                            class="a_text"><? if ($flagShowAllInfo) echo $select->mobile; else echo t('ADS_LIMITED_SHOW') ?></span>
                        </div>

                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <span class="a_label"><?= t('Email') . ' : ' ?></span>
                        <span
                            class="a_text"><? if ($flagShowAllInfo) echo $select->mail; else echo t('ADS_LIMITED_SHOW') ?></span>
                        </div>

                        <div class="col-xs-12 col-sm-12 col-md-12">
                            <span class="a_label"><?= t('ADS_REG_DATE') . ' : ' ?></span>
                            <span class="a_text"><?= $this->dateFormat($select->createDate, 2) ?></span>
                        </div>

                        <? if ($select->expireDate) { ?>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <span class="a_label"><?= t('ADS_TIME_REMAINING') . ' : ' ?></span>
                            <span class="a_text">
                                <?
                                $timeRemaining = 0;
                                if (time() < $select->expireDate) echo Date::formatInterval($select->expireDate - time());
                                ?>
                            </span>
                            </div>
                        <? } ?>

                        <?
                        if ($this->keywords && isset($this->keywords[$select->entityId])) {
                            ?>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <span class="a_label"><?= t('ADS_KEYWORDS') . ' : ' ?></span>
                                <?
                                foreach ($this->keywords[$select->entityId] as $key => $val) {
                                    ?>
                                    <a href="<?= url('app/ad/list', array('baseType' => $select->baseType, 'isRequest' => $select->regType, 'baseTitle' => $this->baseTypeMachineName), array('query' => array('table' => array('keyword' => $val)))) ?>"><?= $val ?></a> |
                                <?
                                }
                                ?>
                            </div>
                        <?
                        }
                        ?>

                    </div>
                </div>
            </fieldset>
        </div>

        <? if ($select->googleLatLong) { ?>
            <script>
                var googlemap_lat = '<?=$select->googleLatLong?>';
                var marker_icon = '<?=$this->basePath().TEMPLATE_PATH.'/images/main/marker2.png'?>';
            </script>
            <div class="col-xs-12 col-sm-5 col-md-5">
                <fieldset class="f_view">
                    <legend>
                        موقعیت جغرافیایی
                    </legend>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="row">

                            <a class="view-real-estate-google-map"
                               href='#'>
                                <img style="color: #000000;"
                                     alt="لطفا کمی صبر نمایید"
                                     src="http://maps.google.com/maps/api/staticmap?center=<?= $select->googleLatLong ?>&zoom=14&size=250x300&markers=<?= $select->googleLatLong ?>&sensor=false"/>
                            </a>

                        </div>
                    </div>
                </fieldset>
            </div>
        <? } ?>

        <div style="clear:both"></div>

        <?
        $columns = array(
            array(
                'title' => 'جزئیات بیشتر آگهی',
                'part' => 1,
                'size' => 12,
                'items' => array(
                    'قیمت' => 4,
                    'قیمت هر مترمربع' => 4,
                    'متراژ' => 4,
                    'تعداد اتاق' => 4,
                    'مستقر در طبقه' => 4,
                    'سال ساخت' => 4,
                    'تعداد واحد در طبقه' => 4,
                    'گواهی پایان کار' => 4,
                    'کف' => 4,
                    'تعداد مالکین' => 4,
                    'نوع مالکیت سند' => 4,
                    'موقعیت ملک' => 4,
                    'تعداد طبقات' => 4,
                    'عرصه' => 4,
                    'اعیان' => 4,
                    'عرض گذرگاه' => 4,
                    'حیاط' => 4,
                    'مساحت پارکینگ' => 4,
                    'ارتفاع پارکینگ' => 4,
                    'تعداد درختان' => 4,
                    'مساحت باغ' => 4,
                    'نوع باغ' => 4,
                    'نوع سند' => 4,
                    'پلاک ثبتی' => 4,
                    'خانه باغ' => 4,
                    'کاربری' => 4,
                    'مکان زمین' => 4,
                    'تعداد سالن سرپوشیده' => 4,
                    'تولید قبلی' => 4,
                    'وضعیت تولید' => 4,
                    'اندازه سالن های اصلی' => 4,
                    'دستگاه یا ماشین های صنعتی' => 4,
                    'نام دستگاه یا ماشین های صنعتی' => 4,
                    'طول مغازه' => 4,
                    'عرض مغازه' => 4,
                    'نحوه فروش' => 4,
                    'اندازه ورودی مغازه' => 4,
                    'نوع درب و پنجره ورودی' => 4,
                    'قیمت رهن' => 4,
                    'قیمت اجاره' => 4,
                    'مورد استفاده قبلی ملک' => 4,
                    'ورودی واحد' => 4,
                    'امکان تحویل تا تاریخ' => 4,
                    'قفسه بندی' => 4,
                    'کرایه برای یک سال زراعی' => 4,
                    'سن درختان' => 4,
                    'وضعیت آبیاری درختان' => 4,
                    'منطقه' => 4,
                    'بازدید حضوری روزهای' => 4,
                    'ساعت' => 4,
                    'نام بنگاه مشاور' => 4,
                    'شماره آگهی ویژه بنگاه' => 4,
                    'شماره بنگاه مشاور' => 4,
                    'شماره همراه بنگاه مورد اعتماد' => 4,
                    'تلفن دفتر' => 4,
                    'نام بنگاه' => 4,
                    'آگهی کننده مدیر بنگاه هستم' => 12,
                    'آگهی دهنده خود مالک هستم' => 12,
                    'اجازه تغییر دکوراسیون داخلی برای مدت اجاره وجود دارد' => 12,
                    'امکان تحویل فوری دارد' => 12,
                    'ملک در پاساژ قرار دارد' => 12,
                )
            ),
            array(
                'title' => 'امکانات',
                'size' => 12,
                'part' => 2,
                'items' => array(
                    'آب' => 2,
                    'برق' => 2,
                    'گاز' => 2,
                    'تلفن' => 2,
                    'آسانسور' => 2,
                    'ریموت کنترل' => 2,
                    'آیفون تصویری' => 2,
                    'شوتینگ زباله' => 2,
                    'آنتن مرکزی' => 2,
                    'شومینه' => 2,
                    'جکوزی' => 2,
                    'نورمخفی' => 2,
                    'کمد دیواری' => 2,
                    'کولر آبی' => 2,
                    'کولر گازی' => 2,
                    'پارکینگ' => 2,
                    'انباری' => 2,
                    'لابی' => 2,
                    'حیاط' => 2,
                    'چاه عمیق' => 2,
                    'چاه نیمه عمیق' => 2,
                    'سرویس بهداشتی' => 2,
                    'آشپزخانه' => 2,
                    'هود آشپزخانه' => 2,
                ),
            ),
        );
        $html = '';
        foreach ($columns as $col) {
            $items = '';
            foreach ($col['items'] as $field => $size) {
                $value = null;
                if (isset($fieldsData[$field]) && $fieldsData[$field] != 'انتخاب کنید') {
                    $value = $fieldsData[$field];
                    if ($field == 'قیمت'
                        || $field == 'قیمت هر مترمربع'
                        || $field == 'رهن'
                        || $field == 'اجاره'
                    )
                        $value = $this->currencyFormat($value);
                }
                if ($col['part'] != 2) {
                    if ($field != 'اجازه تغییر دکوراسیون داخلی برای مدت اجاره وجود دارد'
                        && $field != 'امکان تحویل فوری دارد'
                        && $field != 'ملک در پاساژ قرار دارد'
                        && $field != 'آگهی دهنده خود مالک هستم'
                        && $field != 'آگهی کننده مدیر بنگاه هستم'
                        && $value
                        && $value != 'هیچکدام'
                    ) {
                        if ($field == 'نام بنگاه مشاور'
                            || $field == 'شماره آگهی ویژه بنگاه'
                            || $field == 'شماره بنگاه مشاور'
                            || $field == 'شماره همراه بنگاه مورد اعتماد'
                            || $field == 'تلفن دفتر'
                            || $field == 'نام بنگاه'
                        ) {
                            if (!$flagShowAllInfo)
                                $value = t('ADS_LIMITED_SHOW');
                            $items .= "<div class='col-xs-12 col-sm-12 col-md-12'><span class='a_label'>" . $field . " : </span><span class='a_text'> " . $value . "</span></div>";
                        } else
                            $items .= "<div class='col-xs-12 col-sm-6 col-md-4'><span class='a_label'>" . $field . " : </span><span class='a_text'> " . $value . "</span></div>";
                    } else {

                        if ($value == 1)
                            $items .= "<div class='col-xs-12 col-sm-12 col-md-12'><span class='label label-danger'><span class='glyphicon glyphicon-ok text-success'></span>" . $field . "</span></div>";
                    }
                } else {
                    if ($value) {
                        $items .= "<div class='col-xs-3 col-sm-2 col-md-2'><span class='glyphicon glyphicon-ok text-success'></span>" . $field . "</div>";
                    }
                }
            }
            $html .= "<fieldset class='f_view part_" . $col['part'] . "'><legend>" . $col['title'] . "</legend><div class='col-md-12'><div class='row'>" . $items . "</div></div></fieldset>";
        }
        echo $html;
        ?>

        <? if ($select->text) { ?>
            <fieldset class="f_view">
                <legend>
                    توضیحات آگهی
                </legend>
                <div>
                    <span class="a_label"><?= t('Description') . ' : ' ?></span>

                    <span class="a_text"><?= $select->text ?></span>
                </div>
            </fieldset>
        <? } ?>


        <div class="col-md-6">
            <fieldset class="f_view">
                <legend>
                    تصاویر
                </legend>

                <div>
                    <?
                    $width = 100;
                    $height = 100;
                    $fPath = '';
                    if ($select->smallImage) {
                        $dataImages = unserialize($select->smallImage);
                        if ($dataImages) {
                            if (isset($this->smallImgConfig['width']))
                                $width = $this->smallImgConfig['width'];
                            if (isset($this->smallImgConfig['height']))
                                $width = $this->smallImgConfig['height'];
                        }
                        if (isset($dataImages['fPath']) && $dataImages['fPath'])
                            $fPath = $dataImages['fPath'];
                    } else {
                        $fPath = $this->basePath() . TEMPLATE_PATH . '/images/realestate/defult-img.png';
                    }

                    $imageUrl = getThumbnail()->resize($fPath, $width, $height); //resize image
                    ?>
                    <div class="col-md-4">
                        <a class="colorbox" href="<?= $fPath ?>">
                            <img src="<?= $imageUrl ?>" width="100"
                                 style="display: block; margin: auto;" height="100"
                                 title="<?= $select->title ?>"
                                 alt="<?= $select->title ?>">
                        </a>
                    </div>
                    <?
                    if ($this->selectImage) {
                        foreach ($this->selectImage as $row) {
                            if ($row->fPath)
                                $fPathImg = $row->fPath;
                            else
                                $fPathImg = $this->basePath() . '/__/images/notImage100_100.png';
                            $imageUrl = getThumbnail()->resize($fPathImg, 100, 100); //resize image
                            $href = $fPathImg;
                            ?>
                            <div class="col-md-4">
                                <a class="colorbox" href="<?= $href ?>">
                                    <img src="<?= $imageUrl ?>" width="100"
                                         style="display: block; margin: auto;" height="100"
                                         title="<?= $row->fTitle ?>"
                                         alt="<?= $row->fAlt ?>">
                                </a>
                            </div>
                        <?
                        }
                    }
                    ?>
                </div>

            </fieldset>
        </div>

        <? if (isset($fieldsData['فیلم']) && $fieldsData['فیلم']) { ?>
            <div class="col-md-6">
                <fieldset class="f_view text_center">
                    <legend>
                        فیلم
                    </legend>
                    <div>
                        <?
                        $pos = strpos($fieldsData['فیلم'], 'www.aparat.com');
                        $film = str_replace('width="640"', 'width="100%"', $fieldsData['فیلم']);
                        $film = str_replace('height="360"', 'height="200"', $film);
                        if ($pos)
                            echo $film;
                        else
                            echo t('ADS_ILLEGAL_FILM');
                        ?>
                    </div>
                </fieldset>
            </div>
        <? } ?>

        <div style="clear:both"></div>

        <br>
        <!--show all info-->
        <? if ($this->baseTypeAmountAllInfo > 0 && !$flagShowAllInfo) {
            //Payment
            $paymentParams = array(
                'amount' => $this->baseTypeAmountAllInfo,
                'email' => current_user()->email,
                'comment' => 'Pay For View All Data Ad',
                'validate' => array(
                    'route' => 'app/ad/view-data-validate',
                    'params' => array(
                        'id' => $select->adId,
                        'entityType' => 'ads_' . $select->baseType . '_' . $select->regType,
                        'userId' => current_user()->id,
                    ),
                )
            );
            $paymentParams = serialize($paymentParams);
            $paymentParams = base64_encode($paymentParams);
            ?>
            <? if (current_user()->id == 0) { ?>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <p class="alert alert-danger">
                        <?= t('ADS_ATTENTION_BUY_SHOW_INFO_GUEST_OR_MEMBER') ?>
                        <br>
                        <span class="glyphicon glyphicon-user text-primary"></span>
                        <a href="<?= url('app/user/register') ?>"><?= t('ADS_CLICK_FOR_REGISTER') ?></a>
                        <br>
                        <span class="glyphicon glyphicon-log-in text-primary"></span>
                        <a href="<?= url('app/user/login') ?>"><?= t('ADS_CLICK_FOR_LOGIN') ?></a>
                    </p>
                </div>
            <? } ?>
            <div class="col-xs-12 col-sm-12 col-md-12 text_center">
                <a href="<?= url('app/payment', array(), array('query' => array('routeParams' => $paymentParams))) ?>">
                    <button type="button" class="btn btn-default font_size">
                        <span class="glyphicon glyphicon-credit-card text-success"></span>
                        <?= sprintf(t('ADS_VIEW_DATA_PRICE'), $this->currencyFormat($this->baseTypeAmountAllInfo)) ?>
                    </button>
                </a>
            </div>
            <?
            //end
        } ?>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12 box_view_6000_0_count">
            <div class="col-xs-12 col-sm-4 col-md-4 margin_top">
                <span class="glyphicon glyphicon-comment text-info"></span>
                <?
                $countHits = 0;
                if ($select->hits)
                    $countHits = $select->hits;
                echo sprintf(t('ADS_COUNT_HITS'), $countHits);
                ?>
            </div>

            <div class="col-xs-12 col-sm-4 col-md-4 margin_top">
                <?
                echo $this->add_to_any_helper();
                ?>
            </div>

            <? if ($select->showPm && ($this->showStatusType == 1 || $select->expireDate > time())) { ?>
                <div class="col-xs-12 col-sm-4 col-md-4">
                    <?= $this->pm($select->userId) ?>
                </div>
            <? } ?>
        </div>

        <div style="clear:both"></div>
    <?
    }
} else {
    ?>
    <div class="alert alert-danger">
        <?= t('ADS_NOT_FOUND') ?>
    </div>
<?
}
?>




