<div class="normal-list">
    <h3 class="page-title">
        System Updates
    </h3>

    <ul>
        <li>
            ‎Tuesday, ‎September ‎16, ‎2014
            <ul>
                <li>
                    update Module Payment And Increase Financial Transactions
                </li>
            </ul>
        </li>
        <li>
            Tuesday, ‎June ‎24, ‎2014
            <ul>
                <li>
                    Create Note Module
                </li>
            </ul>
        </li>
        <li>
            Monday, ‎June ‎23, ‎2014
            <ul>
                <li>
                    Update Page module & Gallery Module For Reference gallery to page & insert zoom Picture plugin
                </li>
            </ul>
        </li>
        <li>
            Tuesday, ‎June ‎3, ‎2014
            <ul>
                <li>
                    Create News letter Module
                </li>
            </ul>
        </li>
        <li>
            Saturday, ‎May ‎10, ‎2014
            <ul>
                <li>
                   Create Org Chart Module
                </li>
            </ul>
        </li>
        <li>
            Saturday, ‎May ‎3, ‎2014
            <ul>
                <li>
                    Update Category Module ( Upload Category item images into file table )
                </li>
            </ul>
        </li>
        <li>
            Tuesday, ‎April ‎15, ‎2014
            <ul>
                <li>
                    Modification and optimization Category List Block
                </li>
            </ul>
        </li>
        <li>
            Saturday, April 12, 2014
            <ul>
                <li>
                  Allow to upload Image for menu item
                </li>
            </ul>
        </li>
        <li>
            Monday, April 7, 2014
            <ul>
                <li>
                    System updates news page (this page)
                </li>
            </ul>
        </li>
    </ul>
</div>