<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'OnlineOrder\API\ACL'                          => __DIR__ . '/src/OnlineOrder/API/ACL.php',
  'OnlineOrder\API\EventManager'                 => __DIR__ . '/src/OnlineOrder/API/EventManager.php',
  'OnlineOrder\API\OnlineOrder'                  => __DIR__ . '/src/OnlineOrder/API/OnlineOrder.php',
  'OnlineOrder\Controller\OnlineOrderController' => __DIR__ . '/src/OnlineOrder/Controller/OnlineOrderController.php',
  'OnlineOrder\Form\Config'                      => __DIR__ . '/src/OnlineOrder/Form/Config.php',
  'OnlineOrder\Form\Customer'                    => __DIR__ . '/src/OnlineOrder/Form/Customer.php',
  'OnlineOrder\Form\DomainCustomer'              => __DIR__ . '/src/OnlineOrder/Form/DomainCustomer.php',
  'OnlineOrder\Form\Domains'                     => __DIR__ . '/src/OnlineOrder/Form/Domains.php',
  'OnlineOrder\Model\Client'                     => __DIR__ . '/src/OnlineOrder/Model/Client.php',
  'OnlineOrder\Model\ClientTable'                => __DIR__ . '/src/OnlineOrder/Model/ClientTable.php',
  'OnlineOrder\Model\Customer'                   => __DIR__ . '/src/OnlineOrder/Model/Customer.php',
  'OnlineOrder\Model\CustomerTable'              => __DIR__ . '/src/OnlineOrder/Model/CustomerTable.php',
  'OnlineOrder\Model\Site'                       => __DIR__ . '/src/OnlineOrder/Model/Site.php',
  'OnlineOrder\Model\SiteTable'                  => __DIR__ . '/src/OnlineOrder/Model/SiteTable.php',
  'OnlineOrder\View\Helper\Widget'               => __DIR__ . '/src/OnlineOrder/View/Helper/Widget.php',
);
