<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'OrgChart\API\ACL'                => __DIR__ . '/src/OrgChart/API/ACL.php',
  'OrgChart\API\EventManager'       => __DIR__ . '/src/OrgChart/API/EventManager.php',
  'OrgChart\API\OrgChart'           => __DIR__ . '/src/OrgChart/API/OrgChart.php',
  'OrgChart\Controller\ChartAdmin'  => __DIR__ . '/src/OrgChart/Controller/ChartAdmin.php',
  'OrgChart\Controller\ChartClient' => __DIR__ . '/src/OrgChart/Controller/ChartClient.php',
  'OrgChart\Controller\NodeAdmin'   => __DIR__ . '/src/OrgChart/Controller/NodeAdmin.php',
  'Mail\Factory\DbAdapterFactory'   => __DIR__ . '/src/OrgChart/Factory/DbAdapterFactory.php',
  'OrgChart\Form\ChartNode'         => __DIR__ . '/src/OrgChart/Form/ChartNode.php',
  'OrgChart\Form\Config\Config'     => __DIR__ . '/src/OrgChart/Form/Config/Config.php',
  'OrgChart\Form\Config\Fields'     => __DIR__ . '/src/OrgChart/Form/Config/Fields.php',
  'OrgChart\Form\Config'            => __DIR__ . '/src/OrgChart/Form/Config.php',
  'OrgChart\Form\OrgChart'          => __DIR__ . '/src/OrgChart/Form/OrgChart.php',
  'OrgChart\Install'                => __DIR__ . '/src/OrgChart/Install.php',
  'OrgChart\Model\ChartNode'        => __DIR__ . '/src/OrgChart/Model/ChartNode.php',
  'OrgChart\Model\ChartNodeTable'   => __DIR__ . '/src/OrgChart/Model/ChartNodeTable.php',
  'OrgChart\Model\OrgChart'         => __DIR__ . '/src/OrgChart/Model/OrgChart.php',
  'OrgChart\Model\OrgChartTable'    => __DIR__ . '/src/OrgChart/Model/OrgChartTable.php',
);
