<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'PM\API\ACL'                 => __DIR__ . '/src/PM/API/ACL.php',
  'PM\API\BBCodeDefinitionSet' => __DIR__ . '/src/PM/API/BBCodeDefinitionSet.php',
  'PM\API\EventManager'        => __DIR__ . '/src/PM/API/EventManager.php',
  'PM\API\PM'                  => __DIR__ . '/src/PM/API/PM.php',
  'PM\Controller\PM'           => __DIR__ . '/src/PM/Controller/PM.php',
  'PM\Controller\PMAdmin'      => __DIR__ . '/src/PM/Controller/PMAdmin.php',
  'PM\Form\PM'                 => __DIR__ . '/src/PM/Form/PM.php',
  'PM\Install'                 => __DIR__ . '/src/PM/Install.php',
  'PM\Model\PM'                => __DIR__ . '/src/PM/Model/PM.php',
  'PM\Model\PMTable'           => __DIR__ . '/src/PM/Model/PMTable.php',
  'PM\View\Helper\PM'          => __DIR__ . '/src/PM/View/Helper/PM.php',
);
