<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'Note\API\ACL'                   => __DIR__ . '/src/Note/API/ACL.php',
  'Note\API\Note'                  => __DIR__ . '/src/Note/API/Note.php',
  'Note\Controller\Note'           => __DIR__ . '/src/Note/Controller/Note.php',
  'Note\Form\Note'                 => __DIR__ . '/src/Note/Form/Note.php',
  'Note\Install'                   => __DIR__ . '/src/Note/Install.php',
  'Note\Model\Note'                => __DIR__ . '/src/Note/Model/Note.php',
  'Note\Model\NoteTable'           => __DIR__ . '/src/Note/Model/NoteTable.php',
  'Note\Model\NoteVisibilityTable' => __DIR__ . '/src/Note/Model/NoteVisibilityTable.php',
  'Note\View\Helper\Notes'         => __DIR__ . '/src/Note/View/Helper/Notes.php',
  'Note\View\Helper\Widget'        => __DIR__ . '/src/Note/View/Helper/~Widget.php',
);
