<div class="col-xs-12 col-sm-4 col-sm-offset-2 col-md-2 col-md-offset-4 box_search_btn  ">
    <a class="aran-search-btn" href="<?=url('app/ad/new',array('baseType'=>1000,'isRequest'=>0))?>">
        ثبت مشاغل
    </a>
</div>
<div class="col-xs-12 col-sm-4 col-sm-offset-0 col-md-2 col-md-offset-0 box_search_btn ">
    <a class="aran-search-btn" href="<?=url('app/user/login')?>">
        پنل کاربران
    </a>
</div>
