<div class="col-xs-12 col-sm-4 col-sm-offset-2 col-md-2 col-md-offset-4 box_search_btn ">
    <a class="aran-search-btn" href="<?=url('app/ad/new',array('baseType'=>2000,'isRequest'=>0))?>">
        ثبت رزومه
    </a>
</div>
<div class="col-xs-12 col-sm-4 col-sm-offset-0 col-md-2 col-md-offset-0 box_search_btn ">
    <a class="aran-search-btn" href="http://aranjob.com/fa/new-forms-data/1/%D9%81%D8%B1%D9%85-%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D9%86%DB%8C%D8%B1%D9%88%DB%8C-%DA%A9%D8%A7%D8%B1-%D9%85%D9%88%D8%B1%D8%AF-%D9%86%D8%B8%D8%B1">
آگهی استخدام
    </a>
</div>
