<?
$this->headLink()->prependStylesheet($this->basePath() . '/__/css/ads.css');
if (!$this->error) {
    ?>
    <div class="box_list_ads_2000_0">
        <?
        if ($this->select) {
            $countEndTag = 0;
            $panelId = 0;
            foreach ($this->select as $row) {
                $fields_table = getSM('fields_api')->init('ads_' . $row->baseType . '_' . $row->regType);
                $fields = getSM('fields_table')->getByEntityType('ads_' . $row->baseType . '_' . $row->regType)->toArray();
                $fieldsData = getSM('fields_api')->generate($fields, $row);
                ?>
                <div class="col-md-12 zero_padding">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div class="media">
                                <a target="_blank" class="pull-right"
                                   href="<?= url('app/ad/view', array('baseType' => $row->baseType, 'adId' => $row->adId, 'adTitle' => \Application\API\App::prepareUrlString($row->title))) ?>">
                                    <?
                                    $width = 100;
                                    $height = 100;
                                    if ($row->smallImage) {
                                        $dataImages = unserialize($row->smallImage);
                                        if ($dataImages) {
                                            if (isset($this->smallImgConfig['width']))
                                                $width = $this->smallImgConfig['width'];
                                            if (isset($this->smallImgConfig['height']))
                                                $width = $this->smallImgConfig['height'];
                                        }
                                        if (isset($dataImages['fPath']) && $dataImages['fPath'])
                                            $fPath = $dataImages['fPath'];
                                    } else {
                                        if (!isset($fieldsData['جنسیت']))
                                            $fieldsData['جنسیت'] = 'مرد';
                                        switch ($fieldsData['جنسیت']) {
                                            case 'مرد':
                                                $fPath = $this->basePath() . TEMPLATE_PATH . '/images/resume/men.jpg';
                                                break;
                                            case 'زن':
                                                $fPath = $this->basePath() . TEMPLATE_PATH . '/images/resume/women.jpg';
                                                break;
                                        }
                                    }

                                    $imageUrl = getThumbnail()->resize($fPath, $width, $height); //resize image
                                    ?>
                                    <img class="media-object" src="<?= $imageUrl ?>" alt="<?= $row->title ?>">
                                </a>

                                <div class="media-body">
                                    <div class="col-xs-12 col-sm-12 col-md-12">
                                        <a target="_blank"
                                           href="<?= url('app/ad/view', array('baseType' => $row->baseType, 'adId' => $row->adId, 'adTitle' => \Application\API\App::prepareUrlString($row->title))) ?>">
                                                <span class="r_label">
                                                    عنوان کاری :
                                                </span>
                                                <span
                                                    class="media-heading"><? if (strlen($row->title) > 50) echo mb_substr($row->title, 0, 50, 'UTF-8') . '...'; else echo $row->title; ?></span>
                                        </a>
                                    </div>
                                    <div class="col-xs-12 col-sm-12 col-md-12">
                                            <span class="r_label">
                                                نام و نام خانوادگی :
                                            </span>
                                        <span class="r_text"><?= $row->name ?></span>
                                    </div>

                                    <div class="col-xs-12 col-sm-12 col-md-12">
                                            <span class="r_label">
سال تولد :
                                            </span>
                                        <span
                                            class="r_text"><? if (isset($fieldsData['سال تولد']) && $fieldsData['سال تولد']) echo $fieldsData['سال تولد']; else echo '---'; ?></span>
                                    </div>

                                    <div class="col-xs-12 col-sm-12 col-md-12">
                                            <span class="r_label">
                                                مدرک تحصیلی :
                                            </span>
                                        <span
                                            class="r_text"><? if (isset($fieldsData['مقطع تحصیلی']) && $fieldsData['مقطع تحصیلی']) echo $fieldsData['مقطع تحصیلی']; else echo '---'; ?></span>
                                    </div>

                                    <div class="col-xs-12 col-sm-12 col-md-12">
                                            <span class="r_label">
حقوق درخواستی :
                                            </span>
                                        <span
                                            class="r_text"><? if (isset($fieldsData['حقوق و مزایای در خواستی']) && $fieldsData['حقوق و مزایای در خواستی']) echo $fieldsData['حقوق و مزایای در خواستی']; else echo '---'; ?></span>
                                    </div>

                                    <!-- <div class="col-xs-12 col-sm-12 col-md-12">
                                            <p><? /* if (strlen($row->text) > 100) echo mb_substr($row->text, 0, 100, 'UTF-8') . '...'; else echo $row->text; */ ?></p>
                                        </div>-->

                                    <? if ($this->showCreateDate) { ?>
                                        <div class="col-xs-12 col-sm-12 col-md-12 a_border_bottom">
                                            <p class="text-muted"><?= t('ADS_REG_DATE') . " : " . $this->dateFormat($row->createDate, 2); ?></p>
                                        </div>
                                    <? } ?>
                                    <? if ($row->starCount > 0) { ?>
                                        <div class="col-md-12">
                                            <?= getSM('ads_api')->createViewStarRate($this->starCount, $row->starCount); ?>
                                        </div>
                                    <? } ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <?
            }
        } else {
            ?>
            <div class="alert alert-info">
                <?= t('ADS_NOT_FOUND') ?>
            </div>
        <?
        }
        ?>
        <div style="clear:both"></div>
        <div class="pager" style="padding-top:12px;">
            <?
            /* @var $pages \Zend\Paginator\Paginator */
            echo $this->paginationControl($this->paginate,
                'Sliding',
                'ads/client/search.phtml',
                array(
                    'route' => 'app/ad/list',
                    'route_params' => array('baseType' => $this->baseTypeId, 'baseTitle' => $this->baseTypeMachineName)
                )
            ); ?>
        </div>
        <div style="clear:both"></div>
    </div>
<? } ?>


