<div class="step-order-header">
    <h2><?= t('Your perfect DAF!') ?></h2>

    <h3><?= t('Summary') ?></h3>

    <p><?= t('Here is the result of the choices you made.') ?></p>
</div>
<div class="main-step6 main-step">
    <div>
        <div class="col1">
            <?
            $form = $this->form;
            $form->prepare();
            echo $this->form()->openTag($form);
            echo $this->iptFormRow($form->get('csrf_simple_order_form'));
            ?>
            <div>
                <fieldset>
                    <legend>
                        <?= t('SIMPLE_ORDER_CONTACT_INFO') ?>
                    </legend>
                    <?= $this->iptFormRow($form->get('name')) ?>
                    <?= $this->iptFormRow($form->get('mobile')) ?>
                    <?= $this->iptFormRow($form->get('email')) ?>
                    <?= $this->iptFormRow($form->get('description')) ?>
                    <input type="hidden" name="orderCategory" id="orderCategory" value="<?= $this->catId ?>">
                </fieldset>
                <div>
                    <?= $this->iptFormRow($form->get('captcha')) ?>
                    <?= $this->iptFormRow($form->get('submit')) ?>
                </div>
                <?
                echo $this->form()->closeTag();
                ?>
                <div style="clear:both;"></div>
            </div>
        </div>
        <div class="col2">
            <div class="info-orders">
                <?
                foreach ($this->info as $row) {
                    ?>
                    <p><? if (isset($row['name'])) echo $row['name']; ?></p>
                <? } ?>
            </div>
            <div class="img-orders">
                <?
                foreach ($this->dataArray as $row) {
                    if (isset($row['images']) && $row['images']) {
                        foreach ($row['images'] as $imageRow) {
                            if ($imageRow->fPath) {
                                $imageUrl = getThumbnail()->resize($imageRow->fPath, 100, 100); //resize image
                                ?>
                                <a class="colorbox" href="<?= $imageRow->fPath ?>">
                                    <img src="<?= $imageUrl ?>" alt="<?= $imageRow->fAlt ?>" rel="tooltip"
                                         title="<?= $this->escapeHtml($imageRow->fTitle) ?>">
                                </a>
                            <?
                            }
                        }
                    } ?>
                <? } ?>
            </div>
        </div>
    </div>
    <div style="clear: both"></div>
</div>
<div class="step-order-nav">
    <a class="home" href="<?= url('app/step-order') ?>"></a>
    <span class="end-inactive"></span>
         <span class="main-inactive step-order-link pointer"
               data-id="<? if (isset($this->info[1]['id'])) echo t($this->info[1]['id']); ?>" data-name="">
            <label><?= t('Page1') ?></label>
            <p><? if (isset($this->info[2]['name'])) echo t($this->info[2]['name']); ?></p>
        </span>
    <span class="end-inactive"></span>
        <span class="main-inactive step1-order-link pointer"
              data-id="<? if (isset($this->info[2]['id'])) echo t($this->info[2]['id']); ?>"
              data-name="<? if (isset($this->info[2]['name'])) echo t($this->info[2]['name']); ?>">
            <label><?= t('Page2') ?></label>
            <p><? if (isset($this->info[3]['name'])) echo t($this->info[3]['name']); ?></p>
        </span>
    <span class="end-inactive"></span>
        <span class="main-inactive step2-order-link pointer"
              data-id="<? if (isset($this->info[3]['id'])) echo t($this->info[3]['id']); ?>"
              data-name="<? if (isset($this->info[3]['name'])) echo t($this->info[3]['name']); ?>">
            <label><?= t('Page3') ?></label>
            <p><? if (isset($this->info[4]['name'])) echo t($this->info[4]['name']); ?></p>
        </span>
    <span class="end-inactive"></span>
        <span class="main-inactive step3-order-link pointer"
              data-id="<? if (isset($this->info[4]['id'])) echo t($this->info[4]['id']); ?>"
              data-name="<? if (isset($this->info[4]['name'])) echo t($this->info[4]['name']); ?>">
            <label><?= t('Page4') ?></label>
            <p><? if (isset($this->info[5]['name'])) echo t($this->info[5]['name']); ?></p>
        </span>
    <span class="end-inactive"></span>

        <span class="main-inactive step4-order-link pointer"
              data-id="<? if (isset($this->info[5]['id'])) echo t($this->info[5]['id']); ?>"
              data-name="<? if (isset($this->info[5]['name'])) echo t($this->info[5]['name']); ?>">
            <label><?= t('Page5') ?></label>
            <p><? if (isset($this->info[6]['name'])) echo t($this->info[6]['name']); ?></p>
        </span>
    <span class="start-active"></span>
    <span class="main-active">
            <label><?= t('Summary') ?></label>
        </span>
    <span class="end-active"></span>
</div>
<script>
    $('.colorbox').colorbox({rel: 'colorbox'});
</script>