<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'Links\API\ACL'                    => __DIR__ . '/src/Links/API/ACL.php',
  'Links\API\EventManager'           => __DIR__ . '/src/Links/API/EventManager.php',
  'Links\Controller\ItemsController' => __DIR__ . '/src/Links/Controller/ItemsController.php',
  'Links\Form\Items'                 => __DIR__ . '/src/Links/Form/Items.php',
  'Links\Install'                    => __DIR__ . '/src/Links/Install.php',
  'Links\Model\LinksItem'            => __DIR__ . '/src/Links/Model/LinksItem.php',
  'Links\Model\LinksItemTable'       => __DIR__ . '/src/Links/Model/LinksItemTable.php',
);
