<?
$this->headLink()
    ->appendStylesheet($this->basePath() . '/flyout-slider/flyout-slider.css');

$this->headScript()
    ->appendFile($this->basePath() . '/flyout-slider/flyout-slider.js');


$select = $this->select;
$selectGallery = $this->selectGallery;
?>
<style>
    .flyout_slider{display: block;
        height: 450px;
        position: relative;
        width: 100%;}
    .flyout_slider #itemdescription span{bottom: -430px;
        position: absolute;
        right: 50px;}
</style>
<div class="flyout_slider">
    <?
    $htmlImg='';
    $htmlSpan='';
    foreach ($select as $row) {
        if ($row->image) {
            $width = 100;
            $height = 100;
            if (!empty($row->width))
                $width = $row->width;
            else
                $width = $selectGallery->width;

            if (!empty($row->height))
                $height = $row->height;
            else
                $height = $selectGallery->height;
            $imageUrl = getThumbnail()->resize($row->image, $width, $height); //resize image
            $url = url('app/gallery-counter', array('id' => $row->id, 'hitsType' => $this->hitsType));

            $htmlImg .= '<img src="'.$imageUrl.'" alt="' . $row->title . '" id="flyout_slide_' . $row->id . '"/>';
            $htmlSpan .= '<span data-for="flyout_slide_' . $row->id . '">' . $row->title . '</span>';
            ?>
            <!-- <a href="<? /*= $url */ ?>">
                <img src="<? /*= $imageUrl */ ?>" rel="tooltip" title="<? /*= $row->title */ ?>"
                     alt="<? /*= $row->title */ ?>"/>
            </a>-->
        <?
        }
    }
    ?>
    <div id="itemlist">
        <?= $htmlImg ?>
    </div>

    <div id="itemdescription">
        <?= $htmlSpan ?>
    </div>
</div>



<script type="text/javascript">
    <?$this->inlineScript()->captureStart()?>
    $(document).ready(function(){
        if (!Modernizr.csstransforms3d) document.getElementById('information').style.display = 'block';

        //Initiliaze
        var itemList, item, className, thisItem, newOrder, itemDesc, desc;

        itemList  = $('#itemlist');
        item      = itemList.children('img');

        itemDesc  = $('#itemdescription');
        desc      = itemDesc.children('span');

        //Add class name for each item
        item.each(function(index) {

            className  = 'item-' + index;

            $(this).addClass(className).attr('data-order', index);

        });

        //Show first item description
        desc.filter(':first-child').fadeIn();

        //On clicked fire animation
        item.on('click', function() {

            thisItem  = $(this);
            thisOrder = parseInt(thisItem.attr('data-order')) - 1;

            thisItem.addClass('show');

            //Reorder item position
            item.on('animationend webkitAnimationEnd MSAnimationEnd oAnimationEnd', function() {

                thisItem.removeClass().addClass('item-0').attr('data-order', '0');

                //Show selected item description
                desc.hide();
                desc.filter('[data-for=' + thisItem.attr('id') + ']' ).fadeIn('fast');
            });

            //Move siblings items backward
            window.setTimeout(function () {

                for(var i = thisOrder; i >= 0; i--) {

                    //Reorder item position
                    movedItem = item.filter('[data-order=' + i + ']');
                    newOrder  = parseInt(movedItem.attr('data-order')) + 1;
                    className = 'item-' + newOrder;

                    //Move them with transition
                    movedItem.removeClass().addClass('transition ' + className).attr('data-order', newOrder);

                    //Remove their transition
                    item.on('transitionend webkitTransitionEnd MSTransitionEnd oTransitionEnd', function() {
                        item.removeClass('transition');
                    });
                }
            }, 500);
        });


    });


    <?$this->inlineScript()->captureEnd()?>
</script>
