<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'Analyzer\API\ACL'                       => __DIR__ . '/src/Analyzer/API/ACL.php',
  'Analyzer\API\Analyzer'                  => __DIR__ . '/src/Analyzer/API/Analyzer.php',
  'Analyzer\API\EventManager'              => __DIR__ . '/src/Analyzer/API/EventManager.php',
  'Analyzer\Controller\Admin'              => __DIR__ . '/src/Analyzer/Controller/Admin.php',
  'Analyzer\Controller\Analyzer'           => __DIR__ . '/src/Analyzer/Controller/Analyzer.php',
  'Analyzer\Form\Config'                   => __DIR__ . '/src/Analyzer/Form/Config.php',
  'Analyzer\Form\ReportPeriod'             => __DIR__ . '/src/Analyzer/Form/ReportPeriod.php',
  'Analyzer\Form\SystemStatusBlock'        => __DIR__ . '/src/Analyzer/Form/SystemStatusBlock.php',
  'Analyzer\Install'                       => __DIR__ . '/src/Analyzer/Install.php',
  'Analyzer\Model\Visits'                  => __DIR__ . '/src/Analyzer/Model/Visits.php',
  'Analyzer\Model\VisitsArchive'           => __DIR__ . '/src/Analyzer/Model/VisitsArchive.php',
  'Analyzer\Model\VisitsArchiveTable'      => __DIR__ . '/src/Analyzer/Model/VisitsArchiveTable.php',
  'Analyzer\Model\VisitsTable'             => __DIR__ . '/src/Analyzer/Model/VisitsTable.php',
  'Analyzer\View\Helper\SystemStatusBlock' => __DIR__ . '/src/Analyzer/View/Helper/SystemStatusBlock.php',
);
