<?
$this->headLink()
    ->appendStylesheet($this->basePath() . '/css/real-estate.css');

$this->headScript()
    ->prependFile($this->basePath() . '/js/geographical.js')
    ->prependFile($this->basePath() . TEMPLATE_PATH . '/js/real-estate/real-estate.js')
    ->appendFile($this->basePath() . TEMPLATE_PATH . '/js/real-estate/base-real-estate.js');

$route_prefix = $this->admin_route ? 'admin' : 'app';
?>

<div class="main-new-real-estate border_main">


<div id="real_estate_form_page">
<div class="back_loading">
    <span class="img_loading"></span>
</div>
<?
/* @var $form \Zend\Form\Form */
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
if (!$this->isRequest) {
    ?>

    <div class="div-step step1" id="step1">
        <span class="logo_step1"></span>

        <fieldset class="f_part">
            <legend>
                مشخصات ملک
            </legend>
            <table class="tbl_part1">
                <tr>
                    <td><?= $this->iptFormRow($form->get('stateId')) ?></td>
                    <td><?= $this->iptFormRow($form->get('cityId')) ?></td>
                    <td>
                        <div class="text-new-area">
                            <?= $this->iptFormRow($form->get('newArea')) ?>
                        </div>
                        <div class="select-new-area">
                            <?= $this->iptFormRow($form->get('areaId')) ?>
                        </div>
                        <a href="#open" class="open-new-area" id="openNewArea"
                           data-id="1"><?= t('realEstate_area_not_found') ?></a>
                    </td>
                </tr>
                <tr>
                    <td><?= $this->iptFormRow($form->get('estateType')) ?></td>
                    <td><?= $this->iptFormRow($form->get('regType')) ?></td>
                    <td><?= $this->iptFormRow($form->get('expire')) ?></td>
                </tr>
            </table>
        </fieldset>

        <fieldset class="f_part">
            <legend>
                مشخصات مالک
            </legend>
            <table class="tbl_part2">
                <tr>
                    <td><?= $this->iptFormRow($form->get('ownerName')) ?></td>
                    <td><?= $this->iptFormRow($form->get('ownerEmail')) ?></td>
                    <td><?= $this->iptFormRow($form->get('ownerPhone')) ?></td>
                </tr>
                <tr>
                    <td> <?= $this->iptFormRow($form->get('ownerMobile')) ?></td>
                    <td colspan="2"><?= $this->iptFormRow($form->get('addressFull')) ?></td>
                </tr>
                <tr>
                    <td colspan="3" style="display: none;"><?= $this->iptFormRow($form->get('addressShort')) ?></td>
                </tr>
            </table>
        </fieldset>

        <div class="help_step1">
            <span class="logo_help"></span>

            <div class="content_help">
                <ul>
                    <li>
                        پر کردن موارد ستاره دار الزامی می باشد .
                    </li>
                    <li>
                        برای نوشتن خلاصه آدرس پس از نام شهر خود ، اسم منطقه اصلی که خواهان ثبت ملک هستید را وارد نمایید
                        .
                    </li>
                </ul>
            </div>
        </div>
        <div style="clear: both"></div>
        <br/>
        <span class="next-button" id="next-button" data-id="1"></span>
    </div>

    <div class="div-step step2" id="step2">
        <span class="logo_step2"></span>

        <div class="box_top_step2">
            <div class="help_step2">
                <span class="logo_help"></span>

                <div class="content_help">
                </div>
            </div>
        </div>

        <?
        $columns = array(
            array(
                'title' => 'امکانات ملک',
                'part' => 1,
                'size' => 8,
                'items' => array(
                    'zirbana' => 6,
                    'masahate_zamin' => 6,
                    'sanad' => 6,
                    'priceOneMeter' => 6,
                    'totalPrice' => 6,
                    'mortgagePrice' => 6,
                    'rentalPrice' => 6,
                    'c_otagh_khab' => 6,
                    // 'c_parking' => 6,
                    // 'sale_sakht' => 6,
                    'vaziat_sakhteman' => 6,
                    'kitchen' => 6,
                    //'masahate_arse' => 6,
                   // 'ayan' => 6,
                    'mojaveze_sakht' => 6,
                    'mashinro' => 6,
                    'mosharafbe' => 6,
                    'divarkeshi' => 6,
                    'hesar' => 6,
                    'system_abyari' => 6,
                )
            ),
            array(
                'title' => 'سرویس',
                'size' => 6,
                'part' => 2,
                'items' => array(
                    'service_behdashti' => 12,
                )
            ),
            array(
                'title' => 'رفاهی',
                'size' => 6,
                'part' => 3,
                'items' => array(
                    'refahi' => 12,
                )
            ),
            array(
                'title' => 'کابینت',
                'size' => 12,
                'part' => 4,
                'items' => array(
                    'cabinet_safhe' => 4,
                    'cabinet_badane' => 4,
                    'cabinet_rukesh' => 4,
                )
            ),
            array(
                'title' => 'طراحی و ساخت',
                'size' => 12,
                'part' => 5,
                'items' => array(
                    't_shekle_sakht' => 4,
                    't_kaf' => 4,
                    't_divar' => 4,
                    't_noorgiri' => 12,
                )
            ),
            array(
                'title' => 'ساختمان و زمین',
                'size' => 12,
                'part' => 6,
                'items' => array(
                    's_eskelet' => 4,
                    's_nama' => 4,
                    's_m_kolle_tabaghat' => 4,
                    's_m_kolle_vahedha' => 4,
                    's_m_dar_tabaghe' => 4,
                    's_m_vahed_dar_tabaghe' => 4,
                    's_tasisat' => 12,
                )
            ),
            array(
                'title' => 'طول و عرض',
                'size' => 12,
                'part' => 7,
                'items' => array(
                    'sharghan' => 3,
                    'gharban' => 3,
                    'jonuban' => 3,
                    'shomalan' => 3,
                )
            ),
        );
        $html = '';
        /* @var $fieldset \Zend\Form\Fieldset */
        $fieldset = $this->form->get('transferFields');
        if ($fieldset) {
            $fields = $fieldset->getElements();
            foreach ($columns as $col) {
                $items = '';
                foreach ($col['items'] as $field => $size) {
                    if ($field == 'priceOneMeter' || $field == 'totalPrice' || $field == 'mortgagePrice' || $field == 'rentalPrice')
                        $items .= "<div class='col-xs-" . $size . "'>" . $this->iptFormRow($form->get($field)) . "</div>";
                    else
                        $items .= "<div class='col-xs-" . $size . "'>" . $this->iptFormRow($fields[$field]) . "</div>";
                }
                $html .= "<div class='col-xs-" . $col['size'] . " div_part" . $col['part'] . " base_fields'><div class='row'> <fieldset class='f_part'><legend>" . $col['title'] . "</legend>" . $items . "</fieldset></div></div>";
            }

            echo $html;


            if ($this->form->has('transferFields')) {

                $fieldsName = array(
                    'zirbana',
                );

            }
        } ?>
        <div style="height: 40px; display: block; clear: both;"></div>
        <span class="next-button" id="next-button" data-id="2"></span>
        <span class="back-button" id="back-button" data-id="2"></span>

    </div>

    <div class="div-step step3" id="step3">
        <span class="logo_step3"></span>


        <div class="help_step3">
            <span class="logo_help"></span>

            <div class="content_help">
                <ul>
                    <li>
                        در صورتیکه ملک شما حاوی موارد خاصی می باشد ، در قسمت توضیحات وارد نمایید .
                    </li>
                    <li>
                        حداکثر حجم تصویر آپلودی 1 مگابایت می باشد .
                    </li>
                    <li>
                        حداکثر رزولوشن تصویر 2000*2000 می باشد .
                    </li>
                </ul>
            </div>
        </div>

        <div class="col-xs-8 desc_realestate">
            <div class="row">
                <fieldset class="f_part">
                    <legend>
                        توضیحات بیشتر
                    </legend>
                    <div class="margin real_desc">
                        <?= $this->iptFormRow($form->get('description')) ?>
                        <? //= $this->iptFormRow($form->get('pm')) ?>
                    </div>
                </fieldset>
            </div>
        </div>

        <!--        <div class="col-xs-12 padding_bottom">-->
        <!--            <div class="row">-->
        <!--                --><?php //if (!$this->isRequest): ?>
        <!--                    <div class="margin">-->
        <!--                        --><? //= $this->iptFormRow($form->get('isSpecial')) ?>
        <!--                    </div>-->
        <!--                    <div class="margin">-->
        <!--                        --><? //= $this->iptFormRow($form->get('showInfo')) ?>
        <!--                    </div>-->
        <!--                --><?php //endif; ?>
        <!--            </div>-->
        <!--        </div>-->

        <div class="col-xs-12">
            <div class="row">
                <fieldset class="f_part">
                    <legend>
                        تصاویر
                    </legend>
                    <?php if (!$this->isRequest): ?>
                        <div class="margin">
                            <? if ($this->images)
                                echo $this->fileDisplay($this->images, $this->maxImage); ?>
                        </div>
                        <? if ($form->has('images')) {
                            if ($images = $form->get('images')) {
                                ?>
                                <div class="img_realestate">
                                    <?= $this->iptFormCollection($images) ?>
                                </div>
                            <?
                            }
                        } ?>
                    <?php endif; ?>
                </fieldset>
            </div>
        </div>

        <div style="height: 40px; display: block; clear: both;"></div>
        <span class="next-button" id="next-button" data-id="3"></span>
        <span class="back-button" id="back-button" data-id="3"></span>
    </div>

    <div class="div-step step4" id="step4">
        <span class="logo_step4"></span>

        <div class="step4_right">
            <div class="help_step4">
                <span class="logo_help"></span>

                <div class="content_help">
                    <ul>
                        <li>
                            <?= t('To obtain the coordinates of the desired location click on the map.') ?>
                        </li>
                    </ul>
                </div>
            </div>
            <? if ($form->has('captcha')) echo $this->iptFormRow($form->get('captcha')); ?>
            <div class="new-real-estate-btn">
                <?= $this->iptFormCollection($this->form->get('buttons')) ?>
            </div>
            <span class="back-button" id="back-button" data-id="4"></span>
        </div>
        <div class="step4_left">
            <div>
                <span id="map_selected_loc"></span>
            </div>
            <div id="map" style="width: 100%;height: 100%;">
                <?= t('Google Maps is not available due to filtering.') ?>
            </div>
        </div>
    </div>
    <?
    echo $this->iptFormRow($form->get('googleLatLong'));

} else { // is request
    ?>
    <div class="div-step step1 step_request" id="step1">
        <span class="logo_step_request"></span>

        <div class="help_step1 help_request">
            <span class="logo_help"></span>

            <div class="content_help"></div>
        </div>
        <div style="clear: both"></div>

        <fieldset class="f_part f_request">
            <legend>
                مشخصات ملک مورد تقاضا
            </legend>
            <table class="tbl_part1">
                <tr>
                    <td><?= $this->iptFormRow($form->get('stateId')) ?></td>
                    <td><?= $this->iptFormRow($form->get('cityId')) ?></td>
                    <td>
                        <div class="text-new-area">
                            <?= $this->iptFormRow($form->get('newArea')) ?>
                        </div>
                        <div class="select-new-area">
                            <?= $this->iptFormRow($form->get('areaId')) ?>
                        </div>
                        <a href="#open" class="open-new-area" id="openNewArea"
                           data-id="1"><?= t('realEstate_area_not_found') ?></a>
                    </td>
                </tr>
                <tr>
                    <td><?= $this->iptFormRow($form->get('estateType')) ?></td>
                    <td><?= $this->iptFormRow($form->get('regType')) ?></td>
                    <td><?= $this->iptFormRow($form->get('expire')) ?></td>
                </tr>
            </table>
        </fieldset>

        <?
        $columns = array(
            array(
                'title' => 'شرایط مورد تقاضا',
                'part' => 1,
                'size' => 12,
                'items' => array(
                    'lower_meter' => 12,
                    'highest_meter' => 12,
                    'lower_price' => 12,
                    'highest_price' => 12,
                    'lower_rahn' => 12,
                    'highest_rahn' => 12,
                    'lower_rent' => 12,
                    'highest_rent' => 12,
                )
            ),
        );
        $html = '';
        /* @var $fieldset \Zend\Form\Fieldset */
        $fieldset = $this->form->get('transferFields');
        if ($fieldset) {
            $fields = $fieldset->getElements();
            foreach ($columns as $col) {
                $items = '';
                foreach ($col['items'] as $field => $size) {
                    /* if ($field == 'priceOneMeter' || $field == 'totalPrice' || $field == 'mortgagePrice' || $field == 'rentalPrice')
                         $items .= "<div class='col-xs-" . $size . "'>" . $this->iptFormRow($form->get($field)) . "</div>";
                     else*/
                    $items .= "<div class='col-xs-" . $size . "'>" . $this->iptFormRow($fields[$field]) . "</div>";
                }
                $html .= "<div class='col-xs-" . $col['size'] . " div_part_request_p '><div class='row'> <fieldset class='f_part f_request f_r_slider'><legend>" . $col['title'] . "</legend>" . $items . "</fieldset></div></div>";
            }

            echo $html;

        } ?>
        <div style="height: 40px; display: block; clear: both;"></div>


        <fieldset class="f_part f_request">
            <legend>
                مشخصات تقاضا کننده
            </legend>
            <table class="tbl_part2">
                <tr>
                    <td><?= $this->iptFormRow($form->get('ownerName')) ?></td>
                    <td><?= $this->iptFormRow($form->get('ownerEmail')) ?></td>
                    <td><?= $this->iptFormRow($form->get('ownerPhone')) ?></td>
                </tr>
                <tr>
                    <td> <?= $this->iptFormRow($form->get('ownerMobile')) ?></td>
                    <td colspan="2"><?= $this->iptFormRow($form->get('addressFull')) ?></td>
                </tr>
                <tr>
                    <td colspan="3" style="display: none;"><?= $this->iptFormRow($form->get('addressShort')) ?></td>
                </tr>
            </table>
        </fieldset>

        <div class="col-xs-12 desc_realestate">
            <div class="row">
                <fieldset class="f_part">
                    <legend>
                        توضیحات بیشتر
                    </legend>
                    <div class="margin real_desc desc_request">
                        <?= $this->iptFormRow($form->get('description')) ?>
                        <? //= $this->iptFormRow($form->get('pm')) ?>
                    </div>
                </fieldset>
            </div>
        </div>
        <? if ($form->has('captcha')) echo $this->iptFormRow($form->get('captcha')); ?>
        <div class="new-real-estate-btn">
            <?= $this->iptFormCollection($this->form->get('buttons')) ?>
        </div>
        <div style="clear: both"></div>
        <!--<span class="next-button" id="next-button" data-id="1"></span>-->
    </div>
    <script type="text/javascript">
        <?$this->inlineScript()->captureStart();?>
   $('#regType').children('option').first().html('خرید');
        <?$this->inlineScript()->captureEnd();?>
    </script>
<?
}
?>

<?
echo $this->form()->closeTag();
?>


</div>

</div>

<script type="text/javascript">
    <?$this->inlineScript()->captureStart();?>
    var openNewArea = 1;
    var isRequest = '<?=$this->isRequest?>';
    var estateType_regType = <?=$this->estateType_regType?>;
    var estateType_fields = <?=$this->estateType_fields?>;
    var statistic_url = '<?=url('app/real-estate/region-statistic')?>';
    var error_message = '<?= t('error when deleteing file!') ?>';

    $('.step2 select').addClass('select2');

    if ($('#real_state_form').find('.f_r_slider').length > 0) {
        var flagShowEl = true;
        $('.f_r_slider input').each(function () {
            if (flagShowEl) {
                var min = 0;
                var max = 1000000;
                var step = 10000;
                var el = $(this);
                var idName = $(el).attr('id');
                switch (idName) {
                    case 'transferFields_lower_meter':
                        min = 0;
                        max = 100000;
                        break;
                    case 'transferFields_lower_price':
                        min = 0;
                        max = 1000000000000;
                        break;
                    case 'transferFields_lower_rahn':
                        min = 0;
                        max = 10000000000;
                        break;
                    case 'transferFields_lower_rent':
                        min = 0;
                        max = 1000000000;
                        break;
                }
                var slider = $("<div></div>")
                    .attr('id', $(el).attr('id') + '_slider')
                    .slider({
                        range: true,
                        min: min,
                        max: max,
                        step: step,
                        values: [ min, max ],
                        slide: function (event, ui) {
                            $(el).val(ui.values[0]);
                            $('#' + idName.replace('lower', 'highest')).val(ui.values[1]);
                            $(el).siblings('.price_from').html(insertcomma(ui.values[0].toString()));
                            $(el).siblings('.price_to').html(insertcomma(ui.values[1].toString()));
                        }
                    }).insertAfter(el);
                var values = $(el).hide().val().split(',');
                var text = $(el).siblings('label').text();
                $(el).siblings('label').html(text.replace('کمترین', ''));

                if (values.length == 2) {
                    $(slider).slider("values", 0, values[0]);
                    $(slider).slider("values", 1, values[1]);
                }
                $("<div class='price_from pull-right flip'></div>").insertAfter(slider).html(insertcomma($(slider).slider("values", 0).toString()));
                $("<div class='price_to pull-left flip'></div>").insertAfter(slider).html(insertcomma($(slider).slider("values", 1).toString()));
                $(el).parent().addClass('clearfix');
                $(el).hide().val($(slider).slider("values", 0));
                $('#' + idName.replace('lower', 'highest')).val($(slider).slider("values", 1)).parent().parent().hide();
                flagShowEl = false;
            } else {
                flagShowEl = true;
            }
        });
    }

    $(document).ready(function(){

        onFilterRegTypeChanged(1);

        $('#regType').change(function () {
            onFilterRegTypeChanged($(this).val());
        });

    });
    function onFilterRegTypeChanged(el) {
        if ($('#real_state_form .div_part_request_p').find('.f_r_slider').length > 0) {
            switch (parseInt(el)) {
                case 78 :
                    $('#transferFields_lower_rent').parent().parent().show();
                    $('#transferFields_highest_rent').parent().parent().hide();
                    $('#transferFields_lower_rahn').parent().parent().show();
                    $('#transferFields_highest_rahn').parent().parent().hide();
                    $('#transferFields_lower_price').parent().parent().hide();
                    $('#transferFields_highest_price').parent().parent().hide();
                    break;
                default :
                    $('#transferFields_lower_rent').parent().parent().hide();
                    $('#transferFields_highest_rent').parent().parent().hide();
                    $('#transferFields_lower_rahn').parent().parent().hide();
                    $('#transferFields_highest_rahn').parent().parent().hide();
                    $('#transferFields_lower_price').parent().parent().show();
                    $('#transferFields_highest_price').parent().parent().hide();
                    break
            }
        } else {
            switch (parseInt(el)) {
                case 78 :
                    $('#mortgagePrice').parent().parent().parent().show();
                    $('#rentalPrice').parent().parent().parent().show();
                    $('#priceOneMeter').parent().parent().parent().hide();
                    $('#totalPrice').parent().parent().parent().hide();
                    break;
                default :
                    $('#mortgagePrice').parent().parent().parent().hide();
                    $('#rentalPrice').parent().parent().parent().hide();
                    $('#priceOneMeter').parent().parent().parent().show();
                    $('#totalPrice').parent().parent().parent().show();
                    break
            }
        }
    }

    <?$this->inlineScript()->captureEnd();?>
</script>
<?
if (!$this->isRequest) {
    ?>
    <script src="http://maps.google.com/maps/api/js?sensor=true" type="text/javascript"></script>
<? } ?>
