<div>
    <?
    $headLink = $this->headLink()->toString();
    $headScript = $this->headScript()->toString();
    $inlineScript = $this->inlineScript()->toString();
    $fm = $this->flashMessenger()->render();
    ?>
    <input type="hidden" id="inlineScriptContainer" value="<?= $this->escapeHtmlAttr(trim($inlineScript)) ?>">
    <input type="hidden" id="flashMessengerContainer" value="<?= $this->escapeHtmlAttr(trim($fm)) ?>">
    <input type="hidden" id="headLinkContainer" value="<?= $this->escapeHtmlAttr(trim($headLink)) ?>">
    <input type="hidden" id="headScriptContainer" value="<?= $this->escapeHtmlAttr(trim($headScript)) ?>">
    <?= $this->content ?>
</div>