<div>
    <h3 class="page-title ">
        <?= $this->translate('Optimization'); ?>
    </h3>

    <div>
        <?
//                $form = $this->form;
//                $form->prepare();
//                echo $this->form()->openTag($form);
//                foreach ($form->getElements() as $el) {
//                    echo $this->formRow($el);
//                }
//                echo $this->formCollection($form->get('buttons'));
//                echo $this->form()->closeTag();
        echo $this->form($this->form);
        ?>
    </div>
</div>
