<div class='system-widget-wrapper <?= $this->class ?>' data-row="1" data-col="1" data-sizex="1" data-sizey="1">
    <div class='system-widget' id="<?= $this->widgetId ?>"><?= $this->content ?></div>
</div>
<script type="text/javascript">
    <?$this->inlineScript()->captureStart();?>
    System.Widgets.Items["<?= $this->widgetId ?>"] = {
        fqn: "<?=addslashes($this->fqn)?>",
        id: "<?=$this->widgetId?>",
        timeout:<?=$this->timeout?>
    };
    <?$this->inlineScript()->captureEnd();?>
</script>