<?
$content = \Theme\API\Themes::renderLayout($this);
$direction = $this->translate('lang_direction'); //rtl ? ltr
$bootstrap = $direction == 'rtl' ? '/css/bootstrap.rtl.min.css' : '/css/bootstrap.min.css';
$basePath = $this->basePath();
$this->headLink()
    ->prependStylesheet(
        $basePath . TEMPLATE_PATH . '/css/ie10.css',
        'screen',
        'IE 10'
    )
    ->prependStylesheet($basePath . '/css/system.css')
    ->prependStylesheet($basePath . '/css/base-theme/jquery-ui-1.10.1.custom.min.css')
    ->prependStylesheet($basePath . TEMPLATE_PATH . $bootstrap)
    ->prependStylesheet($basePath . '/css/reset.min.css');

//------------------------------ TEMPLATE STYLE -------------------------------------------
$this->headLink()->appendStylesheet($basePath . TEMPLATE_PATH . '/css/style.css');
if ($direction == 'rtl')
    $this->headLink()->appendStylesheet($basePath . TEMPLATE_PATH . '/css/style-rtl.css');
////-------------------------------------------------------------


$this->headScript()
    ->prependFile($basePath . '/js/system.jquery.ui.buttons.js')
    ->prependFile($basePath . '/js/system.jquery.ui.js')
    ->prependFile($basePath . '/js/system.js')
    ->prependFile($basePath . '/js/forms.js')
    ->prependFile($basePath . '/js/jquery.hoverIntent.min.js')
    ->prependFile($basePath . '/js/jquery.transit.min.js')
    ->prependFile($basePath . '/js/general-client.js')
    ->prependFile($basePath . '/js/jquery-ui-1.10.1.custom.min.js')
    ->prependFile($basePath . '/js/jquery-1.9.1.min.js')
    ->prependFile(
        $basePath . TEMPLATE_PATH . '/js/respond.min.js',
        'text/javascript',
        array('conditional' => 'lt IE 9')
    );

//------------------------------ TEMPLATE JAVASCRIPT -------------------------------------------
$this->headScript()->appendFile($basePath . TEMPLATE_PATH . '/js/template.js');
$path = $this->basePath() . TEMPLATE_PATH;

?>

<!DOCTYPE html>
<html lang="fa" xmlns="http://www.w3.org/1999/html">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <?= $this->head() ?>
    <?= $this->headTitle() ?>
    <?= $this->headMeta() ?>
    <?= $this->headLink() ?>
    <?= $this->headScript() ?>
</head>
<body>
<div id="page-bg">
    <img src="<?= $path ?>/images/bg.jpg" class="img-responsive">
</div>
<div id="container">
    <div class="container">
        <div class="row" id="row-top">
            <div id="title" class="img-responsive col-md-5 col-sm-7 col-xs-9">
                <img src="<?= $path ?>/images/title.png" alt="Sedef Fashion" title="Sedef Fashion">

                <div class="social-links">
                    <a title="Facebook" id="facebook" href="https://facebook.com/sedeffashion" target="_blank">
                        &nbsp;</a>
                    <a title="Instagram" id="instagram" href="http://instagram.com/sedeffashion" target="_blank">
                        &nbsp;</a>
                    <a title="LinkedIn" id="linkedin" href="http://www.linkedin.com/in/sedeffashion" target="_blank">
                        &nbsp;</a>
                </div>
            </div>
            <div id="logo" class="img-responsive col-md-offset-5 col-md-2 col-sm-offset-2 col-sm-3 col-xs-3">
                <img src="<?= $path ?>/images/logo.png" alt="Sedef Fashion" title="Sedef Fashion">
            </div>
        </div>
    </div>
    <div id="body">
        <?= $content ?>
    </div>
    <div class="container footer sticky-bottom">
        <div class="row">
            <div class=" col-md-12">
                <div class="">
                    <?
                    $startYear = mktime(0, 0, 0, 6, 0, 2012);
                    $startYear = $this->dateFormat($startYear, \Localization\View\Helper\DateFormat::YEAR_ONLY);
                    $nowYear = $this->dateFormat(time(), \Localization\View\Helper\DateFormat::YEAR_ONLY);
                    ?>
                    <p align="center">
                        <?= t('APPLICATION_BROWSERS') ?>
                    </p>

                    <p align="center">
                        <span><?= sprintf(t('APPLICATION_RIGHTS'), 'Sedef Fashion') ?></span>
                        <span dir="ltr"><?= sprintf(t('APPLICATION_COPY_RIGHT'), $startYear, $nowYear) ?></span>
                        &nbsp; .
                        <span><?= t('APPLICATION_SUPPORT') ?></span> .
                        <span><?= t('APPLICATION_POWERED_BY') ?></span>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<?= $this->inlineScript() ?>
</body>
</html>
