<div>
    <h3 class="page-title">
        <?= $this->translate('Theme Settings'); ?>
    </h3>

    <div>
        <?
//        $form = $this->form;
//        $form->prepare();
//        echo $this->form()->openTag($form);
//        foreach ($form->getElements() as $el) {
//            echo $this->iptFormRow($el);
//        }
//        echo $this->iptFormCollection($form->get('buttons'));
//        echo $this->form()->closeTag();
        echo $this->form($this->form);
        ?>
    </div>
</div>
<div id="layout-designer" style="display:none;">
    <?= $this->partial('theme/theme/layout-designer', array('layout' => $this->layout)) ?>
</div>