<? \JQuery\API\JQuery::loadColorBox($this);
$this->headLink()->appendStylesheet($this->basePath() . '/css/themes.css');
?>
<div class="">
    <a class="toolbar-button btn btn-default ajax_page_load"
       href="<?= url('admin/themes/config') ?>">
        <i class="glyphicon glyphicon-cog"></i><?= t('Theme Settings') ?></a>

    <h3 class="page-title">
        <?= t('System Themes') ?>
    </h3>

    <div class="row theme-list">
        <?
        foreach ($this->themes as $name => $theme) {
            ?>
            <div class="col-md-4 ">
                <div class="panel panel-default">
                    <div class="panel-heading"><?= $theme['title'] ?></div>
                    <div class="panel-body theme-item"><?
                        $status = '';
                        switch ($theme['status']) {
                            case \Theme\API\Themes::DEFAULT_CLIENT:
                            case \Theme\API\Themes::DEFAULT_ADMIN:
                                $status = "<span class='label label-success'>" . t('Active Theme') . "</span>";
                                break;
                            case \Theme\API\Themes::AVAILABLE:
                                $classes = array('btn', 'btn-default');
                                if ($theme['type'] != 'admin')
                                    $classes[] = 'ajax_page_load';

                                $button = \Theme\API\Common::Link(
                                    '<i class="glyphicon glyphicon-star"></i>',
                                    url('admin/themes/set-default', array('name' => $theme['name'])),
                                    array(
                                        'class' => $classes,
                                        'data-icon-p' => 'ui-icon-star',
                                        'title' => t('Activate this Theme'),));
                                $status = "<span>" . $button . "</span>";
                                break;
                            case \Theme\API\Themes::NOT_AVAILABLE:
                                $status = "<span class='label label-danger' rel='tooltip' title='" . t('You need to purchase this theme before you can use it') . "'>" . t('Template has not been purchased') . "</span>";
                                break;
                        }

                        $preview = '/themes/' . $name . '/preview.png';
                        $preview_thumb = '/themes/' . $name . '/preview.thumb.png';
                        $img = \Theme\API\Common::Img($this->basePath() . $preview_thumb);
                        $link = \Theme\API\Common::Link($img, $this->basePath() . $preview, array('class' => 'colorbox'));

                        ?>
                        <div class="row">
                            <div class="col-md-3">
                                <div>
                                    <span
                                        class="label <?= $theme['type'] == 'client' ? 'label-primary' : 'label-info' ?>">
                                        <?= t(ucfirst($theme['type']) . ' Theme') ?>
                                    </span>
                                </div>
                                <div><?= $status ?></div>
                            </div>
                            <div class="col-md-9" align="center">
                                <?= $link ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?
        }
        ?>
    </div>
</div>