<!-- Creator : Exlord (adeli.farhad@gmail.com) -->
<!DOCTYPE html>
<html>
<head>
    <title>طراحی سایت, طراحی وب سایت, بهینه سازی وب سایت,بازاریابی اینترنتی,تبلیغات اینترنتی, تجارت الکترونیک</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="description" content="شرکت طراحی سایت و طراحی فروشگاه اینترنتی و پورتال سازمانی">
    <meta name="keywords"
          content="طراحی سایت تبریز, طراحی وب سایت, تبلیغات و بازاریابی اینترنتی,شرکت ایده پرداز,طراحی وب سایت,web site design,Ideh Pardaz Tabriz,IPT,IPT24,همایش و کنفرانس,پورتال سازمانی">
    <link type="text/css" rel="stylesheet" href="intro/css/style.css">
    <link type="text/css" rel="stylesheet" href="intro/css/jquery.tooltip.css">
    <script type="text/javascript" src="intro/js/jquery-1.7.1.min.js"></script>
    <script type="text/javascript" src="intro/js/jquery.bgiframe.js"></script>
    <script type="text/javascript" src="intro/js/jquery.tooltip.pack.js"></script>
    <!-- Facebook Conversion Code for شرکت ایده پرداز تبریز - طراحی وب سایت و برنامه نویسی -->
    <script type="text/javascript">
        //        var fb_param = {};
        //        fb_param.pixel_id = '6014238594210';
        //        fb_param.value = '0.01';
        //        fb_param.currency = 'USD';
        //        (function () {
        //            var fpw = document.createElement('script');
        //            fpw.async = true;
        //            fpw.src = '//connect.facebook.net/en_US/fp.js';
        //            var ref = document.getElementsByTagName('script')[0];
        //            ref.parentNode.insertBefore(fpw, ref);
        //        })();
    </script>
    <noscript>
        <img height="1" width="1" alt="" style="display:none"
             src="https://www.facebook.com/offsite_event.php?id=6014238594210&amp;value=0.01&amp;currency=USD"/>
    </noscript>
</head>
<body>
<div id="round_buttons">
    <!---------------------------- images  ----------------------------------------->
    <img class="btn_img" style="position: absolute; top: 50px; right: 124px;" usemap="#Btn1-map"
         id="Btn1"
         alt="تبلیغات اینترنتی"
         src="intro/images/Btn1.png">
    <img class="btn_img" style="position: absolute; right: 50px; top: 124px;" usemap="#Btn2-map"
         id="Btn2"
         alt="میزبانی وب"
         src="intro/images/Btn2.png">
    <img class="btn_img" style="position: absolute; right: 50px; bottom: 124px;" usemap="#Btn3-map"
         id="Btn3"
         alt="بهینه سازی وب سایت"
         src="intro/images/Btn3.png">
    <img class="btn_img" style="position: absolute; bottom:50px;right: 124px;" usemap="#Btn4-map"
         id="Btn4"
         alt="محصولات نرم افزاری شرکت ایده پرداز"
         src="intro/images/Btn4.png">
    <img class="btn_img" style="position: absolute; bottom: 50px; left: 124px;" usemap="#Btn5-map"
         id="Btn5"
         alt="طراحی نرم افزار های تحت وب"
         src="intro/images/Btn5.png">
    <img class="btn_img" style="position: absolute; bottom: 124px; left: 50px;" usemap="#Btn6-map"
         id="Btn6"
         alt="نصب دوربین مدار بسته"
         src="intro/images/Btn6.png">
    <img class="btn_img" style="position: absolute; left: 50px; top: 124px;" usemap="#Btn7-map"
         id="Btn7"
         alt="طراحی گرافیک و چاپ"
         src="intro/images/Btn7.png">
    <img class="btn_img" style="position: absolute; top: 50px; left: 124px;" usemap="#Btn8-map"
         id="Btn8"
         alt="طراحی وب سایت"
         src="intro/images/Btn8.png">
    <img style="position: absolute;top:185px;left: 185px; " alt="" usemap="#Btn9-map" id="Btn9"
         src="intro/images/Btn9-hover.png">
    <!---------------------------- maps ----------------------------------->
    <div>
        <map name="Btn1-map" id="Btn1-map">
            <area shape="poly" target="_blank"
                  coords="93,153,175,72,157,56,138,42,118,30,96,19,73,11,50,5,25,1,0,0,0,114,27,117,51,125,74,137,93,153,93,153"
                  href="http://www.agahi118.ir" alt="تبلیغات اینترنتی"/>
        </map>
        <map name="Btn2-map" id="Btn2-map">
            <area shape="poly" target="_blank"
                  coords="38,174,153,174,152,149,148,125,142,101,134,78,123,57,111,37,97,18,82,0,0,81,16,101,28,123,35,148,38,174,38,174"
                  href="http://support.azaript.com/cart.php" alt="میزبانی وب"/>
        </map>
        <map name="Btn3-map" id="Btn3-map">
            <area shape="poly" target="_blank"
                  coords="38,0,35,26,27,50,15,72,0,92,81,173,97,156,111,137,123,116,133,95,142,73,148,49,151,25,153,0,38,0,38,0"
                  href="http://seo.ipt24.com" alt="بهینه سازی وب سایت"/>
        </map>
        <map name="Btn4-map" id="Btn4-map">
            <area shape="poly" target="_blank"
                  coords="0,38,0,153,25,151,49,148,73,142,96,133,117,123,137,111,156,97,174,81,93,0,73,16,51,28,26,35,0,38,0,38"
                  href="http://www.azaript.com/software-products/57-ipt-products" alt="محصولات نرم افزاری شرکت ایده پرداز"/>
        </map>
        <map name="Btn5-map" id="Btn5-map">
            <area shape="poly" target="_blank"
                  coords="81,3,0,84,18,100,37,114,57,126,78,136,101,145,124,151,148,154,173,156,173,41,147,38,123,31,101,19,81,3,81,3"
                  href="http://www.azaript.com/software-products" alt="طراحی نرم افزار های تحت وب"/>
        </map>
        <map name="Btn6-map" id="Btn6-map">
            <area shape="poly" target="_blank"
                  coords="115,0,0,0,1,25,5,49,11,73,20,95,30,117,42,137,56,156,72,173,153,92,137,73,125,51,118,26,115,0,115,0"
                  href="http://cctv.ipt24.com" alt="نصب دوربین مدار بسته"/>
        </map>
        <map name="Btn7-map" id="Btn7-map">
            <area shape="poly" target="_blank"
                  coords="153,81,72,0,56,17,42,36,29,57,19,78,11,101,5,124,1,149,0,174,115,174,117,148,125,123,137,101,153,81,153,81"
                  href="http://graphic.ipt24.com/" alt="طراحی گرافیک و چاپ"/>
        </map>
        <map name="Btn8-map" id="Btn8-map">
            <area shape="poly" target="_blank"
                  coords="173,114,173,0,148,1,124,5,100,11,78,19,56,30,36,42,17,56,0,72,81,153,100,137,122,125,147,117,173,114,173,114"
                  href="http://ipt24.com/fa" alt="طراحی وب سایت"/>
        </map>
        <map name="Btn9-map" id="Btn9-map">
            <area shape="poly" target="_blank"
                  coords="32,60,76,26,119,16,166,32,197,64,213,101,210,151,188,189,153,213,118,220,66,212,45,186,25,153,17,110"
                  href="http://ipt24.com/fa"/>
        </map>
    </div>
    <!---------------------------- texts  ----------------------------------------->
    <div id="btn1-text" class="btn-text" style="right: 136px;top: 11px;">
        <a target="_blank" href="http://www.agahi118.ir">تبلیغات اینترنتی</a>
    </div>
    <div id="btn2-text" class="btn-text" style="right: -19px; top: 168px;">
        <a target="_blank" href="http://support.azaript.com/cart.php">میزبانی وب</a>
    </div>
    <div id="btn3-text" class="btn-text" style="right: -77px; top: 394px;">
        <a target="_blank" href="http://azaript.com/index.php">بهینه سازی وب سایت</a>
    </div>
    <div id="btn4-text" class="btn-text" style="right: 129px; top: 574px;">
        <a target="_blank" href="http://www.azaript.com/software-products/57-ipt-products">محصولات نرم افزاری شرکت ایده پرداز</a>
    </div>
    <div id="btn5-text" class="btn-text" style="right: 411px; top: 574px;">
        <a target="_blank" href="http://www.azaript.com/software-products">طراحی نرم افزار های تحت وب</a>
    </div>
    <div id="btn6-text" class="btn-text" style="left: -56px; top: 393px;">
        <a target="_blank" href="http://alvercenter.com/">
            نصب دوربین مدار بسته
        </a>
    </div>
    <div id="btn7-text" class="btn-text" style="left: -43px; top: 156px;">
        <a target="_blank" href="http://ipt24.com/multimedia/">
            طراحی گرافیک و چاپ
        </a>
    </div>
    <div id="btn8-text" class="btn-text" style="right: 400px; top: 5px;">
        <a target="_blank" href="http://ipt24.ir/">طراحی وب سایت</a>
    </div>
    <!---------------------------- tooltips  ----------------------------------------->
    <div class="tooltips">
        <div id="Btn1-tooltip">
            <div class="btn-tooltip">
                <ul>
                    <li>تبلیغات اینترنتی در سایتهای پر بازدید و خبری</li>
                    <li>سایر روشهای سنتی بازاریابی</li>
                    <li>تبلیغ در گوگل</li>
                    <li>ارسال پیامك و ایمیلهای انبوه</li>
                </ul>
            </div>
        </div>
        <div id="Btn2-tooltip">
            <div class="btn-tooltip">
                <ul>
                    <li>هاست لینوكس – نسخه شخصی</li>
                    <li>هاست لینوكس – نسخه شركتی</li>
                    <li>هاست لینوكس – نسخه سازمانی</li>
                </ul>
            </div>
        </div>
        <div id="Btn3-tooltip">
            <div class="btn-tooltip">
                <ul>
                    <li>افزایش رتبه سایت در گوگل | گوگل رنك | گوگل پیج رنك</li>
                    <li>بهینه سازی وب سایت - افزایش ترافیك و تعداد بازدید وب سایت</li>
                    <li>تبلیغات كلیكی اسپانسری گوگل - گوگل ادوردز</li>
                    <li>افزایش ترافیك و رتبه سایت در الكسا – الكسا رنك</li>
                    <li>افزایش ترافیك و رتبه سایت در كامپیت – كامپیت رنك</li>
                    <li>افزایش ترافیك و رتبه سایت در سایت اكسپلورر – موز رنك</li>
                    <li>بازاریابی آنلاین | تجارت الكترونیك | افزایش فروش اینترنتی</li>
                </ul>
            </div>
        </div>
        <div id="Btn4-tooltip">
            <div class="btn-tooltip">
                <ul>
                    <li>سیستم مدیریت همایش و کنفرانس</li>
                    <li>سیستم مدیریت مجله الکترونیکی</li>
                    <li>سیستم مدیریت پورتال اینترنتی</li>
                    <li>سیستم مدیریت وب سایت</li>
                    <li>سیستم مدیریت پروژه</li>
                    <li>سیستم مدیریت مشاورین املاک</li>
                </ul>
            </div>
        </div>
        <div id="Btn5-tooltip">
            <div class="btn-tooltip">
                <ul>
                    <li>انواع نرم افزارهای تحت وب</li>
                </ul>
            </div>
        </div>
        <div id="Btn6-tooltip">
            <div class="btn-tooltip">
                <ul>
                    <li>
                        نصب دوربین مدار بسته
                    </li>
                </ul>
            </div>
        </div>
        <div id="Btn7-tooltip">
            <div class="btn-tooltip">
                <ul>
                    <li>
                        طراحی گرافیک و چاپ
                    </li>
                </ul>
            </div>
        </div>
        <div id="Btn8-tooltip">
            <div class="btn-tooltip">
                <ul>
                    <li>طراحی وب سایت صنعتی – تجاری</li>
                    <li>طراحی وب سایت سازمانی</li>
                    <li>طراحی وب سایت خبری</li>
                    <li>طراحی وب سایت شخصی</li>
                    <li>طراحی وب سایت تجارت الكترونیك - فروشگاهی</li>
                    <li>طراحی وب سایت فول فلش</li>
                </ul>
            </div>
        </div>
        <div id="Btn9-tooltip">
            <div class="btn-tooltip">
                <h4>
                    وب سایت اصلی شرکت ایده پرداز تبریز
                </h4>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">

    var images = {};
    for (var i = 1; i < 9; i++) {
        var img = new Image();
        img.src = 'intro/images/Btn' + i + '-hover.png';
    }

    $(document).ready(function () {
        $('map').hover(function () {
            var id = $(this).attr('id').replace('-map', '');
            var el = $('#' + id);
            if (id != 'Btn9')
                el.attr('src', 'intro/images/' + id + '-hover.png').addClass('hover');
            else {
                el.addClass('hover');
            }

        }, function () {
            var id = $(this).attr('id').replace('-map', '');
            var el = $('#' + id);
            if (id != 'Btn9') {
                var src = el.attr('src').replace('-hover', '');
                el.attr('src', src).removeClass('hover');
            }
            else {
                el.removeClass('hover');
            }
        });
        jQuery("map").tooltip({
            bodyHandler: function () {
                var id = $(this).attr('id').replace('-map', '');
                return $('#' + id + '-tooltip').html();
            },
            fade: true,
            showURL: false,
            track: true,
            delay: 0,
            left: -10,
            positionLeft: true,
            opacity: 1
        });
    });
</script>
</body>
</html>