<?
$this->headLink()->prependStylesheet($this->basePath() . '/__/css/ads.css');
if (!$this->error) {
    ?>
    <div class="col-md-12">
        <?
        if ($this->baseType) {
            foreach ($this->baseType as $row) {
                ?>
                <div class="col-md-4">
                    <a href="<?= url('app/ad/list', array('baseType' => $row['id'], 'isRequest' => 0, 'baseTitle' => $row['baseTypeAdsMachineName'])) ?>"
                       class="btn btn-default btn-lg btn-block">
                        <span><?= $row['name'] ?></span>
                    </a>
                </div>
                <? if ($row['isRequest']) { ?>
                    <div class="col-md-4">
                        <a class="ajax_page_load btn btn-default btn-lg btn-block"
                           href="<?= url('app/ad/list', array('baseType' => $row['id'], 'isRequest' => 1, 'baseTitle' => $row['baseTypeAdsMachineName'])) ?>">
                            <span><?= t('ADS_REQUEST') . ' ' . $row['name'] ?></span>
                        </a>
                    </div>
                <?
                }
            }
        }?>
    </div>
<? } ?>


