<?
$this->headLink()->prependStylesheet($this->basePath() . '/__/css/ads.css');
if (!$this->error){
?>
<div class="box_list_ads">
    <div class="col-md-12">
        <select name="sort" id="sort">
            <option value=""><?= t('Default') ?></option>
            <?
            $desc = t('Descending');
            $asc = t('Ascending');
            foreach ($this->sortOptions as $table => $fields) {
                foreach ($fields as $field => $name) {
                    print "<option value='{$table}.{$field}.desc'>{$name} {$desc}</option>";
                    print "<option value='{$table}.{$field}.asc'>{$name} {$asc}</option>";
                }
            } ?>
        </select>

        <div style="clear: both"></div>
        <?
        if ($this->select) {
        $countEndTag = 0;
        $panelId = 0;
        foreach ($this->select as $row) {
        if (isset($this->secondType[$row->secondType]) && $panelId != $row->secondType) {
        $countEndTag++;
        $panelId = $row->secondType;
        if ($countEndTag != 1)
            echo '</div></div>';
        ?>
        <div class="panel panel-primary">
            <div class="panel-heading"><?= $this->secondType[$row->secondType] ?></div>
            <div class="panel-body">
                <? } ?>
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="media">
                            <a class="pull-right" href="#">
                                <?
                                if ($row->smallImage) {
                                    $dataImages = unserialize($row->smallImage);
                                    $width = 100;
                                    $height = 100;
                                    if ($dataImages) {
                                        if (isset($this->smallImgConfig['width']))
                                            $width = $this->smallImgConfig['width'];
                                        if (isset($this->smallImgConfig['height']))
                                            $width = $this->smallImgConfig['height'];
                                    }
                                    if (isset($dataImages['fPath']) && $dataImages['fPath'])
                                        $fPath = $dataImages['fPath'];
                                    else
                                        $fPath = $this->basePath() . '/__/images/notImage100_100.png';
                                    $imageUrl = getThumbnail()->resize($fPath, $width, $height); //resize image
                                }
                                ?>
                                <img class="media-object" src="<?= $imageUrl ?>" alt="<?= $row->title ?>">
                            </a>

                            <div class="media-body">
                                <div>
                                    <?= getSM('ads_api')->createViewStarRate($this->starCount, $row->starCount); ?>
                                </div>
                                <a href="<?= url('app/ad/view', array('baseType'=>$row->baseType,'adId' => $row->adId, 'adTitle' => \Application\API\App::prepareUrlString($row->title))) ?>">
                                    <h4 class="media-heading"><?= $row->title ?></h4>
                                </a>
                                <?
                                if ($this->category && isset($this->category[$row->adId]) && $this->showCategory) {
                                    ?>
                                    <div>
                                    <span class="label label-default"><?= t('ADS_CATEGORIES') ?></span>
                                    <?
                                    foreach ($this->category[$row->adId] as $key => $val) {
                                        ?>
                                        <a href="<?= url('app/ad/list', array('baseType' => $row->baseType, 'baseTitle' => $this->baseTypeMachineName), array('query' => array('table' => array('category' => $val)))) ?>"><?= $val ?></a> |
                                    <?
                                    }
                                    ?>
                                    </div><?
                                }
                                ?>
                                <p><?= mb_substr($row->text, 0, 300, 'UTF-8') . ' ...'; ?></p>
                                <? if ($row->link) { ?>
                                    <a href="<?= $row->link ?>"><?= $row->link ?></a>
                                <? } ?>

                                <? if ($this->showCreateDate) { ?>
                                    <p class="text-muted"><?= t('ADS_REG_DATE') . " : " . $this->dateFormat($row->createDate, 2); ?></p>
                                <? } ?>

                                <? if ($this->showHits) { ?>
                                    <p class="text-muted"><?= t('ADS_HITS') . ' : ' ?> <? if ($row->hits) echo $row->hits; else echo 0; ?></p>
                                <? } ?>

                                <?
                                if ($this->keywords && isset($this->keywords[$row->adId]) && $this->showKeyword) {
                                    ?>
                                    <div>
                                        <span class="label label-default"><?= t('ADS_KEYWORDS') ?></span>
                                        <?
                                        foreach ($this->keywords[$row->adId] as $key => $val) {
                                            ?>
                                            <a href="<?= url('app/ad/list', array('baseType' => $row->baseType, 'baseTitle' => $this->baseTypeMachineName), array('query' => array('table' => array('keyword' => $val)))) ?>"><?= $val ?></a> |
                                        <?
                                        } ?>
                                    </div>
                                <?
                                }
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
                <?
                }
                echo '</div></div>';
                } else {
                    ?>
                    <div class="alert alert-danger">
                        <?= t('ADS_NOT_FOUND') ?>
                    </div>
                <?
                }
                ?>
            </div>
            <div class="pager" style="padding-top:12px;">
                <?
                /* @var $pages \Zend\Paginator\Paginator */
                echo $this->paginationControl($this->paginate,
                    'Sliding',
                    'application/pagination/search.phtml',
                    array(
                        'route' => 'app/ad/list',
                        'route_params' => array('baseType', $this->baseTypeId, 'baseTitle' => $this->baseTypeMachineName)
                    )
                ); ?>
            </div>
        </div>
        <? } ?>


