<?
\JQuery\API\JQuery::loadColorBox($this);
use Localization\API\Date;

$this->headLink()->prependStylesheet($this->basePath() . '/__/css/ads.css');
$flagShowAllInfo = $this->flagShowAllInfo;
?>
<div class="box_view_ads">

<div class="col-md-12">
<?
if ($this->select) {

    if (isAllowed(\Ads\Module::APP_AD_VIEW_ALL_INFO))
        $flagShowAllInfo = true;
    if ($this->baseTypeAmountAllInfo <= 0)
        $flagShowAllInfo = true;

    $select = $this->select;
    $fieldsData = getSM()->get('fields_api')->generate($this->fields, (array)$select);


    if($this->baseTypeRate)
    {
        echo $this->negative_positive($select->adId, 'ads_'.$select->baseType.'_'.$select->regType);
    }


    ?>
    <div class="panel panel-primary">
    <div
        class="panel-heading"><? if (isset($this->secondType[$select->secondType])) echo $this->secondType[$select->secondType]; ?></div>
    <div class="panel-body">
    <div class="panel panel-default">
    <div class="panel-body">
    <div class="media">
    <div class="media-body">
    <div>
        <?= getSM('ads_api')->createViewStarRate($this->starCount, $select->starCount); ?>
    </div>
    <h4 class="media-heading"><?= $select->title ?></h4>
    <?
    if ($this->category && isset($this->category[$select->entityId])) {
        ?>
        <div>
        <span class="label label-default"><?= t('ADS_CATEGORIES') ?></span>
        <?
        foreach ($this->category[$select->entityId] as $key => $val) {
            ?>
            <a href="<?= url('app/ad/list', array('baseType' => $select->baseType, 'isRequest' => $select->regType, 'baseTitle' => $this->baseTypeMachineName), array('query' => array('table' => array('category' => $val)))) ?>"><?= $val ?></a> |
        <?
        }
        ?>
        </div><?
    }
    ?>
    <div>
        <span class="label label-default"><?= t('Description') ?></span>

        <span><?= $select->text ?></span>
    </div>
    <div>
        <span class="label label-default"><?= t('Address') ?></span>

        <span><? if ($flagShowAllInfo) echo $select->address; else echo t('ADS_LIMITED_SHOW') ?></span>
    </div>
    <div>
        <span class="label label-default"><?= t('Mobile') ?></span>

        <span><? if ($flagShowAllInfo) echo $select->mobile; else echo t('ADS_LIMITED_SHOW') ?></span>
    </div>
    <div>
        <span class="label label-default"><?= t('Email') ?></span>

        <span><? if ($flagShowAllInfo) echo $select->mail; else echo t('ADS_LIMITED_SHOW') ?></span>
    </div>
    <div>
        <span class="label label-default"><?= t('Fax') ?></span>

        <span><? if ($flagShowAllInfo) echo $select->fax; else echo t('ADS_LIMITED_SHOW') ?></span>
    </div>

    <? if ($select->link) { ?>
        <div>
            <span class="label label-default"><?= t('Url') ?></span>

            <a href="<?= $select->link ?>"><?= $select->link ?></a>
        </div>

    <? } ?>

    <div>
        <span class="label label-default"><?= t('ADS_REG_DATE') ?></span>

        <span><?= $this->dateFormat($select->createDate, 2) ?></span>
    </div>

    <? if ($select->expireDate) { ?>
        <div>
            <span class="label label-default"><?= t('ADS_TIME_REMAINING') ?></span>

                                        <span><?$timeRemaining = 0;
                                            if (time() < $select->expireDate)
                                                echo Date::formatInterval($select->expireDate - time());?></span>
        </div>
    <? } ?>

    <div>
        <span class="label label-default"><?= t('ADS_HITS') ?></span>

        <span><? if ($select->hits) echo $select->hits; else echo 0; ?></span>
    </div>

    <? if ($fieldsData) {
        foreach ($fieldsData as $key => $val) {
            ?>
            <div>
                <span><?= $key ?> : </span>
                <span><?= $val ?></span>
            </div>
        <?
        }
    }?>
    <?
    if ($this->keywords && isset($this->keywords[$select->entityId])) {
        ?>
        <div>
            <span class="label label-default"><?= t('ADS_KEYWORDS') ?></span>
            <?
            foreach ($this->keywords[$select->entityId] as $key => $val) {
                ?>
                <a href="<?= url('app/ad/list', array('baseType' => $select->baseType, 'isRequest' => $select->regType, 'baseTitle' => $this->baseTypeMachineName), array('query' => array('table' => array('keyword' => $val)))) ?>"><?= $val ?></a> |
            <?
            } ?>
        </div>
    <?
    }
    ?>
    <div class="col-md-12">
        <span class="label label-default">  <?= t('Images') ?> </span>

        <div>
            <?
            if ($select->fPath) {
                $fPath = explode(',', $select->fPath);
                $fAlt = explode(',', $select->fAlt);
                $fTitle = explode(',', $select->fTitle);
                foreach ($fPath as $key => $val) {
                    if ($val)
                        $fPathImg = $val;
                    else
                        $fPathImg = $this->basePath() . '/__/images/notImage100_100.png';
                    $imageUrl = getThumbnail()->resize($fPathImg, 100, 100); //resize image
                    $href = $fPathImg;
                    $fTitleImg = '';
                    $fAltImg = '';
                    if (isset($fAlt[$key]))
                        $fAltImg = $fAlt[$key];
                    if (isset($fTitle[$key]))
                        $fTitleImg = $fTitle[$key];
                    ?>
                    <div class="col-md-3">
                        <a class="colorbox" href="<?= $href ?>">
                            <img src="<?= $imageUrl ?>" width="100"
                                 style="display: block; margin: auto;" height="100"
                                 title="<?= $fTitleImg ?>"
                                 alt="<?= $fAltImg ?>">
                        </a>
                    </div>
                <?
                }
            }
            ?>
        </div>
    </div>
    <? if (!empty($select->googleLatLong)) {
        ?>
        <div class="col-md-12">
            <span class="label label-default">  <?= t('Geographical location') ?> </span>
            <?
            if ($flagShowAllInfo) {
                ?>
                <a target="_blank"
                   href="http://maps.google.com/maps/api/staticmap?center=<?= $select->googleLatLong ?>&zoom=13&size=800x600&markers=<?= $select->googleLatLong ?>&sensor=false">
                    <img style="color: #000000;"
                         alt="<?= t('Please wait ...') ?>"
                         src="http://maps.google.com/maps/api/staticmap?center=<?= $select->googleLatLong ?>&zoom=14&size=300x200&markers=<?= $select->googleLatLong ?>&sensor=false"/>
                </a>
            <?
            } else {
                echo t('ADS_LIMITED_SHOW');
            }?>
        </div>
    <?
    } ?>

    <div style="clear:both"></div>
    <br>
    <!--show all info-->
    <? if ($this->baseTypeAmountAllInfo > 0 && !$flagShowAllInfo) {
        //Payment
        $paymentParams = array(
            'amount' => $this->baseTypeAmountAllInfo,
            'email' => current_user()->email,
            'comment' => 'Pay For View All Data Ad',
            'validate' => array(
                'route' => 'app/ad/view-data-validate',
                'params' => array(
                    'id' => $select->id,
                    'entityType' => 'ads_' . $select->baseType . '_' . $select->regType,
                    'userId' => current_user()->id,
                ),
            )
        );
        $paymentParams = serialize($paymentParams);
        $paymentParams = base64_encode($paymentParams);
        ?>
        <? if (current_user()->id == 0) { ?>
            <div class="col-md-12">
                <p class="alert alert-danger">
                    <?= t('ADS_ATTENTION_BUY_SHOW_INFO_GUEST_OR_MEMBER') ?>
                </p>

                <p class="alert alert-info">
                    <? //= t('ADS_FOR_VIEW_PAYMENT_LOGIN') ?>
                    <a href="<?= url('app/user/register') ?>"><?= t('ADS_CLICK_FOR_REGISTER') ?></a>
                    <a href="<?= url('app/user/login') ?>"><?= t('ADS_CLICK_FOR_LOGIN') ?></a>
                </p>
            </div>
        <? } ?>
        <div class="col-md-12">
            <a href="<?= url('app/payment', array(), array('query' => array('routeParams' => $paymentParams))) ?>">
                <button type="button" class="btn btn-default">
                    <?= sprintf(t('ADS_VIEW_DATA_PRICE'), $this->currencyFormat($this->baseTypeAmountAllInfo)) ?>
                </button>
            </a>
        </div>
        <?
        //end
    } ?>
    </div>
    </div>
    </div>
    </div>
    </div>
    </div>
<?
} else {
    ?>
    <div class="alert alert-danger">
        <?= t('ADS_NOT_FOUND') ?>
    </div>
<?
}
?>
</div>
</div>



