<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'FormsManager\API\ACL'                        => __DIR__ . '/src/FormsManager/API/ACL.php',
  'FormsManager\API\Form'                       => __DIR__ . '/src/FormsManager/API/Form.php',
  'FormsManager\Controller\FormsController'     => __DIR__ . '/src/FormsManager/Controller/FormsController.php',
  'FormsManager\Controller\FormsDataController' => __DIR__ . '/src/FormsManager/Controller/FormsDataController.php',
  'FormsManager\Form\Config'                    => __DIR__ . '/src/FormsManager/Form/Config.php',
  'FormsManager\Form\DynamicForm'               => __DIR__ . '/src/FormsManager/Form/DynamicForm.php',
  'FormsManager\Form\FormConfig'                => __DIR__ . '/src/FormsManager/Form/FormConfig.php',
  'FormsManager\Form\FormTemplate'              => __DIR__ . '/src/FormsManager/Form/FormTemplate.php',
  'FormsManager\Install'                        => __DIR__ . '/src/FormsManager/Install.php',
  'FormsManager\Model\Form'                     => __DIR__ . '/src/FormsManager/Model/Form.php',
  'FormsManager\Model\FormData'                 => __DIR__ . '/src/FormsManager/Model/FormData.php',
  'FormsManager\Model\FormDataTable'            => __DIR__ . '/src/FormsManager/Model/FormDataTable.php',
  'FormsManager\Model\FormTable'                => __DIR__ . '/src/FormsManager/Model/FormTable.php',
);
