<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Exlord
 * Date: 10/21/13
 * Time: 10:25 AM
 */
?>
<div id="users-widget">
    <div class="real-estate-widget-header">
        <label class="real-estate-widget-header-text">
            <?= t('Users') ?>
        </label>
    </div>
    <? if(isAllowed(\USER\Module::ADMIN_USER_WIDGET)){ ?>
    <table cellspacing="0" cellpadding="0" border="0" class="real-estate-widget-tbl">
        <?
       // $i = 0;
        foreach ($this->data as $row) {
            if($row['roleName']=='All User')
            {
/*
            $i++;
            $class = 'real-estate-widget-tbl-tr' . $i;
            if ($i == 2)
                $i = 0;*/
            ?>
            <tr class="real-estate-widget-tbl-tr1">
                <td class="real-estate-widget-tbl-td-title"><a class="real-estate-widget-tbl-td-title-links" href="<?=url('admin/users')?>"><?= sprintf(t('Number of %s'), t($row['roleName'])) ?></a></td>
                <td class="real-estate-widget-tbl-td-content"><b class="digit"><?= localizedDigits((int)$row['count']-1) ?></b></td>
            </tr>
        <? } }?>
    </table>
    <? } else { ?>
        <div class="widget-access-denied real-estate-widget-tbl">
            <?=t('Dear user, your access is limited by the webmaster.')?>
        </div>
    <? }?>
</div>