<div>
    <?
    //    $form = $this->form;
    //    $form->prepare();
    //    echo $this->form()->openTag($form);
    //
    //    foreach ($form->getElements() as $el) {
    //
    ?>
    <!--        <div class="form_element">-->
    <!--            --><? //=$this->iptFormRow($el);?>
    <!--        </div>-->
    <!--        --><? //
    //    }
    //    echo $this->iptFormCollection($form->get('buttons'));
    //    echo $this->form()->closeTag();
    print $this->form($this->form);
    ?>
</div>