<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'ClientManager\API\License'                  => __DIR__ . '/src/ClientManager/API/License.php',
  'ClientManager\Controller\LicenseController' => __DIR__ . '/src/ClientManager/Controller/LicenseController.php',
  'ClientManager\Controller\UpdateController'  => __DIR__ . '/src/ClientManager/Controller/UpdateController.php',
  'ClientManager\Model\License'                => __DIR__ . '/src/ClientManager/Model/License.php',
  'ClientManager\Model\LicenseTable'           => __DIR__ . '/src/ClientManager/Model/LicenseTable.php',
);
