<?
$this->headScript()->appendFile($this->basePath() . '/js/user-admin-permission.js');
$this->headLink()->appendStylesheet($this->basePath() . '/css/user-admin.css');
$perms_json = array();
$perm_index = 0;
?>
<div>
    <a class="toolbar-button btn btn-default ajax_page_load"
       href="<?= $this->url('admin/users/permission/permission-rebuild') ?>"
       title="<?= $this->translate('Rebuild Permission List') ?>">
        <i class="glyphicon glyphicon-refresh text-success"></i>
        <?= $this->translate('Rebuild') ?>
    </a>

    <h3 class="page-title">
        <?= $this->translate('Permissions') ?>
    </h3>

    <div style="clear:both">
        <div id="page-loading-progress" class="ajax-loading" style="height:100px;">&nbsp;</div>
        <div id="tabs" style="display:none">
            <ul>
                <? foreach ($this->roles as $id => $role) {

                    ?>
                    <li>
                        <a href="#tabs-<?= $id ?>">
                            <?
                            for ($i = 1; $i <= $role->indent; $i++) {
                                echo "<span class='level'>- ";
                            }
                            ?>
                            <span>- <?= $this->translate($role->roleName) ?></span>
                            <?
                            for ($i = 1; $i <= $role->indent; $i++) {
                                echo "</span>";
                            }
                            ?>
                        </a>
                    </li>
                <? } ?>
            </ul>
            <? foreach ($this->roles as $id => $role) { ?>
                <div id="tabs-<?= $id ?>">
                    <table class="permissions-table" cellpadding="0" cellspacing='0'>
                        <thead>
                        <tr>
                            <th align='right'><?= $this->translate('Permission') ?></th>
                            <th align="center" width="150px"><?= $this->translate('USER_PERM_Section') ?></th>
                            <th align="center" width="150px"><?= $this->translate('Change Permission') ?></th>
                            <th align="center" width="150px"><?= $this->translate('Current Permission') ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?
                        foreach ($this->permissions as $module => $perm_list) {
                            ?>
                            <tr>
                                <td colspan="4">

                                    <?
                                    $headers = array(
                                        'data' => array(
                                            array('align' => 'right', 'data' => $this->translate('PERM_' . $module)),
                                            array('width' => '150px', 'data' => '&nbsp;'),
                                            array('width' => '150px', 'data' => '&nbsp;'),
                                            array('width' => '150px', 'data' => '&nbsp;'),
                                        ),
                                        'class' => array("perm-module")
                                    );

                                    $rows = array();
                                    ?>

                                    <!--                                    <table cellpadding="0" cellspacing='0' id="PERM_-->
                                    <? //= $module ?><!--">-->
                                    <!--                                        <thead>-->
                                    <!--                                        <tr class="perm-module">-->
                                    <!--                                            <th align="right">-->
                                    <? //= $this->translate('PERM_' . $module) ?><!--</th>-->
                                    <!--                                            <th width="150px">&nbsp;</th>-->
                                    <!--                                            <th width="150px">&nbsp;</th>-->
                                    <!--                                            <th width="150px">&nbsp;</th>-->
                                    <!--                                        </tr>-->
                                    <!--                                        </thead>-->
                                    <!--                                        <tbody>-->
                                    <?
                                    foreach ($perm_list as $key => $perm) {
                                        $isAdmin = strpos($key, 'admin') > -1;
                                        $perm_index = $id . '_' . str_replace(array('/', '-', ':'), '', $key);
                                        $allow = '';
                                        $deny = '';
                                        $isAllowed = false;
                                        if (!$this->acl->isAllowed($id, $key)) {
                                            $allow = 'hidden';
                                            $perms_json[$perm_index] = false;
                                        } else {
                                            $deny = 'hidden';
                                            $perms_json[$perm_index] = true;
                                            $isAllowed = true;
                                        }
                                        if (isAllowed($key)) //is current user has access to this resource
                                        {
                                            $row = array();
                                            ?>
                                            <!--                                                <tr>-->
                                            <?
                                            $col = '';
                                            for ($i = 1; $i <= $perm->indent; $i++) {
                                                $last = '';
                                                if ($i == $perm->indent)
                                                    $last = 'last';
                                                $col = "<div class='indent $last'>";
                                            }

                                            $col .= "<span class='level'>&nbsp;</span>";
                                            $col .= $this->translate($perm->getName());
                                            $note = $perm->getnote();
                                            if ($perm->getName() == $note)
                                                $note = '&nbsp;';
                                            $col .= ("<p class='description'>" . t($note) . "</p>");

                                            for ($i = 1; $i <= $perm->indent; $i++) {
                                                $last = '';
                                                if ($i == $perm->indent)
                                                    $last = 'last';
                                                $col .= ("<div>");
                                            }
                                            $row[] = array('data' => $col, 'class' => array("no-border"));
                                            ?>
                                            <!--                                                    <td class="no-border">-->
                                            <!--                                                        --><? //= $col; ?>
                                            <!--                                                    </td>-->
                                            <?
                                            if ($isAdmin) {
                                                $col = '<label class="label label-info">' . t('Administration') . '</label>';
                                            } else {
                                                $col = '<label class="label label-primary">' . t('Client Section') . '</label>';
                                            }
                                            $row[] = array('data' => $col, 'align' => 'center');

                                            ?>
                                            <!--                                                    <td align="center">-->
                                            <!--                                                        --><? //= $col; ?>
                                            <!--                                                    </td>-->
                                            <?
                                            $col = \Theme\API\Common::Select(array(
                                                "" => $this->translate('-- Select --'),
                                                "0" => $this->translate('Inherited'),
                                                "1" => $this->translate('Allowed'),
                                                "2" => $this->translate('Denied'),
                                            ), "perms[{$id}][{$key}]", "perms[{$id}][{$key}]", array('class' => array('perm-select')));
                                            $row[] = array('data' => $col, 'align' => 'center', 'class' => array('hoverable'));
                                            ?>
                                            <!--                                                    <td align='center' class="hoverable">-->
                                            <!--                                                        <select class="perm-select"-->
                                            <!--                                                                name="perms[-->
                                            <? //= $id ?><!--][--><? //= $key ?><!--]">-->
                                            <!--                                                            <option-->
                                            <!--                                                                value="">-->
                                            <? //= $this->translate('-- Select --') ?><!--</option>-->
                                            <!--                                                            <option-->
                                            <!--                                                                value="0">-->
                                            <? //= $this->translate('Inherited') ?><!--</option>-->
                                            <!--                                                            <option-->
                                            <!--                                                                value="1">-->
                                            <? //= $this->translate('Allowed') ?><!--</option>-->
                                            <!--                                                            <option-->
                                            <!--                                                                value="2">-->
                                            <? //= $this->translate('Denied') ?><!--</option>-->
                                            <!--                                                        </select>-->
                                            <!--                                                        --><? //= $col ?>
                                            <!--                                                    </td>-->

                                            <?
                                            $col = "<span class='label permission-denied " . $deny . "'>" . $this->translate('Denied') . "</span>";
                                            $col .= "<span class='label permission-allowed " . $allow . "'>" . $this->translate('Allowed') . "</span>";
                                            $row[] = array('data' => $col, 'align' => 'center', 'id' => $perm_index, 'class' => array('hoverable'));
                                            ?>
                                            <!--                                                    <td align='center' id="--><? //= $perm_index ?><!--" class="hoverable">-->
                                            <!--                                                        --><? //= $col ?>
                                            <!--                                                    </td>-->
                                            <!--                                                </tr>-->

                                            <?
                                            $rows[] = $row;
                                        }
                                    }
                                    ?>
                                    <!--                                        </tbody>-->
                                    <!--                                    </table>-->

                                    <?= \Theme\API\Table::Table($headers, $rows, array('id' => "PERM_{$module}")); ?>
                                </td>
                            </tr>
                        <? } ?>
                        </tbody>
                    </table>
                </div>
            <? } ?>
        </div>
    </div>
</div>


<script type="text/javascript">
    <?$this->inlineScript()->captureStart();?>
    var permission_change_url = '<?=$this->url('admin/users/permission/permission-change')?>';
    var perms = <?=json_encode($perms_json)?>;
    $(function () {
        $("#tabs").tabs(
            {
                activate: function (event, ui) {
                    $.cookie("permission_tabs_selected", $("#tabs").tabs("option", "active"));
                },
                active: $.cookie("permission_tabs_selected")
            }
        ).addClass("ui-tabs-vertical ui-helper-clearfix").show();
        $("#tabs li").removeClass("ui-corner-top").addClass("ui-corner-right");
        $('#page-loading-progress').remove();
        Permissions.init();
    });
    <?$this->inlineScript()->captureEnd();?>
</script>

