<?
foreach ($this->dataOneLevel as $row3) {
    ?>
    <div id="comment_<?= $row3['id'] ?>" class="comment-div <?= $this->className ?>">
        <?
        if (current_user()->id) {
            ?>
            <?= $this->negative_positive($row3['id'],  \Comment\Module::ENTITY_TYPE) ?>
        <? } ?>
        <div class="comment-header">
            <a class="comment-username"
               href="<?= url('app/user/user-profile', array('id' => $row3['userId'])) ?>">
                <?= $this->escapeHtml($row3['name']) ?>
            </a>
            <span class="line"> | </span>
            <span class="comment-date"> <?= $this->dateFormat($row3['created']) ?></span>
        </div>
        <a href="#toggle" class="slide-toggle-icon" title="<?=t('Open/Close')?>" rel="tooltip"></a>
        <div class="main-content-comments">
            <?
            if (!empty($row3['image'])) {
                $file_path_resize = getThumbnail()->thumbnail($row3['image'], 80, 80);
                $file_path_base = $this->basePath() . $row3['image'];
            } else {
                $file_path_resize = getThumbnail()->thumbnail($this->basePath() . '/images/not-image.png', 80, 80);
                $file_path_base = $this->basePath() . '/images/not-image.png';
            }
            ?>
            <div class="comment-image">
                <a class="colorbox" href="<?= $file_path_base ?>">
                    <img class="img-comment-image" src="<?= $file_path_resize ?>" alt="">
                </a>
            </div>


            <p class="comment-body" id="comment_content_<?= $row3['id'] ?>">
                <?= $this->escapeHtml($row3['comment']) ?>
            </p>

            <div style="clear: both"></div>
            <?
            if ($this->questStatus) {
                ?>
                <div class="comment-buttons">
                                         <span class="span-new-reply">
                                               <a href="#reply" id="newReply" class="new-reply"
                                                  data-id="<?= $row3['id'] ?>"><?= t('Reply') ?></a>
                                         </span>
                    <?
                    if ((isAllowed(\Comment\Module::APP_COMMENT_EDIT) && current_user()->id == $this->row['userId']) || isAllowed(\Comment\Module::APP_COMMENT_EDIT_ALL)) {
                        if ($this->editTime == 0 || (int)$row3['created'] + $this->editTime > time()) {
                            ?>
                            <span class="span-edit-comment-text">
                <a href="#edit" id="open_edit_comment_text" class="edit-comment-text"
                   data-id="<?= $row3['id'] ?>"><?= t('Edit') ?></a>
                </span>
                        <?
                        }
                    }
                    if ((isAllowed(\Comment\Module::APP_COMMENT_DELETE) && current_user()->id == $this->row['userId']) || isAllowed(\Comment\Module::APP_COMMENT_DELETE_ALL)) {
                        if ($this->deleteTime == 0 || (int)$row3['created'] + $this->deleteTime > time()) {
                            ?>
                            <span class="span-delete-comment">
                <a href="#delete" id="delete_comment" class="delete-comment"
                   data-id="<?= $row3['id'] ?>"><?= t('Delete') ?></a>
                </span>
                        <?
                        }
                    }
                    if ($row3['count']) {
                        ?>
                        <span class="span-replies">
                    <a href="#replies" data-id="<?= $row3['id'] ?>" class="replies">
                        <?= t('Replies') ?>
                        ( <span class="count-reply"><?= $row3['count'] ?></span> )
                    </a>
                        </span>
                    <?
                    }
                    if ($row3['count']) {
                        ?>
                        <div style="display: none" id="showReply<?= $row3['id'] ?>"
                             class="show-reply"></div>
                    <?
                    }
                    ?>
                </div>
            <? } else { ?>
                <div class="user-register">
                    <?= t('You must be logged in to comment your user panel.') ?>
                    <a target="_blank" href="<?= url('app/user/register') ?>">
                        <?= t('Click here to register') ?>
                    </a>
                </div>
            <? } ?>
        </div>
    </div>
<?
} ?>