<?
$this->headLink()->appendStylesheet($this->basePath() . TEMPLATE_PATH . '/css/real-estate-print-page.css');
$this->headLink()->appendStylesheet($this->basePath() . TEMPLATE_PATH . '/css/real-estate-print.css', 'print');
//$this->headLink()->appendStylesheet($this->basePath() . TEMPLATE_PATH . '/css/real-estate-melkyab.css');
$route_prefix = $this->admin_route ? 'admin' : 'app';
//----------------------ali

$allowed_REAL_ESTATE_VIEW_ALL_SHOW_USER_AGENT_INFO = isAllowed(\RealEstate\Module::APP_REAL_ESTATE_VIEW_ALL_SHOW_USER_AGENT_INFO);
$allowed_REAL_ESTATE_VIEW_ALL_SHOW_USER_INFO = isAllowed(\RealEstate\Module::APP_REAL_ESTATE_VIEW_ALL_SHOW_USER_INFO);
if ($this->permission) {
    $allowed_REAL_ESTATE_VIEW_ALL_SHOW_USER_INFO = true;
    $allowed_REAL_ESTATE_VIEW_ALL_SHOW_USER_AGENT_INFO = true;
}

//------------------------

$allRegType = getSM('category_item_table')->getItemsArrayByCatName('estate_reg_type');
foreach ($this->item as $row) {
    $extra_fields = getSM()->get('fields_api')->generate($this->fields, $row);

    if ($row->showInfo && $row->expireShowInfo >= time())
        $allowed_REAL_ESTATE_VIEW_ALL_SHOW_USER_INFO = true;

    if ($allowed_REAL_ESTATE_VIEW_ALL_SHOW_USER_INFO) {
        $owner_details = array(
            'Name' => $row->ownerName,
            'Phone' => $row->ownerPhone,
            'Email' => $row->ownerEmail,
            'Mobile' => $row->ownerMobile,
            'Address' => $row->addressFull,
        );
    } else {
        $owner_details = array(
            'Address' => $row->addressShort,
            'Name' => $this->defaultAgent->displayName,
            'Phone' => $this->defaultAgent->phone,
            'Email' => $this->defaultAgent->email,
            'Mobile' => $this->defaultAgent->mobile,
        );
    }

    if ($allowed_REAL_ESTATE_VIEW_ALL_SHOW_USER_AGENT_INFO && is_array($this->userAgent))
        $data_row = $this->userAgent;
    else
        $data_row = $this->defaultAgent;

    ?>
    <div class="box-print-form">
    <div class="title-print">
        <img src="<?=$this->basePath() . TEMPLATE_PATH .'/images/form_header2.png'?>" class="img-header-print" height="80">
    </div>
    <table class="tbl-view-print">
    <tr>
        <td>
            <label><?= $this->translate('Realty Id'); ?></label>

            <p><?= $row->itemId ?></p>
        </td>
        <td>
            <label><?= $this->translate('Owner name'); ?></label>

            <p><?= $owner_details['Name'] ?></p>
        </td>
        <td>
            <label><?= $this->translate('Mobile'); ?></label>

            <p><?= $owner_details['Mobile'] ?></p>
        </td>
        <td>
            <label><?= $this->translate('Phone'); ?></label>

            <p><?= $owner_details['Phone'] ?></p>
        </td>
        <td>
            <label><?= $this->translate('State') ?></label>

            <p><?= $row->stateTitle ?></p>
        </td>
    </tr>
    <tr>
        <td>
            <label><?= $this->translate('City'); ?></label>

            <p><?= $row->cityTitle ?></p>
        </td>
        <td>
            <label><?= $this->translate('Region'); ?></label>

            <p><?= $row->areaTitle ?></p>
        </td>
        <td colspan="3">
            <label><?= $this->translate('Address'); ?></label>

            <p><?= $owner_details['Address'] ?></p>
        </td>
    </tr>
    <tr>
        <td>
            <label><?= $this->translate('realEstate_print_estate_type'); ?></label>

            <p><?if(isset($allRegType[$row->regType])) echo t($allRegType[$row->regType]); ?></p>
        </td>
        <td>
            <label><?= $this->translate('realEstate_print_reg_type'); ?></label>

            <p><?= $row->estateTypeName ?></p>
        </td>
        <td>
            <label><?= $this->translate('realEstate_print_estate_position'); ?></label>

            <p><? if (isset($extra_fields['موقعیت ملک'])) echo $extra_fields['موقعیت ملک']; ?></p>
        </td>
        <td>
            <label><?= $this->translate('realEstate_print_estate_position'); ?></label>

            <p><? if (isset($extra_fields['مساحت زمین'])) echo $extra_fields['مساحت زمین']; ?></p>
        </td>
        <td>
            <label><?= $this->translate('realEstate_print_estate_zirbana') ?></label>

            <p><? if (isset($extra_fields['زیربنا'])) echo $extra_fields['زیربنا']; ?></p>
        </td>
    </tr>
    <tr>
        <?if($row->regType==78){?>
            <td>
                <label><?= $this->translate('RealEstate_mortgage_price'); ?></label>

                <p><? $this->currencyFormat($row->mortgagePrice) ?></p>
            </td>
            <td>
                <label><?= $this->translate('RealEstate_rental_price') ?></label>

                <p><?= $this->currencyFormat($row->rentalPrice) ?></p>
            </td>
        <? }else {?>
            <td>
                <label><?= $this->translate('RealEstate_price_one_meter'); ?></label>

                <p><?= $this->currencyFormat($row->priceOneMeter) ?></p>
            </td>
            <td>
                <label><?= $this->translate('RealEstate_total_price'); ?></label>

                <p><?= $this->currencyFormat($row->totalPrice) ?></p>
            </td>
        <? } ?>
        <td>
            <label><?= $this->translate('realEstate_print_estate_room_count') ?></label>

            <p><? if (isset($extra_fields['تعداد اتاق'])) echo $extra_fields['تعداد اتاق']; ?></p>
        </td>
        <td>
            <label><?= $this->translate('realEstate_print_estate_room_count') ?></label>

            <p><? if (isset($extra_fields['تعداد اتاق'])) echo $extra_fields['تعداد اتاق']; ?></p>
        </td>
        <td>
            <label><?= $this->translate('realEstate_print_estate_room_count') ?></label>

            <p><? if (isset($extra_fields['تعداد اتاق'])) echo $extra_fields['تعداد اتاق']; ?></p>
        </td>
    </tr>
    <tr>
        <td>
            <label><?= $this->translate('realEstate_print_estate_floor_count') ?></label>

            <p><? if (isset($extra_fields['تعداد طبقات'])) echo $extra_fields['تعداد طبقات']; ?></p>
        </td>
        <td>
            <label><?= $this->translate('realEstate_print_estate_witch_floor') ?></label>

            <p><? if (isset($extra_fields['مورد در طبقه'])) echo $extra_fields['مورد در طبقه']; ?></p>
        </td>
        <td>
            <label><?= $this->translate('realEstate_print_estate_build_year') ?></label>

            <p><? if (isset($extra_fields['سال ساخت'])) echo $extra_fields['سال ساخت']; ?></p>
        </td>
        <td>
            <label><?= $this->translate('realEstate_print_estate_vam') ?></label>

            <p><? if (isset($extra_fields['وام'])) echo $extra_fields['وام']; ?></p>
        </td>
        <td>
            <label><?= $this->translate('realEstate_print_estate_usage') ?></label>

            <p><? if (isset($extra_fields['کاربری ملک'])) echo $extra_fields['کاربری ملک']; ?></p>
        </td>
    </tr>
    <tr>
        <td>
            <label><?= $this->translate('realEstate_print_estate_room_floor_type') ?></label>

            <p><? if (isset($extra_fields['کف'])) echo $extra_fields['کف']; ?></p>
        </td>
        <td>
            <label><?= $this->translate('realEstate_print_estate_gozar') ?></label>

            <p><? if (isset($extra_fields['گذر'])) echo $extra_fields['گذر']; ?></p>
        </td>
        <td>
            <label><?= $this->translate('realEstate_print_estate_ensheabat') ?></label>

            <p><? if (isset($extra_fields['انشعابات'])) echo $extra_fields['انشعابات']; ?></p>
        </td>
        <td>
            <label><?= $this->translate('realEstate_print_estate_heating_system') ?></label>

            <p><? if (isset($extra_fields['گرمایش'])) echo $extra_fields['گرمایش']; ?></p>
        </td>
        <td>
            <label><?= $this->translate('realEstate_print_estate_has_parking') ?></label>

            <p><? if (isset($extra_fields['پارکینگ'])) echo $extra_fields['پارکینگ']; ?></p>
        </td>
    </tr>
    <tr>
        <td>
            <label><?= $this->translate('realEstate_print_estate_nama') ?></label>

            <p><? if (isset($extra_fields['نما'])) echo $extra_fields['نما']; ?></p>
        </td>
        <td>
            <label><?= $this->translate('realEstate_print_estate_kitchen_service') ?></label>

            <p><? if (isset($extra_fields['سرویس آشپزخانه'])) echo $extra_fields['سرویس آشپزخانه']; ?></p>
        </td>
        <td>
            <label><?= $this->translate('realEstate_print_estate_wc_service') ?></label>

            <p><? if (isset($extra_fields['سرویس بهداشتی'])) echo $extra_fields['سرویس بهداشتی']; ?></p>
        </td>
        <td>
            <label><?= $this->translate('realEstate_print_estate_sanad_type') ?></label>

            <p><? if (isset($row->sanad_dong)) echo $row->sanad_dong; ?></p>
        </td>
        <td>
            <label><?= $this->translate('realEstate_print_estate_sanad_type') ?></label>

            <p><? if (isset($row->sanad_dong)) echo $row->sanad_dong; ?></p>
        </td>
    </tr>
    <tr>
        <td colspan="5" class="desc-view-print">
            <label><?= $this->translate('Description') ?></label>

            <p><?= $row->description ?></p>
        </td>
    </tr>
    <tr>
        <td colspan="5">
            <?
            $secondFieldsArray = array(
                'آب' => 'em_water',
                'برق' => 'em_bargh',
                'گاز' => 'em_gaz',
                'تلفن' => 'em_phone',
                'استخر' => 'em_estakhr',
                'چاه عمیق' => 'em_chah',
                'دوربین مداربسته' => 'em_durbin',
                'اطفاء حریق' => 'em_etfae_harigh',
                'شوفاژ' => 'em_shufaj',
                'کولر' => 'em_kuler',
                'چیلر' => 'em_chiler',
                'فن کوئل' => 'em_fankuel',
                'آیفون تصویری' => 'em_ifon',
                'پکیج' => 'em_pakeij',
                'نورمخفی' => 'em_noormakhfi',
                'ریموت کنترل' => 'em_rimut',
                'آبگرمکن' => 'em_abgarmkon',
                'شومینه' => 'em_shumine',
                'سونا' => 'em_suna',
                'آنتن مرکزی' => 'em_anten',
                'حیاط خلوت' => 'em_hayat',
                'آسانسور' => 'em_asansor',
                'باربیکیو' => 'em_barbiku',
                'جکوزی' => 'em_jakuzi',
                'لابی' => 'em_labi',
                'فضای سبز' => 'em_fazayesabz',
                'پنجره دوجداره' => 'em_panjare',
                'پاسیو' => 'em_pasu',
                'شوتینگ زباله' => 'em_shuting',
                'نگهبان - سرایدار' => 'em_negahban',
            );
            foreach ($secondFieldsArray as $key => $val) {
                if (isset($extra_fields[$key]) && $extra_fields[$key]) {
                    ?>
                    <div class="p_box_em">
                        <div>
                            <span class="active_icon"></span>
                            <span class="label"><?= $key ?></span>
                        </div>
                    </div>
                <?
                }
            }
            ?>
        </td>
    </tr>

    </table>
    </div>
<?
}
?>