<?
if (!$this->error) {
    $this->headScript()->appendFile($this->basePath() . '/__/js/filter-fields.js');
    $this->headScript()->appendFile($this->basePath() . '/js/geographical.js');
    if ($this->isGoogleMap) {
        $this->headScript()->appendFile($this->basePath() . '/__/js/adsGoogleMapHandler.js');
    }
    ?>
    <style>
        .ad_new_form #ad_part_6000_0_2{ display:none; }
        #image_settings .add_collection_item{ display:none; }
        #ad_part_6000_0_2 .select2-container-multi{ width:auto !important; }
        .filter-field-hidden{ display:none; }
    </style>

    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-6">
                <img src="<?= $this->basePath() . TEMPLATE_PATH . '/images/main/logo_new.png' ?>"
                     class="img-responsive logo_new">
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6">
                <img src="<?= $this->basePath() . TEMPLATE_PATH . '/images/main/titr_new.png' ?>"
                     class="img-responsive titr_new">
            </div>
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12">
    <div class="row">
    <div class="ad_new_form">
    <div class="back_loading">
        <span class="img_loading"></span>
    </div>
    <?
    $form = $this->form;
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('id'));
    echo $this->formRow($form->get('googleLatLong'));
    if ($form->has('sendRequestId'))
        echo $this->formRow($form->get('sendRequestId'));
    if ($form->has('notifyPrice'))
        echo $this->formRow($form->get('notifyPrice'));
    if ($form->has('notifyType'))
        echo $this->formRow($form->get('notifyType'));
    /* @var $fieldset \Zend\Form\Fieldset */
    $fieldset = $form->get('fields');
    $fields = $fieldset->getElements();
    ?>
    <div id="ad_part_6000_0_1">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <span class="box_new_type_desc">
                <span class="glyphicon glyphicon-exclamation-sign text-danger"></span>
                برای انتخاب نوع آگهی خود لطفا یکی از موارد زیر را انتخاب نمایید .
                <span class="caret"></span>
            </span>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 ad_view_type">
            <?
            $el = $form->get('adType');
            $el->setLabel("");
            echo $this->formRow($el);
            ?>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <span class="blue_line"></span>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12 box_type_cars">
            <?
            $elCarType = $fields['c_t_typecars'];
            $elCarType->setLabel("");
            echo $this->formRow($elCarType); ?>
        </div>

        <div class="col-xs-12 col-sm-4 col-md-4 ">
            <div class="row">
                <div class="col-xs-12 col-sm-3 col-md-3 zero_padding">
                    <label>
                        عنوان آگهی
                    </label>
                </div>
                <div class="col-xs-12 col-sm-9 col-md-9">
                    <?= $this->formRow($form->get('title')); ?>
                </div>
            </div>
        </div>

        <div class="col-xs-12 col-sm-4 col-md-4 ">
            <div class="row">
                <div class="col-xs-12 col-sm-2 col-md-2">
                    <label>
                        <?= t('State') ?>
                    </label>
                </div>
                <div class="col-xs-12 col-sm-10 col-md-10">
                    <?= $this->formRow($form->get('stateId')); ?>
                </div>
            </div>
        </div>

        <div class="col-xs-12 col-sm-4 col-md-4">
            <div class="row">
                <div class="col-xs-12 col-sm-2 col-md-2">
                    <label>
                        <?= t('City') ?>
                    </label>
                </div>
                <div class="col-xs-12 col-sm-10 col-md-10">
                    <?= $this->formRow($form->get('cityId')); ?>
                </div>
            </div>
        </div>

        <div style="clear:both"></div>

        <div class="col-xs-6 col-xs-offset-3 col-sm-4 col-sm-offset-4 col-md-2 col-md-offset-5">
            <a class="ad_next" href="#" data-in="1">
                <img src="<?= $this->basePath() . TEMPLATE_PATH . '/images/main/edame.png' ?>" class="img-responsive">
            </a>
        </div>
        <div style="clear:both"></div>
    </div>

    <div id="ad_part_6000_0_2">

    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="description_ad alert alert-info">
            <?= sprintf(t('ADS_VIEW_TYPE'), '<span id="ad_view_param_1"></span>') ?>
            <br>
            <?= sprintf(t('ADS_VIEW_COUNT_AT_DAY'), '<span id="ad_view_param_2"></span>') ?>
            <br>
            <?= sprintf(t('ADS_VIEW_COUNT_CAT_ITEM'), '<span id="ad_view_param_3"></span>') ?>
            <br>
            <?= sprintf(t('ADS_VIEW_COUNT_KEYWORD'), $this->keywordCount) ?>
            <br>
            <?= sprintf(t('ADS_VIEW_COUNT_IMAGE'), '<span id="ad_view_param_4"></span>') ?>
            <br>
            <?= sprintf(t('ADS_VIEW_STAR_PRICE'), '<span id="ad_view_param_5"></span>') ?>
            <br>
        </div>
        <div class="description_ad alert alert-success">
            <?= t('ADS_FINAL_PRICE') . " : " ?>
            <span id="ad_view_final_price"></span>
            <?= t(getCurrency()) ?>
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding box_new_6000_0">
        <div class="row">


            <div class="col-xs-12 col-sm-4 col-md-4">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                        <?= $this->formRow($fields['c_t_brand']); ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                        <?= $this->formRow($fields['c_t_model']); ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                        <?= $this->formRow($fields['c_t_year']); ?>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-4 col-md-4">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                        <?= $this->formRow($fields['c_t_sukht']); ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                        <?= $this->formRow($fields['c_t_karkard']); ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                        <?= $this->formRow($fields['c_t_girbox']); ?>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-4 col-md-4">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding box_radio">
                        <?
                        $fields['c_t_type1']->setLabel("");
                        echo $this->formRow($fields['c_t_type1']); ?>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <span class="blue_line"></span>
            </div>

            <div class="col-xs-12 col-sm-4 col-md-4">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                        <?= $this->formRow($fields['c_t_price']); ?>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-4 col-md-4">
                <div class="row">
                </div>
            </div>

            <div class="col-xs-12 col-sm-4 col-md-4">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding box_radio">
                        <?
                        $fields['c_t_type2']->setLabel("");
                        echo $this->formRow($fields['c_t_type2']); ?>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <span class="blue_line"></span>
            </div>

            <div class="col-xs-12 col-sm-4 col-md-4">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                        <?= $this->formRow($fields['c_t_outcolor']); ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                        <?= $this->formRow($fields['c_t_incolor']); ?>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-4 col-md-4">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                        <?= $this->formRow($form->get('text')); ?>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-4 col-md-4">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding box_radio">
                        <?
                        $fields['c_t_type3']->setLabel("");
                        echo $this->formRow($fields['c_t_type3']); ?>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <span class="blue_line"></span>
            </div>

            <div class="col-xs-12 col-sm-6 col-md-6">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding box_file">
                        <?= $this->formRow($form->get('smallImage')); ?>
                        <? if ($this->flagEdit && $this->oldSmallImagePath) { ?>
                            <div class="box-file-collection">
                                <a id="del_smallImage_ad" class="btn">
                                    <span class="glyphicon glyphicon-remove text-danger"></span>
                                </a>
                                <img src="<?= $this->oldSmallImagePath ?>">
                            </div>
                        <? } ?>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-6 col-md-6">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                        <?= $this->formRow($fields['c_t_moaveze']); ?>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                        <?= $this->formRow($fields['c_t_naghdi']); ?>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <span class="blue_line"></span>
            </div>

            <div class="col-xs-12 col-sm-6 col-md-6">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 ">
                        <div class="box_desc_film">
                            <span class="glyphicon glyphicon-comment text-info"></span>
                            <?= t('ADS_FILM_DESC') ?>
                        </div>
                        <div class="box_sites_film">
                            <span class="glyphicon glyphicon-ok text-success"></span>
                            <a href="<?= t('ADS_FILM_SITE1') ?>" target="_blank"><?= t('ADS_FILM_SITE1') ?></a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-6 col-md-6">
                <div class="row">
                    <div class="col-xs-12 col-sm-10 col-md-10 text_center box_input_film">
                        <?= $this->formRow($fields['c_t_film']); ?>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12">
            <span class="box_new_type_desc">
                <span class="glyphicon glyphicon-paperclip text-danger"></span>
اطلاعات عمومی آگهی
                <span class="caret"></span>
            </span>
    </div>


    <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="row">
            <div class="col-xs-6 col-sm-4 col-md-3 zero_padding">
                <label class="def_label">
                    <?= t('Name') ?>
                </label>
            </div>
            <div class="col-xs-6 col-sm-8 col-md-9">
                <?= $this->formRow($form->get('name')); ?>
            </div>
        </div>
    </div>

    <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="row">
            <div class="col-xs-6 col-sm-4 col-md-3 zero_padding">
                <label class="def_label">
                    <?= t('Mobile') ?>
                </label>
            </div>
            <div class="col-xs-6 col-sm-8 col-md-9">
                <?= $this->formRow($form->get('mobile')); ?>
            </div>
        </div>
    </div>

    <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="row">
            <div class="col-xs-6 col-sm-4 col-md-3 zero_padding">
                <label class="def_label">
                    <?= t('Email') ?>
                </label>
            </div>
            <div class="col-xs-6 col-sm-8 col-md-9">
                <?= $this->formRow($form->get('mail')); ?>
            </div>
        </div>
    </div>

    <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="row">
            <div class="col-xs-6 col-sm-4 col-md-3 zero_padding">
                <label class="def_label">
                    <?= t('Address') ?>
                </label>
            </div>
            <div class="col-xs-6 col-sm-8 col-md-9">
                <?= $this->formRow($form->get('address')); ?>
            </div>
        </div>
    </div>

    <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="row">
            <div class="col-xs-6 col-sm-4 col-md-3 zero_padding">
                <label class="def_label">
                    <?= t('ADS_KEYWORDS') ?>
                </label>
            </div>
            <div class="col-xs-6 col-sm-8 col-md-9">
                <?= $this->formRow($form->get('keyword')); ?>
            </div>
        </div>
    </div>

    <div class="col-xs-12 col-sm-6 col-md-4" id="ad_view_link">
        <div class="row">
            <div class="col-xs-6 col-sm-4 col-md-3 zero_padding">
                <label class="def_label">
                    <?= t('ADS_LINK') ?>
                </label>
            </div>
            <div class="col-xs-6 col-sm-8 col-md-9">
                <?= $this->formRow($form->get('link')); ?>
            </div>
        </div>
    </div>

    <div class="col-xs-12 col-sm-6 col-md-4" id="ad_view_star_count">
        <div class="row">
            <div class="col-xs-6 col-sm-4 col-md-3 zero_padding">
                <label class="def_label">
                    <?= t('ADS_STAR_COUNT') ?>
                </label>
            </div>
            <div class="col-xs-6 col-sm-8 col-md-9">
                <?= $this->formRow($form->get('starCount')); ?>
            </div>
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="row">
            <?= $this->formRow($form->get('showPm')); ?>
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12">
        <span class="blue_line"></span>
    </div>

    <div class="col-xs-12 a_n_images_f box_file">
        <?= $this->formCollection($form->get('image')); ?>
        <? if ($this->flagEdit) { ?>
            <div class="box-file-collection">
                <?= $this->fileDisplay($this->imagesFile, $this->countImage) ?>
            </div>
        <? } ?>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12">
        <span class="blue_line"></span>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12">
        <? if ($form->has('captcha')) echo $this->iptFormRow($form->get('captcha')); ?>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-4 col-md-offset-4 box_button">
        <button class="ad_prev btn btn-default text-danger" data-in="2">
            <span class="glyphicon glyphicon-chevron-right text-danger"></span>
                بازگشت
        </button>
        <?
        echo $this->iptFormCollection($form->get('buttons'));
        ?>
    </div>

    </div>

    <div id="send_request_dialog" style="display:none;">
        <div class="count_request">
            <?= sprintf(t('ADS_COUNT_REQUEST_VIEW'), '<span class"c_r_dialog">0</span>') ?>
        </div>
        <div>
            <? if ($form->has('sendRequestType')) echo $this->formRow($form->get('sendRequestType')); ?>
        </div>
        <a href="#" id="submit_form_final" class="btn btn-default">
            <span class="glyphicon glyphicon-chevron-left text-success"></span>
            ثبت آگهی
        </a>
    </div>



    <?
    echo $this->form()->closeTag();
    ?>
    <div style="clear:both"></div>
    </div>
    </div>
    </div>


    <div id="map-dialog" style="display: none;">
        <div>
            <input type="button" id="select_return" class="btn btn-default pull-right flip"
                   value="<?= t('Confirm and return') ?>">
            <input type="button" id="select_cancel" class="btn btn-default pull-right flip" value="<?= t('Close') ?>">

            <div>
                <?= t('To obtain the coordinates of the desired location click on the map.') ?>
            </div>
            <div id="map_selected_loc"></div>
        </div>
        <div id="map" style="width: 100%;height: 100%;">
            <?= t('Google Maps is not available due to filtering.') ?>
        </div>
    </div>

    <script>
    <?$this->inlineScript()->captureStart();?>
    var ads = {
        config: <?=json_encode($this->adConfig)?>,
        fieldsRequestSearch: <?=json_encode($this->fieldsRequestSearch)?>,
        adConfigId: 0,
        notConfig: '<?=t('ADS_NOT_CONFIG_MESSAGE')?>',
        flagEdit: <?=$this->flagEdit?>,
        filter:<?=$this->filterFields?>,
        filterFieldName:<?if($this->filterFieldsName) echo $this->filterFieldsName; else echo json_encode(false);?>,
        isGoogleMap:<?=$this->isGoogleMap?>,
        flagFormSubmit:<?=$this->flagFormSubmit?>,
        baseType:<?=$this->baseType?>,
        baseTypePriceOneEmail:<?=$this->baseTypePriceOneEmail?>,
        baseTypePriceOneSms:<?=$this->baseTypePriceOneSms?>
    };

    $(document).ready(function () {

        $('input[name="fields[c_t_price]"]').addClass('withcomma');

        $('.ad_new_form .back_loading').fadeIn(300);

        if (ads.flagFormSubmit)
            $('#new_ad_form #buttons_submit').addClass('submitRequest');

        if (ads.flagEdit) {
            $('#ad_part_6000_0_1 .ad_view_type .form-group').hide();
            $('#ad_view_star_count').hide();
            $('#ad_part_6000_0_1 .ad_view_type').prepend($('input[name=adType]:radio:checked').parent().text());
        }

        $('#new_ad_form #buttons_submit').click(function (e) {
            $('.ad_new_form .back_loading').fadeIn(300);
            $("html,body").animate({scrollTop: $('#new_ad_form').offset().top - 50 }, 600);
            var form_tag = $(this);
            if (form_tag.hasClass('submitRequest')) {
                if (ads.fieldsRequestSearch) {
                    e.preventDefault();
                    form_tag.addClass('ajax-loading-inline');
                    var params = {};
                    $.each(ads.fieldsRequestSearch, function (index, value) {
                        if ($('input[name=' + value + ']').val())
                            params[value] = $('input[name=' + value + ']').val();
                        else if ($('textarea[name=' + value + ']').val())
                            params[value] = $('textarea[name=' + value + ']').val();
                        else if ($('select[name=' + value + ']').val())
                            params[value] = $('select[name=' + value + ']').val();
                        else if ($('input[name="fields[' + value + ']"]').val())
                            params[value] = $('input[name="fields[' + value + ']"]').val();
                        else if ($('textarea[name="fields[' + value + ']"]').val())
                            params[value] = $('textarea[name="fields[' + value + ']"]').val();
                        else if ($('select[name="fields[' + value + ']"]').val())
                            params[value] = $('select[name="fields[' + value + ']"]').val();
                    });
                    var data = {};
                    data['baseType'] = ads.baseType;
                    data['params'] = params;

                    $.ajax({
                        url: '<?=url('admin/ad/request-search-count')?>',
                        type: 'POST',
                        data: data,
                        complete: function () {
                            form_tag.removeClass('ajax-loading-inline');
                        },
                        success: function (data) {
                            if (data.status == 1 && data.count!=0) {
                                $('.count_request span').html(data.count);
                                $('.send_request_type').each(function () {
                                    var r_value = $(this).val();
                                    var flagHasTag = 0;
                                    if ($(this).parent().children().find('span').length > 0)
                                        flagHasTag = 1;

                                    switch (parseInt(r_value)) {
                                        case 1 :
                                            if (flagHasTag)
                                                $(this).parent().children('span').html(data.p_sms_v);
                                            else
                                                $(this).parent().append('<span>' + data.p_sms_v + '</span>');
                                            break;
                                        case 2 :
                                            if (flagHasTag)
                                                $(this).parent().children('span').html(data.p_email_v);
                                            else
                                                $(this).parent().append('<span>' + data.p_email_v + '</span>');
                                            break;
                                        case 3 :
                                            if (flagHasTag)
                                                $(this).parent().children('span').html(data.p_sms_email_v);
                                            else
                                                $(this).parent().append('<span>' + data.p_sms_email_v + '</span>');
                                            break;
                                    }
                                });
                                /* $('input[name=sendRequestId]').val(data.r_id);*/
                                $('.ad_new_form .back_loading').fadeOut(300);
                                $("#send_request_dialog").dialog({
                                    resizable: false,
                                    height: 280,
                                    width: 400,
                                    modal: false
                                    // title: Comment.title,
                                });
                                //form_tag.removeClass('submitRequest');
                            }
                            if(data.status==1 && data.count==0){
                                $('input[name=notifyType]').val(0);
                                $('#new_ad_form #buttons_submit').removeClass('submitRequest');
                                $('#new_ad_form #buttons_submit').click();
                            }
                        }

                    });

                }
            }
        });

        $('#submit_form_final').click(function (e) {
            e.preventDefault();
            var notifyType = $('input[name=sendRequestType]:radio:checked').val();
            $('input[name=notifyType]').val(parseInt(notifyType));
            $('#new_ad_form #buttons_submit').removeClass('submitRequest');
            $('#new_ad_form #buttons_submit').click();
        });

        $('.ad_next').click(function (e) {
            e.preventDefault();
            var idLink = parseInt($(this).data('in')) + 1;
            ads.adConfigId = $('input[name=adType]:radio:checked').val();
            var adConfigText = $('input[name=adType]:radio:checked').parent().text();
            var error = __checkElPart1();
            if (ads.config[ads.adConfigId]  && !error) {

                $('#ad_view_param_1').html(adConfigText);
                $('#ad_view_param_2').html(ads.config[ads.adConfigId]['countInDay']);
                $('#ad_view_param_3').html(ads.config[ads.adConfigId]['countCatItem']);
                $('#ad_view_param_4').html(ads.config[ads.adConfigId]['countImage']);
                $('#ad_view_param_5').html(ads.config[ads.adConfigId]['starPrice_name']);
                $('#ad_view_final_price').html(insertcomma(ads.config[ads.adConfigId]['starPrice']));
                // var finalPrice = ads.config[ads.adConfigId]['starPrice'];
                // $('#ad_view_final_price_deducted').html(insertcomma(finalPrice));

                __removeImageBox();
                var countImage = parseInt(ads.config[ads.adConfigId]['countImage']);
                if (countImage == 0)
                    $('#image_settings').parent().hide();
                else {
                    $('#image_settings').parent().show();
                    for (var i = 1; i < countImage; i++) {
                        $('#image_settings .add_collection_item').click();
                    }
                }

                if (parseInt(ads.config[ads.adConfigId]['haveLink']) == 1)
                    $('#ad_view_link').show();
                else
                    $('#ad_view_link').hide();

                if (parseInt(ads.config[ads.adConfigId]['starPrice']) > 0 && !ads.flagEdit)
                    $('#ad_view_star_count').show();
                else if (parseInt(ads.config[ads.adConfigId]['starPrice']) <= 0 && !ads.flagEdit)
                    $('#ad_view_star_count').hide();
                $(this).parent().parent().fadeOut(700, function () {
                    $('#ad_part_6000_0_' + idLink).fadeIn(1000);
                });
            } else{
                if (!error)
                    System.AjaxMessage(ads.notConfig);
            }
        });

        $('.ad_prev').click(function (e) {
            e.preventDefault();
            var idLink = parseInt($(this).data('in')) - 1;
           // __removeImageBox();
            $(this).parent().parent().fadeOut(700, function () {
                $('#ad_part_6000_0_' + idLink).fadeIn(1000);
            });
        });

        $('select[name=starCount]').change(function () {
            var result = parseInt(ads.config[ads.adConfigId]['starPrice']) * parseInt($(this).val());
            $('#ad_view_final_price').html(insertcomma(result));
            //  var finalPrice = result;
            //  $('#ad_view_final_price_deducted').html(insertcomma(finalPrice));
        });

        $('#del_smallImage_ad').click(function (e) {
            e.preventDefault();
            var tag = $(this);
            tag.removeClass('remove-icon').addClass('ajax-loading-inline');
            var data = {};
            data['id'] = $('input[name=id]').val();

            $.ajax({
                url: '<?=url('admin/ad/delete-img')?>',
                type: 'POST',
                data: data,
                complete: function () {
                    tag.removeClass('ajax-loading-inline').addClass('remove-icon');
                },
                success: function (data) {
                    if (data.status) {
                        tag.parent().remove();
                    }
                    else {
                        System.AjaxMessage('Error . Please try again');
                    }
                }

            });
        });

        if (ads.filterFieldName) {
            var fieldsName = [];
            $.each(ads.filterFieldName, function (index, item) {
                fieldsName.push('select[name="' + item + '"]');
                $('select[name="' + item + '"]').data('index', index);
            });

            $(fieldsName.join(',')).change(function () {
                __showFields();
                var baseName = $(this).attr('name');
                // var key = $(this).data('index');
                var name = baseName.replace('fields[', '').replace(']', '');
                var filters = ads.filter;
                var that = $(this);
                $.each(ads.filterFieldName, function (index, item) {
                    var el = null;
                    var elName = '';
                    if (item != baseName) {
                        el = $('select[name="' + item + '"]');
                        item = item.replace('fields[', '').replace(']', '');
                        elName = item;
                    } else {
                        el = that;
                        elName = name;
                    }
                    filters = filters[elName][el.val()];
                });
                $.each(filters, function (index, item) {
                    if (item == '0') {
                        $('[name="fields[' + index + ']"]').parent().addClass('filter-field-hidden');
                    }
                });

            });
        }

        $('.withcomma').each(function () {
            $(this).keyup(function () {
                numFormat(this);
            })
        });

        function __showFields() {
            $('.filter-field-hidden').each(function () {
                $(this).removeClass('filter-field-hidden');
            });
        }

        function __checkElPart1() {
            var error = false;
            if ($('select[name=stateId]').val() == "") {
                $('select[name=stateId]').addClass('error');
                error = true;
            } else
                $('select[name=stateId]').removeClass('error');

            if ($('select[name=cityId]').val() == "") {
                $('select[name=cityId]').addClass('error');
                error = true;
            } else
                $('select[name=cityId]').removeClass('error');

            if ($('input[name=title]').val().length < 1) {
                $('input[name=title]').addClass('error');
                error = true;
            } else
                $('input[name=title]').removeClass('error');
            return error;
        }

        function __removeImageBox()
        {
            var counter = 1;
            $('#image_settings #image').each(function () {
                if (counter != 1)
                    $(this).remove();
                counter++;
            });
        }

       // if (ads.isGoogleMap)
        //    Ads.init();

        $('select[name="fields[c_t_brand]"]').change(function () {
            var vals = $(this).val();
            $('select[name="fields[c_t_model]"] option').each(function () {
                $(this).addClass('op_hidden');
            });
            $('select[name="fields[c_t_model]"] option').each(function () {
                if ($(this).val().contains(vals))
                    $(this).removeClass('op_hidden');
            });
        });

    });

    $(window).bind("load", function () {
        $('.ad_new_form .back_loading').fadeOut(300);
    });

    <?$this->inlineScript()->captureEnd();?>
    </script>
<? } ?>