<?
if (!$this->error) {
    $this->headScript()->appendFile($this->basePath() . '/__/js/filter-fields.js');
    $this->headScript()->appendFile($this->basePath() . '/js/geographical.js');
    if ($this->isGoogleMap) {
        $this->headScript()->appendFile($this->basePath() . '/__/js/adsGoogleMapHandler.js');
    }
    ?>
    <style>
        .ad_new_form #ad_part_5000_1_2{ display:none; }
        #image_settings .add_collection_item{ display:none; }
        #ad_part_5000_1_2 .select2-container-multi{ width:auto !important; }
        .filter-field-hidden{ display:none; }
    </style>

    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-6">
                <img src="<?= $this->basePath() . TEMPLATE_PATH . '/images/main/logo_new.png' ?>"
                     class="img-responsive logo_new">
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6">
                <img src="<?= $this->basePath() . TEMPLATE_PATH . '/images/main/titr_new.png' ?>"
                     class="img-responsive titr_new">
            </div>
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12">
    <div class="row">
    <div class="ad_new_form">
    <div class="back_loading">
        <span class="img_loading"></span>
    </div>
    <?
    $form = $this->form;
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('id'));
    echo $this->formRow($form->get('googleLatLong'));
    if ($form->has('sendRequestId'))
        echo $this->formRow($form->get('sendRequestId'));
    if ($form->has('notifyPrice'))
        echo $this->formRow($form->get('notifyPrice'));
    if ($form->has('notifyType'))
        echo $this->formRow($form->get('notifyType'));
    /* @var $fieldset \Zend\Form\Fieldset */
    $fieldset = $form->get('fields');
    $fields = $fieldset->getElements();
    ?>
    <div id="ad_part_5000_1_1">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <span class="box_new_type_desc">
                <span class="glyphicon glyphicon-exclamation-sign text-danger"></span>
لطفا مدت، قیمت و نوع آگهی خود را انتخاب کنید .
                <span class="caret"></span>
            </span>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 ad_view_type">
            <?
            $el = $form->get('adType');
            $el->setLabel("");
            echo $this->formRow($el);
            ?>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <span class="blue_line"></span>
        </div>

        <div class="col-xs-12 col-sm-4 col-sm-offset-1 col-md-4 col-md-offset-1">
            <div class="row">
                <div class="col-xs-12 col-sm-2 col-md-2 zero_padding">
                    <label>
                        <span class="glyphicon glyphicon-asterisk text-danger def_danger"></span>
                        <?
                        $elRegType = $fields['r_r_regtype'];
                        echo $elRegType->getLabel();
                        $elRegType->setLabel("");
                        ?>
                    </label>
                </div>
                <div class="col-xs-12 col-sm-10 col-md-10">
                    <?
                    echo $this->formRow($elRegType); ?>
                </div>
            </div>
        </div>

        <div class="col-xs-12 col-sm-4 col-sm-offset-1 col-md-4 col-md-offset-1">
            <div class="row">
                <div class="col-xs-12 col-sm-2 col-md-2 zero_padding">
                    <label>
                        <span class="glyphicon glyphicon-asterisk text-danger def_danger"></span>
                        <?
                        $elEstateType = $fields['r_r_estatetype'];
                        echo $elEstateType->getLabel();
                        $elEstateType->setLabel("");
                        ?>
                    </label>
                </div>
                <div class="col-xs-12 col-sm-10 col-md-10">
                    <?
                    echo $this->formRow($elEstateType); ?>
                </div>
            </div>
        </div>

        <div style="clear:both"></div>

        <!--<div class="col-xs-12 col-sm-4 col-md-4 ">
            <div class="row">
                <div class="col-xs-12 col-sm-3 col-md-3 zero_padding">
                    <label>
                        عنوان آگهی
                    </label>
                </div>
                <div class="col-xs-12 col-sm-9 col-md-9">
                    <?/*= $this->formRow($form->get('title')); */?>
                </div>
            </div>
        </div>-->

        <div class="col-xs-12 col-sm-4 col-sm-offset-1 col-md-4 col-md-offset-1">
            <div class="row">
                <div class="col-xs-12 col-sm-2 col-md-2">
                    <label>
                        <span class="glyphicon glyphicon-asterisk text-danger def_danger"></span>
                        <?= t('State') ?>
                    </label>
                </div>
                <div class="col-xs-12 col-sm-10 col-md-10">
                    <?= $this->formRow($form->get('stateId')); ?>
                </div>
            </div>
        </div>

        <div class="col-xs-12 col-sm-4 col-sm-offset-1 col-md-4 col-md-offset-1">
            <div class="row">
                <div class="col-xs-12 col-sm-2 col-md-2">
                    <label>
                        <span class="glyphicon glyphicon-asterisk text-danger def_danger"></span>
                        <?= t('City') ?>
                    </label>
                </div>
                <div class="col-xs-12 col-sm-10 col-md-10">
                    <?= $this->formRow($form->get('cityId')); ?>
                </div>
            </div>
        </div>

        <div style="clear:both"></div>

        <div class="col-xs-6 col-xs-offset-3 col-sm-4 col-sm-offset-4 col-md-2 col-md-offset-5">
            <a class="ad_next" href="#" data-in="1">
                <img src="<?= $this->basePath() . TEMPLATE_PATH . '/images/main/edame.png' ?>" class="img-responsive">
            </a>
        </div>
        <div style="clear:both"></div>
    </div>

    <div id="ad_part_5000_1_2">

    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="row">
            <div class="col-xs-12 col-sm-9 col-md-9">
                <div class="description_ad alert alert-info">
                    <?= sprintf(t('ADS_VIEW_TYPE'), '<span id="ad_view_param_1"></span>') ?>
                    <br>
                    <?= sprintf(t('ADS_VIEW_COUNT_AT_DAY'), '<span id="ad_view_param_2"></span>') ?>
                    <!-- <br>-->
                    <? //= sprintf(t('ADS_VIEW_COUNT_CAT_ITEM'), '<span id="ad_view_param_3"></span>') ?>
                    <br>
                    <?= sprintf(t('ADS_VIEW_COUNT_KEYWORD'), $this->keywordCount) ?>
                    <br>
                    <?= sprintf(t('ADS_VIEW_COUNT_IMAGE'), '<span id="ad_view_param_4"></span>') ?>
                    <br>
                    <?= sprintf(t('ADS_VIEW_STAR_PRICE'), '<span id="ad_view_param_5"></span>') ?>
                    <br>
                </div>
            </div>
            <div class="col-xs-12 col-sm-3 col-md-3">
                <img src="<?= $this->basePath() . TEMPLATE_PATH . '/images/realestate/defult-img.png' ?>" class="img-responsive new_def_img">
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="description_ad alert alert-success">
                    <?= t('ADS_FINAL_PRICE') . " : " ?>
                    <span id="ad_view_final_price"></span>
                    <?= t(getCurrency()) ?>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12 box_new_6000_0 box_new_5000_0">
    <div class="row">
    <!-- next row -->
    <div class="col-xs-12 col-sm-3 col-md-4">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                <?= $this->formRow($fields['r_r_masahat']); ?>
            </div>
        </div>
    </div>

    <div class="col-xs-12 col-sm-3 col-md-4">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                <?= $this->formRow($fields['r_r_mantaghe']); ?>
            </div>
        </div>
    </div>

    <div class="col-xs-12 col-sm-3 col-md-4">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                <?= $this->formRow($fields['r_r_khiaban']); ?>
            </div>
        </div>
    </div>

    <!--<div class="col-xs-12 col-sm-8 col-md-8 box_address">
        <div class="row">
            <div class="col-xs-6 col-sm-4 col-md-3 zero_padding">
                <label class="def_label">
                    <? /*= t('Address') */ ?>
                </label>
            </div>
            <div class="col-xs-6 col-sm-8 col-md-9">
                <? /*= $this->formRow($form->get('address')); */ ?>
            </div>
        </div>
    </div>-->
    <div style="clear:both"></div>

    <div class="col-xs-12 col-sm-12 col-md-12">
        <span class="blue_line"></span>
    </div>

    <!-- next row -->
    <div class="col-xs-12 col-sm-3 col-md-4">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                <?= $this->formRow($fields['r_r_price']); ?>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-4 col-md-4">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                <?= $this->formRow($fields['r_r_rahn']); ?>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-3 col-md-4">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                <?= $this->formRow($fields['r_r_ejare']); ?>
            </div>
        </div>
    </div>

    <!-- next row -->
    <div class="col-xs-12 col-sm-4 col-md-4">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                <?= $this->formRow($fields['r_r_roomcount']); ?>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-4 col-md-4">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                <?= $this->formRow($fields['r_r_karbari']); ?>
            </div>
        </div>
    </div>

    <div class="col-xs-12 col-sm-4 col-md-4">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                <?= $this->formRow($fields['r_r_typebagh']); ?>
            </div>
        </div>
    </div>

    <!-- next row -->
    <div class="col-xs-12 col-sm-3 col-md-4">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                <?= $this->formRow($fields['r_r_typekar']); ?>
            </div>
        </div>
    </div>

    <div class="col-xs-12 col-sm-4 col-md-4">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                <?= $this->formRow($fields['r_r_year']); ?>
            </div>
        </div>
    </div>

    <div class="col-xs-12 col-sm-4 col-md-4">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                <?= $this->formRow($fields['r_r_arzestreet']); ?>
            </div>
        </div>
    </div>

    <!-- next row -->
    <div class="col-xs-12 col-sm-3 col-md-4">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                <?= $this->formRow($fields['r_r_arzekuche']); ?>
            </div>
        </div>
    </div>

    <!--<div class="col-xs-12 col-sm-4 col-md-4">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                <? /*= $this->formRow($fields['r_t_ayan']); */ ?>
            </div>
        </div>
    </div>

    <div class="col-xs-12 col-sm-4 col-md-4">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                <? /*= $this->formRow($fields['r_t_arzegozar']); */ ?>
            </div>
        </div>
    </div>-->


    <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-10 col-md-offset-1 box_check_radio">
        <div class="row">

            <div class="col-xs-6 col-sm-6 col-md-6">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                        <?= $this->formRow($fields['r_r_dakhel']); ?>
                    </div>
                </div>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                        <?= $this->formRow($fields['r_r_sakht']); ?>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12">
        <span class="blue_line"></span>
    </div>

    <div class="col-xs-4 col-sm-2 col-md-2">
        <label>
            امکانات :
        </label>
    </div>
    <div class="col-xs-8 col-sm-10 col-md-10">
        <div class="row">

            <!-- next row -->
            <div class="col-xs-4 col-sm-3 col-md-2">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                        <?= $this->formRow($fields['r_r_e_water']); ?>
                    </div>
                </div>
            </div>
            <div class="col-xs-4 col-sm-3 col-md-2">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                        <?= $this->formRow($fields['r_r_e_bargh']); ?>
                    </div>
                </div>
            </div>
            <div class="col-xs-4 col-sm-3 col-md-2">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                        <?= $this->formRow($fields['r_r_e_gaz']); ?>
                    </div>
                </div>
            </div>
            <div class="col-xs-4 col-sm-3 col-md-2">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                        <?= $this->formRow($fields['r_r_e_phone']); ?>
                    </div>
                </div>
            </div>
            <div class="col-xs-4 col-sm-3 col-md-2">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                        <?= $this->formRow($fields['r_r_e_chahamigh']); ?>
                    </div>
                </div>
            </div>
            <div class="col-xs-4 col-sm-3 col-md-2">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                        <?= $this->formRow($fields['r_r_e_chahnime']); ?>
                    </div>
                </div>
            </div>

            <!-- next row -->
            <div class="col-xs-4 col-sm-3 col-md-2">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                        <?= $this->formRow($fields['r_r_e_parking']); ?>
                    </div>
                </div>
            </div>
            <div class="col-xs-4 col-sm-3 col-md-2">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                        <?= $this->formRow($fields['r_r_e_anbari']); ?>
                    </div>
                </div>
            </div>
            <div class="col-xs-4 col-sm-3 col-md-2">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                        <?= $this->formRow($fields['r_r_e_hayat']); ?>
                    </div>
                </div>
            </div>
            <div class="col-xs-4 col-sm-3 col-md-2">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                        <?= $this->formRow($fields['r_r_e_abyari']); ?>
                    </div>
                </div>
            </div>
            <div class="col-xs-4 col-sm-3 col-md-2">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                        <?= $this->formRow($fields['r_r_e_mostaghel']); ?>
                    </div>
                </div>
            </div>
            <div class="col-xs-4 col-sm-3 col-md-2">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                        <?= $this->formRow($fields['r_r_e_moshtarak']); ?>
                    </div>
                </div>
            </div>

            <!-- next row -->
            <div class="col-xs-4 col-sm-3 col-md-2">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                        <?= $this->formRow($fields['r_r_e_jadid']); ?>
                    </div>
                </div>
            </div>
            <div class="col-xs-4 col-sm-3 col-md-2">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                        <?= $this->formRow($fields['r_r_e_sanad6']); ?>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12">
        <span class="blue_line"></span>
    </div>

    <div class="col-xs-12 col-sm-5 col-md-5">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 zero_padding">
                <?= $this->formRow($form->get('text')); ?>
            </div>
        </div>
    </div>

    <!--<div class="col-xs-12 col-sm-6 col-md-6">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 zero_padding box_file">
                <?/*= $this->formRow($form->get('smallImage')); */?>
                <?/* if ($this->flagEdit && $this->oldSmallImagePath) { */?>
                    <div class="box-file-collection">
                        <a id="del_smallImage_ad" class="btn">
                            <span class="glyphicon glyphicon-remove text-danger"></span>
                        </a>
                        <img src="<?/*= $this->oldSmallImagePath */?>">
                    </div>
                <?/* } */?>
            </div>
        </div>
    </div>-->

    <?/* if ($this->isGoogleMap) { */?><!--
        <div class="col-xs-12 col-sm-2 col-md-2 zero_padding">
            <a href="#googleMap" id="find-google" class="input-google-map btn btn-default btn-lg disabled">
                <?/*= t('Map') */?>
                <i class="fa fa-refresh fa-spin"></i>
            </a>

            <div id="google_text"><?/*= $this->google */?></div>
        </div>
    --><?/* } */?>


    <div class="col-xs-12 col-sm-12 col-md-12">
        <span class="blue_line"></span>
    </div>

    </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12">
            <span class="box_new_type_desc">
                <span class="glyphicon glyphicon-paperclip text-danger"></span>
اطلاعات عمومی آگهی دهنده
                <span class="caret"></span>
            </span>
    </div>


    <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="row">
            <div class="col-xs-6 col-sm-4 col-md-3 zero_padding">
                <label class="def_label">
                    <span class="glyphicon glyphicon-asterisk text-danger def_danger"></span>
                    <?= t('Name') ?>
                </label>
            </div>
            <div class="col-xs-6 col-sm-8 col-md-9">
                <?= $this->formRow($form->get('name')); ?>
            </div>
        </div>
    </div>

    <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="row">
            <div class="col-xs-6 col-sm-4 col-md-3 zero_padding">
                <label class="def_label">
                    <span class="glyphicon glyphicon-asterisk text-danger def_danger"></span>
                    <?= t('Mobile') ?>
                </label>
            </div>
            <div class="col-xs-6 col-sm-8 col-md-9">
                <?= $this->formRow($form->get('mobile')); ?>
            </div>
        </div>
    </div>

    <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="row">
            <div class="col-xs-6 col-sm-4 col-md-3 zero_padding">
                <label class="def_label">
                    <span class="glyphicon glyphicon-asterisk text-danger def_danger"></span>
                    <?= t('Email') ?>
                </label>
            </div>
            <div class="col-xs-6 col-sm-8 col-md-9">
                <?= $this->formRow($form->get('mail')); ?>
            </div>
        </div>
    </div>


    <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="row">
            <div class="col-xs-6 col-sm-4 col-md-3 zero_padding">
                <label class="def_label">
                    <?= t('ADS_KEYWORDS') ?>
                </label>
            </div>
            <div class="col-xs-6 col-sm-8 col-md-9">
                <?= $this->formRow($form->get('keyword')); ?>
            </div>
        </div>
    </div>

    <div class="col-xs-12 col-sm-6 col-md-4" id="ad_view_link">
        <div class="row">
            <div class="col-xs-6 col-sm-4 col-md-3 zero_padding">
                <label class="def_label">
                    <?= t('ADS_LINK') ?>
                </label>
            </div>
            <div class="col-xs-6 col-sm-8 col-md-9">
                <?= $this->formRow($form->get('link')); ?>
            </div>
        </div>
    </div>

    <div class="col-xs-12 col-sm-6 col-md-4" id="ad_view_star_count">
        <div class="row">
            <div class="col-xs-6 col-sm-4 col-md-3 zero_padding">
                <label class="def_label">
                    <?= t('ADS_STAR_COUNT') ?>
                </label>
            </div>
            <div class="col-xs-6 col-sm-8 col-md-9">
                <?= $this->formRow($form->get('starCount')); ?>
            </div>
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="row">
            <?= $this->formRow($form->get('showPm')); ?>
        </div>
    </div>

    <div class="col-xs-12 a_n_images_f box_file">

        <?= $this->formCollection($form->get('image')); ?>
        <? if ($this->flagEdit) { ?>
            <div class="box-file-collection">
                <?= $this->fileDisplay($this->imagesFile, $this->countImage) ?>
            </div>
        <? } ?>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12">
        <span class="blue_line"></span>
    </div>

    <? if ($form->has('captcha')) { ?>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <span class="glyphicon glyphicon-asterisk text-danger def0_danger"></span>
            <?= $this->iptFormRow($form->get('captcha')); ?>
        </div>
    <? } ?>

    <div class="col-xs-12 col-sm-12 col-md-4 col-md-offset-4 box_button">
        <button class="ad_prev btn btn-default text-danger" data-in="2">
            <span class="glyphicon glyphicon-chevron-right text-danger"></span>
            بازگشت
        </button>
        <?
        echo $this->iptFormCollection($form->get('buttons'));
        ?>
    </div>

    </div>

    <div id="send_request_dialog" style="display:none;">
        <div class="count_request">
            <?= sprintf(t('ADS_COUNT_REQUEST_VIEW'), '<span class"c_r_dialog">0</span>') ?>
        </div>
        <div>
            <? if ($form->has('sendRequestType')) echo $this->formRow($form->get('sendRequestType')); ?>
        </div>
        <a href="#" id="submit_form_final" class="btn btn-default">
            <?= t('Next') ?>
        </a>
    </div>

    <?
    echo $this->form()->closeTag();
    ?>
    <div style="clear:both"></div>
    </div>
    </div>
    </div>

    <div id="map-dialog" style="display: none;">
        <div>
            <input type="button" id="select_return" class="btn btn-default pull-right flip"
                   value="<?= t('Confirm and return') ?>">
            <input type="button" id="select_cancel" class="btn btn-default pull-right flip" value="<?= t('Close') ?>">

            <div>
                <?= t('To obtain the coordinates of the desired location click on the map.') ?>
            </div>
            <div id="map_selected_loc"></div>
        </div>
        <div id="map" style="width: 100%;height: 100%;">
            <?= t('Google Maps is not available due to filtering.') ?>
        </div>
    </div>

    <script>
    <?$this->inlineScript()->captureStart();?>
    var ads = {
        config: <?=json_encode($this->adConfig)?>,
        fieldsRequestSearch: <?=json_encode($this->fieldsRequestSearch)?>,
        adConfigId: 0,
        notConfig: '<?=t('ADS_NOT_CONFIG_MESSAGE')?>',
        flagEdit: <?=$this->flagEdit?>,
        filter:<?=$this->filterFields?>,
        filterFieldName:<?if($this->filterFieldsName) echo $this->filterFieldsName; else echo json_encode(false);?>,
        isGoogleMap:<?=$this->isGoogleMap?>,
        flagFormSubmit:<?=$this->flagFormSubmit?>,
        baseType:<?=$this->baseType?>,
        baseTypePriceOneEmail:<?=$this->baseTypePriceOneEmail?>,
        baseTypePriceOneSms:<?=$this->baseTypePriceOneSms?>
    };

    $(document).ready(function () {

        $('select[name="fields[r_t_regtype]"]').select2('val','0');
        $('select[name="fields[r_t_estatetype]"]').select2('val','0');

        $('input[name="fields[r_r_price]"]').addClass('withcomma');
        $('input[name="fields[r_r_rahn]"]').addClass('withcomma');
        $('input[name="fields[r_r_ejare]"]').addClass('withcomma');

        $('.ad_new_form .back_loading').fadeIn(300);

        __insert2Point();

        if (ads.flagEdit) {
            $('#ad_part_5000_1_1 .ad_view_type .form-group').hide();
            $('#ad_view_star_count').hide();
            $('#ad_part_5000_1_1 .ad_view_type').prepend($('input[name=adType]:radio:checked').parent().text());
        }

        $('.ad_next').click(function (e) {
            e.preventDefault();
            var idLink = parseInt($(this).data('in')) + 1;
            ads.adConfigId = $('input[name=adType]:radio:checked').val();
            var adConfigText = $('input[name=adType]:radio:checked').parent().text();
            //check fields
            var error = __checkElPart1();
            if (ads.config[ads.adConfigId] && !error) {

                $('#ad_view_param_1').html(adConfigText);
                $('#ad_view_param_2').html(ads.config[ads.adConfigId]['countInDay']);
                $('#ad_view_param_3').html(ads.config[ads.adConfigId]['countCatItem']);
                $('#ad_view_param_4').html(ads.config[ads.adConfigId]['countImage']);
                $('#ad_view_param_5').html(ads.config[ads.adConfigId]['starPrice_name']);
                $('#ad_view_final_price').html(insertcomma(ads.config[ads.adConfigId]['starPrice']));
                // var finalPrice = ads.config[ads.adConfigId]['starPrice'];
                // $('#ad_view_final_price_deducted').html(insertcomma(finalPrice));

                __removeImageBox();
                var countImage = parseInt(ads.config[ads.adConfigId]['countImage']);
                if (countImage == 0)
                    $('#image_settings').parent().hide();
                else {
                    $('#image_settings').parent().show();
                    for (var i = 1; i < countImage; i++) {
                        $('#image_settings .add_collection_item').click();
                    }
                }

                if (parseInt(ads.config[ads.adConfigId]['haveLink']) == 1)
                    $('#ad_view_link').show();
                else
                    $('#ad_view_link').hide();

                if (parseInt(ads.config[ads.adConfigId]['starPrice']) > 0 && !ads.flagEdit)
                    $('#ad_view_star_count').show();
                else if (parseInt(ads.config[ads.adConfigId]['starPrice']) <= 0 && !ads.flagEdit)
                    $('#ad_view_star_count').hide();
                $(this).parent().parent().fadeOut(700, function () {
                    $('#ad_part_5000_1_' + idLink).fadeIn(1000);
                });
            } else {
                if (!error)
                    System.AjaxMessage(ads.notConfig);
            }

        });

        $('.ad_prev').click(function (e) {
            e.preventDefault();
            var idLink = parseInt($(this).data('in')) - 1;
            $(this).parent().parent().fadeOut(700, function () {
                $('#ad_part_5000_1_' + idLink).fadeIn(1000);
            });
        });

        $('select[name=starCount]').change(function () {
            var result = parseInt(ads.config[ads.adConfigId]['starPrice']) * parseInt($(this).val());
            $('#ad_view_final_price').html(insertcomma(result));
            //  var finalPrice = result;
            //  $('#ad_view_final_price_deducted').html(insertcomma(finalPrice));
        });

        $('#del_smallImage_ad').click(function (e) {
            e.preventDefault();
            var tag = $(this);
            tag.removeClass('remove-icon').addClass('ajax-loading-inline');
            var data = {};
            data['id'] = $('input[name=id]').val();

            $.ajax({
                url: '<?=url('admin/ad/delete-img')?>',
                type: 'POST',
                data: data,
                complete: function () {
                    tag.removeClass('ajax-loading-inline').addClass('remove-icon');
                },
                success: function (data) {
                    if (data.status) {
                        tag.parent().remove();
                    }
                    else {
                        System.AjaxMessage('Error . Please try again');
                    }
                }

            });
        });

        if (ads.filterFieldName) {
            var fieldsName = [];
            $.each(ads.filterFieldName, function (index, item) {
                fieldsName.push('select[name="' + item + '"]');
                $('select[name="' + item + '"]').data('index', index);
            });


            $(fieldsName.join(',')).change(function () {
                __showFields();
                var baseName = $(this).attr('name');
                // var key = $(this).data('index');
                var name = baseName.replace('fields[', '').replace(']', '');
                var filters = ads.filter;
                var that = $(this);
                $.each(ads.filterFieldName, function (index, item) {
                    var el = null;
                    var elName = '';
                    if (item != baseName) {
                        el = $('select[name="' + item + '"]');
                        item = item.replace('fields[', '').replace(']', '');
                        elName = item;
                    } else {
                        el = that;
                        elName = name;
                    }

                    filters = filters[elName][el.val()];
                });
                $.each(filters, function (index, item) {
                    if (item == '0') {
                        $('[name="fields[' + index + ']"]').parent().parent().parent().parent().addClass('filter-field-hidden');
                        $('[name="fields[' + index + '][]"]').parent().parent().parent().parent().parent().addClass('filter-field-hidden');
                    }
                });

            });
        }

        $('.withcomma').each(function () {
            $(this).keyup(function () {
                numFormat(this);
            })
        });

        function __showFields() {
            $('.filter-field-hidden').each(function () {
                $(this).removeClass('filter-field-hidden');
            });
        }

        function __checkElPart1() {
            var error = false;
            if (parseInt($('select[name="fields[r_r_regtype]"]').val()) == 0) {
                $('select[name="fields[r_r_regtype]"]').addClass('error');
                error = true;
            } else
                $('select[name="fields[r_r_regtype]"]').removeClass('error');

            if (parseInt($('select[name="fields[r_r_estatetype]"]').val()) == 0) {
                $('select[name="fields[r_r_estatetype]"]').addClass('error');
                error = true;
            } else
                $('select[name="fields[r_r_estatetype]"]').removeClass('error');

            if ($('select[name=stateId]').val() == "") {
                $('select[name=stateId]').addClass('error');
                error = true;
            } else
                $('select[name=stateId]').removeClass('error');

            if ($('select[name=cityId]').val() == "") {
                $('select[name=cityId]').addClass('error');
                error = true;
            } else
                $('select[name=cityId]').removeClass('error');

            /*if ($('input[name=title]').val().length < 1) {
                $('input[name=title]').addClass('error');
                error = true;
            } else
                $('input[name=title]').removeClass('error');*/
            return error;
        }

        function __removeImageBox()
        {
            var counter = 1;
            $('#image_settings #image').each(function () {
                if (counter != 1)
                    $(this).parent().remove();
                counter++;
            });
        }

        function __insert2Point()
        {
            $(".box_check_radio .form-group").each(function(){
                console.log(1);
                $(this).children().first().addClass('font_bold').append('<span> : </span>');
            });
        }

        //  if (ads.isGoogleMap)
        //    Ads.init();

    });

    $(window).bind("load", function () {
        $('.ad_new_form .back_loading').fadeOut(300);
    });


    <?$this->inlineScript()->captureEnd();?>
    </script>
<? } ?>