<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'Rating\API\ACL'                                   => __DIR__ . '/src/Rating/API/ACL.php',
  'Rating\Controller\NegativePositiveRateController' => __DIR__ . '/src/Rating/Controller/NegativePositiveRateController.php',
  'Rating\Controller\RatingAdminController'          => __DIR__ . '/src/Rating/Controller/RatingAdminController.php',
  'Rating\Controller\RatingController'               => __DIR__ . '/src/Rating/Controller/RatingController.php',
  'Rating\Form\Config'                               => __DIR__ . '/src/Rating/Form/Config.php',
  'Rating\Install'                                   => __DIR__ . '/src/Rating/Install.php',
  'Rating\Model\Rating'                              => __DIR__ . '/src/Rating/Model/Rating.php',
  'Rating\Model\RatingTable'                         => __DIR__ . '/src/Rating/Model/RatingTable.php',
  'Rating\View\Helper\NegativeAndPositiveRate'       => __DIR__ . '/src/Rating/View/Helper/NegativeAndPositiveRate.php',
  'Rating\View\Helper\Rating'                        => __DIR__ . '/src/Rating/View/Helper/Rating.php',
  'Rating\View\Helper\RatingAverage'                 => __DIR__ . '/src/Rating/View/Helper/RatingAverage.php',
);
