<?php
return array(
    'modules' => array(
        'System',
        'Assetic',
        'AssetManager',
        'JQuery',
        'Application',
        'Logger',
        'User',
        'Category',
        'Links',
        'Components',
        'Page',
        'GeographicalAreas',
        'Fields',
//        'RealEstate',
        'DataView',
        'Localization',
        'File',
        'Menu',
//        'OnlineOrder',
        'Sms',
        'Payment',
//        'PhoneBook',
        'Gallery',
        'Comment',
        'FormsManager',
        'Rating',
        'Thumbnail',
        'RSS',
        'Mail',
        'Barcode',
        'Cron',
        'NewsLetter',
        'ServerManager',
        'SiteMap',
        'Theme',
        'ClientManager',
        // 'ECommerce',
        // 'IPTProductOrder',
        'Notify',
        'Contact',
        'Analyzer',
        'ContentSharing',
        'SimpleOrder',
        //  'EdpSuperluminal',
        'Domain',
        'OrgChart',
        'Note',
        'PM',
        'ProductShowcase',
        'EducationalCenter',
        'HealthCenter',
        'CustomersClub',
//        'Ads',
        'DigitalLibrary',
    ),
    'db' => array(
        'driver' => 'Pdo_Mysql',
        'database' => 'iptcms',
//        'hostname' => '192.168.1.67',
        'hostname' => 'localhost',
        'driver_options' => array(
            PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES \'UTF8\''
        ),
        'username' => 'root',
        'password' => '',
    ),
);
