<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'DigitalLibrary\API\ACL'            => __DIR__ . '/src/DigitalLibrary/API/ACL.php',
  'DigitalLibrary\API\DigitalLibrary' => __DIR__ . '/src/DigitalLibrary/API/DigitalLibrary.php',
  'DigitalLibrary\API\EventManager'   => __DIR__ . '/src/DigitalLibrary/API/EventManager.php',
  'DigitalLibrary\Controller\Admin'   => __DIR__ . '/src/DigitalLibrary/Controller/Admin.php',
  'DigitalLibrary\Controller\Client'  => __DIR__ . '/src/DigitalLibrary/Controller/Client.php',
  'DigitalLibrary\Form\Book'          => __DIR__ . '/src/DigitalLibrary/Form/Book.php',
  'DigitalLibrary\Form\Search'        => __DIR__ . '/src/DigitalLibrary/Form/Search.php',
  'DigitalLibrary\Install'            => __DIR__ . '/src/DigitalLibrary/Install.php',
  'DigitalLibrary\Model\Book'         => __DIR__ . '/src/DigitalLibrary/Model/Book.php',
  'DigitalLibrary\Model\BookTable'    => __DIR__ . '/src/DigitalLibrary/Model/BookTable.php',
  'DigitalLibrary\View\Helper\Search' => __DIR__ . '/src/DigitalLibrary/View/Helper/Search.php',
);
