<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'Components\API\ACL'                           => __DIR__ . '/src/Components/API/ACL.php',
  'Components\API\Block'                         => __DIR__ . '/src/Components/API/Block.php',
  'Components\Controller\BlockManagerController' => __DIR__ . '/src/Components/Controller/BlockManagerController.php',
  'Components\Form\NewBlock'                     => __DIR__ . '/src/Components/Form/NewBlock.php',
  'Components\Install'                           => __DIR__ . '/src/Components/Install.php',
  'Components\Model\Block'                       => __DIR__ . '/src/Components/Model/Block.php',
  'Components\Model\BlockTable'                  => __DIR__ . '/src/Components/Model/BlockTable.php',
  'Components\Model\Url'                         => __DIR__ . '/src/Components/Model/Url.php',
  'Components\Model\UrlTable'                    => __DIR__ . '/src/Components/Model/UrlTable.php',
  'Components\View\Helper\Blocks'                => __DIR__ . '/src/Components/View/Helper/Blocks.php',
);
