<h3><?=t('Patch Samples')?></h3>
<table class="grid" style="width: 300px;" dir="ltr">
    <tr>
        <td class="left-align">/</td>
        <td align="right"><?=t('Front Page')?></td>
    </tr>
    <tr>
        <td class="left-align">/fa</td>
        <td align="right"><?=t('Front Page with fa language')?></td>
    </tr>
    <tr>
        <td class="left-align">/fa/blog</td>
        <td align="right"><?=t('Blog page with fa language')?></td>
    </tr>
    <tr>
        <td class="left-align">/*/blog</td>
        <td align="right"><?=t('Blog page for all languages')?></td>
    </tr>
    <tr>
        <td class="left-align">/*/blog/*</td>
        <td align="right"><?=t('for every personal blog for all languages')?></td>
    </tr>
</table>