<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'Notify\API\ACL'                     => __DIR__ . '/src/Notify/API/ACL.php',
  'Notify\API\Notify'                  => __DIR__ . '/src/Notify/API/Notify.php',
  'Notify\API\SystemRecipient'         => __DIR__ . '/src/Notify/API/SystemRecipient.php',
  'Notify\Controller\NotifyController' => __DIR__ . '/src/Notify/Controller/NotifyController.php',
  'Notify\Form\AdvanceConfig'          => __DIR__ . '/src/Notify/Form/AdvanceConfig.php',
  'Notify\Form\Config'                 => __DIR__ . '/src/Notify/Form/Config.php',
  'Notify\Form\Fieldsets\Event'        => __DIR__ . '/src/Notify/Form/Fieldsets/Event.php',
  'Notify\Form\Fieldsets\Module'       => __DIR__ . '/src/Notify/Form/Fieldsets/Module.php',
  'Notify\Form\Fieldsets\Modules'      => __DIR__ . '/src/Notify/Form/Fieldsets/Modules.php',
  'Notify\Form\Fieldsets\NotifyWith'   => __DIR__ . '/src/Notify/Form/Fieldsets/NotifyWith.php',
  'Notify\Form\Fieldsets\Role'         => __DIR__ . '/src/Notify/Form/Fieldsets/Role.php',
  'Notify\Form\Fieldsets\Roles'        => __DIR__ . '/src/Notify/Form/Fieldsets/Roles.php',
  'Notify\Install'                     => __DIR__ . '/src/Notify/Install.php',
  'Notify\Model\Notify'                => __DIR__ . '/src/Notify/Model/Notify.php',
  'Notify\Model\NotifyTable'           => __DIR__ . '/src/Notify/Model/NotifyTable.php',
  'Notify\View\Helper\Notifications'   => __DIR__ . '/src/Notify/View/Helper/Notifications.php',
);
