<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'ProductShowcase\API\ACL'                          => __DIR__ . '/src/ProductShowcase/API/ACL.php',
  'ProductShowcase\API\API'                          => __DIR__ . '/src/ProductShowcase/API/API.php',
  'ProductShowcase\API\EventManager'                 => __DIR__ . '/src/ProductShowcase/API/EventManager.php',
  'ProductShowcase\Controller\PsAdminController'     => __DIR__ . '/src/ProductShowcase/Controller/PsAdminController.php',
  'ProductShowcase\Controller\PsCartAdminController' => __DIR__ . '/src/ProductShowcase/Controller/PsCartAdminController.php',
  'ProductShowcase\Controller\PsCartController'      => __DIR__ . '/src/ProductShowcase/Controller/PsCartController.php',
  'ProductShowcase\Controller\PsController'          => __DIR__ . '/src/ProductShowcase/Controller/PsController.php',
  'ProductShowcase\Form\ImageCollection'             => __DIR__ . '/src/ProductShowcase/Form/ImageCollection.php',
  'ProductShowcase\Form\ImageValue'                  => __DIR__ . '/src/ProductShowcase/Form/ImageValue.php',
  'ProductShowcase\Form\ProductShowcase'             => __DIR__ . '/src/ProductShowcase/Form/ProductShowcase.php',
  'ProductShowcase\Form\PsCart'                      => __DIR__ . '/src/ProductShowcase/Form/PsCart.php',
  'ProductShowcase\Install'                          => __DIR__ . '/src/ProductShowcase/Install.php',
  'ProductShowcase\Model\Ps'                         => __DIR__ . '/src/ProductShowcase/Model/Ps.php',
  'ProductShowcase\Model\PsCart'                     => __DIR__ . '/src/ProductShowcase/Model/PsCart.php',
  'ProductShowcase\Model\PsCartTable'                => __DIR__ . '/src/ProductShowcase/Model/PsCartTable.php',
  'ProductShowcase\Model\PsTable'                    => __DIR__ . '/src/ProductShowcase/Model/PsTable.php',
  'ProductShowcase\View\Helper\PsCart'               => __DIR__ . '/src/ProductShowcase/View/Helper/PsCart.php',
);
