<aside id="workshop-rules">
    <? if ($this->page) {
        ?>
        <h2 class="page-header">
            <?= $this->page->pageTitle ?>
        </h2>
        <p><?= $this->page->fullText ?></p>
    <?
    } ?>
</aside>
<div>
    <a class='btn btn-default btn-lg'
       href="<?= url('app/workshop/class/register', array('workshop' => $this->workshop, 'class' => $this->class)) ?>">
        <span class="glyphicon glyphicon-ok text-success icon-lg"></span>
        <?= t('I Accept') ?>
    </a>
    <a class='btn btn-default btn-lg'
       href="<?= url('app/workshop/class', array('workshop' => $this->workshop, 'class' => $this->class)) ?>">
        <span class="glyphicon glyphicon-remove text-danger icon-lg"></span>
        <?= t('I Do Not Accept') ?>
    </a>
</div>