<div class="workshop-class">
    <? if (isset($this->error)) {
        print $this->alert($this->error, 'alert-danger');
    } else {
        ?>
        <h4 class="page-header">
            <small>»</small>
            <?= $this->item->title ?>
            <small>»</small>

            <a href="<?= url('app/workshop', array('workshop' => $this->item->workshopId)) ?>">
                <small><?= $this->item->workshopTitle ?></small>
            </a>

            <a class="pull-right flip btn btn-default btn-lg" href="<?=
            url('app/workshop/class/agreement',
                array('workshop' => $this->workshop, 'class' => $this->class)) ?>">
                <?= t('Register') ?>
            </a>
        </h4>

        <div class="row">
            <div class="col-md-7">
                <div class="panel panel-default workshop-details">
                    <div class="panel-heading">
                        <?= t('EDUCATINALCENTER_DETAILS_WORKSHOP') ?>
                    </div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table table-hover table-condensed">
                                <tr>
                                    <th><?= t('Price') ?>:</th>
                                    <td><?= $this->currency_format($this->item->price) ?></td>
                                </tr>
                                <tr>
                                    <th><?= t('First session') ?> :</th>
                                    <td><?= $this->date_format($this->item->firstSession, 0, 3) ?></td>
                                </tr>
                                <tr>
                                    <th><?= t('Venue') ?> :</th>
                                    <td><?= $this->item->location ?></td>
                                </tr>
                                <tr>
                                    <th><?= t('Venue phone') ?> :</th>
                                    <td><?= $this->item->phone ?></td>
                                </tr>
                                <tr>
                                    <th><?= t('Capacity') ?> :</th>
                                    <td>
                                        <?
                                        $class = 'progress-bar-success';
                                        $capacity = $this->item->capacity;
                                        $used = $this->users ? $this->users->count() : 0;
                                        if ($used > ($capacity / 3))
                                            $class = 'progress-bar-warning';
                                        if ($used > ($capacity / 3) * 2)
                                            $class = 'progress-bar-danger';

                                        $percent = (int)($used * 100 / $capacity);

//                                        $progress = "<div class='progress' title='{$percent}%'>
//                                              <div class='progress-bar $class progress-bar-striped' role='progressbar' aria-valuenow='{$used}' aria-valuemin='0' aria-valuemax='{$capacity}' style='withh: {$percent}%;min-withh:30px;'>
//                                               {$used}/{$capacity}
//                                              </div>
//                                            </div>";
//
//                                        print $progress;
                                        ?>
                                        <div class='progress' title='<?= $percent ?>%' style='margin-bottom:0;min-width:100px;'>

                                            <div class='progress-bar progress-bar-success progress-bar-striped'
                                                 role='progressbar'
                                                 aria-valuenow='<?= $used ?>' aria-valuemin='0' aria-valuemax='<?= $capacity ?>'
                                                 style='width: <?= $percent ?>%;'>
                                                <?= $used ?>
                                            </div>

                                            <? if ($used > 0) { ?>
                                                <div class="pull-right flip" style="padding:0 2px;"><?= $capacity - $used ?></div>
                                            <? } ?>
                                        </div>
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div class="class-description">
                            <?= $this->item->note ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-5">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <?= t('Educator') ?>
                        <small>»</small>
                        <?
                        print \Theme\API\Common::Link(
                            getUserDisplayName($this->item),
                            url('app/user/user-profile', array('id' => $this->item->educatorId)));?>
                    </div>
                    <div
                        class="panel-body body_info_educator"><?= $this->user_info($this->item->educatorId, array('col-md-12', 'col-md-12')); ?></div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-7">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <?= t('Time Table') ?>
                    </div>
                    <div class="panel-body">
                        <? if ($this->timetable && $this->timetable->count()) { ?>
                            <div class="table-responsive">
                                <table class="table table-striped table-hover">
                                    <thead>
                                    <tr>
                                        <th><?= t('Date') ?></th>
                                        <th><?= t('Start Time') ?></th>
                                        <th><?= t('End Time') ?></th>
                                        <th><?= t('Session Length') ?></th>
                                        <th><?= t('Time Distance') ?></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <? foreach ($this->timetable as $row) { ?>
                                        <tr>
                                            <td><?= $this->date_format($row->date); ?></td>
                                            <td><?= $this->date_format($row->start, -1, 3); ?></td>
                                            <td><?= $this->date_format($row->end, -1, 3); ?></td>
                                            <td>
                                                <?
                                                $diff = $row->end - $row->start;
                                                print \Localization\API\Date::formatInterval($diff);
                                                ?>
                                            </td>
                                            <td>
                                                <?
                                                $diff = $row->start - time();

                                                $class = 'text-success';
                                                $ago = '';
                                                if ($diff < 0) {
                                                    $ago .= ' ' . t('LOCALIZATION_TIME_AGO');
                                                    $diff *= -1;
                                                    $class = 'text-danger';
                                                }

                                                $content = \Localization\API\Date::formatInterval($diff);
                                                $content .= $ago;
                                                ?>
                                                <span class="<?= $class ?>"><?= $content ?></span>
                                            </td>
                                        </tr>
                                    <? } ?>
                                    </tbody>
                                </table>
                            </div>
                        <? } else print $this->alert('no timetable has not been defined for this class yet') ?>
                    </div>
                </div>
            </div>
            <div class="col-md-5">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <?= t('Attendances') ?>
                    </div>
                    <div class="panel-body">
                        <? if ($this->users && $this->users->count()) { ?>
                            <div class="table-responsive">
                                <table class="table table-striped table-hover">
                                    <thead>
                                    <tr>
                                        <th></th>
                                        <th><?= t('Register Date') ?></th>
                                        <th><?= t('Status') ?></th>
                                    </tr>
                                    </thead>

                                    <tbody>
                                    <? foreach ($this->users as $row) { ?>
                                        <tr>
                                            <td> <?
                                                print \Theme\API\Common::Link(
                                                    getUserDisplayName($row),
                                                    url('app/user', array('id' => $row->userId)));?>
                                            </td>
                                            <td><?= $this->date_format($row->registerDate, 0, 3) ?></td>
                                            <td>
                                                <?
                                                if ($row->status == '0')
                                                    print "<span class='text-warning'>" . t('Not Finalized') . "</span>";
                                                else
                                                    print "<span class='text-success'>" . t('Reserved') . "</span>";
                                                ?>
                                            </td>
                                        </tr>
                                    <? } ?>
                                    </tbody>
                                </table>
                            </div>
                        <? } else print $this->alert('no one has not registered for this class yet', 'alert-warning') ?>
                    </div>
                </div>
            </div>
        </div>
    <? } ?>
</div>