<div>
    <h3 class="page-header text-danger">
        <?= t('Your profile is not complete') ?>
    </h3>

    <div>
        <p>
            <?= t('Before you can register in any class you need to complete your profile.'); ?>
        </p>
        <? if (isset($this->items['user']) || isset($this->items['profile'])) { ?>
            <p>
                <?=
                sprintf(t('The values for these fields are required for your %suser profile%s'),
                    "<a target='_blank' href='" . url('admin/users/edit', array('id' => current_user()->id)) . "'>", "</a>"); ?> :
            </p>
            <ul>
                <?
                foreach ($this->items['user'] as $item) {
                    print "<li>{$item}</li>";
                }
                foreach ($this->items['profile'] as $item) {
                    print "<li>{$item}</li>";
                }
                ?>
            </ul>
        <?
        }
        if (isset($this->items['customProfile'])) {
            ?>
            <p>
                <?=
                sprintf(t('The values for these fields are required for your %scustom user profile%s'),
                    "<a target='_blank' href='" . url('admin/users/edit/custom-profile', array('id' => current_user()->id)) . "'>", "</a>"); ?>
                :
            </p>
            <ul>
                <? foreach ($this->items['customProfile'] as $item) { ?>
                    <li><?= $item ?></li>
                <? } ?>
            </ul>
        <? } ?>
    </div>
</div>