<?
$this->headLink()
    ->appendStylesheet($this->basePath() . '/css/real-estate.css');

$this->headScript()
    ->prependFile($this->basePath() . '/js/geographical.js')
    ->prependFile($this->basePath() . '/js/filters.js')
    ->prependFile($this->basePath() . '/js/real-estate-new.js')
    ->appendFile($this->basePath() . '/js/real-estate.js');

$route_prefix = $this->admin_route ? 'admin' : 'app';
?>
<div id="real_estate_form_page">
<?
/* @var $form \Zend\Form\Form */
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>
<fieldset class="fieldset-admin" style="display:none;">
    <legend class="legend-admin">
        <?= $this->translate('Guest Edit Permission') ?>
    </legend>
    <div style="display: <? if ($route_prefix != "admin") echo "none" ?>;">
        <?//= $this->iptFormRow($form->get('allowEdit')) ?>
    </div>
    <div id='guest_user_edit'>
        <?//= $this->iptFormRow($form->get('passForEdit')) ?>
        <?//= $this->iptFormRow($form->get('ownerMobile')) ?>
    </div>

    <div style='clear:both;'>
        <label><?= $this->translate('With entering your custom password and phone number and website managers confirmation, you may edit your estate without registration.') ?></label>

</fieldset>
<?
?>
<fieldset class="fieldset-admin">
    <legend class="legend-admin">
        <?= $this->translate('Specifications Home') ?><?= $this->homeId ?>
    </legend>
    <table cellpadding='0' cellspacing='0' id="real_estate_form">
        <tr>
            <td><?= $this->iptFormRow($form->get('stateId')) ?></td>
            <td><?= $this->iptFormRow($form->get('cityId')) ?></td>
            <td>
                <?= $this->iptFormRow($form->get('areaId')) ?>
                <?= $this->iptFormRow($form->get('newArea')) ?>
            </td>
            <td><?= $this->iptFormRow($form->get('ownerName')) ?></td>
            <td><?= $this->iptFormRow($form->get('ownerPhone')) ?></td>
            <td><?= $this->iptFormRow($form->get('ownerEmail')) ?></td>
        </tr>
        <tr>
            <td><?= $this->iptFormRow($form->get('estateType')) ?></td>
            <td><?= $this->iptFormRow($form->get('regType')) ?></td>
            <td><?//= $this->iptFormRow($form->get('estateArea')) ?></td>
            <td><?= $this->iptFormRow($form->get('expire')) ?></td>
            <td id="price_panel">
                <?= $this->iptFormRow($form->get('priceOneMeter')) ?>
                <?= $this->iptFormRow($form->get('totalPrice')) ?>
            </td>
            <td id="price_panel_2">
                <?= $this->iptFormRow($form->get('mortgagePrice')) ?>
                <?= $this->iptFormRow($form->get('rentalPrice')) ?>
            </td>
        </tr>
        <tr>
            <td colspan="2"><?= $this->iptFormRow($form->get('addressShort')) ?></td>
            <td colspan="2"><?= $this->iptFormRow($form->get('addressFull')) ?></td>
            <td colspan="2"><?= $this->iptFormRow($form->get('ownerMobile')) ?></td>
        </tr>
        <?
        /* @var $fieldset \Zend\Form\Fieldset */
        if ($this->form->has('transferFields')) {
            $fieldset = $this->form->get('transferFields');
            if ($fieldset) {
                $fields = $fieldset->getElements();

                ?>
                <tr>
                    <td colspan="5">
                        <fieldset id="estate_fields_list" class="fieldset-admin">
                            <legend class="legend-admin">
                                <?= $this->translate('Details'); ?>
                            </legend>
                            <?
                            $checkboxes = '';
                            $multi_checkboxes_col1 = '';
                            $multi_checkbox_col1 = true;
                            $multi_checkboxes_col2 = '';
                            $radios = '';
                            $text_boxes_col1 = '';
                            $text_boxes_col2 = '';
                            $text_box_col1 = true;

                            $builds = array();
                            for ($i = 0; $i < count($builds); $i++) {
                                $builds[$i] = 'transferFields[' . $builds[$i] . ']';
                            }
                            /* @var $f \Zend\Form\Element */
                            foreach ($fields as $f) {
                                if (in_array($f->getName(), $builds)) {
                                    continue;
                                } elseif ($f instanceof \Zend\Form\Element\MultiCheckbox || $f instanceof \Zend\Form\Element\Select) {
                                    if ($multi_checkbox_col1)
                                        $multi_checkboxes_col1 .= $this->iptFormRow($f);
                                    else
                                        $multi_checkboxes_col2 .= $this->iptFormRow($f);
                                    $multi_checkbox_col1 = !$multi_checkbox_col1;
                                } elseif ($f instanceof \Zend\Form\Element\Checkbox) {
                                    $checkboxes .= $this->iptFormRow($f);
                                } elseif ($f instanceof \Zend\Form\Element\Text) {
                                    if ($text_box_col1)
                                        $text_boxes_col1 .= $this->iptFormRow($f);
                                    else
                                        $text_boxes_col2 .= $this->iptFormRow($f);
                                    $text_box_col1 = !$text_box_col1;
                                }
                            }
                            ?>
                            <div class="check_list">
                                <?= ($checkboxes) ?>
                                <? //=$this->iptFormRow($fieldset->get('has_parking'))?>
                                <? //=$this->iptFormRow($fieldset->get('has_elevator'))?>
                                <? //=$this->iptFormRow($fieldset->get('cabinet'))?>
                                <? //=$this->iptFormRow($fieldset->get('can_get_vam'))?>
                                <? //=$this->iptFormRow($fieldset->get('kolangi'))?>
                                <? //=$this->iptFormRow($fieldset->get('exchange'))?>
                            </div>
                            <div class="column_2 multi_check_list" style="clear: both;">
                                <?= $multi_checkboxes_col1 ?>
                                <? //=$this->iptFormRow($fieldset->get('melk_position'))?>
                                <? //=$this->iptFormRow($fieldset->get('ensheabat'))?>
                            </div>
                            <div class="column_2 multi_check_list">
                                <?= $multi_checkboxes_col2 ?>
                                <? //=$this->iptFormRow($fieldset->get('sanad_type'))?>
                                <? //=$this->iptFormRow($fieldset->get('melk_usage'))?>
                            </div>
                            <div class="column_2 text_box_list" style="clear: both;">
                                <?= $text_boxes_col1 ?>
                                <? //=$this->iptFormRow($fieldset->get('witch_floor'))?>
                                <? //=$this->iptFormRow($fieldset->get('room_floor_type'))?>
                                <? //=$this->iptFormRow($fieldset->get('gozar_chand_metry'))?>
                                <? //=$this->iptFormRow($fieldset->get('heating_system'))?>
                            </div>
                            <div class="column_2 text_box_list">
                                <?= $text_boxes_col2 ?>
                                <? //=$this->iptFormRow($fieldset->get('floor_count'))?>
                                <? //=$this->iptFormRow($fieldset->get('sanad_dong'))?>
                                <? //=$this->iptFormRow($fieldset->get('room_count'))?>
                                <? //=$this->iptFormRow($fieldset->get('build_year'))?>
                            </div>
                            <div style="clear: both;"></div>
<!--                            <fieldset class="fieldset-admin">-->
<!--                                <legend class="legend-admin">--><?//= $this->translate('Construction Partnership Details') ?><!--</legend>-->
<!---->
<!--                                <div class="inline_elements" style="clear: both;">-->
<!--                                    --><?////= $this->iptFormRow($fieldset->get('build_pilot')) ?>
<!--                                    --><?//= $this->iptFormRow($fieldset->get('build_floor')) ?>
<!--                                    --><?//= $this->iptFormRow($fieldset->get('build_section')) ?>
<!--                                    <div style="clear: both;"></div>-->
<!--                                    --><?//= $this->iptFormRow($fieldset->get('build_owner_percent')) ?>
<!--                                    --><?//= $this->iptFormRow($fieldset->get('build_builder_percent')) ?>
<!--                                    <div style="clear: both;"></div>-->
<!--                                </div>-->
<!---->
<!--                            </fieldset>-->
                            <div style="clear: both;"></div>
                        </fieldset>
                    </td>
                </tr>
            <?
            }
        } ?>
        <tr>
            <td colspan="5"><?= $this->iptFormRow($form->get('description')) ?></td>
        </tr>
        <tr>
            <td colspan="5"><?= $this->iptFormRow($form->get('pm')) ?></td>
        </tr>

        <?php if (!$this->isRequest): ?>
            <tr>
                <td colspan="5"><?= $this->iptFormRow($form->get('isSpecial')) ?></td>
            </tr>
            <tr>
                <td colspan="5"><?= $this->iptFormRow($form->get('showInfo')) ?></td>
            </tr>
            <tr>
                <td colspan="5"> <? if ($this->images)
                        echo $this->fileDisplay($this->images, $this->maxImage); ?></td>
            </tr>
            <? if ($form->has('images')) {
                if ($images = $form->get('images')) {
                    ?>
                    <tr>
                        <td colspan="5">

                            <?= $this->iptFormCollection($images) ?>
                        </td>
                    </tr>
                <?
                }
            } ?>
        <?php endif; ?>

        <tr>
            <!--                <td colspan="5">--><?//=$this->iptFormRow($form->get('test_file')) ?><!--</td>-->
        </tr>
    </table>
    <?php if (!$this->isRequest){ ?>
    <a href="#googleMap" id="find-google" class="input-google-map"><?= t('Google Map') ?></a>
    <? } ?>

    <div id="google_text"><? if($this->google) echo $this->google; ?></div>
    <?
    echo $this->iptFormRow($form->get('googleLatLong'));
    ?>
<div class="captcha-div">
    <? if($form->has('captcha')) echo $this->iptFormRow($form->get('captcha')); ?>
</div>
</fieldset>
<?
echo $this->iptFormCollection($this->form->get('buttons'));
echo $this->form()->closeTag();
?>
</div>
<div id="map-dialog" style="display: none;">
    <div>
        <span>
            <?=t('To obtain the coordinates of the desired location click on the map.')?>
            </span>
        <span id="map_selected_loc"></span>
        <input type="button" id="select_return" value="<?=t('Confirm and return')?>">
        <input type="button" id="select_cancel" value="<?=t('Close')?>">
    </div>
    <div id="map" style="width: 100%;height: 100%;">
    <?=t('Google Maps is not available due to filtering.')?>
    </div>
</div>
<script type="text/javascript">

    var error_message = '<?= t('error when deleteing file!') ?>';
    var estateType_regType = <?=$this->estateType_regType?>;
    var estateType_fields = <?=$this->estateType_fields?>;

</script>
<script src="http://maps.google.com/maps/api/js?sensor=true"
        type="text/javascript"></script>
