<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'Menu\API\ACL'                                     => __DIR__ . '/src/Menu/API/ACL.php',
  'Menu\API\EventManager'                            => __DIR__ . '/src/Menu/API/EventManager.php',
  'Menu\API\Menu'                                    => __DIR__ . '/src/Menu/API/Menu.php',
  'Menu\Controller\MenuController'                   => __DIR__ . '/src/Menu/Controller/MenuController.php',
  'Menu\Controller\MenuItemController'               => __DIR__ . '/src/Menu/Controller/MenuItemController.php',
  'Menu\Form\Fieldset\Mega'                          => __DIR__ . '/src/Menu/Form/Fieldset/Mega.php',
  'Menu\Form\Fieldset\Options'                       => __DIR__ . '/src/Menu/Form/Fieldset/Options.php',
  'Menu\Form\Menu'                                   => __DIR__ . '/src/Menu/Form/Menu.php',
  'Menu\Form\MenuItem'                               => __DIR__ . '/src/Menu/Form/MenuItem.php',
  'Menu\Install'                                     => __DIR__ . '/src/Menu/Install.php',
  'Menu\Model\Menu'                                  => __DIR__ . '/src/Menu/Model/Menu.php',
  'Menu\Model\MenuItem'                              => __DIR__ . '/src/Menu/Model/MenuItem.php',
  'Menu\Model\MenuItemTable'                         => __DIR__ . '/src/Menu/Model/MenuItemTable.php',
  'Menu\Model\MenuTable'                             => __DIR__ . '/src/Menu/Model/MenuTable.php',
  'Menu\Navigation\Page\Mvc'                         => __DIR__ . '/src/Menu/Navigation/Page/Mvc.php',
  'Menu\Navigation\Page\Uri'                         => __DIR__ . '/src/Menu/Navigation/Page/Uri.php',
  'Menu\Navigation\Service\DynamicNavigationFactory' => __DIR__ . '/src/Menu/Navigation/Service/DynamicNavigationFactory.php',
  'Menu\View\Helper\MenuBlock'                       => __DIR__ . '/src/Menu/View/Helper/MenuBlock.php',
  'Menu\View\Helper\Widget'                          => __DIR__ . '/src/Menu/View/Helper/Widget.php',
);
