<?php
/**
 * Created by PhpStorm.
 * User: Exlord
 * Date: 10/30/13
 * Time: 4:14 PM
 */
?>
<a class="btn btn-default btn-lg ajax_page_load" href="<?= url('admin/file/public') ?>">
    <span class="glyphicon glyphicon-user text-info"></span>
    <?= t('Public Files') ?>
</a>
<a class="btn btn-default btn-lg ajax_page_load" href="<?= url('admin/file/private') ?>">
    <span class="glyphicon glyphicon-lock text-primary"></span>
    <?= t('Private Files') ?>
</a>
