<?
$this->headLink()->appendStylesheet($this->basePath() . TEMPLATE_PATH . '/css/photo-gallery.css');
$this->headScript()->prependFile($this->basePath() . '/js/jquery-hover-effect.js');
$this->headScript()->appendFile($this->basePath() . '/js/jquery.lazyLoad.js');
\JQuery\API\JQuery::loadColorBox($this, 'photo-gallery-' . $this->id);
$select = $this->galleryItem;

?>
<div class="photo-gallery">
    <div>
        <h2 class="page-title"><?= $this->gallery->groupName ?></h2>
        <span class="published"><?= t('Published at') ?> : <?= $this->dateFormat($this->gallery->publishUp) ?></span>
        <? if (!empty($this->gallery->groupText)) { ?>
            <p class="description"><?= $this->gallery->groupText ?></p>
        <? } ?>
        <div style="clear:both;"></div>
    </div>
    <div class="freshdesignweb">
        <div class="image_grid portfolio_4col">
            <ul style="height: 495px;" id="list" class="portfolio_list da-thumbs">
                <?
                foreach ($select as $row) {
                    if ($row->image) {
                        $height = 100;
                        $width = 100;
                        if (!empty($row->width))
                            $width = $row->width;
                        if (!empty($row->height))
                            $height = $row->height;
                        $imageUrl = getThumbnail()->resize($row->image, $width, $height); //resize image
                        list($x, $y, $type, $attr) = getimagesize($this->siteUrl.$row->image);
                        $zoomWidth = $x;
                        $zoomHeight = $y;
                        if((int)$x>1000)
                            $zoomWidth=1000;
                        if((int)$y>700)
                            $zoomHeight=700;
                        $zoomImageUrl = getThumbnail()->resize($row->image, $zoomWidth, $zoomHeight); //resize image
                        $url = url('app/gallery-counter', array('id' => $row->id, 'hitsType' => $this->hitsType));
                        ?>
                        <li>
                            <img class="lazy" data-original="<?= $imageUrl ?>" rel="tooltip"
                                 title="<?= $this->escapeHtml($row->title) ?>" width="<?= $width ?>"
                                 height="<?= $height ?>">
                            <noscript>
                                <img rel="tooltip" title="<?= $this->escapeHtml($row->title) ?>" src="<?= $imageUrl ?>"
                                     width="<?= $width ?>" height="<?= $height ?>">
                            </noscript>
                            <article class="da-animate da-slideFromRight" style="display: block;">
                                <h3><?= $this->escapeHtml($row->title) ?></h3>
                                <!--<em></em>-->
                                <span class="link_post">
                                    <a href="<?= $row->image ?>" download="<?= $row->image ?>"></a>
                                </span>
                                <span class="zoom">
                                    <a class="colorbox" data-id="<?= $url ?>" href="<?= $zoomImageUrl ?>"></a>
                                </span>
                            </article>
                        </li>
                    <?
                    }
                }?>
            </ul>
        </div>
    </div>
    <div style="clear:both;"></div>
</div>
<script type="text/javascript">
    //Image Hover
    $(document).ready(function () {

        $("img.lazy").lazyload({
            effect: "fadeIn"
        });

        $('ul.da-thumbs > li').hoverdir();
    });
</script>







