<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'JQuery\API\JQuery' => __DIR__ . '/src/JQuery/API/JQuery.php',
  'JQuery\Install'    => __DIR__ . '/src/JQuery/Install.php',
);
