<?
/* @var $renderer \Zend\View\Renderer\PhpRenderer */
$renderer = $this;
$renderer->layout('layout/empty');
$content = \Theme\API\Themes::renderLayout($this);
$direction = $this->translate('lang_direction'); //rtl ? ltr
$basePath = $this->basePath();
$this->headLink()
    ->prependStylesheet(
        $basePath . TEMPLATE_PATH . '/css/ie10.css',
        'screen',
        'IE 10'
    )
    ->prependStylesheet(
        $basePath . TEMPLATE_PATH . '/css/ie8.css',
        'screen',
        'lt IE 9'
    );

if ($direction == 'rtl')
    $this->headLink()->prependStylesheet($basePath . TEMPLATE_PATH . '/css/bootstrap-rtl.min.css');

$this->headLink()
    ->prependStylesheet($basePath . '/select2/select2-bootstrap.css')
    ->prependStylesheet($basePath . '/select2/select2.css')
    ->prependStylesheet($basePath . TEMPLATE_PATH . '/css/bootstrap-theme.min.css')
    ->prependStylesheet($basePath . TEMPLATE_PATH . '/css/bootstrap.min.css')
    ->prependStylesheet($basePath . '/css/base-theme/jquery-ui-1.10.1.custom.min.css')
    ->prependStylesheet($basePath . '/css/system.css');


//------------------------------ TEMPLATE STYLE -------------------------------------------
$this->headLink()->appendStylesheet($basePath . TEMPLATE_PATH . '/css/style.css');
if ($direction == 'rtl')
    $this->headLink()->appendStylesheet($basePath . TEMPLATE_PATH . '/css/style-rtl.css');
////-------------------------------------------------------------


$this->headScript()
    ->prependFile($basePath . '/js/system.jquery.ui.js')
    ->prependFile($basePath . '/js/system.js')
    ->prependFile($basePath . '/js/forms.js')
    ->prependFile($basePath . '/js/jquery.hoverIntent.min.js')
    ->prependFile($basePath . '/js/jquery.transit.min.js')
    ->prependFile($basePath . '/select2/select2.min.js')
    ->prependFile($basePath . '/js/general-client.js')
    ->prependFile($basePath . '/js/jquery-ui-1.10.4.custom.min.js')
    ->prependFile($basePath . '/js/jquery-1.9.1.min.js')
    ->prependFile(
        $basePath . TEMPLATE_PATH . '/js/respond.min.js',
        'text/javascript',
        array('conditional' => 'lt IE 9')
    )
    ->prependFile(
        $basePath . TEMPLATE_PATH . '/js/html5shiv.min.js',
        'text/javascript',
        array('conditional' => 'lt IE 9')
    );

//------------------------------ TEMPLATE JAVASCRIPT -------------------------------------------
$this->headScript()->appendFile($basePath . TEMPLATE_PATH . '/js/template-intro.js');

//---------------------------------- BLOCKS -----------------------------------------------//
$top_fav_menu_intro = $this->blocks('top_fav_menu_intro');
$top_main_menu_intro = $this->blocks('top_main_menu_intro');
$news_intro = $this->blocks('news_intro');
$slider_intro = $this->blocks('slider_intro');
$user_block = $this->user_logged_in_block();
/*if (!$user_block) {
    $user_login_block = $this->blocks('user-popup');*/
//}
?>

<!DOCTYPE html>
<html lang="fa" xmlns="http://www.w3.org/1999/html">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <?= $this->head() ?>
    <?= $this->headTitle() ?>
    <?= $this->headMeta() ?>
    <?= $this->headLink() ?>
    <?= $this->headScript() ?>
</head>
<body>
<div id="container">
    <div id="body">
        <div class="container-fluid my_container">
            <div class="row">
                <div class="col-md-6 position_relative">
                    <a href="http://donyayematloob.com" id="defaultLinkLogo">
                        <img src="<?= $basePath . TEMPLATE_PATH . '/images/logo.png' ?>" class="logo_menu">
                    </a>
                    <img src="<?= $basePath . TEMPLATE_PATH . '/images/modiriyate-rahbarane2.png' ?>" id="logoImg3"
                         class="logo_menu_1 display_none">
                    <img src="<?= $basePath . TEMPLATE_PATH . '/images/madares.png' ?>" id="logoImg2"
                         class="logo_menu_1 display_none">
                    <img src="<?= $basePath . TEMPLATE_PATH . '/images/moshavereh.png' ?>" id="logoImg1"
                         class="logo_menu_1 display_none">
                    <img src="<?= $basePath . TEMPLATE_PATH . '/images/Amoozesh.png' ?>" id="logoImg4"
                         class="logo_menu_1 display_none">
                    <img src="<?= $basePath . TEMPLATE_PATH . '/images/pazhoohesh-tarjomeh.png' ?>" id="logoImg5"
                         class="logo_menu_1 display_none">
                    <img src="<?= $basePath . TEMPLATE_PATH . '/images/book.png' ?>" id="logoImg6"
                         class="logo_menu_1 display_none">
                    <img src="<?= $basePath . TEMPLATE_PATH . '/images/bashgah-moshtarian.png' ?>" id="logoImg7"
                         class="logo_menu_1 display_none">

                    <div class="logo"></div>
                    <div class="box_circle_menu">
                        <ul class="navigation">
                            <li>
                                <a href="http://donyayematloob.com/fa/content/13/%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87">
                                    <span class="icon_moshavere icon_circle_menu" data-id="1"></span>
                                    <span class="title_circle_menu default_menu">
مشاوره روانشناسی و مدیریت
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="http://donyayematloob.com/fa/content/11/%D9%85%D8%AF%DB%8C%D8%B1%DB%8C%D8%AA-%D8%B1%D8%A7%D9%87%D8%A8%D8%B1%D8%A7%D9%86%D9%87">
                                    <span class="icon_m_rahbarane icon_circle_menu" data-id="3"></span>
                                    <span class="title_circle_menu">
                                        مدیریت راهبرانه
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="http://donyayematloob.com/fa/content/12/%D9%85%D8%AF%D8%A7%D8%B1%D8%B3-%DA%A9%DB%8C%D9%81%DB%8C">
                                    <span class="icon_m_keyfi icon_circle_menu" data-id="2"></span>
                                    <span class="title_circle_menu">
مدارس کیفی
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="http://donyayematloob.com/fa/content/14/%D8%A2%D9%85%D9%88%D8%B2%D8%B4">
                                    <span class="icon_amuzesh icon_circle_menu" data-id="4"></span>
                                    <span class="title_circle_menu">
آموزش
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="http://donyayematloob.com/fa/content/15/%D9%BE%DA%98%D9%88%D9%87%D8%B4-%D9%88-%D8%AA%D8%B1%D8%AC%D9%85%D9%87">
                                    <span class="icon_p_tarjome icon_circle_menu" data-id="5"></span>
                                    <span class="title_circle_menu">
پژوهش و ترجمه
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="http://donyayematloob.com/fa/tags/5/%D9%85%D8%B9%D8%B1%D9%81%DB%8C-%DA%A9%D8%AA%D8%A7%D8%A8">
                                    <span class="icon_m_ketab icon_circle_menu" data-id="6"></span>
                                    <span class="title_circle_menu">
معرفی کتاب
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="http://donyayematloob.com/fa/content/5/%D8%A8%D8%A7%D8%B4%DA%AF%D8%A7%D9%87-%D9%85%D8%B4%D8%AA%D8%B1%DB%8C%D8%A7%D9%86-%DA%86%DB%8C%D8%B3%D8%AA%D8%9F">
                                    <span class="icon_b_moshtarian icon_circle_menu" data-id="7"></span>
                                    <span class="title_circle_menu">
باشگاه مشتریان
                                    </span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-6 zero_padding">
                    <? if ($top_fav_menu_intro) { ?>
                        <div class="col-md-6 zero_padding">
                            <?= $top_fav_menu_intro ?>
                        </div>
                    <? } ?>
                    <div class="col-md-6 zero_padding login_btn">
                        <?if (!$user_block) { ?>
                            <a class="login_img" href="<?= url('app/user/register') ?>"></a>
                            <a href="<?= url('app/user/login') ?>" class="register_img"></a>
                        <? } ?>
                        <?
                        if ($user_block) {
                            echo $user_block;
                            if (isAllowed(\Application\Module::ADMIN)) {
                                ?>
                                <div class="col-xs-12 col-sm-8 col-md-8 zero_padding">
                                    <a href='<?= url('admin') ?>' title="<?= t('Administration') ?>" class="admin">
                                        <button class="btn btn-default">
                                            <span class="glyphicon glyphicon-home text-success"></span>
                                            دنیای مطلوب
                                            <?
                                            $nameUser = getUserDisplayName(current_user());
                                            if (strlen($nameUser) > 12)
                                                echo substr($nameUser, 0, 12) . ' ...';
                                            else
                                                echo $nameUser;
                                            ?>
                                        </button>
                                    </a>
                                </div>
                            <?
                            }
                        }
                        ?>
                    </div>
                    <div style="clear: both"></div>
                    <div class="link_logo_text_site"></div>

                    <div style="clear: both"></div>
                </div>
            </div>
        </div>
        <div class="container-fluid footer sticky-bottom">
            <div class="row position_relative">
                <? if ($top_main_menu_intro) { ?>
                    <?= $top_main_menu_intro ?>
                <? } ?>
                <div class="col-md-6">
                    <? if ($news_intro) { ?>
                        <?= $news_intro ?>
                    <? } ?>
                    <div style="clear: both"></div>
                    <div class="box_sharing_menu">
                        <ul class="navigation">
                            <li>
                                <a href="http://donyayematloob.com/fa/contact">
                                    <span class="sh_address sh_img_menu"></span>
                                </a>
                            </li>
                            <li>
                                <a href="http://ir.linkedin.com/in/qualityworld">
                                    <span class="sh_linkedin sh_img_menu"></span>
                                </a>
                            </li>
                            <li>
                                <a href="https://www.facebook.com/pages/Quality-world/1456285227928410">
                                    <span class="sh_facebook sh_img_menu"></span>
                                </a>
                            </li>
                            <li>
                                <a href="https://twitter.com/donyayematloob">
                                    <span class="sh_twitter sh_img_menu"></span>
                                </a>
                            </li>
                            <li>
                                <a href="">
                                    <span class="sh_instagram sh_img_menu"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-6 zero_padding">
                    <? if ($slider_intro) { ?>
                        <?= $slider_intro ?>
                    <? } ?>
                </div>
                <div style="clear: both"></div>
                <div class="col-md-12">
                    <div class="box_footer_address">
                        <span class="arrow_footer_add"></span>
                        <span class="text_footer_add">
                            تبریز ، ابتدای 17 شهریور جدید ، مابین تقاطع شریعتی و طالقانی ، جنب داروخانه سپیده ، ساختمان 222 ، طبقه دوم. شماره تماس : 35575985 - 041
                        </span>
                    </div>
                </div>
                <div class=" col-md-12">
                    <div class="copy_right">
                        <?
                        $startYear = mktime(0, 0, 0, 6, 0, 2012);
                        $startYear = $this->dateFormat($startYear, \Localization\View\Helper\DateFormat::YEAR_ONLY);
                        $nowYear = $this->dateFormat(time(), \Localization\View\Helper\DateFormat::YEAR_ONLY);
                        ?>
                        <!--<p align="center">
                            <? /*= t('APPLICATION_BROWSERS') */ ?>
                        </p>-->
                        <p align="center">
                            <span><?= sprintf(t('APPLICATION_RIGHTS'), 'موسسه دنیای مطلوب') ?></span>
                                    <span
                                        dir="ltr"><?= sprintf(t('APPLICATION_COPY_RIGHT'), $startYear, $nowYear) ?></span>
                            &nbsp; .
                            <span><?= t('APPLICATION_SUPPORT') ?></span> .
                            <span><?= t('APPLICATION_POWERED_BY') ?></span>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
<?= $this->inlineScript() ?>
</body>
</html>
<script>
    var default_menu_logo = '<?=$basePath .TEMPLATE_PATH. '/images/logo.png'?>';
    var default_menu_link = 'http://ipt24.com';
</script>

