<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'Sms\API\ACL'                  => __DIR__ . '/src/Sms/API/ACL.php',
  'Sms\API\Service\Panel'        => __DIR__ . '/src/Sms/API/Service/Panel.php',
  'Sms\API\Service\PaneleSmsCom' => __DIR__ . '/src/Sms/API/Service/PaneleSmsCom.php',
  'Sms\API\Service\SmsIR'        => __DIR__ . '/src/Sms/API/Service/SmsIR.php',
  'Sms\API\SMS'                  => __DIR__ . '/src/Sms/API/SMS.php',
  'Sms\Controller\SmsController' => __DIR__ . '/src/Sms/Controller/SmsController.php',
  'Sms\Form\Config'              => __DIR__ . '/src/Sms/Form/Config.php',
  'Sms\Form\SendSms'             => __DIR__ . '/src/Sms/Form/SendSms.php',
  'Sms\Install'                  => __DIR__ . '/src/Sms/Install.php',
  'Sms\Model\Sms'                => __DIR__ . '/src/Sms/Model/Sms.php',
);
