<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'Barcode\Controller\BarcodeController' => __DIR__ . '/src/Barcode/Controller/BarcodeController.php',
);
