<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'SiteMap\API\ACL'                      => __DIR__ . '/src/SiteMap/API/ACL.php',
  'SiteMap\API\EventManager'             => __DIR__ . '/src/SiteMap/API/EventManager.php',
  'SiteMap\API\SiteMap'                  => __DIR__ . '/src/SiteMap/API/SiteMap.php',
  'SiteMap\Controller\SitemapController' => __DIR__ . '/src/SiteMap/Controller/SitemapController.php',
  'SiteMap\Form\Config'                  => __DIR__ . '/src/SiteMap/Form/Config.php',
  'SiteMap\Install'                      => __DIR__ . '/src/SiteMap/Install.php',
  'SiteMap\Model\Url'                    => __DIR__ . '/src/SiteMap/Model/Url.php',
  'SiteMap\Model\UrlSet'                 => __DIR__ . '/src/SiteMap/Model/UrlSet.php',
);
