<?
/* @var $r \Zend\View\Renderer\PhpRenderer *//* @var $r \Zend\View\Renderer\PhpRenderer */
?>
<!--<div style="background:green;height:100px;width:200px;" id="block1">block1</div>
<button id="show">show</button>
<button id="hide">hide</button>
<script>
    $(document).ready(function () {
        $('#show').click(function () {
            console.log('show');
            $('#block1').show();
        });
        $('#hide').click(function () {
            console.log('hide');
            $('#block1').hide();
        });
    });
</script>-->

<!--<html>
<head>
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <title>Alver System</title>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Alver System" name="description">
    <meta content="Alver System" name="keywords">
    <meta content="IPT" name="author">
    <style>
        body{background:#0067a2;}
        .top{width:1000px; height:558px; display:block; background:url(intro_images/main-img.jpg) no-repeat center center;}
    </style>
</head>
<body>
<div class="top"></div>
</body>
</html>
-->

