<?php
// Generated by Exlord's(adeli.farhad@gmail.com) tools/classmap_generator.php
return array(
  'Mail\API\ACL'                   => __DIR__ . '/src/Mail/API/ACL.php',
  'Mail\API\Mail'                  => __DIR__ . '/src/Mail/API/Mail.php',
  'Mail\Controller\CronController' => __DIR__ . '/src/Mail/Controller/CronController.php',
  'Mail\Controller\MailController' => __DIR__ . '/src/Mail/Controller/MailController.php',
  'Mail\Factory\DbAdapter'         => __DIR__ . '/src/Mail/Factory/DbAdapter.php',
  'Mail\Factory\MailArchiveTable'  => __DIR__ . '/src/Mail/Factory/MailArchiveTable.php',
  'Mail\Factory\MailQueueTable'    => __DIR__ . '/src/Mail/Factory/MailQueueTable.php',
  'Mail\Factory\MailSendTable'     => __DIR__ . '/src/Mail/Factory/MailSendTable.php',
  'Mail\Form\Config'               => __DIR__ . '/src/Mail/Form/Config.php',
  'Mail\Form\QuickSendMail'        => __DIR__ . '/src/Mail/Form/QuickSendMail.php',
  'Mail\Install'                   => __DIR__ . '/src/Mail/Install.php',
  'Mail\Model\Mail'                => __DIR__ . '/src/Mail/Model/Mail.php',
  'Mail\Model\MailArchiveTable'    => __DIR__ . '/src/Mail/Model/MailArchiveTable.php',
  'Mail\Model\MailTable'           => __DIR__ . '/src/Mail/Model/MailTable.php',
  'Mail\Model\Send'                => __DIR__ . '/src/Mail/Model/Send.php',
  'Mail\Model\SendTable'           => __DIR__ . '/src/Mail/Model/SendTable.php',
  'Mail\View\Helper\QuickSendMail' => __DIR__ . '/src/Mail/View/Helper/QuickSendMail.php',
);
