<div>
    <h3 class="page-title"><?= t('System Captcha Configs') ?></h3>
    <?
    $form = $this->form;
    $form->prepare();
    echo $this->form()->openTag($form);
    foreach ($form->getElements() as $el) {
        echo $this->iptFormRow($el);
    }
    echo $this->iptFormCollection($form->get('math'));
    echo $this->iptFormCollection($form->get('image'));
    echo $this->formCollection($form->get('buttons'));
    echo $this->form()->closeTag();
    ?>
</div>